algolia/instantsearch

.eslintignore
.gitignore
README.md
package.json
test/InstantSearch.js

```sh
> npm test
> instantsearch.js@0.0.1 test /home/vvo/Dev/Algolia/instantsearch.js
> babel-node test/*.js && npm run lint
TAP version 13
ok 1 algoliasearch called
ok 2 algoliasearch(appId, apiKey)
ok 3 algoliasearchHelper not yet called
ok 4 widget.getConfiguration called
ok 5 widget.getConfiguration(current searchParameters)
ok 6 algoliasearchHelper called
ok 7 algoliasearchHelper(merged searchParameters)
ok 8 helper.search called
ok 9 widget.init called
ok 10 widget.init called after widget.getConfiguration
ok 11 widget.init(helper.state, helper)
ok 12 widget.render not yet called
ok 13 widget.render called
ok 14 widget.render(results, state, helper)
1..14
> instantsearch.js@0.0.1 lint /home/vvo/Dev/Algolia/instantsearch.js
> ./scripts/lint.sh
Lint
```

test: unit test core InstantSearch API

---

components/templates/Hogan/index.js
example/app.js
example/index.html
example/style.css
example/templates/hit.html
package.json
webpack.example.config.js

feat: pimp the npm run dev example using instant search data

---

components/Stats/index.js
example/app.js
example/index.html
index.js
widgets/stats/index.js
widgets/stats/template.html

First small contribution to the instantsearch.js :)

feat: Add stats widget

---

lib/InstantSearch.js
package.json
scripts/test.sh
test/InstantSearch/lifecycle.js
test/InstantSearch/recursively-merge-arrays-searchParameters.js

I had to change a lil bit the testing stack because now we have multiple test files :)

fix(core): recursively merge arrays in searchParameters

---

npm-shrinkwrap.json
package.json

fix(slider): fix tap event throwing

---

components/Slider/index.css

The famous "why can't I reach the start and end?" slider "bug"

fix(slider): allow handles to reach the real start and end of the slider

---

components/Pagination/Paginator.js

fix(pagination): handle cases where maxPages is low

---

widgets/url-sync.js

This will add the instantsearch major version number to the url, under the `is_v` name (for `i`nstant`s`earch `v`ersion).
We currently do nothing with it yet, but this is for future reconciliation between old url and new instant search version.
The diff about `onPopState` is simply refactoring of moving the function in its own method.

Add the major version number to the url

---

README.md
widgets/hits.js
widgets/index-selector.js
widgets/menu.js
widgets/pagination.js
widgets/range-slider.js
widgets/refinement-list.js
widgets/toggle.js

I've updated the documentation of most of the widgets and updated the readme with a copy/paste of the jsdoc + usage examples.
I spotted a few inconsistencies in the widgets (error handling, default arguments, method delegation). I'll go over each of them in several PRs.

docs(jsdoc): Update widget jsdoc and readme

---

widgets/url-sync.js

fix(url-sync): handle both hash and query parameter fix #165

---

.eslintrc
README.md
components/Hits.js
package.json
widgets/hierarchicalMenu.js
widgets/range-slider.js
widgets/refinement-list.js
widgets/search-box.js
widgets/stats/index.js
widgets/toggle.js

I've added the jsdoc checks. I put them directly in `.eslintrc` and not our shared config because this seems really specific to this projet (yet).

style(jsdoc): Add ESlint of jsdoc

---

README.md
components/Stats/Stats.js
components/Stats/stats.css
widgets/stats/index.js
widgets/stats/template.html

Updated the Stats widget to use `ais-stats` BEM classes. Exact same rendering as before, but open the way to theme creation.

feat(bem): Add BEM-styling to the Stats widget

---

example/index.html

Make it bigger moving it from the sidebar to the main section. Fix #157

Example searchbox

---

scripts/test.sh
scripts/validate-commit-msgs.sh

chore(test): validate the commit messages on travis

---

example/app.js
example/index.html
example/style.css
lib/InstantSearch.js
lib/__tests__/InstantSearch-test.js
package.json

When all the widgets are finished rendering and for each search response.

feature(core/lifecycle-event): emits `render` after all render

---

scripts/validate-commit-msgs.sh

When using the "update" button from github then we merge develop into
the branch.
Thus the commit message is "Merge branch .."

chore(scripts/validate-commits): ignore branch merges

---

components/Hits.js
index.js
karma.conf.js
widgets/hits/__tests__/hits-test.js
widgets/hits/defaultTemplates.js
widgets/hits/hits.js

@redox, here's how I did it.
I removed the pre-bound Template component because it in fact
complexifies a lot testing and is not more easy to understand than
what I did here I believe.
What do you think?
(And no, it seems react contexts will not be more easy to use than
what we have here).

test(hits): first pass at widgets testing

---

components/Hits.js
components/RefinementList.js
components/Stats/Stats.js
components/__tests__/Hits-test.js
decorators/headerFooter.js
index.js
widgets/hierarchicalMenu.js
widgets/menu.js
widgets/range-slider.js
widgets/refinement-list/refinement-list.js
widgets/stats/index.js
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/defaultTemplates.js
widgets/toggle/toggle.js

I also moved from the Template to templateProps everywhere

test(toggle): start implementing toggle tests

---

scripts/validate-commit-msgs.sh

chore(validate-commit): allow pull request merges

---

package.json

upgrade expect-to-equal-jsx
cc @redox once this merged you can continue pagination tests I believe

test(JSX): handle null and undefined

---

README.md
example/app.js
example/templates/free-shipping.html
package.json
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/defaultTemplates.js
widgets/toggle/toggle.js

Toggle tests

---

lib/__tests__/version-test.js

test(version): ensure the version is refering to the package.json

---

components/Pagination/Pagination.js
components/Pagination/__tests__/Pagination-test.js

fix(pagination): do not generate the URL for disabled pages.

---

components/PoweredBy/__tests__/PoweredBy-test.js
components/__tests__/Hits-test.js
components/__tests__/Template-test.js
decorators/__tests__/autoHide-test.js
decorators/__tests__/headerFooter-test.js
npm-shrinkwrap.json
package.json
scripts/test-ci.sh
widgets/hits/__tests__/hits-test.js
widgets/index-selector/__tests__/index-selector-test.js
widgets/pagination/__tests__/pagination-test.js

Upgraded jsdom, expect-jsx, client, helper, removed stylelint weird
import

chore(deps): upgrade deps and redo shrinkwrap

---

CHANGELOG.md
package.json

It broke the ChangeLog since it seems like conventional changelog uses it to generate links.

fix(package.json): typo in repository

---

README.md
example/app.js
example/style.css
themes/default/default.css
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/defaultTemplates.js
widgets/toggle/toggle.js

Business as usual. Adding BEM classes to the toggle widget (using
refinementList internally)

feat(toggle): Adding BEM class naming

---

README.md
index.js
themes/default/default.css
widgets/hierarchical-menu/defaultTemplates.js
widgets/hierarchical-menu/hierarchical-menu.js

Last widget to go the BEM way.

feat(hierarchical-menu): Add BEM classes

---

lib/__tests__/utils-test.js
lib/utils.js

Also added doc and did some refactoring. (not rebased but I'd like the feedback before)

Chore(utils) : adds tests for utils module

---

components/RefinementList/RefinementList.js
components/RefinementList/__tests__/RefinementList-test.js
widgets/hierarchical-menu/hierarchical-menu.js
widgets/menu/menu.js
widgets/refinement-list/refinement-list.js
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/toggle.js

Based on @vvo input, I used other previous tests as a template. The
whole defining of props seems a bit clumsy, still.

test(refinementList): Add test for default refinementList render

---

README.md
components/RefinementList/RefinementList.js
components/RefinementList/__tests__/RefinementList-test.js
themes/default.css
widgets/hierarchical-menu/hierarchical-menu.js

Hierarchical lists will have classes like
`ais-hierarchical-menu--list__lvl1`. Updated docs and test
Fixes #162

feat(hierarchical-menu): Add CSS classes dependent on the depth

---

components/PriceRanges.js
widgets/price-ranges/__tests__/price-ranges-test.js
widgets/price-ranges/price-ranges.js

Updated doc & propTypes as well
BREAKING CHANGE: the `input-group` modifier has been renamed to `form`

fix(priceRanges): fixed 'active' CSS class not using BEM

---

scripts/test-ci.sh
scripts/validate-pr-done-on-develop.sh

chore(CI): validate pr was done on develop

---

npm-shrinkwrap.json
package.json
scripts/build.sh

chore(themes): plug autoprefixer

---

decorators/headerFooter.js
widgets/hierarchical-menu/hierarchical-menu.js
widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
widgets/hits-per-page-selector/hits-per-page-selector.js
widgets/hits/__tests__/hits-test.js
widgets/hits/hits.js
widgets/index-selector/__tests__/index-selector-test.js
widgets/index-selector/index-selector.js
widgets/menu/menu.js
widgets/pagination/__tests__/pagination-test.js
widgets/price-ranges/__tests__/price-ranges-test.js
widgets/price-ranges/price-ranges.js
widgets/range-slider/__tests__/range-slider-test.js
widgets/refinement-list/refinement-list.js
widgets/stats/__tests__/stats-test.js
widgets/stats/stats.js
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/toggle.js

fix(cssClasses): Fixed duplication of classNames

---

docs/_includes/header.html
docs/_layouts/documentation.html
docs/_plugins/toc_generator.rb
docs/css/_documentation.sass
docs/css/_header.sass
docs/documentation.md

Also fixes the toc_generator missing last `</ul>`

Fix #411 bottom left panel links

---

docs/css/_documentation.sass
docs/js/doc.js

chore(doc): display some debug info when inspecting the HTML of a widget

---

components/RefinementList/RefinementList.js
components/RefinementList/__tests__/RefinementList-test.js

fix(refinementList): ensure the key reflects the underlying state

---

components/Hits.js
components/Slider/Slider.js
components/Slider/__tests__/Slider-test.js
components/Template.js
components/__tests__/Hits-test.js
components/__tests__/Template-test.js
decorators/__tests__/headerFooter-test.js
decorators/headerFooter.js

Fix #422
BREAKING CHANGE: some extra divs have been removed and my break your CSS rules.

chore(template): get rid of extra <div /> wrapping the Template if possible

---

dev/app.js
docs/_includes/widget-jsdoc/priceRanges.md
docs/_includes/widget-jsdoc/rangeSlider.md
docs/documentation.md
widgets/price-ranges/__tests__/price-ranges-test.js
widgets/price-ranges/price-ranges.js
widgets/range-slider/__tests__/range-slider-test.js
widgets/range-slider/range-slider.js

fix(numerical widgets): s/facetName/attributeName

---

components/Slider/Slider.js
components/Slider/__tests__/Slider-test.js
css/default/_range-slider.scss
dev/app.js
widgets/range-slider/__tests__/range-slider-test.js
widgets/range-slider/range-slider.js

- Cleanup+simpler CSS rules (Fix #289)
- Allow configuration of steps (Fix #337)
So by default it looks like that:

style(slider): improved default look & feel of the range slider

---

docs/_layouts/documentation.html
docs/css/_documentation.sass
docs/js/doc.js

chore(doc): add a copy to clipboard button

---

widgets/hits-per-page-selector/hits-per-page-selector.js

See https://github.com/algolia/instantsearch.js/pull/456/files#r43915199
Should make @bobylito happy :)

perf(hitsPerPageSelector): Use the correct lodash function

---

components/Selector.js
components/__tests__/Selector-test.js

fix(selector): makes component as uncontrolled component

---

docs/_includes/widget-jsdoc/hierarchicalMenu.md
docs/documentation.md
widgets/hierarchical-menu/hierarchical-menu.js

docs(hierarchicalMenu): Adds UX guidance on the number of levels

---

dev/app.js
widgets/numeric-refinement-list/numeric-refinement-list.js
widgets/refinement-list/__tests__/refinement-list-test.js
widgets/refinement-list/refinement-list.js

Needs https://github.com/algolia/instantsearch.js/pull/480 to be merged first.
Fixed a bug on the maxValuePerFacet not correctly updated on some
cases.

test(refinement-list): Add tests to refinement-list widget

---

widgets/search-box/__tests__/search-box-test.js
widgets/search-box/search-box.js

fix(searchBox): handling pasting event with contextual menu.

---

docs/examples/airbnb/index.html
docs/examples/airbnb/style.scss
webpack.dev.config.babel.js

docs(airbnb): add map to the results

---

scripts/release.sh

chore(release): regen the widgets jsdoc

---

docs/documentation.md
docs/js/doc.js

fix(doc): ensure selector is not conflicting

---

mocha.opts
widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
widgets/hierarchical-menu/hierarchical-menu.js
widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
widgets/hits-per-page-selector/hits-per-page-selector.js
widgets/hits/__tests__/hits-test.js
widgets/hits/hits.js
widgets/index-selector/__tests__/index-selector-test.js
widgets/index-selector/index-selector.js
widgets/menu/__tests__/menu-test.js
widgets/menu/menu.js
widgets/numeric-refinement-list/__tests__/numeric-refinement-list-test.js
widgets/numeric-refinement-list/numeric-refinement-list.js
widgets/pagination/__tests__/pagination-test.js
widgets/pagination/pagination.js
widgets/price-ranges/__tests__/price-ranges-test.js
widgets/price-ranges/price-ranges.js
widgets/range-slider/__tests__/range-slider-test.js
widgets/range-slider/range-slider.js
widgets/refinement-list/refinement-list.js
widgets/search-box/__tests__/search-box-test.js
widgets/search-box/search-box.js
widgets/stats/__tests__/stats-test.js
widgets/stats/stats.js
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/toggle.js

Also:
- fixes tests for bad usage
- makes parameters consistent

chore(documentation): Updates usage of all widgets. Fixes #396

---

docs/css/_documentation.sass

fix(docs): improved label/input hover debug

---

lib/InstantSearch.js
lib/helpers.js
widgets/hierarchical-menu/defaultTemplates.js
widgets/menu/defaultTemplates.js
widgets/refinement-list/__tests__/refinement-list-test.js
widgets/refinement-list/defaultTemplates.js
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/defaultTemplates.js

fix(counts): missing formatNumber calls

---

docs/css/_base.sass
docs/css/_header.sass
docs/index.haml
docs/js/home.js

docs(menu): last menu display fix with transparency background

---

dev/app.js
dev/index.html
docs/_includes/widget-jsdoc/numericSelector.md
docs/documentation.md
docs/examples/airbnb/index.html
docs/examples/airbnb/search.js
docs/examples/airbnb/style.scss
lib/main.js
widgets/numeric-selector/__tests__/numeric-selector-test.js
widgets/numeric-selector/numeric-selector.js

A new widget to build dropdown menu to refine on a numeric attribute.
(This one is also mandatory for our examples).
Fix #563

chore(numericSelector): initial import

---

docs/documentation.md
lib/InstantSearch.js
lib/__tests__/InstantSearch-test.js
lib/url-sync.js
widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
widgets/hits-per-page-selector/hits-per-page-selector.js
widgets/index-selector/__tests__/index-selector-test.js
widgets/index-selector/index-selector.js
widgets/search-box/__tests__/search-box-test.js
widgets/search-box/search-box.js
widgets/toggle/__tests__/toggle-test.js
widgets/toggle/toggle.js

It now provides an option object instead of simple parameters.

feat(lifecycle): makes init API consistent with the rest

---

css/_base.scss
css/default/_star-rating.scss
css/instantsearch.scss
docs/_includes/widget-jsdoc/starRating.md
docs/documentation.md
docs/examples/youtube/search.js
docs/examples/youtube/style.scss
lib/main.js
widgets/star-rating/__tests__/star-rating-test.js
widgets/star-rating/defaultLabels.js
widgets/star-rating/defaultTemplates.js
widgets/star-rating/star-rating.js

Amazon-like rating widget.
Fix #558

chore(starRating): a new widget to handle ratings

---

docs/css/_documentation.sass
docs/documentation.md

fix(docs): minor CSS fixes

---

docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
docs/_includes/header.html
docs/_includes/search-templates.html
docs/_layouts/default.html
docs/_plugins/search.rb
docs/css/_base.sass
docs/css/_search.sass
docs/css/main.sass
docs/js/search.js

chore(search): add search feature :)

---

README.md

+ note for jsDelivr users
+ move dev workflow AFTER instantsearch.js API details
+ changed the contributing sentence

docs(readme): small reorganization and wording

---

docs/examples/e-commerce/index.html
docs/examples/media/index.html
docs/examples/tourism/index.html

This is the same change than for the dev docs: we load the needed
scripts from the same hostname, but on a different port

docs(examples): Add hack to load dev example on any IP

---

docs/documentation.md

docs(pagination): Add scrollTo: false

---

docs/documentation.md

docs(stats): Ignore template snippets

---

docs/examples/media/search.js
docs/examples/media/style.scss

style(media-example): Use a background image instead of img tag

---

dev/debug.css
src/components/Pagination/Paginator.js
src/components/Pagination/__tests__/Paginator-test.js

fix(pagination): fix #668 edge case

---

src/widgets/star-rating/__tests__/star-rating-test.js
src/widgets/star-rating/star-rating.js

fix(starRating): Retrieve the correct count and use numericRefinement

---

docs/css/_home.sass

docs(animation): Add anti-aliasing for Firefox

---

docs/examples/e-commerce/index.html
docs/examples/media/index.html
docs/examples/tourism/index.html

Since the examples can be loaded from file:// we need to force the
protocol to https:// (the website is anyway https as well).
Fix #686

docs(https): use https:// instead instead of //

---

src/components/Template.js
src/components/__tests__/Template-test.js

chore(Template): Use cloneDeep with transformData

---

CONTRIBUTING.md
package.json
scripts/release-beta.sh
scripts/release.sh
scripts/validate-pr-done-on-develop.sh

+ allow to merge and release hotfixes into master directly for very important bugs where the develop branch is not yet ready to be released
+ enhance CONTRIBUTING with more details

chore(hotfixes): allow hotfixes and hotfixes releases

---

src/widgets/range-slider/__tests__/range-slider-test.js
src/widgets/range-slider/range-slider.js

For reference the owner of nouislider is not going to fix it (https://github.com/leongersen/noUiSlider/issues/236#issuecomment-85953802)
So let's just hide the slider for now

fix(slider): hide the slider when stats.min=stats.max

---

docs/Gemfile
docs/Gemfile.lock
docs/_plugins/scss.rb

docs(autoprefixer): plug the autoprefixer

---

src/css/default/_range-slider.scss

Prevent slider from extending farther than the last pip

---

scripts/validate-pr-done-on-develop.sh

test(CI): fix pr done on develop script

---

docs/documentation.md

docs(url-sync): adds missing parts in documentation fix #712

---

docs/examples/e-commerce/search.js

Removed active classes on widgets with custom templates.
And added some consistency in js file (quotes and line breaks).

Removed active classes on widgets with custom templates

---

docs/documentation.md

docs(events): adds documentation to events

---

docs/examples/tourism/_style.scss
docs/examples/tourism/search.js

Could be backported to default stylesheet, no?

docs(tourism): fixes handles in tourism sample (fix #642)

---

docs/documentation.md
docs/js/doc.js

Fix #781
Well the issue was not clear, but as with @Jerskouille, clearAll was already documented and currentRefinedValues was not so here it is :)

docs(currentRefinedValues): documents the widget

---

docs/documentation.md
src/components/Template.js
src/components/__tests__/Template-test.js

about [#45](https://github.com/algolia/instantsearch.js/issues/45)

feat(Template): allow template functions to return a React element

---

src/widgets/search-box/__tests__/search-box-test.js
src/widgets/search-box/search-box.js

The queryHook can be used to implement debouncing for example.
Usage:
```js
searchBox({
queryHook: (originalQuery, search) => // either call search() or search(newQuery);
});
```

feat(searchBox): allow to pass a queryHook

---

src/widgets/search-box/__tests__/search-box-test.js
src/widgets/search-box/search-box.js

fix(searchBox): handle external updates of the query

---

dev/index.html
functional-tests/app/app.js
scripts/dev-functional-tests-compile-watch.js
scripts/dev-functional-tests-debug-server.js
scripts/dev-functional-tests.js
src/lib/url-sync.js

Very hard to test: no way to mock location.origin

fix(url-sync): handle <base> href pages

---

src/decorators/__tests__/headerFooter-test.js
src/decorators/headerFooter.js

This was no more working since https://github.com/algolia/instantsearch.js/pull/913, sorry abt that

fix(headerFooter): make collapsible click handler work

---

docs/examples/tourism/index.html

hotfix to explain where the data is coming from

docs(example): Adding source of tourism demo data

---

CHANGELOG.md
docs/_includes/widget-jsdoc/refinementList.md
docs/_includes/widget-jsdoc/searchBox.md
docs/_includes/widget-jsdoc/toggle.md
docs/documentation.md
src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
src/widgets/refinement-list/__tests__/refinement-list-test.js
src/widgets/refinement-list/refinement-list.js
src/widgets/search-box/search-box.js
src/widgets/toggle/toggle.js

docs(typo): more proofreading [ci-skip]

---

docs/_includes/footer.html

I took the liberty to send the PR directly to master, since it's just a wording change.

fix(website): footer wording

---

README.md

I know it's just an example, but I think commas are missing.

Pretty sure commas are needed.

---

src/components/Pagination/PaginationLink.js

fix(paginationLink): it's aria-label not ariaLabel

---

src/widgets/toggle/__tests__/toggle-test.js
src/widgets/toggle/toggle.js

This update brings:
- default to showing the next user action items count instead of the
current number of displayed hits
which means:
if checkbox is not checked, show: [ ] free shipping (countWhenChecked)
if checkbox is checked, show: [x] free shipping (countWhenNotChecked)
- fix numeric based on and off values (fixes #1096)
- provide `onFacetValue` and `offFacetValue` template data, fixes #919

feat(toggle): Provide a better default widget

---

docs/documentation.md
src/lib/InstantSearch.js

doc(helper): Update links to the new Helper documentation

---

packages/instantsearch-react/index.js
packages/instantsearch-react/src/connectors/connectEmptyQuery.js
packages/instantsearch-react/src/connectors/connectLoading.js
packages/instantsearch-react/src/connectors/connectNoResults.js
packages/instantsearch-react/src/impl/EmptyQuery.js
packages/instantsearch-react/src/impl/Loading.js
packages/instantsearch-react/src/impl/NoResults.js
packages/instantsearch-react/src/widgets/EmptyQuery.js
packages/instantsearch-react/src/widgets/Loading.js
packages/instantsearch-react/src/widgets/NoResults.js

Instantsearch react conditionals

---

src/widgets/clear-all/clear-all.js

Implemented by getting refinements in the widget and removing the protected ones before passing the attribute list to clearRefinementsAndSearch

feat(clearAll): Add optional excludeAttributes to list protected filters

---

packages/instantsearch-react/examples/Search.js
packages/instantsearch-react/examples/static/Pagination.css
packages/instantsearch-react/index.js
packages/instantsearch-react/src/impl/HierarchicalMenu.js
packages/instantsearch-react/src/impl/HitsPerPage.js
packages/instantsearch-react/src/impl/HitsPerPageSelect.js
packages/instantsearch-react/src/impl/Link.js
packages/instantsearch-react/src/impl/LinkList.js
packages/instantsearch-react/src/impl/Menu.js
packages/instantsearch-react/src/impl/MenuSelect.js
packages/instantsearch-react/src/impl/Pagination.js
packages/instantsearch-react/src/impl/PaginationSelect.js
packages/instantsearch-react/src/impl/RefinementListLinks.js
packages/instantsearch-react/src/impl/Select.js
packages/instantsearch-react/src/impl/SortByLinks.js
packages/instantsearch-react/src/widgets/Pagination.js
packages/instantsearch-react/src/widgets/PaginationSelect.js

PaginationSelect

---

packages/instantsearch-react/src/impl/HitsPerPage.js
packages/instantsearch-react/src/impl/HitsPerPageSelect.js
packages/instantsearch-react/src/impl/Pagination.js
packages/instantsearch-react/src/impl/PaginationSelect.js
packages/instantsearch-react/src/impl/SortBy.js

List Refactor

---

packages/instantsearch-react/examples/index.js
packages/instantsearch-react/examples/isv2.js
packages/instantsearch-react/examples/react.js
packages/instantsearch-react/examples/static/index.html
packages/instantsearch-react/src/core/instantsearchV2.js

Example implementation of an instantsearch.js-like API, but using the architecture from IS-react under the hood.

Add an POC for ISv2

---

docgen/assets/css/site.css
docgen/mdRenderer.js

doc(generator): Add link in the heading of the documentation

---

packages/react-instantsearch/src/widgets/Pagination/connect.js
packages/react-instantsearch/src/widgets/Pagination/connect.test.js

fix(pagination): always transition state

---

docgen/src/examples/e-commerce/App.js
docgen/src/examples/e-commerce/style.css
package.json
packages/react-instantsearch/src/widgets/Range/README.md
packages/react-instantsearch/src/widgets/Range/Range.js
packages/react-instantsearch/src/widgets/Range/Range.test.js
packages/react-instantsearch/src/widgets/Range/RangeInput.enzyme.test.js
packages/react-instantsearch/src/widgets/Range/RangeInput.js
packages/react-instantsearch/src/widgets/Range/RangeInput.test.js
packages/react-instantsearch/src/widgets/Range/__snapshots__/Range.test.js.snap
packages/react-instantsearch/src/widgets/Range/__snapshots__/RangeInput.test.js.snap
packages/react-instantsearch/src/widgets/Range/index.js

This PR add a new widget : InputRange.
It also updates the e-commerce examples with refinements on prices. 
Be careful : there's no sync between the two widgets that refines on price. I open a discussion about it here #1296

feat(widget): add an input range

---

docgen/src/examples/e-commerce/App.js
docgen/src/examples/e-commerce/style.css
packages/react-instantsearch/src/widgets/Range/README.md
packages/react-instantsearch/src/widgets/Range/RangeRatings.enzyme.test.js
packages/react-instantsearch/src/widgets/Range/RangeRatings.js
packages/react-instantsearch/src/widgets/Range/RangeRatings.test.js
packages/react-instantsearch/src/widgets/Range/__snapshots__/RangeRatings.test.js.snap
packages/react-instantsearch/src/widgets/Range/connect.js
packages/react-instantsearch/src/widgets/Range/connect.test.js
packages/react-instantsearch/src/widgets/Range/index.js

feat(widget): add a new rating range

---

.eslintignore
docgen/src/examples/e-commerce/App.js
docgen/src/examples/tourism/App.js
packages/examples/Search.js
packages/react-instantsearch/index.js
packages/react-instantsearch/src/widgets/MultiRange/MultiRange.enzyme.test.js
packages/react-instantsearch/src/widgets/MultiRange/MultiRange.js
packages/react-instantsearch/src/widgets/MultiRange/MultiRange.test.js
packages/react-instantsearch/src/widgets/MultiRange/README.md
packages/react-instantsearch/src/widgets/MultiRange/__snapshots__/MultiRange.test.js.snap
packages/react-instantsearch/src/widgets/MultiRange/connect.js
packages/react-instantsearch/src/widgets/MultiRange/connect.test.js
packages/react-instantsearch/src/widgets/MultiRange/index.js
packages/react-instantsearch/src/widgets/NumericRefinementList/index.js

refactor: rename NumericRefinementList to MultiRange

---

docgen/layouts/archetypes/single-column-formatted.pug
docgen/layouts/common/header.pug
docgen/layouts/example.pug
docgen/src/examples/e-commerce/index.html
docgen/src/examples/e-commerce/style.css
docgen/src/examples/material-ui/App.js
docgen/src/examples/material-ui/index.html
docgen/src/examples/material-ui/style.css
docgen/src/examples/media/index.html
docgen/src/examples/media/style.css
docgen/src/examples/tourism/index.html
docgen/src/header.scss

This PR fixes the header, and adapt the style of each demo to fit the new fixed header.

doc(examples): fix header + adaptation + tweaks on material demo

---

docs/documentation.md
package.json

Ultimately we should have React as a peerDependency.
fixes #1386

fix(react): avoid duplicating React

---

packages/react-instantsearch/src/widgets/CurrentFilters/CurrentFilters.js

Related: http://stackoverflow.com/questions/5353461/which-font-for-css-x-close-button
Looks equals but is different 😄

Better close icon

---

docs/documentation.md

docs(bower): show how to use bower

---

stories/CurrentFilters.stories.js
stories/HierarchicalMenu.stories.js
stories/Hits.stories.js
stories/HitsPerPage.stories.js
stories/Menu.stories.js
stories/MultiRange.stories.js
stories/Pagination.stories.js
stories/Range.stories.js
stories/RangeInput.stories.js
stories/RangeRatings.stories.js
stories/RefinementList.stories.js
stories/SearchBox.stories.js
stories/SortBy.stories.js
stories/Stats.stories.js
stories/Toggle.stories.js
stories/util.css
stories/util.js
storybook/addons.js

docs(storybook): display results for all widgets

---

package.json
stories/3rdPartiesIntegration.stories.js
storybook/config.js
storybook/head.html
storybook/public/rheostat.css

docs(storybook): add example connecting a Range with Airbnb Rheostat

---

packages/react-instantsearch/src/widgets/Pagination/Pagination.enzyme.test.js
packages/react-instantsearch/src/widgets/Pagination/Pagination.js
packages/react-instantsearch/src/widgets/Pagination/__snapshots__/Pagination.test.js.snap
packages/react-instantsearch/src/widgets/Pagination/connect.js
packages/react-instantsearch/src/widgets/Pagination/connect.test.js

feat(pagination): start the pagination at 1

---

package.json
stories/ClearAll.stories.js
stories/CurrentRefinements.stories.js
stories/HierarchicalMenu.stories.js
stories/Hits.stories.js
stories/HitsPerPage.stories.js
stories/Menu.stories.js
stories/MultiRange.stories.js
stories/Pagination.stories.js
stories/RangeInput.stories.js
stories/RangeRatings.stories.js
stories/RangeSlider.stories.js
stories/RefinementList.stories.js
stories/ScrollTo.stories.js
stories/SearchBox.stories.js
stories/SortBy.stories.js
stories/Stats.stories.js
stories/Toggle.stories.js
stories/util.js
storybook/head.html
storybook/public/util.css
yarn.lock

Add link for source code
Fix the prod/dev static assets
For playground, display the knobs on the right when accessed from the docs

docs(storybook): improve display

---

packages/react-instantsearch/src/components/HierarchicalMenu.css
packages/react-instantsearch/src/components/HierarchicalMenu.enzyme.test.js
packages/react-instantsearch/src/components/HierarchicalMenu.test.js
packages/react-instantsearch/src/components/List.js
packages/react-instantsearch/src/components/Menu.css
packages/react-instantsearch/src/components/Menu.enzyme.test.js
packages/react-instantsearch/src/components/Menu.test.js
packages/react-instantsearch/src/components/RefinementList.css
packages/react-instantsearch/src/components/RefinementList.enzyme.test.js
packages/react-instantsearch/src/components/RefinementList.test.js
packages/react-instantsearch/src/components/__snapshots__/HierarchicalMenu.test.js.snap
packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap

fix(List): disable show more button if no more item to display

---

docgen/src/component.md
docgen/src/gettingstarted.md
docgen/src/guides.md

Just read through some of the the new docs in anticipation and found some minor things

Fix minor documentation typos

---

package.json
yarn.lock

fix(slider): avoid multi touch issues

---

packages/react-instantsearch/src/connectors/connectCurrentRefinements.js
packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
packages/react-instantsearch/src/connectors/connectHitsPerPage.js
packages/react-instantsearch/src/connectors/connectMenu.js
packages/react-instantsearch/src/connectors/connectMultiRange.js
packages/react-instantsearch/src/connectors/connectPagination.js
packages/react-instantsearch/src/connectors/connectPoweredBy.js
packages/react-instantsearch/src/connectors/connectRange.js
packages/react-instantsearch/src/connectors/connectRefinementList.js
packages/react-instantsearch/src/connectors/connectScrollTo.js
packages/react-instantsearch/src/connectors/connectSearchBox.js
packages/react-instantsearch/src/connectors/connectSortBy.js
packages/react-instantsearch/src/connectors/connectStats.js
packages/react-instantsearch/src/connectors/connectToggle.js
packages/react-instantsearch/src/widgets/HierarchicalMenu.js
packages/react-instantsearch/src/widgets/RefinementList.js
packages/react-instantsearch/src/widgets/SortBy.js
packages/react-instantsearch/src/widgets/Toggle.js
storybook/public/util.css

add props/providedProps to connectors.
Also fixes some typos on widgets docs.

docs(connectors): add jsdoc to connectors

---

packages/react-instantsearch/src/core/InstantSearch.js
packages/react-instantsearch/src/core/createInstantSearchManager.js
packages/react-instantsearch/src/core/createInstantSearchManager.test.js

feat(api): Expose `algoliaClient` prop in InstantSearch

---

package.json
packages/react-instantsearch/scripts/build.sh

We were having some issues regarding the packaging of react-instantsearch.
Thanks @proudlygeek for spotting this !!

fix(build): missing files + css style were not injected

---

package.json
stories/RefinementList.stories.js
yarn.lock

docs(storybook): use knob array for RefinementList

---

docgen/src/guides/advanced-topics.md

docs(guide): improve url routing example readability

---

src/components/RefinementList/__tests__/RefinementList-test.js
src/components/Template.js
src/components/__tests__/Template-test.js
src/decorators/__tests__/headerFooter-test.js
src/widgets/refinement-list/__tests__/refinement-list-test.js
src/widgets/toggle/implementations/__tests__/currentToggle-test.js

This fixes the nasty regression bug we have seen and reimplement the
transformData fix

fix(transformData): default data is an object when not provided

---

stories/HierarchicalMenu.stories.js
stories/InfiniteHits.stories.js
stories/Menu.stories.js
stories/RefinementList.stories.js
stories/SortBy.stories.js
stories/util.js

-removed sortBy props #1601
-add infiniteHits entry
-fix sortBy default story

docs(storybook): clean up storybook

---

packages/react-instantsearch/src/connectors/connectSearchBox.js

docs(connectSearchBox): there's no options

---

docgen/src/stylesheets/components/_documentation.scss
packages/react-instantsearch/src/widgets/RangeRatings.js
stories/RefinementList.stories.js

- allow line breaks inside api tables
- change refinementList attributeName
- fix RangeRatings description.

docs: update typos + fix design

---

docgen/layouts/common/meta.pug
docgen/layouts/example.pug
docgen/src/examples/e-commerce-infinite/style.css
docgen/src/examples/e-commerce/style.css
docgen/src/examples/material-ui/App.js
docgen/src/examples/material-ui/style.css
docgen/src/examples/media/style.css
docgen/src/examples/tourism/App.js
docgen/src/examples/tourism/style.css
docgen/src/stylesheets/components/_header.scss
docgen/src/stylesheets/header.scss
docgen/src/stylesheets/index.scss

Our style examples should be safe now.

docs: isolate header from other documentation style

---

docgen/layouts/component/widget.pug
stories/ClearAll.stories.js
stories/CurrentRefinements.stories.js
stories/RefinementList.stories.js
stories/Stats.stories.js
stories/util.js
storybook/addons.js
storybook/config.js
storybook/public/util.css

docs(storybook): remove iframe from docs, instead use a button

---

packages/react-instantsearch/src/connectors/connectMenu.js
packages/react-instantsearch/src/connectors/connectMenu.test.js

fix(menu): selecting the currentRefinement should remove it.

---

stories/util.js
storybook/public/util.css

docs(storybook): adapt display to new widgets style

---

docgen/layouts/connector.pug
docgen/layouts/widget.pug

docs(links): fix links in connectors and widgets

---

docgen/layouts/common/header.pug
docgen/plugins/helpers.js
docgen/src/stylesheets/components/_dropdown.scss
docgen/src/stylesheets/components/_header.scss

docs(nav): add active links hints on top nav

---

packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
packages/react-instantsearch/src/connectors/connectMenu.js
packages/react-instantsearch/src/connectors/connectMenu.test.js
packages/react-instantsearch/src/connectors/connectMultiRange.js
packages/react-instantsearch/src/connectors/connectMultiRange.test.js
packages/react-instantsearch/src/connectors/connectRange.js
packages/react-instantsearch/src/connectors/connectRange.test.js
packages/react-instantsearch/src/connectors/connectRefinementList.js
packages/react-instantsearch/src/connectors/connectRefinementList.test.js
packages/react-instantsearch/src/connectors/connectToggle.js
packages/react-instantsearch/src/connectors/connectToggle.test.js

fix(state): when having two widgets of the same type, state were erased when refining

---

docgen/src/Getting started.md
docgen/src/examples/media/App.js
docgen/src/examples/tourism/App.js
docgen/src/guide/Highlighting results.md
packages/react-instantsearch/src/components/Hits.js
packages/react-instantsearch/src/components/Hits.test.js
packages/react-instantsearch/src/components/InfiniteHits.js
packages/react-instantsearch/src/components/InfiniteHits.test.js
packages/react-instantsearch/src/components/__snapshots__/Hits.test.js.snap
packages/react-instantsearch/src/components/__snapshots__/InfiniteHits.test.js.snap
packages/react-instantsearch/src/widgets/Hits.js
packages/react-instantsearch/src/widgets/InfiniteHits.js

BREAKING CHANGE: itemComponent is now named hitComponent in:
- Hits
- connectHit
- InfiniteHits
- connectInfiniteHits

feat(*Hits): rename itemComponent to hitComponent

---

docgen/src/Getting started.md
docgen/src/examples/default-theme/App.js
docgen/src/examples/default-theme/index.html
docgen/src/examples/default-theme/index.js
docgen/src/examples/default-theme/style.css
docgen/webpack.config.babel.js
packages/react-instantsearch-theme-algolia/style.scss
packages/react-instantsearch-theme-algolia/styles/_Highlight.scss
packages/react-instantsearch-theme-algolia/styles/_InstantSearch.scss
packages/react-instantsearch/dom.js
packages/react-instantsearch/native.js
packages/react-instantsearch/src/core/InstantSearch.js
packages/react-instantsearch/src/core/InstantSearch.test.js
packages/react-instantsearch/src/core/createInstantSearch.js
stories/Hits.stories.js
stories/util.js
storybook/public/util.css

**Summary**
- Move from no font to some sans-serif font (using the same rule as HTML5 boilerplate).
- Add highlight styling.
- Adds a wrapper container in InstantSearch
Also a start for a default theme playground to test the default theme.

fix(theme): Defaults for hits and highlights

---

.github/ISSUE_TEMPLATE.md

- react-instantsearch
- instantsearch.js
**Summary**
We want users to be very precise in their issue descriptions so we can better help them solve their problems. We also want to leverage discourse forum for generic questions.
**Result**
This will trigger a new issue template when opening issues.

chore(contributions): new issue template

---

docs/_assets/javascripts/home.js
docs/_assets/stylesheets/_marketing-banner.scss
docs/_assets/stylesheets/main.scss
docs/_config.yml
docs/documentation.md
docs/index.haml

Banner to instantsearch-react added on landing/doc

Add banner instantsearch-react

---

docgen/src/guide/Multi_index.md
packages/react-instantsearch/examples/multi-index/README.md
packages/react-instantsearch/examples/multi-index/package.json
packages/react-instantsearch/examples/multi-index/public/index.html
packages/react-instantsearch/examples/multi-index/src/App.js
packages/react-instantsearch/examples/multi-index/src/index.js
packages/react-instantsearch/examples/react-router/src/App.js
packages/react-instantsearch/examples/reactnative/App.js

see #1746 
Also add our multi-index example into our examples directory.

docs(examples): use only 'latest' and 'react' babel preset syntaxes

---

dev/webpack.staging.config.babel.js
package.json
scripts/staging-deploy.sh
yarn.lock

*instantsearch.js*
**Summary**
Easily deploy the content of /dev to surge to be able to provide links to live env in PR.
**Result**
`yarn run staging` 🔥

build(staging): Easy deploy the dev html to surge

---

.eslintignore
dev/app.js
dev/index.html
scripts/staging-deploy.sh
src/components/RefinementList/RefinementList.js
src/components/SearchBox/index.js
src/components/Template.js
src/components/__tests__/Template-test.js
src/css/default/_refinement-searchbox.scss
src/css/instantsearch.scss
src/widgets/refinement-list/defaultTemplates.js
src/widgets/refinement-list/refinement-list.js
yarn.lock

*This is a preview PR and I would love your input on the implementation, as well as the configuration options. The commits will be squashed to have a proper history.*
**Summary**
This PR provides an implementation of options to be able to search into facet values in the refinementList widget. When activated it adds a search input on top of the list, the results are replacing the values in the list. Pressing return when there are search results, selects the first item.
The API tries to stay consistent with the current implementation with a configuration object that  defaults and with the following structure (using the structure enables the feature):
- placeholder: string (plain text)
- templates: object
- templates.noResults: string (html  template)
**Result**
[See it …

[Search for facet values] Refinement list - InstantSearch.js

---

packages/react-instantsearch/src/components/StarRating.js
packages/react-instantsearch/src/components/StarRating.test.js

fix(starRatings): click on selected range doesn't unselect it

---

docgen/src/examples/material-ui/App.js
docgen/src/examples/material-ui/style.css

UI/UX changes: 
* Add the SearchBox inside the AppBar
* The example can be used on mobile
cc @seafoox

docs(examples): improve material-ui

---

src/lib/url-sync.js

Updating the url bar constantly may be a challenge for some OS +
browsers (OSX, chrome), I want to push this option and see if it's
better for users.

feat(url): add a beta updateOnEveryKeystroke option

---

docgen/src/guide/index.md

Plus a few small text cleanups.

Mention Algolia's hacker plan alongside the trial in the guide

---

docgen/layouts/common/footer.pug
docgen/layouts/common/marketing.pug
yarn.lock

Marketing trackers for react-instantsearch website.

misc(doc): add marketing stuff

---

docs/index.haml

misc(doc): fix typo

---

docgen/src/guide/React_native.md

Fix link to React native example on github

---

docgen/layouts/common/hero.pug
docgen/layouts/common/meta.pug
docgen/src/Getting_started.md
docgen/src/guide/index.md
docgen/src/index.md
packages/react-instantsearch/package.json

docs(SEO): Consistent taglines, titles, description and instant-search usage

---

docgen/src/guide/Search_for_facet_values.md
packages/react-instantsearch-theme-algolia/style.scss
packages/react-instantsearch-theme-algolia/styles/_Menu.scss
packages/react-instantsearch-theme-algolia/styles/_RefinementList.scss
packages/react-instantsearch/src/components/List.js
packages/react-instantsearch/src/components/Menu.js
packages/react-instantsearch/src/components/Menu.test.js
packages/react-instantsearch/src/components/RefinementList.js
packages/react-instantsearch/src/components/RefinementList.test.js
packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
packages/react-instantsearch/src/connectors/connectCurrentRefinements.js
packages/react-instantsearch/src/connectors/connectCurrentRefinements.test.js
packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
packages/react-instantsearch/src/connectors/connectHitsPerPage.js
packages/react-instantsearch/src/connectors/connectHitsPerPage.test.js
packages/react-instantsearch/src/connectors/connectMenu.js
packages/react-instantsearch/src/connectors/connectMenu.test.js
packages/react-instantsearch/src/connectors/connectMultiRange.js
packages/react-instantsearch/src/connectors/connectMultiRange.test.js
packages/react-instantsearch/src/connectors/connectRefinementList.js
packages/react-instantsearch/src/connectors/connectRefinementList.test.js
packages/react-instantsearch/src/connectors/connectSortBy.js
packages/react-instantsearch/src/connectors/connectSortBy.test.js
packages/react-instantsearch/src/core/createConnector.js
packages/react-instantsearch/src/core/createConnector.test.js
packages/react-instantsearch/src/widgets/Menu.js
packages/react-instantsearch/src/widgets/RefinementList.js
stories/Menu.stories.js

feat(Menu, connectMenu): add search for facet values

---

packages/react-instantsearch/src/connectors/connectSearchBox.js
packages/react-instantsearch/src/connectors/connectSearchBox.test.js
stories/SearchBox.stories.js

fix(connectSearchBox): handle `defaultRefinement`

---

packages/react-instantsearch/src/connectors/connectSearchBox.js

chore(connectSearchBox): add missing propTypes

---

docgen/src/Getting_started.md

this is for react-instantsearch
Otherwise it won't render the SFFV searchbox correctly.

doc(getting-started): fix version for CSS theme

---

docgen/src/examples/e-commerce-infinite/App.js
docgen/src/examples/e-commerce/App.js
docgen/src/examples/media/App.js

docs: remove autoComplete from input in the examples

---

packages/react-instantsearch/src/connectors/connectMenu.js
packages/react-instantsearch/src/connectors/connectMenu.test.js
packages/react-instantsearch/src/connectors/connectRefinementList.js
packages/react-instantsearch/src/connectors/connectRefinementList.test.js
packages/react-instantsearch/src/core/createInstantSearchManager.js
packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js

fix(SFFV): empty query was triggered a new SFFV

---

docgen/src/Getting_started.md
docgen/src/guide/<InstantSearch>.md
docgen/src/guide/Custom_connectors.md
docgen/src/guide/Install.md
docgen/src/guide/Multi_index.md
docgen/src/guide/Routing.md
docgen/src/guide/Search_for_facet_values.md
docgen/src/guide/Widgets.md

- react-instantsearch doc
**Summary**
While getting familiar with the guide and API, I fixed typos, or added clarification along the way.

doc(guide): fix typos and add some links

---

.github/ISSUE_TEMPLATE.md

Provides an example to start when providing a live example of a bug.

misc(issue template): starting point for jsFiddle

---

docgen/assets/js/header.js
docgen/layouts/common/meta.pug

docs(header): fix infinite setTimeout loop for docSearch shortcuts

---

docgen/src/examples/Demos.md
docgen/src/examples/e-commerce-infinite/App.js
docgen/src/examples/e-commerce/App.js
docgen/src/examples/material-ui/App.js
docgen/src/examples/tourism/App.js

docs(examples): provide real titles instead of amazing

---

packages/react-instantsearch/src/components/List.js
packages/react-instantsearch/src/components/MultiRange.js
packages/react-instantsearch/src/components/MultiRange.test.js
packages/react-instantsearch/src/connectors/connectMultiRange.js
packages/react-instantsearch/src/connectors/connectMultiRange.test.js
packages/react-instantsearch/src/widgets/MultiRange.js

For the MultiRange, compute a boolean for each item range in order to add classes like:

feat(MultiRange): indicate if a range has no refinements

---

packages/react-instantsearch/src/components/StarRating.js
packages/react-instantsearch/src/components/StarRating.test.js
packages/react-instantsearch/src/connectors/connectRange.js
stories/StarRating.stories.js

https://deploy-preview-1933--algolia-instantsearch.netlify.com/instantsearch.js/react/storybook/?selectedKind=StarRating&selectedStory=with%20filter%20on%20rating&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs

fix(StarRating): usage with filters

---

docgen/src/guide/Custom_connectors.md

doc(customConnector): Fix example

---

packages/react-instantsearch/src/components/ClearAll.js
packages/react-instantsearch/src/components/ClearAll.test.js
packages/react-instantsearch/src/connectors/connectCurrentRefinements.js
packages/react-instantsearch/src/connectors/connectCurrentRefinements.test.js
packages/react-instantsearch/src/widgets/ClearAll.js
stories/ClearAll.stories.js
stories/util.js

https://deploy-preview-1958--algolia-instantsearch.netlify.com/instantsearch.js/react/storybook/?selectedKind=ClearAll&selectedStory=clear%20all%20refinements%20and%20the%20query&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs

feat(ClearAll): add withQuery to also clear the search query

---

docgen/src/guide/Conditional_display.md

**Summary**
The sentence "no results has been found" sounds a bit weird, I simplified it
**Result**
The sentence is now "No results found for {query}".

docs(guide): Conditional display code sample

---

docs/_includes/widget-jsdoc/infiniteHits.md
docs/documentation.md
src/components/InfiniteHits.js
src/widgets/infinite-hits/__tests__/infinite-hits-test.js
src/widgets/infinite-hits/infinite-hits.js

fixes #1971
http://psychotic-finger.surge.sh/?query=sdhc%2010g%20sandisk%20pixto&hits=3&idx=instant_search&p=0&hierarchical%5BhierarchicalCategories.lvl0%5D%5B0%5D=Cameras%20%26%20Camcorders&nR%5Bpopularity%5D%5B%3E%3D%5D%5B0%5D=0&is_v=1
You can load more in this URL but not more than 2 times :)
cc. @julienpa @vvo

fix(infinite-hits): fix load more when no more pages

---

docgen/src/Getting_started.md

Missing bracket in react-instantsearch docs.

Added missing bracket on line 215

---

docgen/src/guide/Default_refinements.md

Fixed broken next link on Default_refinements.md

Update broken next link on Default_refinements.md

---

packages/react-instantsearch/src/widgets/RangeSlider.js

docs(slider): update the static example

---

packages/react-instantsearch/examples/react-router-v4/package.json
packages/react-instantsearch/examples/react-router-v4/src/App.js
packages/react-instantsearch/examples/react-router-v4/src/index.js

docs(react-router-v4): update API

---

packages/react-instantsearch/src/connectors/connectInfiniteHits.js

Could figure out to to load more until looking at the source
**Summary**
Documentation didn't contain information on the function to load more in the infiniteHits connector
**Result**
Just added line to documentation comment

Add documentation to infiniteHits connector

---

docgen/layouts/common/footer.pug

In #2033 I suggest fixing the utm of the footer of the main IS
website. This might in turn require updating that one so they are
different
(Not 100% sure it's required, though)

docs(utm): Updating the utm in the footer

---

docs/_includes/footer.html

Replaced the footer utm with a better one, not referencing Places

docs(utm): Replaced leftover `utm` from Places

---

packages/react-instantsearch/src/components/InfiniteHits.js
packages/react-instantsearch/src/widgets/InfiniteHits.js

fix(InfiniteHits): provide translation key for `Load More`

---

packages/react-instantsearch/dom.js
packages/react-instantsearch/src/core/createInstantSearchManager.error.test.js
packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
packages/react-instantsearch/src/core/createInstantSearchManager.test.js

**Summary**
React instantsearch will never index or do other functions, so just /lite should be good.
(to be tested thoroughly!)
**Result**
Just algoliasearch/lite is imported

feat(size) use algoliasearch/lite

---

README.md

doc(README): fixed typo

---

docs/index.haml

**Summary**
Removed instantsearch.js subdirectory in link to react-instantsearch page. Previously it caused a 404 and now points to the correct page.
**Result**
The link now goes to the correct URL, as evidenced by the following screenshot:

Correct link to react-instantsearch page

---

.github/ISSUE_TEMPLATE.md

**Summary**
Add a "propose solution" section to the issue section.
This is useful if whoever writes the issue already knows how to solve a certain bug.
**Result**
There's a new section called "Bug: What is the proposed solution?"

docs(issue_template): add a "solution proposal" question

---

docgen/src/guides/migration.md
package.json
src/components/Slider/Pit.js
src/components/Slider/Slider.js
src/components/Slider/__tests__/Slider-test.js
src/components/Slider/__tests__/__snapshots__/Slider-test.js.snap
src/css/default/_range-slider.scss
src/widgets/range-slider/__tests__/__snapshots__/range-slider-test.js.snap
src/widgets/range-slider/__tests__/range-slider-test.js
src/widgets/range-slider/range-slider.js
yarn.lock

feat(range-slider): use `rheostat` as slider component

---

CONTRIBUTING.md
functional-tests/config.js
functional-tests/test.js
functional-tests/utils.js
package.json

Just ran them, should be ok now

test(functional): fix CI ip, should be localhost

---

dev/app/index.js
dev/app/init-builtin-widgets.js
dev/app/init-jquery-widgets.js
dev/app/init-vanilla-widgets.js
dev/app/templates/item.html
dev/app/wrap-with-hits.js
dev/index.html
dev/style.css
package.json
yarn.lock

**Summary**
I really liked the developper experience while using storybook for react-instantsearch. Too bad storybook is sticked to a React environment.
To achieve a similar experience, I used https://github.com/algolia/dev-novel (still private to Algolians) which will enable us to test independently the result of every widgets in a much easier way.
I'll add more use-cases of the widgets with default `SearchParameters` while doing #2193 
**Result**

use dev-novel in dev environment

---

docgen/yarn.lock
src/components/Slider/Slider.js
src/connectors/range-slider/connectRangeSlider.js
src/lib/InstantSearch.js
src/lib/__tests__/InstantSearch-test-2.js
src/lib/__tests__/InstantSearch-test.js

This implementation offers:
- a full helper to modify the parameters before sending the request
- all the other search function (searchOnce, searchForFacetValues)
- compatibility with async code (no oops effect)
*warning*: This also contains a modification of the slider to be extra sure that we'll never update the state unnecessarily https://github.com/algolia/instantsearch.js/commit/8b7a6eb60fe879c0fa9841931dffbe2d91d1b24b
Fixes #1924 
- [Deployed version with 2sec lag of all search requests](http://flashy-art.surge.sh/): test the async
- [Nominal version](http://bite-sized-birth.surge.sh/): just a simple search function, this also serve to test the perf of the search function mechanics
- [without any search function implementation](http://busy-snail.surge.sh/): let you test the slider …

Make search function provide a better API

---

README.md

Since we have projects outside of js

docs(readme): Family is InstantSearch, not InstantSearch.js

---

package.json
yarn.lock

Update JS Helper and algolia JS client.

chore(dep): update algoliasearch and algoliasearch-helper

---

docgen/src/data/communityHeader.json

chore(doc): fix header menu on mobile

---

docgen/src/guides/customization.md

chore(doc): fix link to connectMenu

---

README.md

**Summary**
@jonasba tested, and IE9 and lower does not work. Older Safari, Chrome, FF versions are not checked explicitly
**Result**
add a sentence to show we support the latest two versions

docs(readme): list supported browsers

---

README.md
src/css/theme/_base.scss

fix(theme): enforce box-sizing: border-box

---

scripts/release.sh

related to #2230
* run release from develop
* then merge release from develop into master branch

chore(release): allow releases from develop

---

docgen/src/data/communityHeader.json
docgen/src/guides/opensearch.md
docgen/src/stylesheets/components/_code-highlighting.scss
docgen/syntaxHighlighting.js
docgen/yarn.lock
yarn.lock

For this guide, we've also added the syntax highlighting for diff patches.
Fix #2088

feat(doc): Add a guide for opensearch

---

docgen/assets/js/main.js
docgen/src/stylesheets/components/_documentation.sass
docgen/src/stylesheets/components/_sidebar.sass

fix #2221
Also:
- hide `edit this page` button on mobile

chore(doc): foldable sidebar on mobile

---

docgen/src/widgets.md

remove duplicate 'using'

---

docgen/src/data/communityHeader.json
docgen/src/guides/no-result.md

chore(doc): Design a no-result page

---

docgen/src/data/communityHeader.json
docgen/src/guides/custom-widget.md

chore(doc): add a custom widget guide

---

README.md

docs(readme): add link to IS iOS

---

docgen/layouts/connector.pug
docgen/layouts/widget-showcase.pug
docgen/layouts/widget.pug
docgen/plugins/documentationjs-data.js
src/widgets/hierarchical-menu/hierarchical-menu.js
src/widgets/menu/menu.js
src/widgets/numeric-refinement-list/numeric-refinement-list.js
src/widgets/numeric-selector/numeric-selector.js
src/widgets/price-ranges/price-ranges.js
src/widgets/range-slider/range-slider.js
src/widgets/refinement-list/refinement-list.js
src/widgets/star-rating/star-rating.js
src/widgets/toggle/toggle.js

WIP. This is hacky, I did not manage to add @requirements tags
fixes #2302

docs(requirements): add requirements for every widget

---

dev/app/init-builtin-widgets.js
src/widgets/infinite-hits/infinite-hits.js

Fix #2314
The feature was there but not documented.

chore(doc): add showmore cssClass option to doc

---

package.json
yarn.lock

fix(rheostat): use algolia fork

---

dev/app/init-builtin-widgets.js
src/components/Slider/Slider.js
src/components/Slider/__tests__/Slider-test.js
src/components/Slider/__tests__/__snapshots__/Slider-test.js.snap
src/connectors/range-slider/__tests__/connectRangeSlider-test.js
src/connectors/range-slider/connectRangeSlider.js

**Summary**
* When setting `pips: false` it was still showing pips
* Refine on range boundaries where not correctly applied
Fixes #2343

Fix range slider pips and value 0

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

add some explanation to what happens when creating a PR, and show how to use the preview
Also fixed the image in there
see https://github.com/algolia/instantsearch.js/pull/2383

docs(contributing): explain deploy previews

---

scripts/docs/build-dev.sh

Publish dev-novel in a production ready build (without any socket involved or anything :D)

chore(dev-novel): Use production when build doc

---

docgen/src/connectors.md

Adds a link to custom widget documentation.

Add link for custom-widget docs.

---

docgen/package.json

fixes #2420
**Summary**
This will force renovate to come and pin our docgen dependencies, ensuring a stable env
**Result**

chore(dependencies): declare docgen deps as devDeps

---

dev/app/custom-widgets/jquery/currentRefinedValues.js
dev/app/custom-widgets/jquery/hitsPerPageSelector.js
dev/app/custom-widgets/jquery/numericSelector.js
dev/app/custom-widgets/jquery/pagination.js
dev/app/custom-widgets/vanilla/selectMenu.js
index.es6.js
scripts/test-ci.sh
src/components/__tests__/Template-test.js
src/connectors/numeric-selector/connectNumericSelector.js
src/css/theme/_base.scss
src/css/theme/_hits-per-page.scss
src/css/theme/_pagination.scss
src/css/theme/_price-ranges.scss
src/css/theme/_search-box.scss
src/css/theme/_variables.scss
src/decorators/__tests__/autoHideContainer-test.js
src/lib/__tests__/url-sync-test.js

This PR provides a fix for #2426.
I just fix the lint errors not all the warnings.

Fix CI lint

---

.editorconfig

chore(formatting): add .editorconfig

---

src/connectors/hierarchical-menu/connectHierarchicalMenu.js

**Summary**
I found the example link at [](https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html )
And github return 404 not found, 
then I find the example at git repository and its available at 
https://github.com/algolia/instantsearch.js/blob/develop/dev/app/custom-widgets/jquery/hierarchicalMenu.js
**Result**
Update url from (https://github.com/algolia/instantsearch.js/blob/feat/instantsearch.js/v2/dev/app/custom-widgets/jquery/hierarchicalMenu.js)
to (https://github.com/algolia/instantsearch.js/blob/develop/dev/app/custom-widgets/jquery/hierarchicalMenu.js)
User will can see the example immediately when click example link

Update example url on connectHierarchicalMenu document

---

src/widgets/menu-select/menu-select.js

Properties documented were wrong. Thanks to @timothyjblevins for noticing that!
Fix #2453

chore(doc): fix select template parameters

---

src/widgets/menu-select/__tests__/menu-select-test.js
src/widgets/menu-select/menu-select.js

menuSelect widget was done with React and in between we merged the Preact dependency move 👍

fix(menuSelect): use preact instead of React

---

src/widgets/clear-all/__tests__/clear-all-test.js
src/widgets/current-refined-values/__tests__/current-refined-values-test.js
src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
src/widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
src/widgets/hits/__tests__/hits-test.js
src/widgets/infinite-hits/__tests__/infinite-hits-test.js
src/widgets/menu/__tests__/menu-test.js
src/widgets/numeric-refinement-list/__tests__/numeric-refinement-list-test.js
src/widgets/numeric-selector/__tests__/numeric-selector-test.js
src/widgets/pagination/__tests__/pagination-test.js
src/widgets/price-ranges/__tests__/price-ranges-test.js
src/widgets/range-slider/__tests__/range-slider-test.js
src/widgets/sort-by-selector/__tests__/sort-by-selector-test.js
src/widgets/star-rating/__tests__/star-rating-test.js
src/widgets/stats/__tests__/stats-test.js
src/widgets/toggle/__tests__/currentToggle-test.js

fix(test): correctly reset the wired dependency

---

src/css/theme/_base.scss
src/css/theme/_hits-per-page.scss
src/css/theme/_menu-select.scss

style(menuSelect): apply select theme

---

docgen/src/data/communityHeader.json

fixes #2452, this looked bad
**Summary**
**Result**

docs(v1): sane menu width

---

package.json
scripts/test-ci.sh
yarn.lock

**Summary**
Try `bundlesize` on the build pipeline. 
Check if the feedback is interesting, if it's not the case we can remove it 🙂

Feat bundlesize

---

.travis.yml

Make the CI check the tests on version branches.

chore(ci): ci tests on version branches

---

dev/app/init-builtin-widgets.js
src/components/Slider/__tests__/Slider-test.js
src/components/Slider/__tests__/__snapshots__/Slider-test.js.snap
src/widgets/range-slider/__tests__/__snapshots__/range-slider-test.js.snap
src/widgets/range-slider/__tests__/range-slider-test.js
src/widgets/range-slider/range-slider.js

**Summary**
Fix #2501 
**Result**
You can play with the story `collapsible` on `RangeSlider` in [`dev-novel`](https://deploy-preview-2502--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=RangeSlider.collapsible).

Fix range slider collapsible

---

src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/refinement-list/connectRefinementList.js

fix(connectRefinementList): set default value for limit

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
README.md
package.json

This PR changes the wording and the structure of the CONTRIBUTING and README. The idea is to make those already great content more friendly to our potential contributors, as well as adding new key elements for a new contribution.

chore:reword content for contributors

---

docgen/src/guides/angular-integration.md

**Summary**
Fixed typo in InstantSearchService import statement
**Result**
Importing service is successful

Fixed typo in InstantSearchService import

---

src/connectors/refinement-list/connectRefinementList.js

fix(connectRefinementList): add label to searched items

---

docgen/src/guides/angular-integration.md

I have added a message about Angular InstantSearch to redirect users to the new library 👍

docs(angular): add message about angular instantsearch

---

docs/examples.haml

fixes #2631
Needs republishing of website, this is documented in CONTRIBUTING

docs(v1): fix examples GitHub links

---

docgen/src/guides/migration.md

**Summary**
fixed a link that was broken

docs(migration): fixed broken link

---

docgen/layouts/common/footer.pug

Fixes https://github.com/algolia/instantsearch.js/issues/2666 #2536

docs(Homepage): fix SVG icons not displaying correctly in Firefox

---

docgen/CONTRIBUTING.md
docgen/src/guides/calendar-widget.md

**Summary**
* The `index` attribute in the documentation is actually called `indexName`.
* The `indexName` attribute in the frontmatter of a documentation page is now supported.

Specify `indexName` in guide

---

src/connectors/clear-all/connectClearAll.js
src/connectors/current-refined-values/connectCurrentRefinedValues.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/connectors/hits-per-page/connectHitsPerPage.js
src/connectors/hits/connectHits.js
src/connectors/infinite-hits/connectInfiniteHits.js
src/connectors/menu/connectMenu.js
src/connectors/numeric-refinement-list/connectNumericRefinementList.js
src/connectors/numeric-selector/connectNumericSelector.js
src/connectors/pagination/connectPagination.js
src/connectors/price-ranges/connectPriceRanges.js
src/connectors/range/connectRange.js
src/connectors/refinement-list/connectRefinementList.js
src/connectors/search-box/connectSearchBox.js
src/connectors/sort-by-selector/connectSortBySelector.js
src/connectors/star-rating/connectStarRating.js
src/connectors/stats/connectStats.js
src/connectors/toggle/connectToggle.js

Checked:
- URLs for connectors
- API name

chore(dx): make sure that the usage message are correct

---

docgen/src/stylesheets/components/_sidebar.sass

Fix #2667 
Removes the horizontal scroll, can't do anything about fading them or not.

chore(doc): remove horizontal scroll in sidebar

---

README.md

docs(readme): add missing instantsearch

---

src/widgets/breadcrumb/breadcrumb.js

docs: update Breadcrumb widget example

---

src/widgets/geo-search/geo-search.js

**Summary**
1. wdiget
2. informations (no need to make it plural)
**Result**
fixed typos

docs(geo): typo fixes

---

src/connectors/geo-search/connectGeoSearch.js
src/widgets/geo-search/geo-search.js

docs(GeoSearch): use static example

---

docgen/src/guides/customization.md

see #2394, cc @gzzo
**Summary**
link earlier was to ../ which goes to the page without the v2 prefix 
**Result**
link is really relative now

docs(customisation): make link relative

---

src/css/theme/_geo-search.scss

fix(GeoSearch): override button style

---

functional-tests/app/index.html
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/lib/InstantSearch.js
src/lib/__tests__/escape-highlight-test.js
src/lib/__tests__/utils-test.js
src/widgets/geo-search/GeoSearchRenderer.js
src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
src/widgets/geo-search/__tests__/geo-search-test.js
src/widgets/geo-search/geo-search.js
src/widgets/range-slider/__tests__/range-slider-test.js

doc(core): fix typos

---

docgen/package.json
docgen/yarn.lock
package.json
yarn.lock

Also increase the threshold for the size of the bundle (hopefully temporarily)

chore(deps): update node-sass

---

src/lib/InstantSearch.js
src/lib/__tests__/__snapshots__/InstantSearch-test.js.snap

**Summary**
fixes #2730 (see that issue for context)
**Result**
Now you can have InstantSearch as a dependency in a rollup **UMD** build

fix(main): correctly import EventEmitter

---

package.json

**Summary**
keywords on package.json are useful for filtering
**Result**
```json
{
"keywords": [
"algolia",
"instantsearch",
"search",
"vanilla"
]
}
```

chore(pkg): add keywords

---

docgen/src/guides/routing.md

Just a small update, see https://github.com/algolia/instantsearch.js/pull/2879#discussion_r180686523

docs(routing): update code sample

---

docgen/src/data/communityHeader.json

Instead of InstantSearch React

docs(header): use React InstantSearch

---

dev/app/builtin/stories/geo-search.stories.js

**Summary**
The previous APIKey was on my account. This one is on the Algolia account.

chore(stories): update Google Maps APIKey

---

docgen/src/widgets-common-api.md

Sentence correction in #cssClasses paragraph

---

docgen/src/examples/tourism/index.html

Do you see another places where the key might be?

chore(example): update Google Maps API Key in Tourism

---

docgen/src/guides/usage.md.hbs

**Summary**
Just fixing a small typo.
**Result**
N/A

docs(usage): fix a typo

---

docs/_layouts/default.html
docs/examples/e-commerce/index.html
docs/examples/media/index.html
docs/examples/tourism/index.html

Results for v1 are still in Google, I had put a robots.txt but since
it's not at the root of community.algolia.com it did not work, this
should work 100% sure

docs(seo): disallow crawler/remove v1 results from google

---

dev/app/builtin/stories/breadcrumb.stories.js
dev/app/index.js
dev/template.html
docgen/src/guides/migrate-instantsearchcss.md
src/components/Breadcrumb/Breadcrumb.js
src/components/Breadcrumb/__tests__/Breadcrumb-test.js
src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb-test.js.snap
src/widgets/breadcrumb/breadcrumb.js
src/widgets/breadcrumb/defaultTemplates.js

This PR contains a modified version of the breadcrumb to comply with is.css

feat(breadcrumb): is.css implementation of breadcrumb

---

README.md

doc(Readme): add "we're hiring"

---

index.es6.js

fix(warning): make sure suggested import is possible

---

src/connectors/hierarchical-menu/connectHierarchicalMenu.js

**Summary**
The link was broken.
**Result**
Now it's not :tada:

Fix link to hierarchicalMenu.js example

---

src/components/InfiniteHits.js
src/widgets/infinite-hits/__tests__/__snapshots__/infinite-hits-test.js.snap
src/widgets/infinite-hits/infinite-hits.js

**Summary**
See #2165
**Result**
I added a `showmoreButton` option to `cssClasses` for the `infiniteHits` widget.

feat(infiniteHits): add showmoreButton to cssClasses

---

dev/app/builtin/init-stories.js
dev/app/builtin/stories/menu-select.stories.js

This PR adds a set of stories for menu-select.

docs(dev-novel): add menu-select

---

dev/app/builtin/stories/geo-search.stories.js

Just a correction for a super minor misspelling.

style: fix misspelled variable

---

scripts/release.js

Incorrect git command for resetting master during a rollback.

chore(release): fix rollback command

---

src/css/theme/_search-box.scss
src/css/theme/_variables.scss

This PR is created to fix #3075

Add missing color to searchbox input field

---

docgen/src/examples/e-commerce/index.html

The "materials" refinement list is not used anymore.

docs(demo): clean up e-commerce

---

docgen/src/guides/angular-integration.md

docs: fix typos

---

dev/app/builtin/stories/menu-select.stories.js
docgen/src/guides/v3-migration.md
src/components/MenuSelect.js
src/components/__tests__/MenuSelect-test.js
src/components/__tests__/__snapshots__/MenuSelect-test.js.snap
src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/menu/connectMenu.js
src/widgets/menu-select/__tests__/__snapshots__/menu-select-test.js.snap
src/widgets/menu-select/__tests__/menu-select-test.js
src/widgets/menu-select/defaultTemplates.js
src/widgets/menu-select/menu-select.js
src/widgets/menu/menu.js

[spec](https://instantsearch-css.netlify.com/widgets/menu-select/)
Nothing special about this one. Just a markup update and `attributeName` -> `attribute`

feat(menuSelect): implement is.css

---

index.es6.js

See https://github.com/algolia/instantsearch.js/pull/3132#discussion_r219532900

feat(highlight): export function highlight

---

package.json
yarn.lock

chore: add Jest typeahead plugin

---

src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb-test.js.snap
src/components/Stats/__tests__/__snapshots__/Stats-test.js.snap
src/components/__tests__/__snapshots__/Template-test.js.snap
src/lib/__tests__/utils-test.js
src/lib/utils.js
src/widgets/breadcrumb/__tests__/__snapshots__/breadcrumb-test.js.snap
src/widgets/breadcrumb/breadcrumb.js
src/widgets/breadcrumb/defaultTemplates.js

feat: compress templates

---

package.json
yarn.lock

ref: https://github.com/algolia/instantsearch.js/issues/984#issuecomment-427830179

fix(deps): unpinned production dependencies

---

package.json

chore(scripts): remove finish-release

---

package.json

This makes `package.json` easier to read.

chore(package): reorder fields

---

README.md
package.json

This updates the tagline of the package (approved by @mthuret). I will edit the GitHub description when this PR gets merged.
I also added a campaign URL to keep track of the links usage.

chore(package): update description

---

README.md

This replaces the previous `attributeName` option to `attribute`.

docs(readme): update Getting Started

---

dev/app/builtin/stories/current-refinements.stories.js

This adds a default story to CurrentRefinements so that existing links in the documentation redirect to the correct story.
Link to the story: https://deploy-preview-3252--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=CurrentRefinements.default

feat(stories): add default CurrentRefinements story

---

scripts/dev-functional-tests-compile-watch.js

This updates the development functional tests to Rollup.

build(dev): update functional tests to Rollup

---

package.json
src/components/Selector/__tests__/Selector-test.js
src/components/Selector/__tests__/__snapshots__/Selector-test.js.snap
src/components/Slider/__tests__/Slider-test.js
src/components/Template/__tests__/Template-test.js
yarn.lock

This converts the remaining tests using `react-test-renderer` to `enzyme`.

refactor(tests): convert to Enzyme

---

src/widgets/range-input/range-input.js

This fixes the documentation of the CSS classes for the widget `rangeInput`.

docs(rangeInput): update CSS classes

---

docgen/src/guides/migration.md

**Summary**
Documentation typo fix

docs(migration): boolan -> boolean

---

src/connectors/clear-refinements/__tests__/connectClearRefinements-test.js
src/connectors/clear-refinements/connectClearRefinements.js
src/lib/__tests__/utils-test.js
src/lib/utils.js
src/widgets/clear-refinements/__tests__/__snapshots__/clear-refinements-test.js.snap
src/widgets/clear-refinements/__tests__/clear-refinements-test.js
src/widgets/clear-refinements/clear-refinements.js
src/widgets/clear-refinements/defaultTemplates.js
storybook/app/builtin/stories/clear-refinements.stories.js

https://instantsearch-css.netlify.com/widgets/clear-refinements/
https://deploy-preview-3308--instantsearchjs.netlify.com/stories/?selectedStory=ClearRefinements.default

feat(clearRefinements): implement InstantSearch.css

---

docgen/src/examples/media/index.html
docgen/src/examples/media/main.scss
docgen/src/examples/media/search.js

This uses the latest beta version for now (https://cdn.jsdelivr.net/npm/instantsearch.js@beta).
Demo: https://deploy-preview-3352--instantsearchjs.netlify.com/examples/media/

chore(examples): migrate Media example

---

src/connectors/menu/connectMenu.js
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/refinement-list/connectRefinementList.js
src/widgets/refinement-list/__tests__/__snapshots__/refinement-list-test.js.snap
src/widgets/refinement-list/__tests__/refinement-list-test.js
src/widgets/refinement-list/refinement-list.js
storybook/app/builtin/stories/refinement-list.stories.js

Implements #3343 fixes for `refinementList`.

fix(refinementList): update "show more" behavior

---

src/components/MenuSelect/MenuSelect.js
src/components/MenuSelect/__tests__/MenuSelect-test.js
src/components/MenuSelect/__tests__/__snapshots__/MenuSelect-test.js.snap
src/widgets/menu-select/__tests__/__snapshots__/menu-select-test.js.snap
src/widgets/menu-select/defaultTemplates.js
src/widgets/menu-select/menu-select.js
storybook/app/builtin/stories/menu-select.stories.js

Related: algolia/vue-instantsearch#595

feat(menuSelect): rename seeAllOptions template to defaultOption

---

docgen/layouts/example.pug
docgen/src/examples/e-commerce/index.html
docgen/src/examples/e-commerce/main.scss
docgen/src/examples/e-commerce/search.js

This upgrades the E-commerce example to InstantSearch 3.0.0.
Demo: https://deploy-preview-3374--instantsearchjs.netlify.com/examples/e-commerce/

chore(examples): upgrade E-commerce example

---

docgen/layouts/common/header.pug
docgen/src/stylesheets/components/_banner.sass
docgen/src/stylesheets/style.sass

docs(banner): link to the Algolia documentation website

---

package.json
src/index.es.js
src/lib/main.js
yarn.lock

**Summary**
The impact this module is having on our code base is negligent, but it takes up space, and can be removed since it's so trivial.
**Result**
This save a little bit of space (.1 / .05 kb gz)
fixes #3327
**Build before**
```
~/g/instantsearch.js (develop|✚1) $ yarn build
yarn run v1.12.3
$ yarn run build:cjs && yarn run build:es && yarn run build:umd
$ BABEL_ENV=cjs babel src --out-dir cjs/ --ignore src/index.es.js,__tests__,__mocks__ --quiet
$ BABEL_ENV=es babel src --out-dir es/ --ignore src/index.es.js,__tests__,__mocks__ --quiet && BABEL_ENV=es babel src/index.es.js --out-file es/index.js --quiet
$ BABEL_ENV=umd rollup --config scripts/rollup.config.js
src/index.js → dist/instantsearch.development.js...
┌────────────────────────────────────────────────────┐
│ …
```

chore(core): remove to-factory

---

stories/hits.stories.js

This story has never worked with this dataset.

chore(stories): remove hits with highlighted array story

---

README.md

The stories link has changed since #3376.

docs(readme): update stories link

---

src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/refinement-list/connectRefinementList.js
src/widgets/refinement-list/__tests__/refinement-list-test.js
src/widgets/refinement-list/refinement-list.js

This updates the usage errors for `refinementList`.

fix(refinementList): update usage errors

---

src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
src/widgets/hierarchical-menu/hierarchical-menu.js

This updates the usage errors for `hierarchicalMenu`.

fix(hierarchicalMenu): update usage errors

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
src/connectors/breadcrumb/connectBreadcrumb.js
src/widgets/breadcrumb/__tests__/breadcrumb-test.js
src/widgets/breadcrumb/breadcrumb.js

This updates the usage errors for `breadcrumb`.

fix(breadcrumb): update usage errors

---

src/connectors/geo-search/__tests__/connectGeoSearch-test.js
src/connectors/geo-search/connectGeoSearch.js
src/widgets/geo-search/__tests__/geo-search-test.js
src/widgets/geo-search/geo-search.js

This updates the usage errors for `geoSearch`.

fix(geoSearch): update usage errors

---

src/widgets/analytics/__tests__/analytics-test.js
src/widgets/analytics/analytics.js

This updates the usage errors for `analytics`.

fix(analytics): update usage errors

---

src/connectors/clear-refinements/__tests__/connectClearRefinements-test.js
src/connectors/clear-refinements/connectClearRefinements.js
src/widgets/current-refinements/__tests__/__snapshots__/current-refinements-test.js.snap
src/widgets/current-refinements/__tests__/current-refinements-test.js
src/widgets/current-refinements/current-refinements.js

This updates the usage errors for `currentRefinements`.

fix(currentRefinements): update usage errors

---

src/connectors/range/__tests__/connectRange-test.js
src/connectors/range/connectRange.js
src/widgets/range-input/__tests__/range-input-test.js
src/widgets/range-input/range-input.js
src/widgets/range-slider/__tests__/__snapshots__/range-slider-test.js.snap
src/widgets/range-slider/__tests__/range-slider-test.js
src/widgets/range-slider/range-slider.js

This updates the error messages for the `range*` widgets with the new function signature.
Closes #3514.

fix(range): update error messages

---

src/components/CurrentRefinements/CurrentRefinements.js
src/components/CurrentRefinements/__tests__/CurrentRefinements-test.js

**Summary**
Implement the work of #3515 into the component
**Result**
Thinking about it, I think this might be a major change unfortunately (in case someone already relies on the transformItems for `attributeName` 🤔

chore(CurrentRefinements): use label instead of attribute (PART 2)

---

README.md

docs(readme): update instructions

---

.storybook/preview-head.html
website/examples/calendar-widget/index.html
website/examples/e-commerce/index.html
website/examples/tourism/index.html

[See InstantSearch.css release notes →](https://github.com/algolia/instantsearch-specs/releases/tag/7.1.1)

chore(deps): update InstantSearch.css to 7.1.1

---

.travis.yml
scripts/ci/functional-test.sh

See https://github.com/algolia/instantsearch.js/pull/3578#issuecomment-469648069.

build: run Bundlesize after functional tests

---

src/widgets/pagination/pagination.js

Closes #3390.
I sent a PR on the documentation website: algolia/doc#2804.

docs(pagination): fix cssClasses

---

README.md

This updates the Travis badge to Circle CI.

docs(readme): update CI badge

---

src/lib/escape-highlight.ts

This removes `lodash/isArray` usage.

refactor(lodash): remove isArray usage

---

src/components/Slider/Slider.js

This removes the `lodash/has` usage.

refactor(lodash): remove has usage

---

stories/voice-search.stories.ts

**Summary**
This fixes a wrong string interpolation in a test story.
**Result**
When `transcript` is undefined, it shouldn't display "undefined" but just an empty string.

test(voiceSearch): fix a wrong string interpolation in a test story

---

babel.config.js
package.json
scripts/rollup/config.js
yarn.lock

This reverts commit 5ec4609a8b99bf85a2b7b3ceab70bc27a01e6f6c.
closes #3775

revert: chore(build): remove PropTypes from builds (#3697)

---

src/types/widget.ts

This updates the `UiState` type as addressed in https://github.com/algolia/instantsearch.js/pull/3763#pullrequestreview-237282004.
The keys were taken from the current documentation which is outdated.

fix(types): update UiState type

---

stories/clear-refinements.stories.js

**Summary**
This PR clean the `clearRefinements` stories.
- remove the duplicated widgets
- remove the duplicated stories
**Result**
Check out the example inside [Storybook](https://deploy-preview-3780--instantsearchjs.netlify.com/stories/?path=/story/clearrefinements--default).

refactor(clearRefinements): update stories

---

CONTRIBUTING.md

- Wording
- Mention TypeScript
- Update commit conventions
- Update branch organization
- Update folder structure

docs(contributing): update guide

---

scripts/release/publish.js

**Summary**
The release script didn't push tags when releasing beta, while it pushs tags when releasing stable.
**Result**

chore: push git tags on beta release

---

src/lib/InstantSearch.js
src/lib/__tests__/InstantSearch-test.js

This PR switches the `.search` implementation to `. searchOnlyWithDerivedHelpers`. We override the `.search` method to keep the exact same API for the consumer of the libraries. Only the module `InstantSearch` is impacted by the change. 
This switch allow a full control on each request made by the Helper, which is not the case with the regular `.search` function. We're able to alter the request without any impact on the internal state of the Helper (via the derivation function). Now the "main" Helper is only in charge of managing the state, the derived one is in charge of the requests.

feat(InstantSearch): switch to DerivedHelper only

---

test/mock/createWidget.ts

This PR introduces a typed mock for the `DiposeOptions`.

test(mock): create dispose options

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.js
src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
src/connectors/clear-refinements/__tests__/connectClearRefinements-test.js
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.js
src/connectors/geo-search/__tests__/connectGeoSearch-test.js
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
src/connectors/hits/__tests__/connectHits-test.js
src/connectors/hits/__tests__/connectHitsWithInsights-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHitsWithInsights-test.ts
src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
src/connectors/pagination/__tests__/connectPagination-test.js
src/connectors/powered-by/__tests__/connectPoweredBy-test.js
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/range/__tests__/connectRange-test.js
src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/sort-by/__tests__/connectSortBy-test.js
src/connectors/stats/__tests__/connectStats-test.js
src/connectors/toggleRefinement/__tests__/connectToggleRefinement-test.js
src/connectors/voice-search/__tests__/connectVoiceSearch-test.js

**Summary**
This PR adds tests for the cases when umountFn is not specified in connectors.
[Related PR](https://github.com/algolia/instantsearch.js/pull/3955)

chore: add tests for default unmountFn

---

src/connectors/query-rules/connectQueryRules.ts
src/lib/RoutingManager.ts
src/lib/utils/mergeSearchParameters.ts
src/types/instantsearch.ts
test/mock/createInstantSearch.ts

We leverage the types of the Helper now.

fix: remove useless types 

---

src/connectors/pagination/__tests__/connectPagination-test.js
src/connectors/pagination/connectPagination.js

This fixes the lifecycle of `connectPagination`.

fix(pagination): update lifecycle state

---

src/connectors/hits/__tests__/connectHits-test.js
src/connectors/hits/connectHits.js

This fixes the lifecycle of `connectHits`.

fix(hits): update lifecycle state

---

src/widgets/index/__tests__/index-test.ts

This PR only update the structure of the tests. 
- scoped `uiState` related tests together
- scoped reset related tests together
- replaced snake-case with camel-case to avoid linter issues

test(index): scope related tests

---

src/connectors/range/__tests__/connectRange-test.js
src/connectors/range/connectRange.js
src/widgets/range-slider/__tests__/range-slider-test.js

1. add tests for dispose
2. make getConfiguration accept & return SearchParameters
IFW-891

chore(range): update life cycles

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
src/connectors/breadcrumb/connectBreadcrumb.js

i only updated the return value of getConfiguration, since this seems like the only requirement.
IFW-877

chore(breadcrumb): update life cycles

---

src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/menu/connectMenu.js

IFW-886
This was forgotten in the initial PR of menu
requires https://github.com/algolia/algoliasearch-helper-js/pull/743 for the removal test to pass
**Summary**
**Result**

fix(menu): apply & remove refinement

---

src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/connectors/range/connectRange.js
src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js

IFW-882
also fixes maxValuesPerFacet on dispose, which wasn't tested.
this requires: https://github.com/algolia/algoliasearch-helper-js/pull/743
**Summary**
**Result**

chore(hierarchical): consistent state

---

examples/e-commerce/package.json
examples/e-commerce/src/routing.ts
examples/e-commerce/src/search.ts
examples/e-commerce/yarn.lock

**Summary**
This PR migrates routing for InstantSearch.js@4.
At the moment, it's depending on `instantsearch.js@4.0.0-beta.0`.
**Result**
The routing should works the same.
**How to test this**
```
(cd examples/e-commerce/ && yarn && yarn start)
```
1. Open http://localhost:3000 on your browser.
2. Refine search and see if the url changes correctly.
3. Copy the url and paste it in a new tab, and see if the search result is the same.

chore(examples): migrate routing for IS.js@4 on e-commerce demo

---

src/lib/utils/logger.ts

Had to cast the warning, see https://stackoverflow.com/a/48675307 for a similar question.

chore(ts): migrate "logger"

---

MIGRATION.md
README.md
src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js

Migration guide already mentions this since dc75d2fc64c68876d91e9daf847038607c1215aa, discussed with @samouss

feat(core): deprecate addWidget & removeWidget

---

stories/geo-search.stories.js

**Summary**
This PR disable the Places example inside Storybook until the widget is compatible with 4.x.x.

fix(stories): hide Places

---

package.json
yarn.lock

**Summary**
We released while still relying on a canary version of the helper, this means that people would not get patch updates to the helper if we ever did so.
**Result**
By relying on the real released v3 now, we are sure people will get the latest bug fixes

fix(helper): rely on stable version of algoliasearch-helper

---

.storybook/static/storybook.css

**Summary**
forgotten hash here in the rgb
**Result**
value fixed

chore(storybook): fix css format

---

.circleci/config.yml

**Summary**
test naming of the jobs is pretty repetitive, but it can be avoided, as noticed in https://github.com/algolia/instantsearch.js/pull/4250#issuecomment-564073193
**Result**
We need to update the required tests after this, so merge whenever that feels well.

ci(circle): update job naming

---

src/widgets/configure-related-items/__tests__/configure-related-items-test.ts

chore: typo

---

stories/configure.stories.js

**Summary**
more typos
**Result**

chore: typos

---

src/connectors/geo-search/connectGeoSearch.js

Connector isn't defined here, so it caused an error when used in Angular InstantSearch.
<details><summary>Before:</summary>
```ts
export default connectGeoSearch;
export type LatLng = {
/**
* The latitude in degrees.
*/
lat: number;
/**
* The longitude in degrees.
*/
lng: number;
};
export type Bounds = {
/**
* The top right corner of the map view.
*/
northEast: LatLng;
/**
* The bottom left corner of the map view.
*/
southWest: LatLng;
};
export type CustomGeoSearchWidgetOptions = {
/**
* If true, refine will be triggered as you move the map.
*/
enableRefineOnMapMove?: boolean;
/**
* Function to transform the items passed to the templates.
*/
transformItems?: (arg0: any[]) => any[];
};
export type GeoSearchRenderingOptions = {
/**
* The matched hits from Algolia API.
*/
items: any[];
/** …
```

chore(ts): remove undefined type declaration in JSDoc

---

src/connectors/hierarchical-menu/connectHierarchicalMenu.js

**Summary**
This PR removes  a dead link in the comment.

chore: remove a dead link in the comment

---

src/components/RefinementList/__tests__/RefinementList-test.js
src/components/RefinementList/__tests__/__snapshots__/RefinementList-test.js.snap

This updates the `RefinementList` component tests in anticipation of a refactor. It now tests the public API.

test(RefinementList): test public API

---

scripts/release/build-experimental-typescript.js

related to: https://github.com/algolia/instantsearch.js/pull/4307#discussion_r369120809

chore: fix wrong version in experimental typescript tag

---

package.json
yarn.lock

**Summary**
This PR updates the Ship.js dependency to 0.16.0.

chore: update shipjs dependency to 0.16.0

---

stories/autocomplete.stories.ts
stories/configure.stories.js
stories/geo-search.stories.js
stories/hits.stories.js
stories/index.stories.ts

This pull request migrates stories of connectors and widgets already migrated to typescript

chore(ts-migration): migrates configure and autocomplete related stories

---

.storybook/playgrounds/default.ts
.storybook/playgrounds/movies.ts
src/components/Panel/Panel.tsx
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/numeric-menu/connectNumericMenu.ts
src/widgets/numeric-menu/__tests__/__snapshots__/numeric-menu-test.ts.snap
src/widgets/numeric-menu/__tests__/numeric-menu-test.ts
src/widgets/numeric-menu/numeric-menu.tsx
src/widgets/panel/__tests__/panel-test.ts
src/widgets/panel/panel.tsx
stories/numeric-menu.stories.js

This pull request migrates 2 widgets, 1 connector and 2 stories:
- The numeric menu connector, widget, and stories;
- The panel widget, and stories;

chore(ts-migration): migrates numeric menu and panel connector, widget, and stories

---

src/widgets/analytics/__tests__/analytics-test.ts
src/widgets/analytics/analytics.ts
stories/analytics.stories.js

This pull request adjusts widgets and stories in analytics to be similar to the other already migrated widgets and stories;

chore(ts-migration): updates analytics widgets and stories

---

.storybook/playgrounds/default.ts
src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/lib/escape-highlight.ts
src/types/connector.ts
src/types/instantsearch.ts
src/widgets/hits/__tests__/hits-test.ts
src/widgets/hits/hits.tsx
stories/configure-related-items.stories.ts
stories/hits.stories.js
stories/index.stories.ts

This pull request migrates the hits connector, widget, and stories.
As usual, this pull request needs to merged first: https://github.com/algolia/instantsearch.js/pull/4390.
Going to validate myself this work, but you can help making a validation too 👍

chore(ts-migration): migrates hits contents connector, widget, and stories.

---

.storybook/playgrounds/default.ts
src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/lib/escape-highlight.ts
src/types/instantsearch.ts
src/widgets/hits/__tests__/hits-test.ts
src/widgets/hits/hits.tsx
stories/configure-related-items.stories.ts
stories/hits.stories.js
stories/index.stories.ts

This pull request was already validated here: https://github.com/algolia/instantsearch.js/pull/4396.

chore(ts-migration): migrates hits contents connector, widget, and stories

---

src/components/CurrentRefinements/CurrentRefinements.tsx
src/components/CurrentRefinements/__tests__/CurrentRefinements-test.tsx
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/widgets/current-refinements/current-refinements.tsx
stories/current-refinements.stories.js

This pull request adjusts the current refinements contents to the new conventions

chore(ts-migration): current refinements contents

---

.codesandbox/ci.json

**Summary**
This PR configures CodeSandbox CI app.
related to https://github.com/algolia/react-instantsearch/pull/2927

chore: add codesandbox ci

---

api-extractor.json
package.json
src/lib/utils/checkIndexUiState.ts
src/widgets/geo-search/createHTMLMarker.ts
yarn.lock

**Summary**
- correct entry file
- type  createHTMLMarker
- utils: prevent circular import
**Result**
some less warnings

chore: improvements to typescript migration

---

.circleci/config.yml
package.json
src/types/algoliasearch.ts
yarn.lock

**Summary**
Client v3 also has `addAlgoliaAgent`, and TypeScript doesn't seem strict enough to infer that the signatures don't match, unless a "marker" key is added.
**Result**
- https://github.com/algolia/algoliasearch-helper-js/pull/789
- same, but here

fix(ts): correct dummy v4 client

---

src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/connectors/stats/connectStats.js

**Summary**
In Angular InstantSearch, TypeScript is needed for every item. To avoid having to cast these connectors as generic `Connector`, we make sure they have the right shape
**Result**
All connectors fit `Connector` type now

fix(ts): jsDoc comments which conform to Connector definition

---

src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/types/widget.ts
src/widgets/hierarchical-menu/__tests__/__snapshots__/hierarchical-menu-test.js.snap
src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js

This implements the `getWidgetRenderState` widget lifecycle hook in `hierarchicalMenu`.

feat(hierarchicalMenu): implement `getWidgetRenderState`

---

.circleci/config.yml
package.json
ship.config.js
yarn.lock

**Summary**
This PR sets up scheduled release. And it additionally upgrades `ship.js` to the latest version and updated some configs due to the breaking changes from `ship.js`.
We can periodically release the newer version of the library. And I hope to get rid of unnecessary communication like:
> Can I release this today? Any blocker?
Instead, the pull request will be created automatically, and as reviewers, we can address any blocker in the pull request if there is any.
**Result**
Every Tuesday 09:00 UTC (11am Paris), `shipjs prepare` will run and create a release pull-request.
If there is a patch update and there is no `fix` commit, then it will skip.

chore: setup scheduled release

---

stories/breadcrumb.stories.ts

**Summary**
fix error in breadcrumb example
**Result**
changed breadcrumb to breadcrumbDiv
Changed it to TS too, since it would have broken the build

chore(storybook): fix breadcrumb example

---

package.json

**Summary**
Updates the `homepage` of the NPM package.
**Result**
Homepage section at https://www.npmjs.com/package/instantsearch.js should be the current website https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/.

docs(package): update package homepage

---

CONTRIBUTING.md
examples/media/index.html
examples/tourism/index.html

**Summary**
Updates the old website links with the new ones.
**Result**
A developer would have a direct access to v4 docs instead of v2.

docs: replace community website with Algolia website

---

src/widgets/hits/__tests__/hits-integration-test.ts

**Summary**
This PR adds a test for the regression addressed in https://github.com/algolia/instantsearch.js/pull/4519

test(insights): add a test for the regression regarding old insights methods

---

yarn.lock

**Summary**
I used https://github.com/atlassian/yarn-deduplicate and ran yarn install again afterwards (https://github.com/atlassian/yarn-deduplicate/issues/5)
**Result**
Basically what this does is remove a bunch of overlappign versions of dependencies, which will result in a faster install & smaller node modules

chore(yarn): clean lockfile

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts

**Summary**
This PR adds the missing tests for `getWidgetRenderState` at `connectBreadcrumb`.

test(renderState): add tests for getWidgetRenderState at connectBreadcrumb

---

src/widgets/clear-refinements/clear-refinements.tsx
src/widgets/current-refinements/current-refinements.tsx
src/widgets/hits-per-page/hits-per-page.tsx
src/widgets/hits/hits.tsx
src/widgets/infinite-hits/infinite-hits.tsx
src/widgets/numeric-menu/numeric-menu.tsx
src/widgets/query-rule-context/query-rule-context.tsx
src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
src/widgets/voice-search/voice-search.tsx

**Summary**
This PR updates all the widget typings around `WidgetFactory` to include the render options as the first generic.

fix(types): update WidgetFactory types

---

src/connectors/geo-search/__tests__/connectGeoSearch-test.js
src/connectors/geo-search/connectGeoSearch.js
src/types/instantsearch.ts
src/types/widget.ts

I didn't migrate the connector to typescript, so had to write some types hardcoded in the widget file

feat(getWidgetRenderState): support connectGeoSearch

---

src/connectors/configure/__tests__/connectConfigure-test.ts
src/connectors/configure/connectConfigure.ts
src/types/widget.ts

feat(configure): getRenderState for multiple configure widgets

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js
src/middlewares/createRouterMiddleware.ts

**Summary**
we haven't needed to make changes here, so i don't think the warning is still useful :)
**Result**
no more warning when you call setUiState

chore(setUiState): remove warning

---

src/widgets/index/index.ts

**Summary**
this isn't needed anymore since a recent helper update
**Result**
no type errors and one less suppression

chore(ts): remove ts-ignore

---

src/types/widget.ts

**Summary**
this used to be an implicit any
**Result**
correct type for queryHook (searchBox) in renderState

fix(types): correct type for queryHook return

---

stories/smart-sort.stories.ts

**Summary**
This PR removes an unused SmartSort story. It was added to test its relevancyStrictness parameter, which is now removed.

chore(storybook): remove unused SmartSort story

---

.circleci/config.yml
package.json
src/middlewares/__tests__/createMetadataMiddleware.ts
src/middlewares/createMetadataMiddleware.ts
tsconfig.v3.json

**Summary**
The user agent can be used to inspect whether the client is using InstantSearch.js via an integration like Vue InstantSearch or Angular InstantSearch
**Result**
metadata now exposes the algolia agent

feat(metadata): expose client's algolia agent

---

src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts

Reverts algolia/instantsearch.js#4690

Revert "feat(currentRefinements): implement canRefine"

---

src/connectors/pagination/__tests__/connectPagination-test.ts
src/connectors/pagination/connectPagination.ts
src/widgets/index/__tests__/index-test.ts

**Summary**
implements canRefine in connectPagination as true when more than one page of hits is visible
DX-1313
**Result**
pagination now has a canRefine

feat(pagination): implement canRefine

---

src/connectors/toggle-refinement/__tests__/connectToggleRefinement-test.js
src/connectors/toggle-refinement/connectToggleRefinement.js

**Summary**
implements canRefine in connectToggleRefinement as true when there value.count exists.
DX-1309
**Result**
toggleRefinement now has a canRefine

feat(toggleRefinement): implement canRefine

---

src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
src/connectors/rating-menu/connectRatingMenu.js

**Summary**
implements canRefine in connectRatingMenu as true when nbHits > 0.
DX-1308
**Result**
ratingMenu now has a canRefine

feat(ratingMenu): implement canRefine

---

.eslintrc.js
src/lib/utils/escapeRefinement.ts

**Summary**
escapeRefinement works for both numbers and strings, and indeed returns a number or a string, however in the case of string, it can't return a number
**Result**
makes type more correct, updates eslint rules to allow overloading

chore(ts): more detailed type for escapeRefinement

---

src/types/connector.ts
src/types/index.ts
src/types/middleware.ts
src/types/render-state.ts
src/types/router.ts
src/types/templates.ts
src/types/ui-state.ts
src/types/widget-factory.ts
src/types/widget.ts
src/widgets/index/index.ts

**Summary**
the types in Widget.ts aren't all directly related to widgets, which makes it very hard to read
**Result**
more smaller files

refactor(types): split up widget.ts

---

package.json
src/components/RefinementList/RefinementList.tsx
src/lib/insights/client.ts
yarn.lock

**Summary**
for a following PR the better inferring of 4.2 is needed
**Result**
typescript is updated, and resulting errors are fixed

chore(ts): update version

---

src/lib/InstantSearch.ts
src/lib/utils/checkIndexUiState.ts
src/lib/utils/resolveSearchParameters.ts
src/middlewares/createMetadataMiddleware.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
updates the index widget
**Result**
because the types don't match, Index no longer is a Widget, which has impact in addWidget / removeWidget / getWidget

refactor(ts): update index with new type

---

src/widgets/panel/__tests__/panel-test.ts
src/widgets/panel/panel.tsx

**Summary**
the panel widget implementation is slightly more changes than the other widgets, so it has its own PR
**Result**
The panel widget now works as expected with the new widget type

refactor(ts): update panel

---

.circleci/config.yml
.gitignore
jest.config.js
package.json
yarn.lock

**Summary**
Junit summary can be used to give a clean output in CircleCI of which tests have failed
**Result**
- adds jest-junit
- sets up junit report on CircleCI
example for the report: https://app.circleci.com/pipelines/github/algolia/instantsearch.js/6317/workflows/428b121b-6129-4a5e-8397-335e8b4d8f33/jobs/30004/tests

ci(test): store junit results for unit tests

---

src/widgets/answers/answers.tsx
src/widgets/breadcrumb/breadcrumb.tsx
src/widgets/clear-refinements/clear-refinements.tsx
src/widgets/current-refinements/current-refinements.tsx
src/widgets/geo-search/geo-search.ts
src/widgets/hierarchical-menu/hierarchical-menu.tsx
src/widgets/hits-per-page/hits-per-page.tsx
src/widgets/hits/hits.tsx
src/widgets/infinite-hits/infinite-hits.tsx
src/widgets/menu-select/menu-select.tsx
src/widgets/menu/menu.tsx
src/widgets/numeric-menu/numeric-menu.tsx
src/widgets/pagination/pagination.tsx
src/widgets/panel/panel.tsx
src/widgets/powered-by/powered-by.tsx
src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
src/widgets/range-input/range-input.tsx
src/widgets/range-slider/range-slider.tsx
src/widgets/rating-menu/rating-menu.tsx
src/widgets/refinement-list/refinement-list.tsx
src/widgets/relevant-sort/relevant-sort.tsx
src/widgets/search-box/search-box.tsx
src/widgets/sort-by/sort-by.tsx
src/widgets/stats/stats.tsx
src/widgets/toggle-refinement/toggle-refinement.tsx
src/widgets/voice-search/voice-search.tsx

**Summary**
We decided to convert all the exported types that are completely optional to `Partial` since it's less error prone.
**Results**
Fully optional types are now `Partial`s.

feat(ts): use `Partial` exports

---

.circleci/config.yml
package.json
scripts/build/types.js
yarn.lock

**Summary**
build:types failed silently on master when a release is done
**Result**
1. add build:types to main CI
2. update dependencies to make build pass
3. exit with right error code if build:types fails

ci(types): update dependencies & test on CI build:types

---

src/index.es.ts

**Summary**
Types are useful outside of InstantSearch for for example Vue InstantSearch, React InstantSearch, so we want to expose this from the root
**Result**
This was changed in https://github.com/algolia/instantsearch.js/pull/4829, as i thought it was a mistake (like most of the other entries in that fake file), but /types is still useful

feat(ts): export types from entry point

---

src/widgets/rating-menu/rating-menu.tsx
src/widgets/refinement-list/__tests__/__snapshots__/refinement-list-test.ts.snap
src/widgets/search-box/__tests__/__snapshots__/search-box-test.ts.snap
src/widgets/search-box/defaultTemplates.ts
src/widgets/voice-search/defaultTemplates.ts
stories/query-rule-custom-data.stories.ts

**Summary**
xml namespace is not required for svg elements (and has never been https://stackoverflow.com/a/18468348/3185307), only for svg documents.
**Result**
- This saves a probably insignificant amount of bundlesize
- xmlns nowhere left

fix(svg): remove xmlns

---

src/connectors/index.ts
src/widgets/__tests__/index.test.ts
src/widgets/index.ts

**Summary**
DX-2422
dynamicWidgets works as expected and the feature is fully released
**Result**
dynamicWidgets is no longer experimental, and the EXPERIMENTAL_ form is deprecated

feat(dynamicWidgets): mark as stable

---

package.json
src/middlewares/__tests__/createInsightsMiddleware.ts
test/mock/createInsightsClient.ts
tsconfig.json
yarn.lock

**Summary**
This PR removes the redundant exclusion from `tsconfig.json`.
depends on https://github.com/algolia/search-insights.js/pull/333
**Result**
It works the same.

chore(types): remove redundant exclusion from tsconfig

---

src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/numeric-menu/connectNumericMenu.ts
stories/numeric-menu.stories.ts

**Summary**
fixes #4121
**Result**
I've added an example on the storybook (inspired by the issue).

fix(connectNumericMenu): allow option for same start/end values

---

examples/media/index.html
examples/media/src/app.css

**Summary**
This PR adds a footer in the new media example, informing that the dataset comes from Algolia blog, and providing them a direct link to this resource.
**[Preview](https://deploy-preview-4958--instantsearchjs.netlify.app/examples/media/)**

chore(examples/media): add mentions in footer

---

src/components/Pagination/Pagination.tsx
src/components/Pagination/PaginationLink.tsx
src/components/Pagination/__tests__/Pagination-test.tsx

**Summary**
refactors the pagination component to not use a class anymore
This also simplifies the wrapping and removes implementation details from a test
**Result**
slightly better test, no class used in Pagination

refactor(pagination): move from class-component to functional

---

src/connectors/toggle-refinement/connectToggleRefinement.ts

**Summary**
adds docs to every key  of the renderState of toggle 
**Result**
Docs on all keys of the toggle refinement render state
This is exposed by TypeScript, and based on the docs I wrote in https://github.com/algolia/doc/pull/6551

docs(connectToggleRefinement): document render state

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/breadcrumb/connectBreadcrumb.ts

**Summary**
Small updates related to the `connectBreadcrumb` connector from @francoischalifour review:
https://github.com/algolia/instantsearch.js/pull/4980#pullrequestreview-845463182

fix(connectBreadcrumb): updates from review

---

scripts/typescript/extract.js

**Summary**
the file instantsearch.development.min.js does not exist, only a non-minified version of dev mode exists
**Result**
only existing files have type definitions

fix(typescript): remove non-existing UMD type definition

---

package.json
wdio.saucelabs.conf.js
yarn.lock

**Summary**
This PR updates `instantsearch-e2e-tests` to its latest version.
**Result**
Pipelines should have less issues with flaky tests.

chore: update e2e tests

---

package.json
yarn.lock

**Summary**
This is done by updating the helper minimal dependency and thus includes https://github.com/algolia/algoliasearch-helper-js/pull/906 and https://github.com/algolia/algoliasearch-helper-js/pull/911
**Result**
- parameters are sent sorted, avoiding edge cases where widgets get removed and added again in a different order resulting in missed cache
- supports client.search for searchForFacetValues, simplifying the requirement for searchClient (via https://github.com/algolia/instantsearch.js/pull/5066 in types too later)

fix(core): sort parameters & support client.search for sffv

---

ship.config.js

**Summary**
the team name has changed
**Result**
right team name asked for review

ci(shipjs): ask right reviewers

---

.circleci/config.yml

**Summary**
Increase the number of CPU available for the examples test as it failed with not enough memory before
**Result**
Examples tests should no longer fail with error code 139 and finish a little faster than in previous runs

ci(circle): large resource class for examples

---

examples/js/calendar-widget/package.json
examples/js/e-commerce/package.json
examples/js/media/package.json
examples/js/tourism/package.json
package.json
yarn.lock

**Summary**
deduplicate installed packages in the repo (mainly using the https://github.com/scinos/yarn-deduplicate tool).
I couldn't find a tool that highlighted duplicates, but this is already an improvement, especially in preparation of more packages being added later.
**Result**
Highlights:
- only one version of babel in the whole project
- saves ~100MB of node_modules (950MB -> 850MB)
There's probably even more simplifications possible, but these I saw easily possible.

chore(deps): deduplicate lockfile

---

packages/instantsearch.js/package.json
packages/instantsearch.js/test/module/is-cjs-module.cjs
packages/instantsearch.js/test/module/is-es-module.mjs

**Summary**
imports from the built package (not local file imports) to have a more "real-life" scenario
**Result**
Also introduces the CJS test as present in react instantsearch hooks for more consistency

test(is-module): test from built/resolved package

---

README.md
packages/instantsearch.css/README.md

This adds a link to the specs site in the README.

docs(instantsearch.css): add link to site in README

---

babel.config.js
examples/react/media/App.js
scripts/website/webpack.config.js

**Summary**
I didn't notice this in the migration since the build passed, but something about constant elements causes webpack to be confused about which references are from a dependency, somehow consistently the RatingMenu. If that plugin is disabled, there's no issue.
**Result**
https://deploy-preview-5226--instantsearchjs.netlify.app/examples/react/media/

fix(examples): make react media example work

---

package.json
packages/create-instantsearch-app/package.json
yarn.lock

deduplicate and remove an unused shipjs and instantsearch.css dependency

chore(deps): clean up shipjs dependencies

---

.github/ISSUE_TEMPLATE/config.yml
README.md
packages/create-instantsearch-app/README.md
packages/instantsearch.css/README.md
packages/instantsearch.js/README.md
packages/react-instantsearch-hooks-server/README.md
packages/react-instantsearch-hooks-web/README.md
packages/react-instantsearch-hooks/README.md

**Summary**
This PR ensures the contributing section in relevant README files follows the same convention and has appropriate links.

chore: normalize contribution section in packages README files

---

packages/react-instantsearch-dom-maps/scripts/version.js

see: https://github.com/algolia/instantsearch.js/pull/5364/files#r1058174310

chore(scripts): right file written in Dom-maps version

---

packages/react-instantsearch-dom/package.json

**Summary**
The react storybook was broken since migration, as the folder name was changed from `storybook` to `.storybook`, but the script wasn't updated
**Result**
see <https://deploy-preview-5371--instantsearchjs.netlify.app/stories/react>

docs(website): fix react storybook

---

packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap

**Summary**
update snapshot in Create InstantSearch App 
I don't think this can be avoided without some code to specifically mock this part, so for now let's update yearly
**Result**
tests are green

test(create-instantsearch-app): update yearly snapshot

---

.github/workflows/release-templates.yml

**Summary**
This PR sets the correct workspace for running the `release-templates` script in a GitHub action when a tag is pushed.

chore: update template action command

---

README.md

Fix typo
**Summary**
**Result**

docs(README.md): Fix typo: "declining" to "designing"

---

examples/react-hooks/default-theme/src/App.css

**Summary**
You can see an overflow before this PR by selecting `apple` in the RefinementList and seeing it going well past the container size.
**Result**
No overflow when selecting apple in the default-theme React InstantSearch Hooks example

docs(example): prevent overflow in default-theme

---

tests/versions/index.js

**Summary**
in #5194 this test was introduced to ensure sync versions between React InstantSearch versions, but it had the wrong grouping
**Result**
ensure version consistency between on one hand the React InstantSearch Hooks packages, and other hand the React InstantSearch core packages

test(versions): correct package grouping

---

examples/react-hooks/next/package.json
examples/react-hooks/react-native/package.json
package.json
packages/instantsearch.js/package.json
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/lib/__tests__/RoutingManager-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/dispose-start-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/duplicate-url-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/external-influence-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/modal-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/spa-debounced-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/spa-replace-state-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/spa-test.ts
packages/instantsearch.js/src/lib/infiniteHitsCache/__tests__/sessionStorage.ts
packages/instantsearch.js/src/lib/stateMappings/__tests__/simple-test.ts
packages/instantsearch.js/src/lib/templating/prepareTemplateProps.ts
packages/instantsearch.js/src/lib/utils/getContainerNode.ts
packages/instantsearch.js/src/lib/voiceSearchHelper/__tests__/index-test.ts
packages/react-instantsearch-dom/src/lib/voiceSearchHelper/__tests__/index.ts
packages/react-instantsearch-hooks-web/src/widgets/__tests__/__utils__/all-widgets.tsx
tests/mock/__tests__/createAPIResponse.test.ts
tests/mocks/__tests__/createAPIResponse.test.ts
yarn.lock

**Summary**
It seems like notably SpeechRecognition is no longer builtin.
Some other more strict behaviour shouldn't have an impact on users.
I didn't update api-extractor, as it's not yet depending on the latest typescript, and updating seemed to break something in the configuration I didn't feel like figuring out :D
**Result**
Libraries and types are built with latest TypeScript. I didn't detect any change in the output

fix(dependencies): update typescript

---

examples/react-hooks/next/README.md
examples/react-hooks/react-native/README.md
examples/react-hooks/ssr/README.md
examples/react/autocomplete/README.md
examples/react/geo-search/README.md
examples/react/multi-index/README.md
examples/react/next/README.md
examples/react/react-router-v3/README.md
examples/react/react-router/README.md
examples/react/server-side-rendering/README.md

**Summary**
This PR updates the code snippet present in some examples README's so that it still work with the new name and structure of the monorepo.

chore(examples): update examples download code snippet

---

ship.config.js

**Summary**
We tried to recreate tags that already exist if the package wasn't published in this release
**Result**
filter out packages that have already been published

ci(shipjs): only tag non-tagged packages

---

packages/instantsearch.js/src/lib/utils/detect-insights-client.ts

**Summary**
this file is not used
**Result**
removed the file, it's not even referenced in the barrel file.

chore: remove dead code

---

packages/instantsearch.js/src/components/Answers/Answers.tsx
packages/instantsearch.js/src/components/Hits/Hits.tsx
packages/instantsearch.js/src/components/InfiniteHits/InfiniteHits.tsx
packages/instantsearch.js/src/lib/utils/index.ts
packages/instantsearch.js/src/lib/utils/omit.ts
packages/instantsearch.js/src/widgets/hits/__tests__/hits.test.tsx
packages/instantsearch.js/src/widgets/hits/defaultTemplates.ts
packages/instantsearch.js/src/widgets/hits/hits.tsx
packages/instantsearch.js/src/widgets/infinite-hits/__tests__/infinite-hits.test.tsx
packages/instantsearch.js/src/widgets/infinite-hits/defaultTemplates.ts
packages/instantsearch.js/src/widgets/infinite-hits/infinite-hits.tsx

**Summary**
Add a real warning and deprecation for __hitIndex (the position within the visible page)
**Result**
JSDoc comments only work when in a docblock, so that's changed.
Also added a proper warning so string templates see this too.

fix(infinitehits/hits): correctly deprecate __hitIndex

---

packages/instantsearch.js/README.md

**Summary**
some of these badges were outdated, some not useful, so I removed them.
**Result**
Remove all badges from the InstantSearch.js readme. None of the other flavours have badges in the readme.

docs(readme): remove badges

---

packages/react-instantsearch-hooks-router-nextjs/package.json

**Summary**
For some reason (possibly the PR introducing this package) was merged with a version that wasn't the latest React InstantSearch Hooks as dependency, and thus doesn't get updated by shipjs during releases.
In a different PR, we should change those dependencies to caret so they are more robust.
**Result**
fixes #5568

fix(dependencies): depend on sync version of React InstantSearch Hooks

---

examples/js/calendar-widget/app.js
examples/js/e-commerce/src/search.ts
examples/js/getting-started/src/app.js
examples/js/media/src/search.ts
examples/js/tourism/search.js
examples/react-hooks/default-theme/src/App.tsx
examples/react-hooks/e-commerce/App.tsx
examples/react-hooks/getting-started/src/App.tsx
examples/react-hooks/next-routing/pages/index.tsx
examples/react-hooks/next/pages/index.tsx
examples/react-hooks/ssr/src/App.js
examples/vue/default-theme/src/App.vue
examples/vue/e-commerce/src/App.vue
examples/vue/getting-started/src/App.vue
examples/vue/media/src/App.vue
examples/vue/nuxt/pages/search.vue
examples/vue/ssr/src/main.js

**Summary**
Only examples not touched are react-instantsearch-core based, or react native.
**Result**
All examples have insights: true.
FX-2316

docs(examples): add insights to all examples

---

examples/js/e-commerce/README.md
examples/js/getting-started/README.md
examples/js/media/README.md
examples/react-hooks/getting-started/README.md
examples/react-hooks/next-routing/README.md
examples/react-hooks/next/README.md
examples/react-hooks/react-native/README.md
examples/react-hooks/ssr/README.md
examples/react/autocomplete/README.md
examples/react/geo-search/README.md
examples/react/getting-started/README.md
examples/react/multi-index/README.md
examples/react/next/README.md
examples/react/react-router-v3/README.md
examples/react/react-router/README.md
examples/react/server-side-rendering/README.md
examples/vue/default-theme/README.md
examples/vue/e-commerce/README.md
examples/vue/getting-started/README.md
examples/vue/media/README.md
examples/vue/nuxt/README.md
examples/vue/ssr/README.md

**Summary**
This PR adds CodeSandbox links to all of our examples, so that users can easily edit them without having to clone the repository first.

chore: add codesandbox link to all code samples

---

bundlesize.config.json
packages/vue-instantsearch/package.json
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js
packages/vue-instantsearch/src/util/createServerRootMixin.js
scripts/prepare-vue3.js
yarn.lock

Issue during SSR, i18n is not defined inside the cloned component instance
This fix solve the issue by adding $i18n in the options of the cloned component.

fix(createServerRootMixin): forward i18n on  option

---

packages/instantsearch.js/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-dom/package.json
packages/react-instantsearch-hooks/package.json
packages/vue-instantsearch/package.json
tests/mocks/package.json
yarn.lock

**Summary**
Although automatic updates can already solve this issue on its own, an explicit update will prevent many more people seeing it.
fixes #5658
**Result**
TypeScript 5.1.3 works for PlainSearchParameters/Configure out of the box, without manually updating algoliasearch-helper

fix(dependencies): update helper requirement

---

examples/vue/default-theme/vue.config.js
examples/vue/getting-started/vue.config.js
examples/vue/media/vue.config.js

**Summary**
Config adjustments to make the vue-cli-service dev server play well with Codesandbox's MicroVMs.
**Result**
- Current: https://codesandbox.io/p/sandbox/github/algolia/instantsearch/tree/master/examples/vue/getting-started
- Fixed: https://codesandbox.io/p/sandbox/github/algolia/instantsearch/tree/examples/vue-csb-disablehostcheck/examples/vue/getting-started

chore(examples): disable host check on devserver for codesandbox proxy

---

packages/algoliasearch-helper/package.json
packages/algoliasearch-helper/scripts/update-version.js
packages/algoliasearch-helper/src/version.js
tests/versions/index.js

**Summary**
Same as done for the other flavours, missed during helper migration from the original release script
**Result**
Helper has and keeps the same version number

fix(version): ensure version file/export matches package

---

scripts/retry.sh

**Summary**
The retry.sh script becomes portable (and callable from everywhere) if it recursively calls itself from the right place, instead of using a relative page (which broke in helper)
**Result**
Retry script actually works for the helper

test(retry): use local script

---

packages/instantsearch.js/README.md

We shouldn't recommend string-templates anywhere :)

docs(readme): use html templates

---

packages/algoliasearch-helper/documentation-src/content/examples.md

**Summary**
Codepen replaced with one of my own account, as i don't have the login information for "algoliamanager"
**Result**
example using toggleExclude (deprecated) replaced with toggleFacetExclusion (its alias)
fixes https://github.com/algolia/instantsearch/issues/5710

docs(examples): replace toggleExclude with toggleFacetExclusion

---

packages/instantsearch-codemods/package.json

**Summary**
Just added a bit more stuff to the file to make it more in line with the other packages.
Not sure if I should change the version already though

feat: add more info to instantsearch-codemods `package.json`

---

packages/instantsearch-codemods/src/codeshift.config.js

**Summary**
I'll probably have to raise an issue to the maintainers of `@codeshift/cli` too 😅

fix(codemods): add empty transforms object so that script does not fail

---

packages/create-instantsearch-app/src/cli/index.js

The label for `attributesForFaceting` was wrong, it said "Attributes to display" instead of "Attributes for faceting".

fix(create-instantsearch-app): fix option label for `attributesForFaceting`

---

packages/instantsearch.js/package.json
yarn.lock

**Summary**
updates ui-components packages to include the fix done there that polluted the JSX namespace
**Result**
fixes #5853

fix(dependencies): update ui-components

---

bundlesize.config.json

fix(bundlesize): raise limit

---

packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/src/templates/InstantSearch.js/src/app.js.hbs
packages/create-instantsearch-app/src/templates/React InstantSearch/src/App.tsx.hbs
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/src/App.vue

**Summary**
adds `future` to the templates with `preserveSharedStateOnUnmount` set to true
**Result**
These give a warning, so we want to encourage people to use these flags as much as possible.

feat(templates): add "future" flags

---

packages/react-instantsearch-nextjs/package.json
packages/react-instantsearch-router-nextjs/package.json

**Summary**
mark next packages as compatible with next 14
**Result**
https://github.com/algolia/instantsearch/discussions/5933

fix(next): mark compatibility with next 14

---

packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap

**Summary**
update the year in template of InstantSearch widget 
**Result**
no test failure

test(templates): update year

---

examples/react/next-app-router/README.md

Updated README for accuracy in [this](https://github.com/algolia/instantsearch/tree/master/examples/react/next-app-router) sample project.
**Result**
Providing Accurate Project, Sandbox, and Documentation Links to Avoid User Confusion

Update README.md for Next.js with App router

---

packages/instantsearch.js/src/lib/InstantSearch.ts

**Summary**
This is clearly not experimental anymore, we've been relying on this for years in react, vue and angular
**Result**
no EXPERIMENTAL warning for adding or removing widgets after start

chore(comments): remove outdated "experimental" warnings

---

packages/algoliasearch-helper/src/SearchParameters/index.js
packages/algoliasearch-helper/src/requestBuilder.js
packages/algoliasearch-helper/test/datasets/SearchParameters/search.dataset.js

Reverts algolia/instantsearch#6006

Revert "fix(perf): improve speed of setQueryParameters"

---

packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/src/templates/InstantSearch.js/src/app.css
packages/create-instantsearch-app/src/templates/InstantSearch.js/src/app.js.hbs
packages/create-instantsearch-app/src/templates/JavaScript Client/src/app.css
packages/create-instantsearch-app/src/templates/JavaScript Client/src/app.js.hbs
packages/create-instantsearch-app/src/templates/JavaScript Helper/src/app.css
packages/create-instantsearch-app/src/templates/JavaScript Helper/src/app.js.hbs
packages/create-instantsearch-app/src/templates/React InstantSearch/src/App.css
packages/create-instantsearch-app/src/templates/React InstantSearch/src/App.tsx.hbs
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/src/App.vue
packages/create-instantsearch-app/src/templates/Vue InstantSearch/src/App.vue

**Summary**
Small adjustments for [FX-2750](https://algolia.atlassian.net/browse/FX-2750)
**Result**
Markup changes a bit with additional styling
[FX-2750]: https://algolia.atlassian.net/browse/FX-2750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cisa): style images

---

packages/instantsearch-ui-components/__tests__/types.test.ts
packages/instantsearch-ui-components/src/components/Highlight.tsx
packages/instantsearch-ui-components/src/components/Hits.tsx
packages/instantsearch-ui-components/src/components/__tests__/Hits.test.tsx
packages/instantsearch.js/src/connectors/hits/__tests__/connectHits-test.ts
packages/instantsearch.js/src/widgets/hits/hits.tsx
packages/react-instantsearch/src/widgets/Hits.tsx
packages/vue-instantsearch/src/components/Hits.js

**Summary**
Add a test and fix the signature of createHitsComponent. The test ensures:
- export of ui component is a function
- function has correct name
- type of the return is a function
- return type has only one parameter, which is just a name
**Result**
- No reproduction of https://github.com/algolia/ui-components/pull/29 in this code base
- test based on https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter (I think this could be eslint as well, but that was harder to understand. We can migrate later with basically the same logic, or continue using this TS test/linter as it is based on the output, not the input)

test(types): ensure correct signature

---

packages/vue-instantsearch/src/components/Configure.js
packages/vue-instantsearch/src/components/__tests__/Configure.js

**Summary**
Fixes #6163 
Fixes #6164
**Result**
Added a test that was failing in Vue3, it works now !

fix(vue): avoid passing a proxied object in Configure

---

packages/react-instantsearch-core/src/connectors/__tests__/useTrendingItems.test.tsx
packages/react-instantsearch-core/src/connectors/useTrendingItems.ts
packages/react-instantsearch-core/src/index.ts
packages/react-instantsearch/src/__tests__/common-connectors.test.tsx

**Summary**
adds the useTrendingItems react hook and enable the connector tests
**Result**
FX-2852

feat(recommend): introduce useTrendingItems connector

---

packages/instantsearch-ui-components/src/components/LookingSimilar.tsx
packages/instantsearch-ui-components/src/components/__tests__/LookingSimilar.test.tsx
packages/instantsearch-ui-components/src/components/index.ts

**Summary**
Only adds the ui component
**Result**
FX-2834

feat(recommend): implement LookingSimilar UI Component

---

bundlesize.config.json
packages/instantsearch.js/src/__tests__/common-connectors.test.tsx
packages/instantsearch.js/src/connectors/index.ts
packages/instantsearch.js/src/connectors/looking-similar/connectLookingSimilar.ts
packages/react-instantsearch/src/__tests__/common-connectors.test.tsx
packages/vue-instantsearch/src/__tests__/common-connectors.test.js
tests/common/connectors/index.ts
tests/common/connectors/looking-similar/index.ts
tests/common/connectors/looking-similar/options.ts

**Summary**
adds connectLookingSimilar and its tests in cts
**Result**
FX-2835

feat(recommend): introduce connectLookingSimilar

---

packages/react-instantsearch-core/src/connectors/useLookingSimilar.ts
packages/react-instantsearch-core/src/index.ts
packages/react-instantsearch/src/__tests__/common-connectors.test.tsx
packages/react-instantsearch/src/__tests__/common-widgets.test.tsx
packages/react-instantsearch/src/widgets/LookingSimilar.tsx
packages/react-instantsearch/src/widgets/__tests__/LookingSimilar.test.tsx
packages/react-instantsearch/src/widgets/__tests__/__utils__/all-widgets.tsx
packages/react-instantsearch/src/widgets/__tests__/all-widgets.test.tsx
packages/react-instantsearch/src/widgets/index.ts

**Summary**
adds the LookingSimilar react widget and the useLookingSimilar hook
**Result**
FX-2768

feat(recommend): add LookingSimilar and useLookingSimilar

---

bundlesize.config.json
packages/instantsearch.css/src/themes/algolia.scss
packages/instantsearch.css/src/themes/reset.scss
packages/instantsearch.css/src/themes/satellite.scss
specs/src/pages/widgets/frequently-bought-together.md
specs/src/pages/widgets/looking-similar.md
specs/src/pages/widgets/related-products.md
specs/src/pages/widgets/trending-items.md

**Summary**
This PR adds base CSS styles for the Looking Similar widget.

feat(recommend): set up base CSS styles for `lookingSimilar` widget

---

examples/js/getting-started/index.html
examples/js/getting-started/src/app.css
examples/js/getting-started/src/app.js
examples/js/getting-started/src/products.js
examples/react/getting-started/index.html
examples/react/getting-started/package.json
examples/react/getting-started/products.html
examples/react/getting-started/src/App.css
examples/react/getting-started/src/App.tsx
examples/react/getting-started/src/Product.tsx
examples/react/getting-started/src/products.tsx

**Summary**
Adds recommend to the js and react getting-started examples.
- if you don't have recommend access, it displays no results as expected, and doesn't break the search
- trendingItems in the search page
- new "products" page (PDP) with relatedItems
**Result**
FX-2804

chore(examples): integrate recommend into getting started

---

examples/js/calendar-widget/index.html
examples/js/e-commerce-umd/index.html
examples/js/e-commerce/index.html
examples/js/getting-started/index.html
examples/js/getting-started/products.html
examples/js/media/index.html
examples/js/tourism/index.html
examples/react/default-theme/index.html
examples/react/e-commerce/index.html
examples/react/ssr/src/server.js
examples/vue/default-theme/public/index.html
examples/vue/e-commerce/public/index.html
examples/vue/getting-started/public/index.html
examples/vue/media/public/index.html
examples/vue/nuxt/pages/search.vue
examples/vue/ssr/public/index.html
packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/src/templates/Angular InstantSearch/src/index.html
packages/create-instantsearch-app/src/templates/InstantSearch.js widget/example/index.html
packages/create-instantsearch-app/src/templates/InstantSearch.js/index.html.hbs
packages/create-instantsearch-app/src/templates/React InstantSearch/index.html
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/index.html
packages/create-instantsearch-app/src/templates/Vue InstantSearch/public/index.html
packages/instantsearch.js/.storybook/preview-head.html

**Summary**
update all examples to consistently use InstantSearch.css v8 for consistency and ensuring recommend works everywhere.
**Result**
All examples, including Create InstantSearch App use InstantSearch v8 pinned to the major version

chore(examples): use InstantSearch.css v8

---

examples/js/media/src/widgets/Articles.ts
examples/react/default-theme/package.json
examples/react/e-commerce/package.json
examples/react/getting-started/package.json
examples/react/next-app-router/package.json
examples/react/next-routing/package.json
examples/react/next/package.json
examples/react/react-native/package.json
package.json
yarn.lock

**Summary**
No particularly notable changes, just one place where eslint now found `!` to be unneeded.
**Result**
We use latest typescript in the project. No auxiliary dependencies have been updated like typescript-eslint or api-extractor

chore(typescript): update to 5.5.2

---

examples/js/e-commerce-umd/polyfills.js
examples/js/e-commerce/polyfills.js
tests/e2e/wdio.base.conf.js
tests/e2e/wdio.saucelabs.conf.js

**Summary**
add replaceAll to IE polyfills, as it's now used in the js client, update browser version for chrome/ff
**Result**
E2E for IE passes
(FWIW netlify does pass but it seems to fail and stuck on a broken commit https://app.netlify.com/sites/instantsearchjs/deploys/66c46341a05dbfe2247128dc)

chore(examples): update polyfill for replaceall

---

packages/react-instantsearch-router-nextjs/wdio.saucelabs.conf.cjs
tests/e2e/wdio.base.conf.js

**Summary**
Follow-up to #6331.
**Result**
e2e passes for react-instantsearch-router-nextjs

chore(e2e): update chrome target version

---

examples/js/e-commerce-umd/package.json
examples/js/e-commerce/package.json
examples/react/e-commerce/package.json

**Summary**
Align browserslist versions for Chrome and Firefox to the version used for e2e tests.

chore(examples): update browserslist versions for chrome and firefox

---

examples/js/e-commerce-umd/package.json
examples/js/e-commerce/package.json
examples/react/e-commerce/package.json
examples/vue/default-theme/package.json
examples/vue/e-commerce/package.json
examples/vue/getting-started/package.json
examples/vue/media/package.json
yarn.lock

chore(examples): use same browserslist config for all examples

---

examples/js/calendar-widget/package.json
examples/js/e-commerce-umd/package.json
examples/js/e-commerce/package.json
examples/js/getting-started/package.json
examples/js/media/package.json
examples/js/tourism/package.json
examples/react/default-theme/package.json
examples/react/e-commerce/package.json
examples/react/getting-started/package.json
yarn.lock

**Summary**
https://algolia.atlassian.net/browse/DI-2904
See this GitHub issue https://github.com/algolia/algoliasearch-client-javascript/issues/1551#issuecomment-2342817718
It seems like Parcel requires a setting to enable exports resolution [docs](https://parceljs.org/features/dependency-resolution/#enabling-package-exports), [initial issue](https://github.com/parcel-bundler/parcel/issues/4155#issuecomment-2193642588).
**Result**
The example works

chore(example): update parcel examples

---

packages/algolia-experiences/src/banner.tsx
packages/algolia-experiences/src/render.tsx
packages/algolia-experiences/src/types.ts
packages/algolia-experiences/src/widgets.ts

**Summary**
see also https://github.com/algolia/AlgoliaWeb/pull/22256
**Result**
render from config, not from rules, as this is harder to edit and control

feat(banner): render from config

---

packages/react-instantsearch-nextjs/src/InitializePromise.tsx

**Summary**
Got reports of memory leaks with the Next.js App Router solution.
It seems partly related to `ServerInsertedHTML` or maybe just the fact that renders are streamed.
**Result**
Prior to the change, on an index with stringified results weighing ~50kb, for 500 concurrent requests we had a peak of 1GB which reduced to 600mb when idle.
By moving the initialisation of `createInsertHTML` so that it does not capture the scope of the whole component, it peaks at 600mb then reduces to 160mb when idle.
There are definitely more ways this could be improved as I see stringified results are kept in memory way after, so does certain React nodes with results in them. Should try to see with the Next.js team perhaps.

fix(next-app-router): mitigate memory leak

---

packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/src/templates/InstantSearch.js widget/example/index.ts.hbs
packages/instantsearch.js/stories/dynamic-widgets.stories.ts

**Summary**
small leftover parts where we document hogan templates now removed
**Result**
[FX-3103]
[FX-3103]: https://algolia.atlassian.net/browse/FX-3103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(templates): remove hogan from examples

---

packages/react-instantsearch-nextjs/package.json

**Summary**
This will allow Deno to install the package as it won't do it with a loose semver.
You can check the semver using the official npm website.
https://semver.npmjs.com/#syntax-examples
**Result**

fix(dependencies): Fixed semver of `peerDependencies` to be strict.

---

examples/js/media/package.json
examples/js/media/src/widgets/Articles.ts

**Summary**
Document usage of htm in connectInfiniteHits of the media example
**Result**
This avoids the usage of the deprecated `highlight` and `snippet` functions

doc(templates): explain how to use htm in a connector

---

.circleci/config.yml
tests/e2e/CONTRIBUTING.md
tests/e2e/all-flavors.spec.ts
tests/e2e/flavors.js
tests/e2e/helpers/clickClearRefinements.ts
tests/e2e/helpers/clickHierarchicalMenuItem.ts
tests/e2e/helpers/clickNextPage.ts
tests/e2e/helpers/clickPage.ts
tests/e2e/helpers/clickPreviousPage.ts
tests/e2e/helpers/clickRatingMenuItem.ts
tests/e2e/helpers/clickRefinementListItem.ts
tests/e2e/helpers/clickToggleRefinement.ts
tests/e2e/helpers/dragRangeSliderLowerBoundTo.ts
tests/e2e/helpers/dragRangeSliderUpperBoundTo.ts
tests/e2e/helpers/setHitsPerPage.ts
tests/e2e/helpers/setSearchBoxValue.ts
tests/e2e/helpers/setSortByValue.ts
tests/e2e/wdio.saucelabs.conf.js

**Summary**
This PR removes tests targeting IE11.
FX-3054

feat(tests): remove ie11 targeting tests

---

packages/algolia-experiences/src/get-configuration.ts

Change the domain to `experiences-beta.algolia.com`

fix(fetch): change endpoint and path

---

packages/instantsearch.js/package.json
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/instantsearch.js/src/types/insights.ts
packages/react-instantsearch-core/CHANGELOG.md
packages/react-instantsearch-core/src/__tests__/insights.test.tsx
tests/common/shared/insights.ts
tests/common/widgets/hits/insights.ts
tests/common/widgets/infinite-hits/insights.ts
tests/mocks/createInsightsClient.ts
yarn.lock

**Summary**
update search-insights 
**Result**
fixes #6432

fix(deps): update search-insights

---

packages/instantsearch.js/src/lib/__tests__/InstantSearch-composition-test.tsx
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/lib/__tests__/server-composition.test.ts
packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-composition-test.ts
packages/react-instantsearch-nextjs/src/__tests__/InitializePromise-composition.test.tsx
packages/react-instantsearch-nextjs/src/__tests__/InitializePromise.test.tsx
tests/mocks/createCompositionClient.ts
tests/mocks/index.ts

**Summary**
- adding tests for composition implementation, cf. #6437 
[EMERCH-1750](https://algolia.atlassian.net/browse/EMERCH-1750)
[EMERCH-1750]: https://algolia.atlassian.net/browse/EMERCH-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

tests: Composition

---

examples/vue/ssr/src/main.js

**Summary**
always read the url as it's the source of truth
**Result**
fixes #6561 for this repo

fix(example): always read URL

---

examples/react/css/src/App.tsx
examples/react/css/src/algolia.css
examples/react/css/src/variables.css

**Summary**
This PR adds the CSS variables for the Algolia InstantSearch theme.

poc: add CSS variables

---

examples/react/css/src/App.css
examples/react/css/src/App.tsx

**Summary**
This PR updates the app styles to add background color and text color in light and dark mode.
It also adds some space between the filters and adds "Show more" buttons for the `HirerachicalMenu` and `RefinementList` components.

poc: update App styles

---

examples/react/css/src/App.tsx
examples/react/css/src/Panel.tsx
examples/react/css/src/algolia.css
examples/react/css/src/panel.css

**Summary**
This PR adds the `Panel` styles.

poc: add `Panel` styles

---

examples/react/css/src/App.css
examples/react/css/src/variables.css

**Summary**
Fixes the checkbox icon and header background in dark mode.

poc: small fixes

---

examples/react/css/src/App.css
examples/react/css/src/App.tsx
examples/react/css/src/algolia.css
examples/react/css/src/breadcrumbs.css
examples/react/css/src/variables.css

Add styles for the Breadcrumbs component

feat: add Breadcrumb styling

---

CONTRIBUTING.md
packages/instantsearch.js/README.md

*.netlify.com is dead now, use *.netlify.app

docs(contributing): correct netlify link

---

packages/instantsearch-ui-components/src/components/chat/Chat.tsx
packages/instantsearch.js/src/widgets/chat/chat.tsx
packages/react-instantsearch/src/widgets/Chat.tsx

**Summary**
This PR adds top level translations and classNames that are forwarded to their respective UI components.
Translations for JS would be done in the template changes PR.

feat(chat): add top level translations and classnames

---

examples/js/getting-started/index.html
examples/js/getting-started/src/app.css
examples/js/getting-started/src/app.js
examples/react/getting-started/src/App.css
examples/react/getting-started/src/App.tsx
packages/instantsearch.css/src/components/chat/_chat-message.scss
packages/instantsearch.css/src/components/chat/_chat-prompt.scss
packages/instantsearch.css/src/shared/_variables.scss

**Summary**
This PR adds the chat widget to the InstantSearch.js and React InstantSearch Getting Started examples.

chore(examples): add chat widget to the getting started examples
