- scripts/dev.sh
We had some very long log when doing:
```sh
npm run dev
```
Now hidden but you still get important messages: build errors
> chore: hide useless info log, only show error log (build errors)

- README.md
- components/SearchBox/index.js
- example/app.js
- index.js
- widgets/search-box/index.js
- widgets/searchbox/index.js
+ do no send the full helper to widgets, bind functions
+ switch from widgets.searchbox to widgets.searchBox namespace (start with camelcase right now, avoid bad names later on)
+ allow adding classes to the generated input
+ add some doc
+ change folder requires to have a trailing slash
> feat: more searchBox work

- .eslintrc
- README.md
- components/BemHelper/index.js
- components/Hits/index.js
- components/Pagination/PaginationLink/index.js
- components/Pagination/Paginator/index.js
- components/Pagination/index.js
- components/SearchBox/index.js
- components/templates/Function/index.js
- components/templates/Hogan/index.js
- example/app.js
- example/index.html
- example/style.css
- example/templates/no-results.html
- index.js
- lib/InstantSearch.js
- lib/widgetUtils.js
- package.json
- widgets/hits/index.js
- widgets/pagination/index.js
- widgets/search-box/index.js
Mostly based on the work in ui-kit.
- default padding is 3 not 5
- labels are strings and merged with the default ones
- there is no wrapping `<nav>` around, only the `<ul>`
- `<, <<, >, >>` are hidden if not available instead of disabled.
Showing a no-click sign felt frustrating. If not available, not shown,
not needed
```html
<div id="pagination"></div>
```
```js
instant.addWidget(
instantsearch.widgets.pagination({
container: '#pagination',
// cssClass, // no default
// padding: 3, // number of page numbers to show before/after current
// showFirstLast: true, // show or hide first and last links
// hitsPerPage: 20,
// maxPages, // automatically computed based on the result set
// labels: {
//   previous: '‹', // &lsaquo;
//   next: '›', // &rsaquo;
//   first: '«', // &laquo;
// …
```
> feat(pagination): add pagination widget

- .eslintrc
- README.md
- components/Hits/index.js
- components/SearchBox/index.js
- example/app.js
- package.json
- widgets/hits/index.js
- widgets/pagination/index.js
+ allow configuring hitsPerPage on hits widget
+ rewrite a little of the hits widget to only use what we need to use (may have to expose more things in the future, like the query done in the empty template)
+ rename noResults in the widget API to empty (typeahead style)
+ removed hitsPerPage configuration from the pagination template
+ some linting and deps upgrade for free
> feat(hits): allow configuring hitsPerPage

- widgets/pagination/index.js
If we passed a `maxPages` attribute to the pagination widget, it used to always display that number of page, even if the `nbPages` returned was lower. No will only display pagination according to what is really returned.
> fix: cap the number of page displayed

- README.md
- components/MultipleChoiceList/index.js
- example/app.js
- example/templates/or.html
- webpack.config.js
- widgets/multiple-choice-list/index.js
- widgets/multiple-choice-list/template.html
New options:
- sortBy
- cssClass
- limit
- operator options
Also it DOES refine now.
There's some funny code inside the click handle on the LI.
> feat: MutlipleChoiceList second pass

- README.md
- components/MultipleChoiceList.js
- example/app.js
- example/index.html
- example/templates/category.html
- example/templates/or.html
- index.js
- widgets/menu.js
- widgets/multiple-choice-list.js
So it works(tm).
After a bit of tuning I was even able to get the bootstrap rendering to be fine. I first thought that we would hit a wall because of the react div wrapping but we are still ok.
As for the APIs: `menu`, `multipleChoiceList` (or `refinementList` is we rename it).
It does seems that they could all be the same widget. We only have three behaviors:
- `menu`: refinementList with only one selectable item at a time
- `refinementList` + multiple selectable items + AND
- `refinementList` + multiple selectable items + AND
We could merge both widgets into a single widget.
But we still need to express the hierarchical menu feature.
So having already a menu widget seems the easiest rather than trying to bend the `multipleChoiceList` API into something understanding the hierarchical …
> feat(menu): first widget version

- components/RefinementList.js
- example/index.html
- widgets/refinement-list.js
To be more precise: `<ul>` has a default margin of 10px bottom in bootstrap. It's not an issue if you precisely follow the bootstrap DOM format but otherwise it does not works.
So `<div>` being unstyled by default will in the end by easier to use for most websites.
Example:
> fix: switch back to divs in refinementList, rendering glitch

- README.md
- example/app.js
- lib/InstantSearch.js
- test/InstantSearch/lifecycle.js
- test/InstantSearch/recursively-merge-arrays-searchParameters.js
This adds named parameters when instanciating `instantsearch`, instead of having fixed arguments:
```javascript
var search = instantsearch({
applicationID: 'latency',
searchAPIKey: '6be0576ff61c053d5f9a3225e2a90f76',
indexName: 'instant_search'
});
```
This is needed for #77. I used `searchAPIKey` instead of `apiKey` to be explicit that this plugin is used for search only (we often have people on support using the wrong key). Better be explicit.
> feat:named parameters when instanciating

- README.md
- components/Stats.js
- components/Template.js
- example/app.js
- lib/InstantSearch.js
- lib/utils.js
- test/InstantSearch/lifecycle.js
- widgets/hits.js
- widgets/index-selector.js
- widgets/menu.js
- widgets/pagination.js
- widgets/range-slider.js
- widgets/refinement-list.js
- widgets/stats/index.js
- widgets/stats/template.html
- widgets/toggle.js
I've added `_formatNumber` to Hogan templates. It is also available through `search.templateHelpers.formatNumber` (`search` being the `instantsearch.js` instance).
I've updated all other widgets to accept the new `widget.render` syntax.
I'll update the other widgets (to use the `formatNumber` in prices and facet counts) after this PR is merged. I currently need to pass the `templateHelper` from instant search to the widget, then to the component, then to the template which is not optimal, though.
Also fixes #82 since the new render API is option object based
> feat: formatNumber in Stats widget

- lib/utils.js
> fix: More explicit error message when DOM selector is invalid

- components/RefinementList.js
- example/app.js
- widgets/menu.js
- widgets/refinement-list.js
Adds `transformData` parameter to the menu and refinementList widgets for review before implementing everywhere.
See #116 .
> feat(transformData): refinementList + menu implementation

- README.md
- example/index.html
- widgets/menu.js
- widgets/refinement-list.js
https://cdn.polyfill.io/v1/docs/ is a nice small polyfill
+ can't use Object.assign, would require another polyfill for most
browsers
IE8 support currently waiting for https://github.com/Financial-Times/polyfill-service/pull/483 merge, should be ok
> feat:IE8-9 support using a simpler polyfill

- README.md
- components/Hits.js
- components/RefinementList.js
- components/Stats.js
- components/Template.js
- components/Toggle.js
- widgets/hits.js
- widgets/refinement-list.js
- widgets/stats/index.js
- widgets/toggle.js
I've transferred the `transformData` call to the `Template` component because it seemed logical to put it here. Does this work for you guys ?
On widgets with header and footer, `transformData` is only used for item right now. Should we also enable it on header and footer?
For `hits`, which is the only one with two `Template`s, here is the API:
```js
transformData: {
empty: function (data) { /* ... */ },
hit: function (data) { /* ... */ }
}
```
> feat(transformData): add transformData to every widget using the Template component

- README.md
- components/Hits.js
- example/app.js
- widgets/hits.js
- Set JSON.stringify as default template
- Removing unused attributes (`hideWhenNoResults`, `hasResults`)
- Throw error if no valid container node
- Small ES6 changes
- Sorting of attributes
> refactor(hits): Remove unused attributes, set sensible defaults

- widgets/search-box.js
fixes #163
At some point we said that there was no need to update the input while it's focused since you are typing in it. Wonder if there are some cases where this can be an issue, but since we are using the "change" helper event it should be good.
> fix(searchBox): do not update input's value if focused

- README.md
- lib/InstantSearch.js
- lib/utils.js
Hogan still hasn't fixed it, so we implemented our own fix, but we weren't following the Mustache(5) spec either.
Changes the helper syntax from:
```js
helpers: function (renderedText) {
return '<h1>' + renderedText + '</h1>';
};
```
to:
```js
helpers: function (text, render) {
return '<h1>' + render(text) + '</h1>';
};
```
Also replaced the fat arrow of the wrapping closure by a simple `function` to allow Hogan to bind the currently rendered object. (This is unspecified by the Mustache spec, but is really useful)
> fix(templatesConfig): helpers are now following Mustache spec

- README.md
- components/Pagination/PaginationLink.js
- widgets/pagination.js
Allows to scroll to a particular element/CSSSelector after a click.
On by default (scroll to body).
Can be deactivated by setting it to false.
fixes #73
> feat(pagination): add `scrollTo` option

- index.js
- shams/Object.freeze.js
Object.freeze is used in various places in our code and is not
polyfilled by polyfill.io (because not doable): https://github.com
/Financial-Times/polyfill-service/issues/232
So we "sham" it, which means that the API is here but it just returns
the object.
IE8 support still waiting for https://github.com/Financial-Times
/polyfill-service/pull/485#issuecomment-145880032
> chore(IE8): add Object.freeze sham

- widgets/hierarchicalMenu.js
- widgets/menu.js
To avoid collisions when reordering widgets.
> fix(hierarchicalFacets): use a real attribute name for the hierarchicalFacet name

- README.md
- components/IndexSelector.js
- example/app.js
- widgets/index-selector.js
This one does not have any default styles (so no `css` file with it).
I still allow the styling of individual `option`, even if I'm unsure
this is even useful.
BREAKING CHANGE: We now use `cssClasses.select` and
`cssClasses.option` instead of `cssClass` for the index-selector
widget.
> feat(bem): Add BEM to the index-selector widget

- widgets/range-slider.js
Do not add the numeric refinements if the values are equal to min/max to
cleanup the state+URL. Fix #147
> Range slider: refinements cleanuo

- components/PoweredBy/index.js
- widgets/search-box.js
It must not be the responsability of the PoweredBy component to
show/hide itself. Fix #189
> PoweredBy: extract its hiding capabilities

- components/RefinementList.js
- widgets/refinement-list.js
The default limit should be 1000 to fit the API's default configuration.
Remove the limit option from the component itself, it's enough to have it in the
widget.
Set the maxValuesPerFacet if not set to optimize the JSON answer
payload.
Fix #155
> Refinement list limit improvement

- components/Hits.js
- components/Pagination/PaginationLink.js
- components/RefinementList.js
- components/Slider/index.js
- components/Template.js
- components/__tests__/Hits-test.js
- package.json
- widgets/hierarchicalMenu.js
- widgets/menu.js
- widgets/range-slider.js
- widgets/refinement-list.js
- widgets/stats/index.js
- widgets/toggle.js
React props and propTypes should now be set in alphabetical order.
This will help in the diffs and overall visual parsing of props.
Fixes #154 
For vim users, you can add `vnoremap s :!sort -V<CR>` to be able to
sort the current visual selection.
> style(eslint): Add ordering rule on React props

- components/Template.js
- components/__tests__/Template-test.js
- widgets/toggle.js
In case the `transformData` is not returning any value or
the wrong type, we now throw an explicit error.
Fix #212
> fix(transformData): add an explicit error message

- components/RefinementList.js
Before this fix, when clicking inside the child of a <a>..</a> would
propagate to the parent and thus in hierarchical facets would close the
parent as soon as we open the child.
fixes #191
> fix(RefinementList): click on child should not click on parent

- README.md
- widgets/refinement-list.js
I've passed the `operator` as optional in the docs as it was already done in the code. I've also removed the default value of `null` for mandatory parameters and simply check for them being falsy before triggering the usage message.
> docs(refinement-list): Update jsdoc and usage message

- scripts/validate-commit-msgs.sh
The current regexp was sometime refusing commit messages that are
valid (see
https://travis-ci.org/algolia/instantsearch.js/builds/85530333)
I've simply removed the `?:` and added a check on the `: `, and this
seems to work better.
I still have no idea why some commits where ok and some not. If anyone
has a guess...?
> fix(validate-commit): Update the regexp

- README.md
- widgets/refinement-list.js
Fixes #220
This also more explicitly set the default operator to `or`.
> fix(refinementList): Remove `singleRefine` attribute

- index.js
- widgets/refinement-list/defaultTemplates.js
- widgets/refinement-list/refinement-list.js
I've moved the default template from inline inside the widget to its
own file.
This will make my work adding the CSS classes much easier as I will
now have separate js, html and css files. As a bonus I gain syntax
highlighting and linters in vim as well.
I also think this will make generating the documentation (with HTML
code examples of the default templates) easier.
@vvo pointed out that `require`-ing html files was more or less
a webpack-specific feature and would be hard to port to other build
system. I feel that it's still worth it; what are your thoughts?
> feat(refinement-list): Move default template to its own file

- .babelrc
This will enable us writing this like:
```js
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
```
or
```js
var defaults = { first: 'John', last: 'Doe', age: 42 };
var trainer  = { last: 'Smith', age: 35 };
trainer      = { ...defaults, ...trainer, age: 36 }
// => { first: 'John', last: 'Smith', age: 36 }
```
More info: https://github.com/sebmarkbage/ecmascript-rest-spread
Babeljs should have this enabled by default, but it seems than for it
to work when using the babel plugin for webpack, we need to explicitly
enable it.
> feat(es7): Enable `es7.objectRestSpread`

- README.md
- components/RefinementList.js
- example/app.js
- example/style.css
- themes/debug.css
- widgets/refinement-list/defaultTemplates.js
- widgets/refinement-list/refinement-list.css
- widgets/refinement-list/refinement-list.js
This adds BEM classes to the refinement list in this form:
```html
<div class="ais-refinement-list--list">
<div class="ais-refinement-list--item">
<label class="ais-refinement-list--label">
<input type="checkbox" class="ais-refinement-list--checkbox" value="your_value"> Your value
<span class="ais-refinement-list--count">42</span>
</label>
</div>
<div class="ais-refinement-list--item ais-refinement-list--item__active">
<label class="ais-refinement-list--label">
<input type="checkbox" class="ais-refinement-list--checkbox" value="your_selected_value" checked="checked"> Your selected value
<span class="ais-refinement-list--count">42</span>
</label>
</div>
</div>
```
ie. adding classes on the lists, items (with active item flaggued as such), labels, checkboxes and counts. As usual, it is …
> feat(refinement-list): Add BEM naming

- README.md
- decorators/headerFooter.js
- example/app.js
- widgets/refinement-list/refinement-list.js
All headers and footers will now receive a `ais-header` and
`ais-footer` class. Additional classes can also be added through
`cssClasses.{root,header,body,footer}`.
It means that it is no longer necessary to pass a full HTML div in the
`templates.header`. One can simply pass the header text content and
pass a `cssClasses.header` custom class.
So far only the `refinementList` widgets correctly add the
`ais-widgetname-header`/`ais-widgetname-footer` classes. I'll update
the other widgets once this gets merged.
Fixes #259
Relies on https://github.com/algolia/instantsearch.js/pull/264 being
merged first
> feat(headerFooter): Add BEM classes to header and footer

- README.md
- components/Pagination/Pagination.js
- components/Pagination/PaginationLink.js
- components/RefinementList.js
- components/Template.js
- example/app.js
- example/templates/and.html
- example/templates/category.html
- index.js
- lib/InstantSearch.js
- lib/__tests__/InstantSearch-test.js
- lib/url-sync.js
- npm-shrinkwrap.json
- package.json
- widgets/hierarchicalMenu.js
- widgets/menu.js
- widgets/pagination/__tests__/pagination-test.js
- widgets/pagination/pagination.js
- widgets/refinement-list/refinement-list.js
- widgets/toggle/__tests__/toggle-test.js
- widgets/toggle/toggle.js
The urlSync is not a widget anymore and is now activated by the presence of the urlSync config object in the parameters of the instantSearch. Widget should implement the URL link feature.
This feature allow widget implementers to generate url for the changes to happen. This provide a createURL function as part of the rendering arguments. This is bound to the filtering and type of URL's.
The Template has been modified to be able to pass contextual data computed from the other components or widgets.
> feat(urlSync): url generation for widget links. Fix #29

- README.md
- components/IndexSelector.js
- components/__tests__/IndexSelector-test.js
- themes/default/default.css
- widgets/index-selector/__tests__/index-selector-test.js
- widgets/index-selector/index-selector.js
BREAKING CHANGE: Classes are now named `ais-index-selector` and
`ais-index-selector--item` to stay consistent with other widgets.
Updated tests as well. Widget is responsible for adding default
classes + user-defined ones. Then component simply add them to the
markup.
> feat(theme): Move `indexSelector` styling to default.css

- components/Pagination/Pagination.js
- components/Pagination/PaginationLink.js
- components/Pagination/__tests__/Pagination-test.js
- components/RefinementList.js
- lib/utils.js
It seems to be a common practice to not do anything if one of the special (shift, ctrl, alt or meta) keys are down:
https://github.com/search?q=react+metakey+ctrlkey+preventdefault&type=Code&utf8=%E2%9C%93
Fix #278
> fix(onClick): do not replace the browser's behavior on special clicks

- README.md
- components/Stats/Stats.js
- components/Stats/__tests__/Stats-test.js
- themes/default/default.css
- widgets/stats/__tests__/stats-test.js
- widgets/stats/defaultTemplates.js
- widgets/stats/stats.js
We can now easily spot in default.css which widget are not yet
BEMified (yeah, that's a verb now).
- Moved the BEM definition to widget instead of component
- Updated the tests
- This widget is using the headerFooter decorator, I updated the docs
- The initial root class was added twice because we already used it in the default template. I removed the wrapping div in the template.
BREAKING CHANGE: `cssClasses.root` now applies to the main root
element (above header and footer) and no longer to the template
wrapper. To style the template wrapper, use `cssClasses.body`
> fix(stats): Move CSS classes definition to widget from component

- README.md
- example/app.js
- index.js
- themes/default/default.css
- widgets/menu/defaultTemplates.js
- widgets/menu/menu.js
You know the drill.
- Updated BEM classes, including root, header, footer
- Updated docs
BREAKING CHANGE: The default template now has the count element inside
the link, not outside.
> feat(menu): Add BEM classes

- components/Hits.js
I forgot to move the `key` key to the parent element
> fix(hits): Fix warning about unique key in iterator

- components/Pagination/__tests__/Pagination-test.js
- components/Slider/__tests__/Slider-test.js
- components/Stats/__tests__/Stats-test.js
- components/__tests__/IndexSelector-test.js
- karma.conf.js
- npm-shrinkwrap.json
- package.json
- widgets/range-slider/__tests__/range-slider-test.js
- widgets/stats/__tests__/stats-test.js
- widgets/toggle/__tests__/toggle-test.js
In browser, every test file is a context so expect is not shared, so
we need to import it everywhere.
Which is good in the end, it's explicit.
> test: fix npm run test:watch:browser task

- README.md
- components/RefinementList/__tests__/RefinementList-test.js
- decorators/__tests__/autoHide-test.js
- decorators/autoHideContainer.js
- widgets/hierarchical-menu/hierarchical-menu.js
- widgets/index-selector/__tests__/index-selector-test.js
- widgets/index-selector/index-selector.js
- widgets/menu/menu.js
- widgets/pagination/__tests__/pagination-test.js
- widgets/pagination/pagination.js
- widgets/price-ranges/__tests__/price-ranges-test.js
- widgets/price-ranges/price-ranges.js
- widgets/range-slider/__tests__/range-slider-test.js
- widgets/range-slider/range-slider.js
- widgets/refinement-list/refinement-list.js
- widgets/stats/__tests__/stats-test.js
- widgets/stats/stats.js
- widgets/toggle/__tests__/toggle-test.js
- widgets/toggle/toggle.js
BREAKING CHANGE: Widget attribute is now named
`hideContainerWhenNoResults` instead of `hideWhenNoResults` to be more
explicit on what it is really doing.
Also internally renamed the `autoHide` decorator to
`autoHideContainer`
Fixes #325
> fix(autohide): Rename attribute to `hideContainerWhenNoResults`

- components/Template.js
- components/__tests__/Template-test.js
The Template component shouldn't throw an error if you define
the transformData for a single templateKey.
Fix #347
> fix(template): transformData checks too strict

- scripts/build.sh
I also took the liberty to remove "useless" double quotes because I hope we'll never consider putting spaces in the filename and added braces for clarity when a variable was followed by a dot (the syntax coloration of vim failed on it, and colored it with the extension).
See #145 .
> chore(build): Add map file to the build

- README.md
- widgets/hierarchical-menu/hierarchical-menu.js
- widgets/hits-per-page-selector/hits-per-page-selector.js
- widgets/hits/hits.js
- widgets/index-selector/index-selector.js
- widgets/menu/menu.js
- widgets/pagination/pagination.js
- widgets/price-ranges/price-ranges.js
- widgets/range-slider/range-slider.js
- widgets/refinement-list/refinement-list.js
- widgets/search-box/search-box.js
- widgets/stats/stats.js
- widgets/toggle/toggle.js
Used this script to automatically do it:
```sh
#! /usr/bin/bash
for wrapper in String Number Boolean; do
prim=`echo $wrapper | tr '[:upper:]' '[:lower:]'`
for file in `echo README.md widgets/*/*.js`; do
for i in `seq 3`; do
sed -i -r "s/(@param.*)(${wrapper})/\1${prim}/g" $file
done
done
done
```
I think it should have gotten all of them. Maybe you can think of some other places than on the `@param` lines where we should replace them?
> docs(widgets): Use primitive types instead of wrappers

- README.md
- themes/default.css
- widgets/search-box/__tests__/search-box-test.js
- widgets/search-box/search-box.js
BREAKING CHANGE: The `input` used by the search-box widget is now
wrapped in a `<div class="ais-search-box">` by default. This can be
turned off with `wrapInput: false`.
This PR is a bit long, I had to do some minor refactoring to keep the
new code understandable. I simply split the large `init` method into
calls to smaller methods.
There is some vanilla JS DOM manipulation involved to handle all the
possible cases: targeting an `input` or a `div`, adding or not the
`poweredBy`, adding or not the wrapping div.
Note that there is no `targetNode.insertAfter(newNode)` method, so
I had to resort to the old trick of `parentNode.insertBefore(newNode,
targetNode.nextSibling)`.
> feat(searchBox): Add `wrapInput` option

- decorators/__tests__/autoHide-test.js
- decorators/__tests__/headerFooter-test.js
The warning `Warning: React.createElement: type should not be null,
undefined, boolean, or number. It should be a string (for DOM
elements) or a ReactClass (for composite components).` was caused by
calling the test decorator on `<div />` instead of `'div'`.
As the message suggest, we should use strings for basic DOM elements.
> chore(warnings): Remove test warning about `type should not be null`

- lib/InstantSearch.js
- lib/__tests__/InstantSearch-test.js
- lib/__tests__/main-test.js
- lib/main.js
Fix #372
BREAKING CHANGE: the instantsearch.createURL method is now taking a
simple JS object and not a SearchParameter instance anymore.
> feat(urls): ability to create an URL from a set of params

- decorators/__tests__/TestComponent.js
- decorators/__tests__/autoHide-test.js
- decorators/__tests__/headerFooter-test.js
As discussed in #374, I've added the TestComponent to test decorators.
> test(decorators): Use TestComponent instead of string

- decorators/__tests__/headerFooter-test.js
- decorators/headerFooter.js
Fixes #370
BREAKING CHANGE: The `<div class="ais-header">` and `<div
class="ais-footer">` markup is only added when
a `templates.{header,footer}` is passed.
> feat(headerFooter): Only add markup if a template is defined

- decorators/__tests__/autoHideContainer-test.js
- decorators/autoHideContainer.js
- widgets/hierarchical-menu/hierarchical-menu.js
- widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
- widgets/hits-per-page-selector/hits-per-page-selector.js
- widgets/index-selector/__tests__/index-selector-test.js
- widgets/index-selector/index-selector.js
- widgets/menu/menu.js
- widgets/pagination/__tests__/pagination-test.js
- widgets/pagination/pagination.js
- widgets/price-ranges/__tests__/price-ranges-test.js
- widgets/price-ranges/price-ranges.js
- widgets/range-slider/__tests__/range-slider-test.js
- widgets/range-slider/range-slider.js
- widgets/refinement-list/refinement-list.js
- widgets/stats/__tests__/stats-test.js
- widgets/stats/stats.js
- widgets/toggle/__tests__/toggle-test.js
- widgets/toggle/toggle.js
Removed `hideContainerWhenNoResults` prop from the props passed to all components.
`autoHideContainer` now accepts only one prop: `shouldAutoHideContainer` instead of `hasResults`.
Closes #324
> chore(autoHideContainer): Generic implementation

- docs/css/_documentation.sass
- docs/js/doc.js
I managed to extract the HTML code from the actual widgets and make it look pretty nice (heavyweight regexps however):
> chore(documentation): add the rendered HTML code as well. Fix #402

- docs/css/_documentation.sass
Move the scrollbars around, remove some useless scrollbars on the body. (also change the font-weight of the menu to make it lighter)
> fix(live-doc): move scrollbars, removes useless ones #412

- docs/_includes/header.html
- docs/css/_header.sass
Before: 
and
After:
Let me know
> doc(github): put logo next to the menu

- package.json
Maybe the simplest is to use vanilla JS here :)
```
./scripts/doc/gen-widget-doc.js:3
let jsdoc2md = require('jsdoc-to-markdown');
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:413:25)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:475:10)
at startup (node.js:117:18)
at node.js:951:3
``
> fix(jsdoc): use babel-node

- package.json
- scripts/build.sh
- webpack.config.jsdelivr.babel.js
fixes #373
This is a try at it, not sure this is sufficient
> feat(build): allow building React based custom widgets

- widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
- widgets/hits-per-page-selector/hits-per-page-selector.js
Removes the dependency on hitsPerPage.
Follow-up of #450.
Basically, the issue this solves is mostly linked to the fact that the user can have an impact on the `hitsPerPage` through the URL.
It can happen in two ways:
- Either the end-user modifies the `hPP` in the URL
- Or the developer changes the options and a user uses an old URL with `hPP` not available in the options.
@ElPicador Would this work for you?
> fix(hitsPerPageSelector): Be more tolerant in options

- docs/css/_documentation.sass
- docs/js/doc.js
I had a hard time finding how to fix this one :skull: 
Fix #444
(includes a fix in the indentation of the HTML code as well)
> fix(doc): ensure the documentation content doesn't overflow

- docs/_layouts/documentation.html
- webpack.dev.config.babel.js
That's required while creating doc of new (non-published) widgets
> chore(website): override with the latest/dev instantsearch.js if possible

- docs/_includes/widget-jsdoc/toggle.md
- docs/documentation.md
- widgets/toggle/__tests__/toggle-test.js
- widgets/toggle/toggle.js
Fixes #409
Adds the `values` option to the `toggle` widget. Defaults to `{on:
true, off: undefined}`.
- It does not break previous API, new default value is
retro-compatible
- If `off` set to `undefined`, it will simply remove all filtering on
this facet when unchecking
- If `off` set to anything else, it will allow toggling between `on`
and `off` value when checking/unchecking the checkbox
- If an `off` value is set and the results are not currently filtered
on the `on` value at startup, then we add filtering on `off`. This
helps in not creating an undefined state on first load.
To test if a refinement was currently set on a specific value, I had
to use `helper.state.isFacetRefined`, I did not found any method
directly on the helper. Maybe I missed something.
> feat(toggle): Allow custom on/off values

- widgets/numeric-refinement-list/numeric-refinement-list.js
`Array.protoype.find` does not have a large enough support. Let's use
lodash instead.
> fix(numeric-refinement): Replace Array.find with lodash find

- CONTRIBUTING.md
I think what we want to say is that we should squash commits together
to remove the unnecessary and temporary commits before accepting the
PR. We still use rebase when keeping in sync with develop.
> docs(contributing): Use squash instead of rebase

- lib/__tests__/utils-test.js
- lib/utils.js
- npm-shrinkwrap.json
- package.json
Used temporarily before https://github.com/algolia/algoliasearch-helper-js/issues/195 is resolved.
The rationale of why I did it in `lib/utils` instead of the helper is that the helper's `getRefinements` is not sending back tags right now and throws errors on `state.get{Conjunctive,Disjunctive,Numeric}Refinements(facetName)` when `facetName` is `undefined` and I didn't want to mess it up.
Will be used for #404 and #405 .
> chore(getRefinements): Returns a list of refinements

- npm-shrinkwrap.json
- package.json
- widgets/price-ranges/price-ranges.js
- widgets/range-slider/__tests__/range-slider-test.js
- widgets/range-slider/range-slider.js
Previously : 
Now : 
FAQ : 
I can still see the outer bounds changing when you click on the first prices ranges ?
This is because the first widgets is based on different attribute. So even though, the slider uses a disjunctive facet, the outer bounds will be modified.
> Fixes various update problems in numerics widgets

- lib/utils.js
We let middle clicks go through
`Array.protoype.find` does not have a large enough support. Let's use
lodash instead.
(Requires https://github.com/algolia/instantsearch.js/pull/480 being merged first)
> fix(middle-click): Allow middle click on links

- widgets/range-slider/range-slider.js
My browser (Chromium Version 44.0.2403.89 Ubuntu 15.04 (64-bit)) does not have Array.prototype.find.
Tests in the console are passing, but everytime I launch the demo I have errors. I'll see to find a way to have eslint preventing us from using Array.prototype.find
> fix(range-slider): Use lodash find instead of Array.prototype.find

- css/default/_hierarchical-menu.scss
- dev/style.css
BREAKING CHANGE: Hierarchical menu levels 1 and 2 now have
a margin-left added in the default theme.
> feat(hierarchicalMenu): Adding indentation with default theme

- docs/README.md
- docs/_layouts/documentation.html
- package.json
- scripts/dev-docs.sh
Added an `npm run dev:docs` task to avoid doing weird hacks to handle both devs running `npm run dev` + `docs/guard`.
Now you just do `npm run dev:docs` when you want to dev on docs.
We might want at some point to have the docs instantsearch watch build running on another port.
> documentation(workflow): add npm run dev:docs

- css/default/_pagination.scss
- docs/css/default-theme.css
Needs #511 merged first
- Moved pagination default styling (aligning items on the same line) to default instantsearch.css
- Removed a few unused CSS rules from `default-theme.css`
> docs(theme): Fix a few styling issues on documentation

- docs/css/_header.sass
- docs/index.haml
- docs/js/home.js
> docs(menu): change the text color when reaching the white background

- css/default/_pagination.scss
This have been reverted in a bad merge, I'm re-adding it.
> fix(theme): Revert default spacing into pagination

- components/Pagination/Pagination.js
- components/Pagination/PaginationLink.js
- components/Pagination/__tests__/Pagination-test.js
- css/default/_pagination.scss
- docs/_includes/widget-jsdoc/pagination.md
- docs/examples/airbnb/scss/_pagination.scss
- docs/examples/youtube/scss/_pagination.scss
- widgets/pagination/__tests__/pagination-test.js
- widgets/pagination/pagination.js
Fixes #500
BREAKING CHANGE: Removes all `__disabled`, `__first`, `__last`,
`__next`, `__previous`, `__active` and `__page` classes added on the links in the
pagination. It only adds them to the parent `li`. Links instead now
have a `.ais-pagination--link` class
Previously, the same CSS classes where added to both the `item` (`li`) and the
link inside it. I've split them in `--item` and `--link`.
I've also made the various active/first/disabled/etc modifiers as
actual `__modifier` classes.
I've updated the tests, the CSS skeleton, the examples and the docs
accordingly.
The mixins and internal variable where misnamed. We use the BEM naming
with the following pattern: `.ais-block--element__modifier`.
Mixins where usin `component` instead of `block` and where swapping
`element` and …
> fix(pagination): Fix double BEM classes on elements

- docs/documentation.md
Was previously using the `hits` description
> docs(hitsPerPageSelector): Add widget description

- docs/examples/airbnb/scss/_pagination.scss
- docs/examples/youtube/scss/_pagination.scss
`_pagination.scss` files were not scss compatible, Guard could not
process them. They were missing `;`. My bad.
We'll have to add a lint rule for that.
> doc(examples): Lint scss

- docs/_includes/widget-jsdoc/hitsPerPageSelector.md
- docs/_includes/widget-jsdoc/pagination.md
- docs/_includes/widget-jsdoc/priceRanges.md
- docs/_includes/widget-jsdoc/rangeSlider.md
- docs/_includes/widget-jsdoc/searchBox.md
- widgets/hits-per-page-selector/hits-per-page-selector.js
- widgets/pagination/pagination.js
- widgets/price-ranges/price-ranges.js
- widgets/range-slider/range-slider.js
- widgets/search-box/search-box.js
This was messing the display of some documentations.
> doc(jsdoc): Wrap HTML code examples in `quotes`

- scripts/gh-pages.sh
Current website for instantsearch is trying to load the local css
> docs(jekyll): set env to production when building gh pages

- docs/_includes/header.html
- docs/_includes/newsletter-mc.html
- docs/documentation.md
- docs/examples.haml
- docs/index.haml
As a dev I hate target=_blank. If I want to open a new tab I
will do it: **trust me** I am an engineer!
I feel we do not need target=_blank, we should not fear people will
"leave" our website and not comeback. They will and they will not be
disapointed because of weird target blank (especially on mobile, its
painful. The navigation flow is stopped).
back button works really well
> docs(target): remove target=_blank from links

- docs/_includes/widget-jsdoc/addWidget.md
- docs/_includes/widget-jsdoc/hierarchicalMenu.md
- docs/_includes/widget-jsdoc/hits.md
- docs/_includes/widget-jsdoc/hitsPerPageSelector.md
- docs/_includes/widget-jsdoc/indexSelector.md
- docs/_includes/widget-jsdoc/instantsearch.md
- docs/_includes/widget-jsdoc/menu.md
- docs/_includes/widget-jsdoc/numericRefinementList.md
- docs/_includes/widget-jsdoc/pagination.md
- docs/_includes/widget-jsdoc/priceRanges.md
- docs/_includes/widget-jsdoc/rangeSlider.md
- docs/_includes/widget-jsdoc/refinementList.md
- docs/_includes/widget-jsdoc/searchBox.md
- docs/_includes/widget-jsdoc/stats.md
- docs/_includes/widget-jsdoc/toggle.md
- docs/css/_documentation.sass
- docs/documentation.md
- lib/InstantSearch.js
- scripts/doc/gen-widget-doc.js
- scripts/doc/widgetTemplate.hbs
- use the jsdoc2md tool to generate the `instantsearch()` and
`addWidget` documentation as well
- update the default template to display the default value & type
Fix #473
> chore(doc): add default values & parameter types

- components/ClearAll/ClearAll.js
- components/ClearAll/__tests__/ClearAll-test.js
- css/default/_clear-all.scss
- css/instantsearch.scss
- dev/app.js
- dev/index.html
- docs/_includes/widget-jsdoc/clearAll.md
- docs/documentation.md
- lib/main.js
- widgets/clear-all/__tests__/clear-all-test.js
- widgets/clear-all/clear-all.js
- widgets/clear-all/defaultTemplates.js
Uses #407 's `autoHideContainer` instead of `hideContainerWhenNoResults`. We might want to wait until this is implemented in all widgets before merging.
Closes #405
> feat(clearAll): New widget

- components/RefinementList/RefinementList.js
- components/RefinementList/__tests__/RefinementList-test.js
- docs/_includes/widget-jsdoc/menu.md
- docs/_includes/widget-jsdoc/refinementList.md
- docs/_includes/widget-jsdoc/toggle.md
- docs/css/_documentation.sass
- docs/documentation.md
- docs/js/doc.js
- widgets/hierarchical-menu/hierarchical-menu.js
- widgets/menu/__tests__/menu-test.js
- widgets/menu/menu.js
- widgets/refinement-list/__tests__/refinement-list-test.js
- widgets/refinement-list/refinement-list.js
- widgets/toggle/__tests__/toggle-test.js
- widgets/toggle/toggle.js
Fixes #156 
There are a few unrelated changed in this PR and I apologize for that.
The more controversial change is renaming the `facetName` to `attributeName` everywhere. After discussing with @vvo and @seafoox, we realized that not all widgets needed an `attributesForFacetting` defined. For example, the `numericFacetRefinement` does not need one, but the `rangeSlider` does (to get the min/max values).
In order to make the public API more consistent, we decided that all attributes could be named `attributeName` and that the required facet configuration should be clearly indicated in the docs.
Most of the diff is actually the search/replace part and the regeneration of the markdown doc.
I've also had to refactor the way the button toggling was working to use a more generic method of …
> docs(requirements): Add Algolia requirements to the doc

- .gitattributes
We have some files with windows line feed, dunno why. We can force it from gitattributes. Anyone with git powerskills can check this? :)
> chore(line endings): force lf

- docs/_layouts/default.html
- docs/_layouts/documentation.html
- docs/css/instantsearch.css
- docs/js/instantsearch.js
This will load `instantsearch.css` and `instantsearch.js` from the same host in dev. This only use symlinks to the build files.
> docs(documentation): Stop loading files from localhost:8080

- docs/_config.yml
- docs/_layouts/default.html
- docs/_layouts/documentation.html
Jekyll now is exposed on 0.0.0.0, which means that you can connect to
it through your machine ip. Webpack-dev-server was already doing it,
as well as the guard livereload.
All the instantsearch css, js and livereload are now loaded through
ugly `document.write` calls in dev mode, to be able to know which is
the current ip that is used to access the website.
This works both when testing locally on desktop, on mobile through the
same wifi network, and through an ngrok tunnel.
> docs(dev): Expose all internal webservers to the same ip

- docs/_layouts/default.html
- docs/documentation.md
`active` class was defined twice and was breaking IE11 strict mode.
Also, it is needed to encode the `<` in the `document.write` hack otherwise the parser gets confused.
> docs(ie11): Fix rendering on IE11

- docs/examples/e-commerce/style.scss
Fix found at: http://www.carsonshold.com/2014/07/css-display-table-cell-child-width-bug-in-firefox-and-ie/
> docs(examples): Fix e-commerce image display on IE11

- docs/_includes/header.html
- docs/css/_search.sass
As discussed with @Shipow I expanded the search bar on the documentation page.
I took the liberty of adding a placeholder, I think it's better with it but I can remove it if needed
> fix(doc): Expand input on documentation page

- docs/_config.yml
- docs/js/search.js
- scripts/gh-pages.sh
Reindex the documentation as soon as you release a new version of the
website. You need to export the associated ALGOLIA_API_KEY env variable.
Also move to the world-wildly replicated `latency` account.
> chore(doc): documentation reindexing

- src/widgets/price-ranges/__tests__/generate-ranges-test.js
- src/widgets/price-ranges/generate-ranges.js
This is to avoid having a no result "<= n" first range if the round was < to stats.min
> fix(priceRanges): Remove round from first range

- scripts/build.sh
- scripts/webpack.config.jsdelivr.babel.js
Instead of having the whole bundle being the source of all the code.
This will show individual source maps back to the original src/ filetree when debugging live implementations using jsdelivr. Nice
> chore(build): generate source map based on original files

- npm-shrinkwrap.json
- package.json
Before:
```sh
=> instantsearch.min.js gzipped will weight 104.14 kB
```
After:
```sh
=> instantsearch.min.js gzipped will weight 96.82 kB
```
=> -7% filesize
Found out that we were using bad files by using http://chrisbateman.github.io/webpack-visualizer/ and https://github.com/danvk/source-map-explorer which are doing the same thing but showing the filetree differently.
I had done a bad thing: insert a copy pasted cloning function into
nouislider algolia fork. This clone function made usage of nodejs
Buffer class (for nothing, just importing it in case there was a
Buffer to copy).
It's now removed since we are re-creating instances of nouislider
everytime props changes.
It's still tracked in nouislider repo:
leongersen/noUiSlider#537
> chore(build): upgrade nouislider to reduce build size

- src/lib/__tests__/utils-test.js
- src/lib/utils.js
- src/widgets/clear-all/__tests__/clear-all-test.js
- src/widgets/clear-all/clear-all.js
Since currentRefinedValue will use the same methods because it embeds a
"Clear all" link, they need to be extracted and able to only receive
a subset of `attributeNames`.
> feat(clearRefinements): Added two utils methods

- index.js
- scripts/bump-package-version.js
- src/components/ClearAll/ClearAll.js
- src/components/ClearAll/__tests__/ClearAll-test.js
- src/components/Pagination/Pagination.js
- src/components/RefinementList/RefinementList.js
- src/lib/InstantSearch.js
- src/lib/main.js
- src/lib/url-sync.js
- src/widgets/clear-all/clear-all.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/hits-per-page-selector/hits-per-page-selector.js
- src/widgets/hits/hits.js
- src/widgets/menu/menu.js
- src/widgets/numeric-refinement-list/numeric-refinement-list.js
- src/widgets/numeric-selector/numeric-selector.js
- src/widgets/pagination/pagination.js
- src/widgets/price-ranges/price-ranges.js
- src/widgets/range-slider/range-slider.js
- src/widgets/refinement-list/__tests__/refinement-list-test.js
- src/widgets/refinement-list/refinement-list.js
- src/widgets/search-box/search-box.js
- src/widgets/sort-by-selector/sort-by-selector.js
- src/widgets/star-rating/star-rating.js
- src/widgets/stats/stats.js
- src/widgets/toggle/__tests__/toggle-test.js
- src/widgets/toggle/toggle.js
For `require`s
```sh
ag -l "require\(.*.js.\)" | xargs -I {} sed -i -r '/(hogan|instantsearch)/! s#(require\(.*)\.js(.\))#\1\2#g' {}
```
For `import ... from ...`
```sh
ag -l "import .* from .*\.js" | xargs -I {} sed -i -r 's/(import.*from .*)\.js/\1/g' {}
```
Just here for consistency.
> style(require/from): Never use .js in requires and froms

- src/lib/__tests__/utils-test.js
- src/lib/utils.js
Bug fix of not retrieving the count on a hierarchical facet
It now only returns the last value (will be needed by `currentRefinedValues`).
Incidentally, getRefinements now also returns the type of facet for convenience.
> fix(getRefinements): hierarchical facets

- dev/app.js
- dev/index.html
- dev/style.css
- src/components/CurrentRefinedValues/CurrentRefinedValues.js
- src/components/CurrentRefinedValues/__tests__/CurrentRefinedValues-test.js
- src/css/default/_current-refined-values.scss
- src/css/instantsearch.scss
- src/lib/main.js
- src/widgets/current-refined-values/__tests__/current-refined-values-test.js
- src/widgets/current-refined-values/current-refined-values.js
- src/widgets/current-refined-values/defaultTemplates.js
New widget specified in multiple issues (#112, #378 and #404) and took a long time. :)
Closes #404.
Needs #698 and #699 merged first.
- A `label` can be specified in the `attributes` objects and is used in the default *item* template if given.
This is especially needed for numeric filters, where displaying a label is needed, and the `attributeName` is rarely what you want to display.
In the end, this allows to do this:
```js
currentRefinedValues({
container: '#my-container',
attributes: [
{
name: 'price_range',
label: 'Price range'
}
]
})
/*
* => Displays:
* Price range: $10 - $20
* Price range: $20 - $30
* Price range: $30 - $40
*/
```
- A `template` can also be passed to a specific attribute. Since you can pass a custom `transformData`, it also made sense to be able to pass a template. …
> feat(currentRefinedValues): new widget

- dev/app.js
Was not working with `undefined` first value (linked with #665)
Did not have the right operator nor the right values for the dataset
> chore(dev): fix dev app popularity selector

- src/components/PoweredBy/PoweredBy.js
- src/components/PoweredBy/__tests__/PoweredBy-test.js
Suggestion of Guillaume D that @redox approved. Makes a bit more sense, but definitely open to discussion.
If we chose to accept that, we could maybe also rename the `PoweredBy` component and the `searchBox` parameter `poweredBy`, but this would be a breaking change.
> refactor(PoweredBy): Use "Search by Algolia"

- index.js
Related to https://github.com/webpack/webpack/issues/706 .
Basically, we can't do `export default mymodule;` with webpack. The library would end up being:
```js
{
default: MyLib
}
```
> fix(index): Use module.exports instead of export on index

- src/components/Hits.js
- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
This solves a bug found using safari and that may or may not
break an implementation based on InstantSearch.
Safari triggers a pop state event on load, which triggers a new
search. But at this point the index is not in the initial
configuration, so this search will fail with a 400, indexName not
valid.
With this fix the value for the index name is taken from the parameters
and its value is added to the initial search configuration.
> fix(url-sync): adds indexName in the helper configuration

- src/widgets/search-box/__tests__/search-box-test.js
- src/widgets/search-box/search-box.js
we were previously using the previous state I believe.
This bug can be seen by hitting the back button while not being
focused.
> fix(search-box): update value when state changes from the outside

- scripts/release-beta.sh
- scripts/release.sh
- stop releasing beta along with stable when releasing stable
- stop comitting beta version metadata to package.json etc.. It then trigger conflicts when merging stable into develop
> chore(beta): do not commit to git the beta release meta

- dev/app.js
- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/url-sync.js
- src/widgets/search-box/__tests__/search-box-test.js
- src/widgets/search-box/search-box.js
2 main changes here :
- the url-sync internal widget now relies on the helper directly and
not on the instantsearch lifecycle anymore.
- there is dedicated channel of update for the changes coming from the
history (private API for the moment)
FIX #730
FIX #729
> fix(url-sync): Makes url sync more reliable

- dev/app.js
- dev/index.html
- dev/style.css
- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/components/Template.js
- src/components/__tests__/Template-test.js
- src/css/default/_refinement-list.scss
- src/lib/__tests__/utils-test.js
- src/lib/utils.js
- src/widgets/refinement-list/__tests__/refinement-list-test.js
- src/widgets/refinement-list/defaultShowMoreTemplates.js
- src/widgets/refinement-list/refinement-list.js
The API changed slightly from the original proposition; It still adds a new object in the configuration of the refinementlist, but the attributes are : 
- limit : for the max number of items when showing more
- templates : 
- active: when showing more
- inactive: when showing less
and it reuses the currently implemented limit parameter .
> feat(refinementlist): lets configure showmore feature FIX #401

- dev/app.js
- dev/index.html
- dev/templates/all-items.html
- dev/templates/item.html
- src/components/Hits.js
- src/components/__tests__/Hits-test.js
- src/widgets/hits/__tests__/hits-test.js
- src/widgets/hits/hits.js
Adds a way to let the user specify how to do the complete rendering of the hits. FIX #771
> feat(hits): adds allItems template as an alternative to item

- docs/_includes/footer.html
- docs/css/_examples.scss
- docs/css/main.scss
- docs/examples.haml
So I added breakpoints as @pixelastic suggested. If the screen is too small then the enclosing link will widen to 100%, and if the screen is even smaller the image will be centered.
Also I made sure that all the elements in the page were using the same left/right margin (container).
> docs(css): Fix example page on mobile (fix #636)

- src/widgets/hits/hits.js
Seems like the `allItems` property for both template and transformData
was a copy-paste of the `item` one.
> docs(hits): Update documentation for the `allItems` property

- docs/documentation.md
Link was incorrectly pointing to documentation for the googleMaps widget.
> (docs): fix link to full documentation for Ion.RangeSlider

- functional-tests/app/app.js
- src/components/Slider/Slider.js
- src/components/Slider/__tests__/Slider-test.js
- src/decorators/__tests__/autoHideContainer-test.js
- src/decorators/autoHideContainer.js
The previous strategy for autoHideContainer was to either return an
empty div or the wrapped element.
So when the widget cycle was like this: init => hide (no results) =>
show (results) then we would re-create instances of React components because of a
different render() output in autoHideContainer.
This I discovered it while going to do #835: when the widgets would
hide => show we would lose the wrapped React component state resulting
in lost collaspable state.
Not only this commit will permit doing #835 easily but it also somehow
enhance performance since I also added a shouldComponentUpdate
strategy.
Added more precise tests on this decorator/HOC.
The slider needed an update because we are now trying to render it (once as soon as we are transitioning from hidden) with ranges being the …
> perf(autoHideContainer): stop re-creating React components when going from hide to show

- src/components/Template.js
- src/components/__tests__/Template-test.js
templateKey can be updated in some cases while the data stayed the
same, example: showMore => showLess
> fix(Template): now render() when templateKey changes

- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/RefinementListItem.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/widgets/toggle/__tests__/toggle-test.js
- src/widgets/toggle/toggle.js
Was broken since perf improvements: we did not wanted to bind the
function with isRefined in render() to avoid generating new function
references each time.
But we still need it, so passed all the way down from RefinementListItem
> fix(toggle): pass isRefined to toggleRefinement

- src/widgets/search-box/__tests__/search-box-test.js
- src/widgets/search-box/search-box.js
We were previously setting the query on every keystroke twice, because
of the keyup + input events.
Now fixed.
This was not triggering any bad behavior but extra work and maybe bad
performance because the way we set queries in the helper (to be worked
on)
+ refactor
+ update tests
> fix(searchBox): stop setting the query twice

- dev/app.js
- dev/style.css
- src/css/_base.scss
- src/decorators/__tests__/headerFooter-test.js
- src/decorators/headerFooter.js
- src/widgets/clear-all/__tests__/clear-all-test.js
- src/widgets/clear-all/clear-all.js
- src/widgets/current-refined-values/__tests__/current-refined-values-test.js
- src/widgets/current-refined-values/current-refined-values.js
- src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/menu/menu.js
- src/widgets/numeric-refinement-list/__tests__/numeric-refinement-list-test.js
- src/widgets/numeric-refinement-list/numeric-refinement-list.js
- src/widgets/price-ranges/__tests__/price-ranges-test.js
- src/widgets/price-ranges/price-ranges.js
- src/widgets/range-slider/__tests__/range-slider-test.js
- src/widgets/range-slider/range-slider.js
- src/widgets/refinement-list/refinement-list.js
- src/widgets/star-rating/__tests__/star-rating-test.js
- src/widgets/star-rating/star-rating.js
- src/widgets/stats/__tests__/stats-test.js
- src/widgets/stats/stats.js
- src/widgets/toggle/__tests__/toggle-test.js
- src/widgets/toggle/toggle.js
Demo:
All `header` capable widgets are now collapsable aware.
New options:
- collapsable: Hide the widget body and footer when clicking on header
- collapsed: Initialize the widget in collapsed state
This also adds:
- ais-root generic css class
- ais-body generic css class
To be in par with already existing ais-header, ais-footer.
This also adds:
- ais-root__collapsable css class
- ais-root__collapsed css class
> feat(collapsable widgets): add collapsable and collapsed option

- dev/app.js
- dev/index.html
- dev/style.css
- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
add a new option to the instantsearch: searchFunction. It allows user
to override the default call to helper.search() by anything they want.
With this, they will be able to implement:
- do not search at first render
- do not search when query < 3 chars
- any conditional we cannot think of
Example usages:
```js
var search = instantsearch({
searchFunction(helper) {
if (initialRender) {
initialRender = false;
return;
}
if (helper.state.query.length < 3) {
return;
}
helper.search();
}
})
```
> feat(instantsearch): allow overriding the helper.search function

- src/widgets/menu/menu.js
- src/widgets/refinement-list/refinement-list.js
This should be a non breaking change since we are ranking the same way as before but on cases where we have same counts, we rank by name
> fix(menu,refinementList): sort by count AND name to avoid reorders on refine

- docs/documentation.md
- src/widgets/toggle/toggle.js
When we updated the toggle widget to provide on/off values, we didn't properly document the update.
Related to http://stackoverflow.com/questions/35750620/setting-initial-facet-refinement-values-when-using-instantsearch-js .
> docs(toggle): refresh the widget description

- src/components/CurrentRefinedValues/CurrentRefinedValues.js
- src/components/Hits.js
- src/components/Pagination/PaginationLink.js
- src/components/PriceRanges/PriceRanges.js
- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/RefinementListItem.js
- src/components/Slider/Slider.js
- src/components/Template.js
- src/lib/__tests__/main-test.js
Using import {forEach} from 'lodash'; seems not supported in lodash 3:
the function is imported but also the whole lodash code is exposed and
erase the `window._`.
Not good!
This is a hotfix
> fix(lodash): stop leaking lodash in the global scope

- scripts/validate-pr-done-on-develop.sh
I've added the possibility to push `docs()` commits when doing a PR to
master. Previously only messages containing the word `hotfix` could
pass the test. This should allow us more flexibility in fixing
documentation issues.
The public website is automatically build whenever a new commit lands
on master.
I've also refactored the file to follow linting advice from
`shellcheck` and make the three tests (hopefully) more readable.
> feat(validate-pr): Allow `docs()` commits to be merged in master

- src/components/Hits.js
- src/components/RefinementList/RefinementList.js
- src/components/Template.js
- src/components/__tests__/Hits-test.js
- src/components/__tests__/Template-test.js
- src/decorators/__tests__/headerFooter-test.js
- src/decorators/headerFooter.js
- src/widgets/refinement-list/__tests__/refinement-list-test.js
- src/widgets/toggle/__tests__/toggle-test.js
Avoid `<div data="[object Object]">` being inserted in the DOM in
production builds.
The bug was introduced by
https://github.com/algolia/instantsearch.js/commit/fcfb990c9d059f59389b753b5abdecfba0dcd0f8
where we started using transform-react-remove-prop-types.
We cannot rely on PropTypes in production env because they are
removed.
We ask the dev to be explicit in what he's doing: use rootProps versus
forwarding everything a bit magically.
fixes #899
> fix(Template): stop leaking `data="[object Object]"` attributes in production

- dev/app.js
- src/lib/InstantSearch.js
- src/lib/url-sync.js
No test added to this commit because the `url-sync-test.js` does not yet exist.
Will close #838 .
Uses https://github.com/algolia/algoliasearch-helper-js/pull/281 .
> feat(url-sync): use the new mapping option

- scripts/validate-pr-done-on-develop.sh
The script to validate PRs was really confusing about what being a PR
meant or not. This version should work better.
Basically it will succeed when not on Travis, reject PRs not on
develop, except if they are on master with either a `docs()` or
a `hotfix` mention.
So this very own PR, even if done on master, should just be valid and fix #931
> fix(pr): Testing PR on master

- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/menu/menu.js
- src/widgets/numeric-refinement-list/__tests__/numeric-refinement-list-test.js
- src/widgets/numeric-refinement-list/numeric-refinement-list.js
- src/widgets/refinement-list/refinement-list.js
- src/widgets/star-rating/__tests__/star-rating-test.js
- src/widgets/star-rating/star-rating.js
- src/widgets/toggle/__tests__/toggle-test.js
- src/widgets/toggle/toggle.js
This actually fixes all my perf issues on the SteamDB demo.
> perf(refinementList): Stop creating URL for hidden refinements.

- docs/examples.haml
Unless you are familiar with the icons of each widget, the current images are hard to understand. I added the title so you at least get a tooltip - making it easier to find the widget in the doc afterwards.
> docs(examples): add titles on widget icons

- docs/documentation.md
- docs/js/doc.js
- Renamed "All Options" to "Usage"
- Renamed "Snippet" to "Example"
- Moved "Requirements" at the 2nd position
- do not use display:none in the raw HTML code
Fix #966
> docs(codebox): the options tab is now the default

- src/components/Pagination/Pagination.js
- src/components/Pagination/PaginationLink.js
- src/components/Pagination/__tests__/Pagination-test.js
Fixes #974.
`PaginationLinks` with the `isDisabled` props now render as `span` and
not as `a`. We also remove the now unwanted `href`, `aria-label` and
`onClick` props.
There were no tests files for PaginationLink, and I did not added one.
I'd like #948 to be merged before adding those kind of fine-grained
tests.
> fix(pagination): Disabled pagination link can no longer be clicked

- npm-shrinkwrap.json
- package.json
- scripts/karma.conf.babel.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/widgets/stats/stats.js
So what is this PR about?
In the process of fixing #934, I tried to add a test to assert that we did not generated more urls than needed in the RefinementList component. 
By doing so I discovered in the test file that we had no test to test the `showMore` feature (we had a comment saying basically "I don't know how to test that") and most of our tests where actually testing a whole bunch of fonctionnalities at once (using full JSX diff) instead of just tiny parts of it.
This resulted in a lot of boilerplate (we needed to copy the whole props in each tests), and made the tests very brittle because they needed both an internal knowledge of the components and were all very dependent. Adding a new prop would break all tests, even those that are not relevant.
I then looked for a more granular …
> refactor(enzyme): Moved tests of RefinementList component to enzyme

- src/components/RefinementList/RefinementList.js
If number of facet values is 5 and limit is 5 then we were still
displaying the showMore button.
Now fixed, no added tests, waiting for
#948
> fix(showMore): hide showMore when no more facet values to show

- CONTRIBUTING.md
- npm-shrinkwrap.json
- package.json
- scripts/karma.conf.babel.js
- scripts/serve.sh
- scripts/webpack.config.serve.babel.js
`npm run serve` will build the current instantsearch and expose the
file on http://127.0.0.1:8080/instantsearch.js. It will get
automatically updated in each change.
This is useful when you want to test your branch in a specific
project. Just run `npm run serve` in the instantsearch repo and link
to the file in your project.
I've regenerated the shrinkwrap but had to run a `npm prune` before
shrinkwrap allowed me to do it, so I updated the doc accordingly.
> feat(serve): Adding `npm run serve` command

- docs/examples/e-commerce/main.scss
- docs/examples/media/main.scss
- docs/examples/tourism/main.scss
Otherwise, the SCSS files are not considered by Jekyll's assets pipeline
> docs(examples): ensure the YAML header is first in the file

- README.md
- src/lib/url-sync.js
This PR aims to fix #985 and get Turbolinks compatibility by setting `pushStateObject: { turbolinks: true }`.
You may reproduce the problem described by @ThomasBush on http://www.welcometothejungle.co/companies : 
* Activate some filters/facets
* Click on whatever company
* Go back => NOK (it doesn't work until you reach back `/companies` in the history)
---
see:
* https://github.com/algolia/instantsearch.js/issues/985
* https://github.com/turbolinks/turbolinks-classic/issues/363#issuecomment-85626145
> Add `pushStateObject` to get Turbolinks compatibility

- dev/app.js
- dev/index.html
- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
Before this commit, every configuration done in widget.init would not
be remembered when going back in the browser history.
Scenario: You built a custom widget using helper.setQueryParameter in
widget.init. Then you load "/", widget.init() sets some helper params,
you go to page 2, you click on <= back. Before this commit we would
forget what was done in widget.init(). Now it works.
This was needed to fix the "rootPath" option of the hierarchicalMenu.
The rootPath option triggers a state change from inside the helper
(which may have been a bad idea after all) => it was not remembered
when going back to empty url.
Thanks to @maxiloc for the bug report and big help solving this!
> fix(lifecycle): save configuration done in widget.init

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/url-sync.js
- src/widgets/search-box/__tests__/search-box-test.js
- src/widgets/search-box/search-box.js
Before this commit, if one of the widget was making helper changes in
his init(), we would trigger a change event that would update the url.
What we want is that everything done before the first render should be
considered as start configuration and not synced into the url UNLESS
there are new differences (user changes the query).
It also fixed a nasty IE10/11 bug where the input event would be
triggered as soon as a placeholder is set into the DOM or
programmatically.
> fix(urlSync): only start watching for changes at first render

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/url-sync.js
Before this commit, when using the rootpath option and clicking on
backbutton after switching a page would result in the rootpath option
seeming "forgotten"
This was triggered because rootpath is a "magical" (BAD!!) option that
is triggering a refinement internally in the helper's SearchParameters
constructor.
Thus, in the urlSync widget, to determine the "original configuration"
(= all widgets getConfiguration before url sync) we need to go through
the SearchParameters constructor.
Also note that we originally wanted to understand the url sync
"original config" as being widget's getConfiguration + widget's init
but that's no doable because the way we implemented url sync. Indeed
there's no way to differentiate the state of the url from the state of
the widget's init action after all …
> fix(rootpath): remember rootpath option on 'back' button

- src/widgets/clear-all/clear-all.js
- src/widgets/current-refined-values/__tests__/current-refined-values-test.js
- src/widgets/current-refined-values/current-refined-values.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/hits/hits.js
- src/widgets/menu/menu.js
- src/widgets/numeric-refinement-list/numeric-refinement-list.js
- src/widgets/refinement-list/refinement-list.js
- src/widgets/star-rating/star-rating.js
- src/widgets/stats/stats.js
- src/widgets/toggle/toggle.js
We can currently pass for `transformData` either an object or
a function. If passed a function, it will be applied on every
template, while if passing an object, each key function will only be
applied to the template with a matching name.
We think the "top level" call to a function creates more issues than
an explicit definition. It usually creates weird effects when the
method is applied to a "no result" set, resulting in errors. To avoid
that, we will stop documenting the feature, and remove it completely
in a next major version.
I've updated the documentation to reflect this change, ie always
documenting `transformData.item` instead of just `transformData` as
the place to put the custom method. I've updated the `usage` errors
accordingly as well. It should still silently accept the top …
> docs(transformData): Only document explicit objects for `transformData`

- src/components/RefinementList/RefinementList.js
- src/widgets/numeric-refinement-list/__tests__/numeric-refinement-list-test.js
- src/widgets/numeric-refinement-list/numeric-refinement-list.js
Fixes #1010
The `shouldComponentUpdate` of `RefinementList` was checking if the
`facetValues` from the props where actually changed before issuing
a new rendering. It turns out that in `numericRefinementList`, the
new `facetValues` was always equal to the already set one. More
precisely, the filters seemed to already be set in the props before
reaching `shouldComponentUpdate`.
Turns out that we were editing a variable in place instead of working
on a copy so the internal props where changing without the component
really noticing.
I updated the `render` method of the `numericRefinementList` to pass
a new array instead of working on the same copy over and over again.
I refactored the `shouldComponentUpdate` and `_toggleRefinement`
methods by splitting in several variables in my quest to …
> fix(numericRefinementList): Correctly apply active class

- docs/documentation.md
Following #1026 I also added an entry on how to set default filters on
the first loading of instantsearch. This question often pop ups in
support and we were never really explaining how to do it.
I tried to keep it as simple as possible for most cases when you
already have a widget in place on that specific attribute, and only
need to set default values.
I also explained how to do it on attributes on which you do not have
a widget, with a bit more config.
Let me know what you think
> docs(faq): Add explanation on default filters

- docs/documentation.md
I suggest adding a FAQ section to the documentation where we could put
some of the most common use cases of instantsearch that are either not
yet into the core, or are not suitable to be put into the core.
I just had a user asking me how to make instantsearch not display the
first results, and only display them on the first keystroke.
I wrote a small explanation, with code example and added it to the
docs.
Let me know what you think
> docs(faq): Add "hide results on init"

- docs/_assets/stylesheets/_header.scss
- docs/_assets/stylesheets/_home.scss
- docs/_assets/stylesheets/_page.scss
I've had feedbacks that when discovering instantsearch.js for the
first time, people scroll down on the home page and once they are at
the bottom they don't know where to go because the menu disappeared.
They thought it was just a promo page, with no more content, so they
closed it.
I've set the header as `position: fixed` like on the documentation
page. Seems like a recent commit did remove the fixed header by
mistake.
| Before | After |
|---------- | --------- |
| ![2016-05-25_15h33m39](https://cloud.githubusercontent.com/assets/283419/15558342/2bdd7340-228e-11e6-972a-7ed52c0f3ba3.gif) | ![2016-05-25_15h36m18](https://cloud.githubusercontent.com/assets/283419/15558370/7a611c6a-228e-11e6-9869-63386795945e.gif) |
cc @Shipow
> docs(header): Fix the header when scrolling

- npm-shrinkwrap.json
- package.json
- src/lib/InstantSearch.js
fixes #1024 by forcing to load /lite and avoid bad resolve of the
browser field.
This could break if people were using search.client to do things like
indexing. But we do document this as an API entry. We only have an
infinite scroll tutorial using the client passed to the helper. Thus I
had to make browse and browseFrom part of the lite build.
> fix(lite): use lite algoliasearch build (js client)

- docs/_assets/javascripts/doc.js
- docs/_assets/stylesheets/_documentation.scss
- docs/_includes/widget-jsdoc/addWidget.md
- docs/_includes/widget-jsdoc/clearAll.md
- docs/_includes/widget-jsdoc/currentRefinedValues.md
- docs/_includes/widget-jsdoc/hierarchicalMenu.md
- docs/_includes/widget-jsdoc/hits.md
- docs/_includes/widget-jsdoc/hitsPerPageSelector.md
- docs/_includes/widget-jsdoc/instantsearch.md
- docs/_includes/widget-jsdoc/menu.md
- docs/_includes/widget-jsdoc/numericRefinementList.md
- docs/_includes/widget-jsdoc/numericSelector.md
- docs/_includes/widget-jsdoc/pagination.md
- docs/_includes/widget-jsdoc/priceRanges.md
- docs/_includes/widget-jsdoc/rangeSlider.md
- docs/_includes/widget-jsdoc/refinementList.md
- docs/_includes/widget-jsdoc/searchBox.md
- docs/_includes/widget-jsdoc/sortBySelector.md
- docs/_includes/widget-jsdoc/starRating.md
- docs/_includes/widget-jsdoc/stats.md
- docs/_includes/widget-jsdoc/toggle.md
- scripts/docs/widgetTemplate.hbs
Proposition to enhance the readability of the parameters in the documentation. All the descriptions are hidden by default, this let the user have a better overview of the parameters, makes the list of parameters less daunting.
Updated based on @Shipow feedback :) (thanks man :))
Demo:
> Docs: makes parameter descriptions collapsible

- src/decorators/__tests__/headerFooter-test.js
- src/decorators/headerFooter.js
- src/widgets/refinement-list/__tests__/refinement-list-test.js
- src/widgets/refinement-list/refinement-list.js
Partially fixes #1013
The goal of the PR was to make the `count` variable accessible to the
header template of the `refinementList` widget. This `count` is the
number of active filters applied to the facet.
_(I click on the header in this demo to show that it works with `collapsible` as well)_
```javascript
templates: {
header: (data) => {
if (data.count === 0) {
return `<h3 class="facet--title">Teams</h3>`;
}
return `<h3 class="facet--title">Teams (${data.count})</h3>`;
}
},
```
To do so the first step was to make the `header` template dynamic.
Before the PR, it was static, meaning that it was defined at the
widget init and never updated. I changed that part so the header
template is re-rendered on every render of its component.
It also meant that I had to remove the custom …
> feat(header): Pass count of current refined filters in header

- src/components/Hits.js
- src/components/__tests__/Hits-test.js
Fixes #903
The change itself was easy to do, but it broke all the tests because
we were testing a full JSX output and we now had one more key passed
to the `data`.
It took this as an opportunity to refactor the Hits tests uzing enzyme
to make them easier to read. It allow me to spot one or two
inconsistencies in the way the `root` class was added or not depending
on the kind of template used.
> feat(hits): Add a `__position` attribute to data passed to items

- docs/_includes/widget-jsdoc/instantsearch.md
- src/lib/InstantSearch.js
I had to stop `urlSync` tracking the index. I could a simple way to remove one element except redefining the whole list. I had to dig in the source code to find the default value, so I thought it would be easier to just put the default value in the documentation.
> docs(urlSync): Explicitly display the trackedParameters default value

- src/lib/url-sync.js
tl;dr; Urls stored in the browser bar were made to look not too bad by omitting to encode some characters. Turns out it was a bad idea, copy pasting the url from browser bar to slack or github failed.
Fixes #982 #848 by using the new safe: true option from the helper when asking for a state as a url (https://github.com/algolia/algoliasearch-helper-js/pull/317).
This seems to be backward compatible (instantsearch wise):
- for current implementations, urls in the browser bar will move from `&hRF[color]` to `&hRF%05Bcolor%05D`
- urls sent to the server (if it happen people were reading them) will move from `&hRF[color]` to `&hRF%05Bcolor%05D` but I believe most server side code is already using decodeURI
- no change to current urls, they will be properly decoded (no change was needed on the …
> fix(urlSync): urls should be safe by default

- src/widgets/search-box/__tests__/search-box-test.js
- src/widgets/search-box/search-box.js
The complexity of the searchBox starts to be crazy, mostly because we allowed too much different ways to instantiate it.
I will take that into account while doing V2 and React
> fix(searchBox): update helper query on every keystroke

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
Fixes #1130
Thanks a lot @morhaus for your help when debugging
> fix(searchParameters): avoid mutating provided objects

- scripts/jsdom.js
- scripts/mocha.opts
- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/url-sync.js
- src/widgets/toggle/__tests__/toggle-test.js
- src/widgets/toggle/implementations/__tests__/currentToggle-test.js
- src/widgets/toggle/implementations/currentToggle.js
- src/widgets/toggle/implementations/legacyToggle.js
- src/widgets/toggle/toggle.js
Context: I upgrade the default toggle behavior in #1146.
To do this, I switched from using a facet to a disjunctive facet. Which
led to inconsistencies with the already public instantsearch websites urls using
facetRefinements for toggle.
So now, if there's a matching facetRefinement for the attributeName used
in the toggle, I will switch to a legacy implementation.
Otherwise, I will switch to the current implementation.
I wrote some tests around this but this is very messy. Our whole test
stack has evolved in a monster, mostly because of the way we are writing
our own code.
This should get better with instantsearch-react and so I did not spend
my whole day on this. Tested this multiple times: it works.
> fix(toggle): add backward compatibility for previous toggle implem

- docs/documentation.md
Instant Search has typo on widget stats.
Reference :
https://community.algolia.com/instantsearch.js/documentation/#stats
`
// Function template example
search.addWidget(
instantsearch.widgets.stats({
container: '#stats',
templates: {
body: function(data) {
return '<div>You have ' + data.nbHits + ' results, fetched in ' +
data.processingTimMS +'ms.</div>'
}
}
})
);
`
While api data object contains these properties : 
`
hasManyResults: true, hasNoResults: false, hasOneResult: false, hitsPerPage: 10, nbHits: 2446, nbPages: 100, page: 0, processingTimeMS: 1,
`
TYPO is data.processingTimMS should be data.processingTimeMS
> fix(documentation): Change instantsearch.widgets.stats typo 

- package.json
- src/components/Slider/Slider.js
NoUiSlider added a `cssClasses` option in 8.5.0. Since we also have a `cssClasses` prop on our Slider component that is consumed by the higher order components (but still forwarded), we were passing an invalid option to the underlying NoUiSlider.
> fix(nouislider): fix the slider for nouislider 8.5.1

- src/widgets/search-box/search-box.js
When the page is coming from BFCache
(https://developer.mozilla.org/en-US/docs/Working_with_BFCache)
then we force the input value to be the current query.
Otherwise, this happens:
- `<input>` autocomplete = off (default)
- search $query
- navigate away
- use back button
- input query is empty (because `<input>` autocomplete = off)
Firefox and Safari are using BFCache for instant back button
> fix(searchBox): handle BFCache browsers

- docs/examples/tourism/search.js
- src/widgets/numeric-selector/__tests__/numeric-selector-test.js
- src/widgets/numeric-selector/numeric-selector.js
We were calling a helper method that was resetting the page to 0.
~~Tries to fix #1253~~
~~Basically the issue is that calling the helper.addNumericRefinement
upfront in init() will reset the page to 0 (linked issue)~~
~~@bobylito how could we solve that? Currently the fix will still fail,
because if I change the value of the tourism selector to 5 guest then
we will end up merging [1] with [5] in the IS init phase. This is not
what we want, The init() solution is the way to go but it has other
consequences.~~
UPDATE:
Done.
> fix(numericSelector): do not change state on init

- docgen/layouts/api.pug
- docgen/middlewares.js
- docgen/src/InstantSearch.md
- docgen/src/ecommerce.html
- docgen/src/materialui.html
- docgen/src/media.html
- docgen/src/tourism.html
added an examples section,
commented out the headers#, I feel like it's not useful for now and
hard to understand.
Preview:
> docs(nav): small reorg

- docgen/devServer.js
- package.json
Was failing since 6ee4d55e3e32718582612360bdd2e1269d38e956 because
browserSync would pick examples/.js files updates and reload the page
before react-hot-loader was able to hot reload it
> chore(docs): fix react hot loader

- docgen/plugins/inlineProps/extractMetadata.js
@mthuret lost some good time with that because there's no context on
which dev script generated this error. JS stack traces FTW
> chore(dev): better err message when extractprops fails

- .eslintrc.js
- packages/react-instantsearch/index.js
- packages/react-instantsearch/src/core/highlight.js
- packages/react-instantsearch/src/core/highlight.test.js
Usage in a custom hits widget:
```javascript
const ProductHits = Hits.connect(({hits}) => {
const hitComponents = hits.map( hit =>
<div key={hit.objectID}>
<span className="hit-name">{hightlight('name', hit)}</span>
</div>
);
return <div className="hits">{hitComponents}</div>;
});
```
> feat(highlight): provide a function to use highligth in react

- packages/react-instantsearch/src/components/LinkList.js
- packages/react-instantsearch/src/widgets/Pagination/Pagination.enzyme.test.js
- packages/react-instantsearch/src/widgets/Pagination/Pagination.js
- packages/react-instantsearch/src/widgets/Pagination/connect.js
- packages/react-instantsearch/src/widgets/Pagination/connect.test.js
The bug is caused by the use of two conflicting semantics
with the same set of changes. Previously we had "if the value for the
page, reset the page number", which led to reseting the pager to 0
if we were selecting the same page (the toggle effect). I previously
removed this behaviour, but it introduced the impossibility to reset
the pager to 0 when changing any other filter (setting the value was
the trigger).
In order to fix this issue I introduce a new type of value to
express the intent of using the same value without changing the page.
This way we have two distinctly defined intents and values:
- same value as numbers -> reset to 0
- value with isSamePage flag -> change to page value
It relies on `valuesOf`, which is not that nice and introduces the use
of the dreaded `==`. At …
> fix(pagination): reset on other filter + no toggle

- package.json
- src/lib/InstantSearch.js
We got an infinite loop on objects created by Ember which had weird
functions attached to it.
Not even able to completely udnerstand it, I would have to dig a lot
more. This is just plain easy solving.
cc @rayrutjes
> fix(merge): merge only plain object from searchParameters

- packages/react-instantsearch/src/widgets/CurrentFilters/CurrentFilters.css
- packages/react-instantsearch/src/widgets/CurrentFilters/CurrentFilters.js
- packages/react-instantsearch/src/widgets/CurrentFilters/connect.js
- packages/react-instantsearch/src/widgets/CurrentFilters/connect.test.js
- packages/react-instantsearch/src/widgets/HierarchicalMenu/connect.js
- packages/react-instantsearch/src/widgets/HierarchicalMenu/connect.test.js
- packages/react-instantsearch/src/widgets/Menu/connect.js
- packages/react-instantsearch/src/widgets/Menu/connect.test.js
- packages/react-instantsearch/src/widgets/MultiRange/connect.js
- packages/react-instantsearch/src/widgets/MultiRange/connect.test.js
- packages/react-instantsearch/src/widgets/Range/connect.js
- packages/react-instantsearch/src/widgets/Range/connect.test.js
- packages/react-instantsearch/src/widgets/RefinementList/connect.js
- packages/react-instantsearch/src/widgets/RefinementList/connect.test.js
- packages/react-instantsearch/src/widgets/SearchBox/connect.js
- packages/react-instantsearch/src/widgets/SearchBox/connect.test.js
- packages/react-instantsearch/src/widgets/Toggle/connect.js
- packages/react-instantsearch/src/widgets/Toggle/connect.test.js
Before:
1. we computed a `key` property that was pretty similar to the `label`
one but different.
2. we injected a `filters: [{label, key}]` with the connector
3. we used hide: true in the searchBox metadata to not display it in
our default component
After:
1. Cannot see the reasoning for this, it works well without it, maybe
in edge cases where different ids are manipulating the same
attributeName. But then, I can't imagine any situation where it would
make sense to display: Category: Movies, Type: Movies since it's the
same attributeName
2. Now injecting `items: [{label}]`, on my way to provide a consistent
connector API (#1423, #1405)
3. hide: true was only used to hide and avoid refining the query but
still give the possibility to users to display and clear the query in
their …
> feat(CurrentFilters): remove `key`, remove `hide`, rename filters to `items`

- docgen/layouts/HOC/connector.pug
- docgen/layouts/component/widget.pug
- docgen/plugins/navigation.js
- docgen/src/component.md
- docgen/src/connector.md
- docgen/src/examples.md
- docgen/src/examples/e-commerce/index.html
- docgen/src/examples/material-ui/index.html
- docgen/src/examples/media/index.html
- docgen/src/examples/tourism/index.html
- docgen/src/gettingstarted.md
- docgen/src/guides.md
- docgen/src/guides/3rd-party-librairies.md
- docgen/src/guides/advanced-topics.md
- docgen/src/guides/conditional-display.md
- docgen/src/guides/connectors.md
- docgen/src/guides/create-own-widget.md
- docgen/src/guides/internationalization.md
- docgen/src/guides/styling.md
- docgen/src/stylesheets/components/_documentation.scss
Contains the reorganization of our guide section following #1315 proposition.
Also includes:
1. Usage of navWeight to make intro page first in their TOC
2. Remove Examples section from connectors API
3. Resizing of the storybook iframe
4. Correcting dead links
I'll let you watch the doc but they are currently some duplications between the Guides Intro Page and the API Intro Page, as well as the intro for the Using Connectors guide. Your feedback on that is more than welcome :)
> docs(guide): reorganising the guide section

- docgen/layouts/HOC/connector.pug
- docgen/layouts/component/core.pug
- docgen/layouts/component/widget.pug
- docgen/src/guides/3rd-party-librairies.md
- docgen/src/guides/advanced-topics.md
- docgen/src/guides/conditional-display.md
- docgen/src/guides/connectors.md
- docgen/src/guides/create-own-widget.md
- docgen/src/guides/internationalization.md
- docgen/src/guides/styling.md
- packages/react-instantsearch/src/core/InstantSearch.js
* markdown is taken into account inside props #1517
* highlighting added for guide section
also, removed some documented properties for InstantSearch: History and those about Controlled State.
> docs: fix some typos and bugs

- docs/_includes/widget-jsdoc/hierarchicalMenu.md
- docs/_includes/widget-jsdoc/menu.md
- docs/_includes/widget-jsdoc/refinementList.md
- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/menu/menu.js
- src/widgets/refinement-list/refinement-list.js
This is a small update of our docs to indicate that the function option for `sortBy` in the menu, hierarchicalMenu and refinementList widgets is the same as the `compareFunction` param for the standard Javascript `Array.prototype.sort`.
> docs(sort function): more info on expected function param

- README.md
- docgen/src/gettingstarted.md
- package.json
- scripts/docs:update.sh
- scripts/release.sh
- yarn.lock
There's now two separate commands:
- npm run release
- npm run docs:update
So that we can update the website without having to do a new release
of the libraries.
> chore(release): separate release from docs update

- docgen/src/examples/media/App.js
- docgen/src/guides/advanced-topics.md
- packages/react-instantsearch/src/core/InstantSearch.js
- stories/util.js
Contains the react-router example within a guide and re-document props on InstantSearch.
history stays undocumented, and the idea is to never expose it (and remove it from the props in the end)
> docs(guides): add a guide explaining how to use react-router with ris

- docgen/src/examples/e-commerce/App.js
- docgen/src/examples/e-commerce/style.css
- docgen/src/examples/material-ui/App.js
- docgen/src/examples/media/App.js
- docgen/src/examples/tourism/App.js
- docgen/src/examples/urlSync.js
- package.json
- yarn.lock
uses browser history and a 700 ms threshold. 
the url sync on our examples does not cover:
* removing empty refinements
* ordering query params by alphabetical order
I can add them if you think it worth it.
> docs(examples): add url sync

- src/widgets/price-ranges/__tests__/generate-ranges-test.js
- src/widgets/price-ranges/generate-ranges.js
> fix(priceRanges): avoid displaying solo ranges

- docgen/src/examples/media/App.js
- docgen/src/examples/tourism/App.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/widgets/HierarchicalMenu.js
- packages/react-instantsearch/src/widgets/Menu.js
- packages/react-instantsearch/src/widgets/RefinementList.js
**Summary**
We have chosen to make the widget API simple and let the customisation of behavior for components that will be wrapped in connectors. This sortBy option is now removed.
> feat(sortBy): implement default sortBy, remove option

- src/widgets/toggle/implementations/__tests__/currentToggle-test.js
- src/widgets/toggle/implementations/currentToggle.js
fixes #1537
Summary:
When the user passed values={on: -2, off: 5}, we would send to Algolia as for facet refinements: stock:-2 which would not be what we wanted to express.
Using stock:-2 as a facetRefinement is supported only if you escape
the minus sign, otherwise it's considered as negative facet refinement
(remove "-2" from facets).
Now we escape this sign when it makes sense.
> fix(toggle): support negative numeric values for on/off

- docgen/src/guides/styling.md
- docgen/syntaxHighlighting.js
Fix the syntax highlighting on the styling page:
> doc(highlight): fix hl for html and css

- packages/react-instantsearch/src/connectors/connectHits.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.js
**Summary**
Removes the itemComponent that doesn't make sense on the connector (only on the widget).
fix #1554
> fix(connectors): remove itemComponent from hits connectors

- src/components/RefinementList/__tests__/RefinementList-test.js
- src/components/Template.js
- src/components/__tests__/Template-test.js
- src/decorators/__tests__/headerFooter-test.js
- src/widgets/refinement-list/__tests__/refinement-list-test.js
- src/widgets/toggle/implementations/__tests__/currentToggle-test.js
Summary:
Even when data does not changes, we now call transformData. So that
if the transformed data changes, there will be a new render call.
fixes #1538
linked to #1100
> fix(transformData): always call transformData

- packages/react-instantsearch/src/components/CurrentRefinements.css
- packages/react-instantsearch/src/components/CurrentRefinements.js
- packages/react-instantsearch/src/connectors/connectCurrentRefinements.js
- packages/react-instantsearch/src/connectors/connectCurrentRefinements.test.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectMultiRange.js
- packages/react-instantsearch/src/connectors/connectMultiRange.test.js
- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/connectors/connectToggle.js
- packages/react-instantsearch/src/connectors/connectToggle.test.js
final items structure: 
```js
items: [
{
label: string (for display),
attributeName: string, 
currentRefinement: string, {min/max}, or array
value: to pass to refine
items: array optional [{label, value}]
}
]
```
> feat(api): add data to CurrentRefinements connector

- src/widgets/price-ranges/defaultTemplates.js
> fix(priceRanges): use formatNumber in defaultTemplate

- docgen/src/guides/advanced-topics.md
- packages/react-instantsearch/dom.js
- packages/react-instantsearch/index.js
- packages/react-instantsearch/native.js
- packages/react-instantsearch/scripts/build.sh
- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/InstantSearch.test.js
- packages/react-instantsearch/src/core/createInstantSearch.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.test.js
- packages/react-instantsearch/src/core/createWidgetsManager.js
- packages/react-instantsearch/src/core/createWidgetsManager.test.js
Contains:
- new native namespace
- guide for react-native with the source code of an example showing searchbox+infinitHits (the api of the connector is really simple to use, thanks @bobylito !)
> feat(react-native): make react-instantsearch compatible for native dev

- src/lib/utils.js
- src/widgets/toggle/implementations/currentToggle.js
following #1551, we also now need to unescape in currentRefinedValues
widget because the refinement name is public API.
fixes #1569
> fix(currentRefinedValues): unescape disjunctive facet refinement names

- docgen/src/examples/urlSync.js
- docgen/src/guides/create-own-widget.md
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectHitsPerPage.js
- packages/react-instantsearch/src/connectors/connectHitsPerPage.test.js
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectMultiRange.js
- packages/react-instantsearch/src/connectors/connectMultiRange.test.js
- packages/react-instantsearch/src/connectors/connectPagination.js
- packages/react-instantsearch/src/connectors/connectPagination.test.js
- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/connectors/connectSearchBox.js
- packages/react-instantsearch/src/connectors/connectSearchBox.test.js
- packages/react-instantsearch/src/connectors/connectSortBy.js
- packages/react-instantsearch/src/connectors/connectSortBy.test.js
- packages/react-instantsearch/src/connectors/connectToggle.js
- packages/react-instantsearch/src/connectors/connectToggle.test.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
Clean the state when a widget is unmounted except if the widget is marked has persistent (via a props). 
Needs review about the way to achieve the clean:
-> I did it forcing the user to define an id inside the connector (instead of having it outside). 
It avoids the repetition of the clean up code and in a way clarify the need of an id (when there's a refinement). But it also complexify the user api and some widgets code (you need to pass the id a lot of time). Also it hides from the user how the widget cleanup is done. 
An alternative from Vincent would be to let the user do the cleanup using the same interface as the refine method (you got the whole state, and return the whole state). The cleanup function would be called when the widget unmount. 
What do you think?
> feat(unmount): clean state if a widget is unmounted except if it is persistent

- .eslintignore
- docgen/src/guides/advanced-topics.md
- packages/react-instantsearch/examples/react-router/README.md
- packages/react-instantsearch/examples/react-router/package.json
- packages/react-instantsearch/examples/react-router/public/index.html
- packages/react-instantsearch/examples/react-router/src/App.js
- packages/react-instantsearch/examples/react-router/src/index.js
I decided to remove the code sample from the guide and just add the link pointing to the demo app. 
Let me know if you think we need both.
Also, can someone just perform a yarn install in the demo directory and tell me if the react-instantsearch directory under node_modules is correct? (without any /dist, /.storybook...etc)?
> docs: add react-router small demo app

- packages/react-instantsearch/src/components/LinkList.js
- packages/react-instantsearch/src/components/Pagination.test.js
- packages/react-instantsearch/src/components/__snapshots__/Pagination.test.js.snap
Before this commit, when on first page, the "First" link was selected
AND disabled.
Ultimately it's overkill to have LinkList.js since Pagination is the
only one using it, should we remove this layer of abstraction?
> fix(Pagination): when page === 1, first should not be selected

- packages/react-instantsearch/src/widgets/RangeSlider.js
- stories/3rdPartiesIntegration.stories.js
Our jsdoc example (copy and paste from the story range slider source code) was oudated. 
Also I improved it by displaying labels showing in real time the selected values in order to avoid confusion between the slider instantsearch state and the one only used for those label values. 
see #1617
> docs(slider): update out-of-date example and improve it

- docgen/src/examples/e-commerce-infinite/style.css
- docgen/src/examples/e-commerce/style.css
- docgen/src/examples/material-ui/App.js
- packages/react-instantsearch-theme-algolia/styles/_HierarchicalMenu.scss
- packages/react-instantsearch/src/components/HierarchicalMenu.enzyme.test.js
- packages/react-instantsearch/src/components/HierarchicalMenu.js
- packages/react-instantsearch/src/components/HierarchicalMenu.test.js
- packages/react-instantsearch/src/components/List.js
- packages/react-instantsearch/src/components/__snapshots__/HierarchicalMenu.test.js.snap
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/widgets/HierarchicalMenu.js
For consistency with other nested data connectors like
connectCurrentRefinements
BREAKING CHANGE:
- HierarchicalMenu ais-HierarchicalMenu__itemChildren css class name
is now ais-HierarchicalMenu__itemItems
- connectHierarchicalMenu item.children forwarded prop is now
item.items
fixes #1605
> fix(connectHierarchicalMenu): use item.items instead of item.children

- packages/react-instantsearch-theme-algolia/style.scss
- packages/react-instantsearch-theme-algolia/styles/_HierarchicalMenu.scss
- packages/react-instantsearch-theme-algolia/styles/_Menu.scss
> style(widget): add badge style to Menu + open caret on HierarchicalMenu

- docgen/src/examples/e-commerce-infinite/App.js
- docgen/src/examples/e-commerce/App.js
- docgen/src/examples/material-ui/App.js
- docgen/src/examples/media/App.js
- docgen/src/guide/Routing.md
- docgen/src/guide/Search parameters.md
- packages/react-instantsearch/src/connectors/connectHits.js
- packages/react-instantsearch/src/connectors/connectHits.test.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.test.js
- packages/react-instantsearch/src/widgets/Hits.js
- packages/react-instantsearch/src/widgets/InfiniteHits.js
- packages/react-instantsearch/src/widgets/ScrollTo.js
- stories/Hits.stories.js
- stories/ScrollTo.stories.js
- stories/util.js
Before this commit, Hits, connectHits, InfinitHits,
connectInfiniteHits, HitsPerPage, connectHitsPerPage were responsible
for dealing with the hitsPerPage parameter.
This encouraged usages like:
```jsx
Hits hitsPerPage=20
HitsPerPage items={[{value: 20, value:30}]}
```
Leading to confusions and conflict handling if both Hits's hitsPerPage
and items of HitsPerPage are different.
Now only HitsPerPage or the searchParameters prop (InstantSearch prop)
are able to control it.
Our goal being to always emphasis on the best UX, providing a way to
choose the number of hits to be shown by the user should be something
we push for. Therefore this PR removing hitsPerPage parameter on Hits
(and InfiniteHits).
This also removes inconsistency because utlimately <Hits
hitsPerPage={20}> should have been …
> feat(hitsPerPage): hitsPerPage is now only configured by HitsPerPage

- packages/react-instantsearch/src/components/HitsPerPage.enzyme.test.js
- packages/react-instantsearch/src/components/HitsPerPage.js
- packages/react-instantsearch/src/components/SortBy.enzyme.test.js
- packages/react-instantsearch/src/components/SortBy.js
- packages/react-instantsearch/src/connectors/connectHitsPerPage.js
- packages/react-instantsearch/src/connectors/connectHitsPerPage.test.js
- packages/react-instantsearch/src/connectors/connectSortBy.js
- packages/react-instantsearch/src/connectors/connectSortBy.test.js
- stories/HitsPerPage.stories.js
- stories/SortBy.stories.js
* connectHitsPerPage must provide isRefined in items data
* connectHitsPerPage must disallow configuring with only numbers (HitsPerPage items=[10,20,30]). We should always force using the object form. For consistency and single way to do one thing.
> feat(api): make hitsPerPage/SortBy connector consistent

- docgen/src/examples/e-commerce-infinite/App.js
- docgen/src/examples/e-commerce/App.js
- docgen/src/examples/material-ui/App.js
- docgen/src/examples/media/App.js
- docgen/src/guide/Connectors.md
- docgen/src/guide/React native.md
- packages/react-instantsearch/src/components/SearchBox.enzyme.test.js
- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/SearchBox.test.js
- packages/react-instantsearch/src/connectors/connectSearchBox.js
- packages/react-instantsearch/src/connectors/connectSearchBox.test.js
Connectors are following the currentRefinement, refine pattern.
Somehow connectSearchBox was missed.
BREAKING CHANGE:
- connectSearchBox now forward the query as props.currentRefinement
like any other connector
> fix(connectSearchBox): provide currentRefinement instead of query

- packages/react-instantsearch/src/components/StarRating.js
- packages/react-instantsearch/src/components/__snapshots__/StarRating.test.js.snap
- packages/react-instantsearch/src/connectors/connectHighlight.js
**Summary**
Fixes the ability to click even though there is no behavior triggered, when clicking on the default value and it is already selected. #1650 For reference:
**Result**
Now the default value is not clickable if it is selected:
And it also fixes a bug introduced by the highlighting PR :(
> fix(StarRating): Fix UX bug #1650

- packages/react-instantsearch/src/connectors/connectHighlight.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/highlightTags.js
Before this commit, when using `<Highlight>` inside `<Hit>` or any
`connectHits` we ended up in an infinite loop.
This loop was hard to notice because it was doing some network at each
iteration.
We will open new issues related to this bug because it's not just the
`Highlight` widget fault, it's the current design of computing
searchParameters and dynamic mounting that is failing.
This needs a deeper investigation and is actually why server side
today is not really supported.
> fix(Highlight): remove infinite loop

- packages/react-instantsearch/src/components/Highlight.test.js
- packages/react-instantsearch/src/connectors/connectHighlight.js
- packages/react-instantsearch/src/core/highlight.js
- packages/react-instantsearch/src/core/highlight.test.js
pathToAttribute was a legacy implementation of attributeName on
Highlight
Took the opportunity to only use attributeName in Highlight. Let's
agree that attributeName everywhere in the API right now is a path to
any attribute in your object. Like Algolia API does
> fix(Highlight): error message now says "attributeName" as it's the public prop

- docgen/assets/js/sidebar.js
- docgen/src/stylesheets/components/_documentation.scss
- docgen/src/stylesheets/components/_sidebar.scss
- docgen/webpack.config.start.babel.js
This PR is for react-instantsearch documentation.
**Summary**
When scrolling the sidebar was jumping when it was starting to follow the content.
**Result**
No jump at the start
No jump at the end
Scroll below the title of the page (not scrolling the title)
> doc(sidebar): fix jumping menu #1671

- .eslintignore
- .gitignore
- docgen/config.js
- scripts/gh-pages.js
So that if an npm start script is running, we do not use its output as
a documentation website.
> chore(docs): isolate production publishing from dev mode

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/widgets/RangeSlider.js
- stories/3rdPartiesIntegration.stories.js
Behavior: when using NaN as min/max current values of a range, an infinite loop is triggered. 
This fix check inside the connector if the values are finite, if not, we are defaulting to the one provided to the widget (either by hand ou by using the search results). 
=> We discovered this behavior when using the rheostat slider widget. For an unknown reason when you have the same value for Min/Max, the slider gaves you NaN/NaN instead of the real value. 
The consequence for react-instantsearch is that when the 'shouldComponentUpdate' hook of the range connector is triggered, equality will never be reached as the currentRefinement contains 'null' value.
> fix(range): when unfinite numbers are passed, use search results instead.

- packages/react-instantsearch/src/components/StarRating.js
- packages/react-instantsearch/src/components/StarRating.test.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
By adding a check to non finite values in the `connectRange` connector, a bug was highlighted inside the starRating widget. createURL function was called with the following format {lowerbound, max}, instead of {min, max}.
> fix(starRating): call createURL with the right interface (min/max)

- package.json
Updating to node-sass 4 makes the documentation crash at least with macos x.
> chore: rollback to previous version of node-sass (3 instead of 4)

- docgen/src/guide/Autocomplete_menu.md
- docgen/src/guide/Server-side_rendering.md
- package.json
- packages/react-instantsearch/examples/autocomplete/README.md
- packages/react-instantsearch/examples/autocomplete/package.json
- packages/react-instantsearch/examples/autocomplete/public/index.html
- packages/react-instantsearch/examples/autocomplete/public/style.css
- packages/react-instantsearch/examples/autocomplete/src/App-Hits-And-Facets.js
- packages/react-instantsearch/examples/autocomplete/src/App-Multi-Index.js
- packages/react-instantsearch/examples/autocomplete/src/index.js
Those examples shows how to use an external react autocomplete component with react-instantsearch with two use cases: 
* targetting multiple indices 
* displaying both hits and facet values. 
Those examples are boilerplate but will serve to derive the right API to perform the same thing.
> docs(examples): add autocomplete recipe

- packages/react-instantsearch/src/core/createInstantSearchManager.error.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.test.js
This PR is for **React-InstantSearch**
The event model for the helper is implemented in a way that it will drop outdated requests.
This change makes react-instantsearch use the event model. This mechanism ensures reliability in the algolia answers.
It also results in some fewer instanciations of objects for callbacks and the base search parameters.
The previous implementation was based on `searchOnce`. This method does not protect you from responses that come back unordered because it is based on the cb / promise from the algolia client which will always call the callback even if they are unordered.
Use the helper properly with events and its protection against this kind of behaviour.
**The tests are now up to date 🍾 **
The tests were based on mocks that were making a lot of assumptions …
> fix(createInstantSearchManager): drop outdated response

- docs/_config.yml
Current generated link is `https://community.algolia.com/instantsearch.jshttps://community.algolia.com/instantsearch.js/react/`
> chore(website): fixed URL to react-instantsearch

- packages/react-instantsearch/src/components/InfiniteHits.js
- packages/react-instantsearch/src/components/InfiniteHits.test.js
- packages/react-instantsearch/src/components/__snapshots__/InfiniteHits.test.js.snap
**Summary**
When styling load more button from InfiniteHits I want to have a specific class to it so I can specifically target it
**Result**
Tests are passing and are updated and wrapper now get the new classname instead of a generic button
> feat(InfiniteHits): Add class to load more button

- packages/react-instantsearch/src/components/InfiniteHits.js
- packages/react-instantsearch/src/components/InfiniteHits.test.js
- packages/react-instantsearch/src/components/__snapshots__/InfiniteHits.test.js.snap
**Summary**
Used wrongly `reset` instead of `loadMore` 
@bobylito Sorry about the typo, just fixed it as the previous PR was merged
> fix(InfiniteHits): better classname to loadmore btn

- packages/react-instantsearch/src/core/highlight.js
- packages/react-instantsearch/src/core/highlight.test.js
**Summary**
Since algolia does not enforce a schema on the records, it is possible
that an highlighted value is only available on some of them. This means
that react-instantsearch should not throw when highlighting an attribute
that is missing from the hit.
fix #1790
> fix(highlight): highlight should work even if the attribute is missing

- docgen/layouts/widget.pug
- docgen/src/examples/e-commerce-infinite/App.js
- docgen/src/examples/e-commerce/App.js
- docgen/src/guide/Custom_connectors.md
- docgen/src/guide/Default_refinements.md
- docgen/src/guide/Search_for_facet_values.md
- docgen/src/guide/Virtual_widgets.md
- packages/react-instantsearch-theme-algolia/styles/_RefinementList.scss
- packages/react-instantsearch-theme-algolia/styles/_SearchBox.scss
- packages/react-instantsearch/src/components/RefinementList.js
- packages/react-instantsearch/src/components/RefinementList.test.js
- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/SearchBox.test.js
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/InstantSearch.test.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.error.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
- packages/react-instantsearch/src/widgets/RefinementList.js
- stories/RefinementList.stories.js
You can run the storybook, to see the widget live. 
**New API entry:** 
- make the <RefinementList/> widget have the search for facet values: 
```
<RefinementList attributeName="category" searchForFacetValues/>
```
- use search for facet values inside a custom RefinementList
* a new exposed prop **searchForFacetValues**: a boolean that if set to true will add the `searchForFacetValues` to the provided props. 
* a new provided prop **isFromSearch**: a boolean that says if the `items` props contains facets values from the global search, or searchForFacetValues results. 
* a new provided prop **searchForFacetValues**: a function that take a query as a parameter. To call for searching facet values. 
- create a connector that will propose search for facet values:
* a new …
> feat(SearchForFacetValues): connector functions + refinementList implementation

- packages/react-instantsearch-theme-algolia/mixins/_searchbox.shipow.scss
- packages/react-instantsearch-theme-algolia/style.scss
- packages/react-instantsearch-theme-algolia/styles/_RefinementList.scss
- packages/react-instantsearch-theme-algolia/styles/_SearchBox.scss
- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
Instead of using the generated css. This makes some customization
easier, for example in the search for facet value input in the
refinement list. Also we reuse the knowledge that is already in there
and make us able to provide feedback to shipow's work.
**Result**
It's almost the same, I will see with @LukyVj for the small changes (mainly the icons). I also fixed the animation of the reset button, which was too much.
Old:
New:
> chore(searchbox): Make the theme use @shipow's mixin [react-instantsearch]

- docgen/src/guide/Highlighting_results.md
- packages/react-instantsearch/dom.js
- packages/react-instantsearch/src/components/Highlighter.js
- packages/react-instantsearch/src/components/Highlighter.test.js
- packages/react-instantsearch/src/components/Snippet.js
- packages/react-instantsearch/src/components/Snippet.test.js
- packages/react-instantsearch/src/connectors/connectHighlight.js
- packages/react-instantsearch/src/core/highlight.js
- packages/react-instantsearch/src/core/highlight.test.js
- packages/react-instantsearch/src/widgets/Snippet.js
- stories/Hits.stories.js
You can now write this: `<Snippet attributeName="description" hit={hit}/>` and have highlighting for snippet attributes.
#1776
> feat(snippet): add a snippet widget to be able to highlight snippet results

- packages/react-instantsearch/src/core/createInstantSearchManager.test.js
- packages/react-instantsearch/src/core/createWidgetsManager.js
- packages/react-instantsearch/src/core/createWidgetsManager.test.js
- packages/react-instantsearch/src/core/utils.js
- packages/react-instantsearch/src/core/utils.test.js
See https://github.com/algolia/instantsearch.js/issues/1807 => usage of react-instantsearch is not possible with Meteor without the use of a `setImmediate` polyfill.
Previously we already add a problem using `process.nextTicks` with react-native.
I tested this version with our react-native example and also a Meteor small app.
> fix(widgets): replace setImmediate use with Promise use when update is needed

- docgen/src/guide/Connectors.md
- docgen/src/guide/Sorting_and_filtering.md
- docgen/src/guide/i18n.md
- packages/react-instantsearch/src/components/CurrentRefinements.js
- packages/react-instantsearch/src/components/HierarchicalMenu.js
- packages/react-instantsearch/src/components/HitsPerPage.js
- packages/react-instantsearch/src/components/Menu.js
- packages/react-instantsearch/src/components/Menu.test.js
- packages/react-instantsearch/src/components/MultiRange.js
- packages/react-instantsearch/src/components/RefinementList.js
- packages/react-instantsearch/src/components/SortBy.js
- packages/react-instantsearch/src/connectors/connectCurrentRefinements.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHitsPerPage.js
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMultiRange.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectSortBy.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
- packages/react-instantsearch/src/widgets/CurrentRefinements.js
- packages/react-instantsearch/src/widgets/HierarchicalMenu.js
- packages/react-instantsearch/src/widgets/HitsPerPage.js
- packages/react-instantsearch/src/widgets/Menu.js
- packages/react-instantsearch/src/widgets/MultiRange.js
- packages/react-instantsearch/src/widgets/RefinementList.js
- packages/react-instantsearch/src/widgets/SortBy.js
- stories/Menu.stories.js
- stories/RefinementList.stories.js
Usage:
```js
<RefinementList attributeName="category"
transformItems={items => orderBy(items, ['label', 'count'], ['asc', 'desc'])}/>
```
Results:
> feat(widgets): add transformItems to be able to sort and filter

- docgen/src/guide/Default_refinements.md
- docgen/src/guide/Sorting_and_filtering.md
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectMultiRange.js
- packages/react-instantsearch/src/connectors/connectMultiRange.test.js
- packages/react-instantsearch/src/connectors/connectPagination.js
- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/connectors/connectToggle.js
- packages/react-instantsearch/src/connectors/connectToggle.test.js
- packages/react-instantsearch/src/widgets/ClearAll.js
Also add a guide to explain how you can hide a default refinement. Then it will not be possible to remove it.
> fix(clear): clearing wasn't working with too+ same type facets selected

- docgen/assets/js/dropdowns.js
Before this commit you could not click on the ꜜ next to API.
> docs(website): fix dropdowns to allow clicking on ꜜ

- packages/react-instantsearch/.babelrc
- packages/react-instantsearch/package.json
- packages/react-instantsearch/src/core/__snapshots__/createInstantSearch.test.js.snap
- packages/react-instantsearch/src/core/createInstantSearch.js
- packages/react-instantsearch/src/core/createInstantSearch.test.js
- packages/react-instantsearch/yarn.lock
Before this commit we were not identifying react-instantsearch
in Algolia analytics, now we are.
> fix(InstantSearch): add specific `react-instantsearch ${version}` agent

- packages/react-instantsearch/src/components/List.js
A warning was thrown for `<HierarchicalMenu/>` and `<MultiRange/>` because the `isFromSearch` prop was marked as required.
> fix(SFFV): correct propTypes and add missing default values

- packages/react-instantsearch/src/core/__snapshots__/createInstantSearch.test.js.snap
- packages/react-instantsearch/src/core/createInstantSearch.js
Based on @zackify findings: add back the missing props types and forward
them to InstantSearch. This commit adds them explicitly.
Fixes #1849
> fix(createInstantsearch): fix missing props

- packages/react-instantsearch/examples/react-router/src/App.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
- add deepEqual instead of shallowEqual comparaison when dealing with new widgets props. 
- also compare at react-router example level if the App should update because of a `render` that is triggered even if the `onSearchStateChange`. 
Also I'm not sure if we need yet the check for equality when passing new props to `<InstantSearch/>` so I didn't included it in this PR.
> fix(react-router): search was triggered too many times

- docgen/src/stylesheets/components/_documentation.scss
- react-instantsearch docs
**Summary**
In the docs, [links that are followed by an `h2`](https://community.algolia.com/instantsearch.js/react/Getting_started.html#load-the-theme) are not clickable:
This prevents the user from accessing them.
This is due to the `h2:before` overflowing the underlying text.
**Result**
After removing `h2:before`, the block doesn't overflow the text anymore:
> doc(getting-started): Some links are unclickable

- docgen/src/stylesheets/components/_documentation.scss
**Summary**
This continues #1848. It let anchors link be clickable.
It turned out to be a little trickier than expected, but  the idea was to use `point-events: all` to allow mouse events on some parts:
- The title needs to be hoverable (see the added `::after`)
- The anchor link needs to be clickable (it's now absolutely positionned on top of the `::after`)
> doc(getting-started): Fix anchor links 

- packages/react-instantsearch-theme-algolia/package.json
- packages/react-instantsearch-theme-algolia/scripts/build-and-publish.sh
- packages/react-instantsearch/package.json
- packages/react-instantsearch/scripts/build-and-publish.sh
- packages/react-instantsearch/scripts/build.sh
- scripts/release.sh
Before this commit, we broke the publishing process
> fix(publish): publish react-instantsearch/dist instead of root

- packages/react-instantsearch/src/connectors/connectToggle.js
- packages/react-instantsearch/src/connectors/connectToggle.test.js
- stories/CurrentRefinements.stories.js
Steps to reproduce:
1.  Use Toggle with CurrentRefinements
2.  Click on Toggle component
3.  Refinement is shown in CurrentRefinements
4.  Remove Refinement from CurrentRefinements
5.  BUG: Toggle was not unchecked.
> Fix Toggle component used with CurrentRefinements

- docgen/config.js
- docgen/rootFiles/_redirects
- scripts/docs:build-preview.sh
- scripts/release.sh
Before this commit I messed up with the production website and made
the base href path /react/ instead of /instantsearch.js/react/
Now both the preview and production website will reside at
/instantsearch.js/react/.
> chore(website): fix production website paths

- docgen/src/stylesheets/components/_documentation.scss
- docgen/src/stylesheets/components/_fonts.scss
To fix the issue I had to play a lot with margin values, and to increase a bit the distance between titles and paragraphs. 
| Before  | After |
| ------------- | ------------- |
| ![](https://puu.sh/txMjO/dd84b2ce6b.png)  | ![](https://puu.sh/txMlf/c1b739334b.png) |
But I don't think it looks that bad after all. 
So now, all the "anchors / links" issues should be fixed :) 
Next time we should consider using Javascript to make anchors, to get rid of this issue.
> Fix header links, again

- packages/react-instantsearch/src/components/Hits.js
- packages/react-instantsearch/src/components/Hits.test.js
- packages/react-instantsearch/src/components/__snapshots__/Hits.test.js.snap
**Summary**
This merge request limits the `hitComponent` prop of `<Hits>` to be only a function. It keeps the API simple, and will now print a warning if the user pass a string.
**Result**
Passing a string to `hitComponent` now makes React complain about it.
> fix(Hits): limit the hitComponent to be only a function

- docgen/assets/js/sidebar.js
- docgen/layouts/widget.pug
- docgen/src/stylesheets/components/_documentation.scss
This commit fixes many issues around anchors:
- widget pages were not referencing right anchor for classnames
- anchors inside tables were displaying in a bad way
- anchors were adding too much top margin to most titles
- sidebar higlighting was broken
> docs(anchors): fix anchors situation

- docgen/src/examples/urlSync.js
Before this commit, we were advocating for updating the url at every keystrokes.
We had multiple reports since releases of instansearch.js that this led to slowdowns
of the browser UI.
fixes #1856
> docs(examples): urlSync example implem now update URL every 700ms

- src/lib/url-sync.js
Before this commit, our default implementation tried to update
the url at every character. This led to many slowdown reports from users
of the library.
Now we only update the url after the threshold
> fix(urlSync): update url only after threshold

- package.json
- packages/react-instantsearch/src/components/List.js
Before this commit, when using searchForFacetValues,
the default SearchBox shortcuts would be listening for shortcuts.
Thus when hitting `/` or `s` it would try to focus
the SearchBox of RefinementList instead of something else.
fixes #1920
Note: we are not testing List.js right now, we need to fix that.
> fix(*List): disable shortcuts in *List SearchBoxes

- packages/react-instantsearch/src/components/StarRating.js
- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- stories/StarRating.stories.js
> fix(StarRating): indicate no refinement

- packages/react-instantsearch/src/components/List.js
Before this commit, the SearchBox inside RefinementList was being
unmounted as soon as the search for items was not retrieving anything.
> fix(withSearchBox): keep displaying searchBox when no items found

- packages/react-instantsearch-theme-algolia/styles/_MultiRange.scss
- packages/react-instantsearch-theme-algolia/styles/_Panel.scss
- packages/react-instantsearch-theme-algolia/styles/_RangeInput.scss
- packages/react-instantsearch/src/components/Menu.js
- packages/react-instantsearch/src/components/MultiRange.js
- packages/react-instantsearch/src/components/RangeInput.js
- packages/react-instantsearch/src/components/RefinementList.js
- packages/react-instantsearch/src/components/__snapshots__/MultiRange.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/RangeInput.test.js.snap
- packages/react-instantsearch/src/connectors/connectMultiRange.js
- stories/ClearAll.stories.js
- stories/HitsPerPage.stories.js
- stories/Menu.stories.js
- stories/MultiRange.stories.js
- stories/StarRating.stories.js
When widgets are no more relevant/have no refinements, we were already
adding specific CSS classes. Now the default theme also define more
precise rendering states for widgets.
Basically noRefine panels will get an opacity of 0.7.
Also did some fixes so that MultiRange is working with Panel feature.
> feat(widgets): default design for disabled states

- packages/react-instantsearch/src/connectors/connectConfigure.js
- packages/react-instantsearch/src/connectors/connectConfigure.test.js
- stories/Stats.stories.js
This PR add to the search state all configure parameters. That way, if you perform some changes to them when listening to `onSearchStateChange` it will be taken into account. 
I used the `transitionState` function of the connector to be able to add those parameters to the state without the need of calling refine (that triggers a new search). It might not be the most obvious name though.
> feat(Configure): add configure parameters in search state

- packages/react-instantsearch/src/components/LinkList.js
- packages/react-instantsearch/src/components/Pagination.js
- packages/react-instantsearch/src/components/Pagination.test.js
- packages/react-instantsearch/src/components/__snapshots__/Pagination.test.js.snap
> fix(Pagination): add disabled property

- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
**Summary**
Use cases: 
- Use createConnector to create a new custom connector.
- Use this new connector to create a component.
- Update the `props` of this component.
- Trigger a `state` change.
- This component still calls `getProvidedProps` with initial props.
**Result**
- Should calls `getProvidedProps` with latest props.
cc @vvo
> fix(createConnector): updates with latest props on state change

- packages/react-instantsearch/src/connectors/connectConfigure.js
- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
- stories/Configure.stories.js
This fix: 
- bug when cleanUp `<Configure/>`
- trigger `onSearchStateChange` when props are updated (but search state is computed only by passing through `transitionState`). 
This will not perform on `onSearchStateChange` as the first rendering. If we do this, it's a breaking change. 
Also, with this method, the `search state` is still not computed correctly at any given update. For this, we need a further refactoring in order for us to be able to call the `refine` props with the extra args pre computed.
> fix(Configure): onSearchStateChange when props are updated

- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
The previous fix was triggering the onSearchStateChange hooks with the wrong information because the update was not yet performed.
Ultimately we want to:
1. call refine + transitionState when new props are passed to our component. 
2. call refine + transition when a component did mount.
> fix(Configure): update was not apply when trigger onSearchStateChange

- package.json
- packages/react-instantsearch/scripts/build.sh
- packages/react-instantsearch/webpack.config.babel.js
- scripts/release.sh
- yarn.lock
This adds a standalone JavaScript bundle of React InstantSearch so that
we can easily build demos and jsFiddles with it. Example usage:
https://jsfiddle.net/o7kfw88g/ (to be added to the issue template
afterwards).
The build will be available on unpkg.com as usual.
> chore(dev tools): add standalone browser bundle to ease demos/fiddles

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
- instantsearch.js (use develop base)
**Summary**
This PR allows one to provide his own Algolia JS client instance to instantsearch.js, instead of letting it create an internal one.  
This can be useful in different scenarios... Some that come to mind:
- when hosts/other options need to be overriden
- when Algolia is needed in another context than instantsearch only
**Result**
You just have to pass a new option to the initialization function:
```js
let search = instantsearch({
appId: 'appId',
apiKey: 'apiKey',
// ...
clientInstanceFunction: (appID, apiKey) => algoliasearch(appID, apiKey, { timeout: 4000  }),
});
```
Open to feedback of course!
Things we could consider:
- another name for the option?
- provide the same mechanism for the …
> feat(custom client): allows to provide a custom JS client instance

- dev/app.js
- docs/_includes/widget-jsdoc/analytics.md
- src/widgets/analytics/analytics.js
- instantsearch.js
**Summary**
Right now on some websites the statistics might got screwed by initial searches.
The PR adds a parameter to analytics widget which decides whether the `pushFunction` should be called after the very first search. Setting it to false prevents the `pushFunction` to be called after the first search.
**Result**
```js
search.addWidget(
instantsearch.widgets.analytics({
pushFunction(/* formattedParameters, state, results*/) {
// your analytics code
},
triggerOnUIInteraction: true,
pushInitialSearch: false,
})
);
```
> feat(analytics-widget): add a new parameter "pushInitialSearch"

- CONTRIBUTING.md
- README.md
**Summary**
you had to click on "getting started" on the documentation site to know how react-instantsearch is published on npm, so that was added to the main README.
In my opinion it makes more sense to have the detailed contributing information into a separate file, because it's less relevant if you just want to use it.
**Result**
The readme is now shorter, and filled with only information you really need when wanting to use `react-instantsearch`. For detailed info the documentation website is used.
> move development info into contributing and add install info

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
**Summary**
Safari can’t have <use> with href, it needs xlink:href. Relevant [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href)
**Result**
Since React [0.14](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#notable-enhancements) it's allowed to use all svg features, and thus also those that are usuallly written
with a colon.
closes #1968
before|after
---|---
> fix(SearchBox): Safari can only have <use> with xlinkHref

- stories/RangeInput.stories.js
- stories/SearchBox.stories.js
- stories/StarRating.stories.js
**Summary**
It was kind of confusing to realise that the actual prop to add was an object with "translations" as name, since using "translate" would cause "object is not a function" errors.
I haven't yet checked if this is the case with all of the stories, or just this one.
**Result**
the story now shows "translations" as key
> docs(storybook): use 'translations' in SearchBox

- docgen/src/guide/Styling_widgets.md
**Summary**
it's not so hard, but the actual svg elements don't have a class, so you will have to target them explicitly.
SVG elements also have a different feature set, so this example should clear things up.
**Result**
Extra piece of text in the `Styling widgets` part that explains briefly that we work with svg, so it's styleable and how.
see #1981
> docs(guide): how to style svgs

- docgen/src/examples/e-commerce-infinite/App.js
- docgen/src/examples/e-commerce/App.js
**Summary**
link to instantsearch/react instead of instantsearch/ in header of ecom example
**Result**
link is correct
> fix(example): link to instantsearch/react

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/SearchBox.test.js
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
- stories/SearchBox.stories.js
**Summary**
Because the searchbox is icon-based, but we still want to allow people to give custom icons, the solution here is to have custom components. They start lowercase and then end with Component.
A similar solution might be used for example in pagination if this seems useful
see #1954
fixes #1952
**Result**
Here a text-based (span with emoji content) submit button and an svg as reset button have been chosen as demo.
> feat(SearchBox): allow custom reset and submit components

- src/lib/url-sync.js
The effect was there since the begining but only visible since the move
to "only update url every 700ms". Since you can definitely move the
search box cursor back in 700ms, you would see the input cursor move to
the end of the search box from time to time.
The bug fix is done by ignoring any hashchange event occuring after a
manual url hash update.
fixes #2012
> fix(searchBox): avoid unwanted cursor jumps on hashchange

- package.json
this is exposed in multiple places, and otherwise becomes `github.com/algolia/instantsearch.js#readme`
> chore(package): add homepage to package.json

- packages/react-instantsearch/package.json
- packages/react-instantsearch/yarn.lock
Update algoliasearch-helper dependency to 2.19.0 which contains the access to raw results in the SearchResults. CC. @proudlygeek ;)
> chore(helper): update dependency to algoliasearch-helper

- packages/react-instantsearch/examples/react-router-v4/src/App.js
**Summary**
Related with https://github.com/algolia/instantsearch.js/pull/2023#issuecomment-284677368
> example/react-router-v4: Update push reference

- .babelrc
- package.json
- yarn.lock
**Summary**
Use https://github.com/babel/babel-preset-env to target only 2 last versions of browsers and IE9 (sad react only 😭)
see: https://github.com/algolia/instantsearch.js/issues/1868
**Result**
Do we have access to browserstack or similar tool to test it live on other browsers?
> chore: switch to `babel-preset-env`

- src/components/Slider/Slider.js
- src/components/Slider/__tests__/Slider-test.js
- src/css/default/_range-slider.scss
- instantsearch.js (use develop base)
**Summary**
Instead of showing nothing when `range.min === range.max` of the slider, we show it on a disabled state.
**Result**
Active
Disabled
> fix(Slider): display disabled slider when `min === max`

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
**Summary**
Add a `role=search` to the form of the searchbox. 
This helps for screenreaders, and is valid html5 since december 2015. Before then it was working, but not valid. see also https://github.com/w3c/html-aria/issues/18
**Result**
Some screen readers will read our search input as `search form: 3 inputs`. Others will still say `form: 3 inputs`.
> feat(SearchBox) add role=search to the form

- packages/react-instantsearch/src/widgets/RangeSlider.js
The URL is set as absolute, leading to a 404 in the docs.
Fixing by removing the leading `/`
> fix(connectRange URL): from absolute to relative

- CONTRIBUTING.md
- packages/react-instantsearch-theme-algolia/scripts/build-and-publish.sh
- packages/react-instantsearch/scripts/build-and-publish.sh
- scripts/release.sh
**Summary**
partial fix for #2056 
add `-b` or `--beta` when releasing, which will then propagate the `--tag beta` to `npm publish`. With these changes it's also possible to set flags for the yarn commands run in the packages `build-and-publish.sh`
> chore(tooling) allow beta versions

- src/decorators/__tests__/autoHideContainer-test.js
- src/decorators/autoHideContainer.js
If you click on a DOM element which has a state (ex radio button), React wont see this state change because children component of `autoHideContainer` wont be updated because of the implementation of `shouldComponentUpdate`.
It's a weird bug where UI and state aren't in sync because the navigator saves on it's own the state of the DOM element.
fixes https://github.com/algolia/instantsearch.js/issues/2066
- instantsearch.js (use develop base)
> fix(autoHideContainer): dont prevent render with `shouldComponentUpdate`

- packages/react-instantsearch/src/components/List.js
- packages/react-instantsearch/src/components/Menu.js
- packages/react-instantsearch/src/components/RefinementList.js
When using SFFV (RefinementList or Menu) with a slow network (like regular 2G), then the query was not saved properly. 
If you want to test this:
- Use the preview and go to the [storybook](https://deploy-preview-2086--algolia-instantsearch.netlify.com/instantsearch.js/react/storybook/?selectedKind=RefinementList&selectedStory=with%20search%20inside%20items&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs)
- Simulate slow network with devtools
- Search for facet values.
> fix(SFFV): fix wrong query behaviour with slow network

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- LICENSE
- README.md
- docs/_config.yml
- docs/documentation.md
- docs/index.haml
- scripts/docs/gh-pages.js
Since we moved react-instantsearch to
https://github.com/algolia/react-instantsearch/ and
https://community.algolia.com/react-instantsearch/
We can now remove mentions of the old repo organisation
> docs(react-instantsearch): remove mentions of ris

- dev/app/custom-widgets/vanilla/hits.js
- dev/app/custom-widgets/vanilla/index.js
- dev/app/init-vanilla-widgets.js
- package.json
- yarn.lock
**Summary**
[Bel](https://github.com/shama/bel) is an easy 'vanilla'-ish element create thingy, and it's nice to try if we play nice with it for hits. It turns out we do!
Theres's a way to transform these into real `document.createElement` calls with [yo-yoify](https://github.com/shama/yo-yoify#how-this-works), but that's browserify specific, and for production.
It's possible to switch this to [yo-yo](https://github.com/maxogden/yo-yo#dynamic-updates) which is does DOM diffing etc, but that seemed superfluous for this.
**Result**
A custom hits via a connector made with bel
> docs(connectHits): make a custom hits example using bel

- dev/app.js
- dev/index.html
- src/lib/url-sync.js
This fixes an issue when setting searchOnEnterKeyPressOnly to true on
searchbox. Before it would update the URL even though the search was
not triggered (on enter key press).
This also adds a new searchbox that uses the searchOnEnterKeyPressOnly
on the searchbox in the kitchen sink.
Fixes #2105
> fix(url-sync): sync url on search

- CONTRIBUTING.md
**Summary**
We don't have beta releases yet (see the [script](https://github.com/algolia/instantsearch.js/blob/develop/scripts/release.sh#L85-L92) and https://github.com/algolia/instantsearch.js/issues/2056), so the contributing section shouldn't be added yet.
We will put this back when `-b` works, and we've found a strategy for making it work with jsDeliver
**Result**
Remove the beta section in CONTRIBUTING for now
> fix(CONTRIBUTING): remove section about beta releases

- src/components/RefinementList/RefinementList.js
- src/components/SearchBox/index.js
When the number of items displayed in a refinement list is lower than
the max number of facet displayed, the search for facet input should be
disabled.
This fix disables the input and adds a new classname to identify the
state of the input.
**Result**
[staging default](http://capricious-song.surge.sh/): the search input is not disabled.
fixes #2111 
[staging with a query that limits the items](http://capricious-song.surge.sh/?query=SanDisk%20-%20Ultra%20Plus%2032GB%20microSDHC%20Class%2010%20UHS-1%20Memory%20Card%20-%20Gray%2FRed&hits=3&idx=instant_search&p=0&hierarchical%5BhierarchicalCategories.lvl0%5D%5B0%5D=Cameras%20%26%20Camcorders&nR%5Bpopularity%5D%5B%3E%3D%5D%5B0%5D=0&is_v=1): the input is disabled.
> fix(sffv): disable sffv input when few facet values FIX #2111

- docs/_config.yml
since the header adds `/instantsearch.js` to all urls in the nav (with `{{site.baseurl}}`), this is needed to be able to link to `/react-instantsearch` instead of `/instantsearch.js/react-instantsearch`.
reported by @seafoox
fixes #2119
> fix(url): link relatively to react-instantsearch

- src/components/SearchBox/index.js
The original fix for #2111 didn't add a class name at the form level, which prevents the user from completely hiding the form part of the refinement list when using search for facet values.
This patch adds that class.
> fix(sffv): add class for disabled state at the form level

- dev/app/init-builtin-widgets.js
- dev/app/init-jquery-widgets.js
- docgen/src/guides/migration.md
- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.js
- src/connectors/infinite-hits/connectInfiniteHits.js
- src/widgets/infinite-hits/__tests__/infinite-hits-test.js
- src/widgets/infinite-hits/infinite-hits.js
hitsPerPage is an option of the `hits` and `infiniteHits` that we decided we should move away from. The reason is that there are already many ways to define it, and it's not always clear why it should be on those widgets.
The migration guide and examples have been updated accordingly.
> fix(infinite-hits): Remove hitsPerPage option

- docgen/src/guides/migration.md
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/connectors/menu/connectMenu.js
- src/connectors/refinement-list/connectRefinementList.js
- src/widgets/menu/menu.js
- src/widgets/refinement-list/refinement-list.js
Add a migration guide for users using the default sortBy, and make the sortBy scheme consistent between widgets and connectors.
> fix(sortby): Consistent across widget / connectors + migration

- src/lib/url-sync.js
I'm using Instantsearch in the context of a single page application.  Each time the user hits the page with the search field, a new instance of Instantsearch is created, and whenever they navigate away all handlers are destroyed.  
This generally works, with the exception of the urlSync feature.  Since the `firstRender` variable is defined outside of the URLSync class, once it is set to false the code in lines 127 - 129 never executes again, even when I spin up a new Instantsearch instance.  As a result that the `onHistoryChange` handler is never attached, and the url does not update when the query is changed.  This pr sets the `firstRender` instead to be an attribute on the `URLSync` class, so that it will be reset every time the class is re-instantiated.  This revision is one resolution …
> Fix for url sync issue in SPA

- package.json
Only upload `/dist` and `/dist-es5-modules` to npm, should fix the issue with jsdelivr size limit 👍
> chore: whitelist only `dist` && `dist-es5-modules`

- docgen/assets/js/activateClipboard.js
- docgen/src/stylesheets/components/_documentation.scss
**Summary**
The “clipboard” header would scroll with the code, as seen in 
**Result**
1. put clipboard above pre
2. update styles to look seamless
> docs(clipboard): put outside of pre

- scripts/test-ci.sh
The Jekyll build is slowing down the travis build, but Netlify already does this build on another machine, and also gives a status when the build fails. 
If it’s a release the build would even run twice, so there’s no need to run it at all in test (see [update-website.sh#L25](https://github.com/algolia/instantsearch.js/blob/feat/instantsearch.js/v2/scripts/docs/update-website.sh#L25))
fixes #2110 
Should I also do this PR on the develop branch for v1?
> chore(travis): don’t build the docs when it’s a test

- package.json
fixes #2150
was `dist-es5-modules` but should be `dist-es5-module` @iam4x
> fix deploy of 1.11.9

- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/connectors/menu/__tests__/connectMenu-test.js
- src/connectors/menu/connectMenu.js
- src/connectors/refinement-list/__tests__/connectRefinementList-test.js
- src/connectors/refinement-list/connectRefinementList.js
- src/widgets/menu/__tests__/__snapshots__/menu-test.js.snap
- src/widgets/menu/menu.js
- src/widgets/refinement-list/refinement-list.js
As noticed by @timkelty in #2160, showMore button should not be rendered
if there are not enough items to display based on the limits. With the
new connector API, this means that we should add a new parameter to
the renderer to give the information that this button should be
displayed.
fixes #2160
http://faithful-anger.surge.sh/?query=Canon%20-%20PowerShot%20SX720%20HS%2020.3-Megapixel%20Digital%20Camera%20-%20Red&idx=instant_search&p=0&dFR%5Bbrand%5D%5B0%5D=Canon&hierarchical%5BhierarchicalCategories.lvl0%5D%5B0%5D=Cameras%20%26%20Camcorders&nR%5Bpopularity%5D%5B%3E%3D%5D%5B0%5D=0&is_v=2
Check the menu widget and the collapsible refinement list.
> fix(show-more): should hide button when show more is not available

- dev/app.js
- dev/index.html
- src/components/RefinementList/RefinementList.js
- src/widgets/refinement-list/refinement-list.js
In the case we're using the widget with a very big limit (number of
items displayed) in the refinement list, we often still have a huge
number of items. Therefore we should be able to continue searching
in the list, even though all the items are displayed.
Fixes #2156
> fix(sffv): when using a large limit, retain the search

- src/widgets/hits/hits.js
- src/widgets/infinite-hits/infinite-hits.js
**Summary**
As `hitsPerPage` is no longer supported as an argument in `hits` & `infiniteHits` widgets, I removed it from the examples.
> Documentation: remove hitsPerPage from hits & infiniteHits examples

- src/lib/url-sync.js
This reverts the behaviour of the URL sync to using the `change` event.
Unfortunately it reverts back the state prior to fixing #2105. However
this behaviour was introduced on purpose with #1015
Fixes #2173 #2171
http://aromatic-card.surge.sh/
> fix(url-sync): reverting back to using `change` event

- package.json
This then warns user installing via npm about their engine not being compatible.
> chore(packaging): do not add engine instruction to package.json

- src/connectors/numeric-refinement-list/__tests__/connectNumericRefinementList-test.js
- src/connectors/numeric-refinement-list/connectNumericRefinementList.js
Fixes #2195 
The numericRefinementList was not reseting the page when refining, so the infiniteHits could not know it was new results from the first page.
> Fix numeric refinementlist page

- functional-tests/test.js
- functional-tests/utils.js
**Summary**
The focus bar visibility is flaky, we cant take screenshots with it.
**Result**
Fix that build https://www.argos-ci.com/algolia/instantsearch.js/builds/4431.
For reference, here are some of [the tweaks](https://github.com/argos-ci/argos/blob/master/examples/with-rails/test/ui_tweak_helper.rb) we use at Doctolib to make it work at scale (for a lot of e2e tests).
> fix(argos-ci): blur the active element

- CONTRIBUTING.md
- package.json
- scripts/release-maintenance.sh
Fixes #2203
This adds a new script to release the maintenance version. It is based on the previous release.sh.
> chore(build): Add release script for maintenance

- docgen/src/data/communityHeader.json
Link in top right header was not to the good repository url
> docs(header): fix link to GitHub source code

- dev/app/custom-widgets/vanilla/index.js
- dev/app/custom-widgets/vanilla/selectMenu.js
- dev/app/init-vanilla-widgets.js
**Summary**
A menu definitely works as a `<select>` too! Someone asked on [Stack Overflow](https://stackoverflow.com/questions/37033654/create-a-select-dropdown-with-algolia-instantsearch-js/45169476#45169476), so I made it general-purpose
**Result**
A selectMenu vanilla custom widget in the dev novel
> docs(menu): add a connectMenu as a select

- docs/_layouts/default.html
- docs/_plugins/asset_url_tag.rb
- docs/_preview.yml
- docs/_production.yml
**Summary**
The `og:image` and `twitter:image:src` meta tags need to provide an absolute URL to be usable from external websites linking to the page.
Today, `asset_path` is used and returns a relative path, making the thumbnail broken on some websites such as our Discourse forum.
**Result**
Using `asset_url` instead of `asset_path` for `og:image` and `twitter:image:src` meta tags will output an absolute URL instead of a relative path.
Fixes #2238
> [v1 Docs] Absolute URLs for meta images

- docgen/middlewares.js
- scripts/docs/publish.sh
The in-place plugin seems to tamper all the files, even
though it does not transform them >> Scoping this plugin to
only relevant extensions.
Also in this PR: we let the user publish the doc from any branch but we ask for confirmation if not on master.
> chore(website): Fix corrupted assets during build

- docgen/src/getting-started.md.hbs
The `in-place` plugin replaced these tags by their value (undefined), so they didn't show up.
Thanks @ronanlevesque for noticing this!
> docs(getting-started): make sure that the template doesn't get replaced

- docgen/src/getting-started.md.hbs
This is the one used in the examples of the widgets, which is almost the same as bestbuy, but slightly different.
As noticed by @ronanlevesque, there are a few widgets (range, rangeSlider, hierarchicalMenu and menu) that didn't work with the attribute names in `latency`, but that does work with the ones in `instant_search`.
The API key here is search-only
> docs(getting-started): use `instant_search` as indexName

- package.json
- scripts/build.sh
- yarn.lock
The v2.1.0 was not providing an unminified css build used by the examples.
> fix(build): provide unminified css as well

- index.es6.js
Fixes https://discourse.algolia.com/t/instantsearch-with-angular-1-5/2468
The path was the old one to the `dist-es6-module` folder that we renamed `es` after all.
> fix(es): wrong path to files

- docgen/src/guides/angular-integration.md
Fix sidebar navigation for the integrate angular guide. Was displaying the examples.
Was:
Now:
> chore(doc): Fix side navigation for integrate angular guide

- dev/app/init-builtin-widgets.js
- src/widgets/refinement-list/defaultTemplates.searchForFacetValue.js
- src/widgets/refinement-list/refinement-list.js
When there was no results and the template is not provided, is.js would trigger an error.
Fix #2087
> fix(sffv): no error when not providing noResults and no results

- dev/webpack.config.js
- docgen/layouts/example.pug
* Remove `rheostat` from the vendors bundled by webpack-autodll-plugin
* Import minified styles & scripts for examples
> Fix range slider dev env

- .eslintignore
Leftover from the back and forth about the naming of the exported files.
> chore(eslint): ignore the correct files

- dev/app/init-builtin-widgets.js
- src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
- src/connectors/hits-per-page/connectHitsPerPage.js
- src/widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
- src/widgets/hits-per-page-selector/hits-per-page-selector.js
**Summary**
Actually, there is no options to set a default hitsPerPage appart from using the `searchParameters` object when you instantiate `instantsearch`.
My proposal, is to add a key `default: true` into the items[] of the hitsPerPageSelector options to specify on which value you want to start.
```js
instantsearch.widgets.hitsPerPageSelector({
container,
items: [
{ value: 3, label: '3 per page' },
{ value: 5, label: '5 per page', default: true },
{ value: 10, label: '10 per page' },
],
});
```
In this example the default value will be "5 per page" hits on the first search.
Fixes #2288
> default hits per page

- src/components/Slider/Slider.js
> Fix edge case slider

- CHANGELOG.md
- scripts/conventionalChangelog.js
- scripts/release.js
- scripts/validate-commit-msgs.sh
We forgot to add the changelog in the new release script. This PR also regen the changelog missing for some releases, and fix the commit validation (based on @rayrutjes suggestion)
> fix(release-script): Add the generation of changelog for the release

- src/widgets/analytics/analytics.js
**Summary**
Currently the analytics widget doesn't trigger `pushFunction` during pagination. This PR adds a parameter to allow the `pushFunction` to be triggered there.
**Result**
`pushFunction` can be triggered on pagination 🎉
> feat(analytics): Push pagination

- dev/app/init-builtin-widgets.js
- src/components/MenuSelect.js
- src/components/__tests__/MenuSelect-test.js
- src/components/__tests__/__snapshots__/MenuSelect-test.js.snap
- src/connectors/menu/connectMenu.js
- src/widgets/index.js
- src/widgets/menu-select/__tests__/__snapshots__/menu-select-test.js.snap
- src/widgets/menu-select/__tests__/menu-select-test.js
- src/widgets/menu-select/defaultTemplates.js
- src/widgets/menu-select/menu-select.js
- src/widgets/menu/menu.js
**Summary**
Works like a menu widget but displays as a select DOM element.
**Result**
Fixes #1904
> add menu select widget

- docgen/src/guides/customization.md
Previously the link for more info on connectors led to a 404.
> Fix the connector-docs link + typo

- scripts/release.js
The doc is not auto updated anymore using TravisCI because we don't have to wait for
jsDeliver to publish the packages anymore. This PR makes the release script to publish
the doc just after we've pushed to NPM.
> chore(doc): publish doc during the build process

- dev/app/init-builtin-widgets.js
- src/components/Slider/Slider.js
- src/components/Slider/__tests__/Slider-test.js
- src/components/Slider/__tests__/__snapshots__/Slider-test.js.snap
- src/connectors/range-slider/__tests__/connectRangeSlider-test.js
- src/connectors/range-slider/connectRangeSlider.js
- src/widgets/range-slider/__tests__/__snapshots__/range-slider-test.js.snap
- src/widgets/range-slider/__tests__/range-slider-test.js
- src/widgets/range-slider/range-slider.js
**Summary**
Fix #2386 
- The boundaries were ignored in `getConfiguration` for the first render
- They were ignored when a refinement was triggered and reset
**Result**
You can play with the `RangeSlider` on `dev-novel` (some stories added)
> Fix range slider boundaries

- dev/webpack.config.js
Sourcemaps are buggy in chrome, let's use a less aggressive option in webpack to restore them until it's fixed in webpack.
-> Impacts a slower re-build time
> fix(webpack.dev): sourcemaps in dev

- package.json
- scripts/build.sh
- scripts/webpack.config.js
- yarn.lock
Now webpack build output un-minified CSS and we process the CSS into https://github.com/css/csso after.
Fixes #2375
> fix(build): minify css with `csso` instead of unminify css

- docgen/middlewares.js
Before this fix, when we would deploy the new org (v1, v2) to the live
website, link to /v2/ (homepage) could endup in a 404 (because the cloudflare redirect takes some time to be activated). With this fix it will not
and I will at the same time activate a rule to redirect /v2/ (homepage) to /.
> docs(org): ensure /v2/index.html still works while reorg

- docgen/src/data/communityHeader.json
This add a link back to v1 docs
> docs(v1): add v1 link

- docgen/.babelrc
- docgen/layouts/archetypes/content-with-menu.pug
- docgen/layouts/widget-showcase.pug
- docgen/package.json
- docgen/yarn.lock
- src/widgets/menu-select/menu-select.js
After releasing the v2.2.0, I found several problems when building the docs: 
- incorrect types
- updated babel doesn't support some of the presets we were using
- menuSelect wasn't displayed in the showcase (updated the instantsearch.js loaded to the latest but that should be fixed correctly #2446)
> chore(doc): misc. issues in the doc

- src/widgets/menu-select/__tests__/__snapshots__/menu-select-test.js.snap
- src/widgets/menu-select/menu-select.js
**Summary**
Bug fix: `select` in `cssClasses` are currently applied to `footer` element.
> fix(menuSelect): select in userCssClasses

- src/connectors/range-slider/__tests__/connectRangeSlider-test.js
- src/connectors/range-slider/connectRangeSlider.js
**Summary**
The `connectRangeSlider` clear all the refinements when refinement change.
This fix restrict the `clearRefinements` only on the current attribute.
> fix: avoid connectRangeSlider to clear all refinements

- package.json
- yarn.lock
This update fixes the analytics of the subsequent queries when disjunctive or hierarchical facets. It also expose the `userData` attribute in the search results. And finally it fixes a problem preventing us from moving forward in the implementation of dynamic add remove widgets.
> feat(dep): update helper to 2.22.0

- docs/_config.yml
https://community.algolia.com/instantsearch.js/v1/documentation/
If you go to this page you can see the broken link :)
> chore(doc): update link to v2 in v1

- scripts/docs/build-dev.sh
Also adds `yarn install` before building instantsearch.js for the website
> chore(publish): fix dev dep install on docgen when publishing

- docgen/src/examples/e-commerce/index.html
- docgen/src/examples/e-commerce/main.scss
- docgen/src/examples/e-commerce/search.js
**Summary**
Add a breadcrumb to the e-commerce example (following #2451).
**Result**
Now there is a breadcrumb widget displayed on the example, making it easier to see the facet hierarchy.
> chore(doc): add breadcrumb to e-commerce demo

- dev/app/init-builtin-widgets.js
- src/components/Breadcrumb/Breadcrumb.js
- src/components/Template.js
- src/connectors/breadcrumb/connectBreadcrumb.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/connectors/range/__tests__/connectRange-test.js
- src/connectors/range/connectRange.js
- src/css/default/_breadcrumb.scss
- src/css/theme/_breadcrumb.scss
- src/widgets/range-input/range-input.js
- src/widgets/range-slider/__tests__/range-slider-test.js
- src/widgets/range-slider/range-slider.js
**Summary**
In the `connectRange` we always round the range even with a precision greater than 0. Now we round the range only for a precision of 0 and leave the original value in the other case.
**Result**
You can play with the `RangeInput` on dev-novel.
**Before:**
**After:**
> Avoid to always round the range in connectRange

- src/widgets/hierarchical-menu/hierarchical-menu.js
see #2505, thanks @Giovanni-Mattucci
> docs(hierarchicalMenu): showParentLevel is boolean

- src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
- src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
When:
If there is already`currentConfiguration.hierarchicalFacets` in the configuration, we would check if it's the same added and throw a warning.
Bug:
If it's not the same `hierarchicalFacets` we were returning an empty object as well.
> Fix connect hierarchical menu

- src/widgets/hierarchical-menu/hierarchical-menu.js
Add an example to show what is the expected behaviour of the `showParentLevel` option.
Schema proposed by @Giovanni-Mattucci
> chore(doc): add showParentLevel example

- dev/app/wrap-with-hits.js
**Summary**
During my work on the `geosearch` widget I need to target another index. This changes allow me to do it from the stories.
> chore(wrapWithHits): enable to extend all options from stories

- README.md
Algolia's link in the main description was using parentheses (`()`) instead of square brackets (`[]`) for [Markdown reference links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links), referencing to a [broken link](https://github.com/algolia/instantsearch.js/blob/develop/algolia-website).
> docs(readme): fix Algolia link

- docgen/src/guides/angular-integration.md
**Summary**
`HitsComponent` example does not compile due to:
`A parameter property is only allowed in a constructor implementation.`
- Problem: `construcor` should be `constructor`
- Result: Fixed typo in HitsComponent constructor examples
Note: also made grammatical clarification.
> fix: typo in HitsComponent constructor

- dev/app/init-builtin-widgets.js
- dev/app/wrap-with-hits.js
- package.json
- src/lib/__tests__/__snapshots__/url-sync-test.js.snap
- src/lib/__tests__/url-sync-test.js
- src/lib/url-sync.js
When there is a search function that prevents the initial rendering,
the first actual change should be able to update the URL.
Fix #2523
> fix(url-sync): make URLSync consistent even if search is tampered

- src/connectors/refinement-list/__tests__/connectRefinementList-test.js
- src/connectors/refinement-list/connectRefinementList.js
- src/widgets/refinement-list/__tests__/refinement-list-test.js
This check depends on whether or not there is another widget setting the
max value per facet to a bigger value, we can't be sure that if there is
the same number of items than the limit that it is exhaustive.
Fixes the other part of #2552
> fix(refinementList): fix facet exhaustivity check

- src/css/theme/_search-box.scss
Usually you want the searchbox to have the same font size (at least) as your body text. Otherwise it'll look awkardly small without other styling.
Also fixed a typo in `appearance` and deduplicated two properties
before|after
---|---
> fix(theme): searchbar should have normal size input

- CONTRIBUTING.md
- scripts/release.js
This commit adds a new flag to the release command to be able to force a
new beta version from develop.
`npm run release -- --beta`
Remaining tasks:
> chore(release): ability to release a beta from develop

- docgen/src/stylesheets/components/_documentation.sass
- src/lib/InstantSearch.js
This PR adds some documentation about the new method to add and remove widgets from InstantSearch. The new methods and behaviors are explicitly marked as experimental so that users are encouraged to give us feedback.
This PR also fixes the problem with the anchors hack that made the links unclickable if they were underneath one of the pseudo elements.
> chore(doc): add experimental flag about new dynamic is API's 

- src/connectors/price-ranges/connectPriceRanges.js
- src/connectors/toggle/connectToggle.js
- src/widgets/price-ranges/__tests__/price-ranges-test.js
- src/widgets/toggle/__tests__/currentToggle-test.js
Previously we were using bind, which will be applied at each init. This
is ok for one time mount, but since we can mount and unmount dynamically
now, it's a problem.
> fix(connectors): prefer wrappers over bind

- docgen/src/data/communityHeader.json
- docgen/src/guides/angular-integration.md
This is the preferred way of spelling it according to them
> docs(spelling): Github -> GitHub

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
Case:
If you have `urlSync: true` and refinement for a widget you dispose in the URL, the search will crash because calling `URLSync.getConfiguration()` will add back the removed refinement found in the URL for the next search.
Fix:
Don't call `URLSync.getConfiguration()` when a widget is disposed 👍
> fix(InstantSearch.dispose): dont call `URLSync.getConfiguration`

- src/components/Breadcrumb/Breadcrumb.js
- src/components/RangeInput/RangeInput.js
- src/widgets/breadcrumb/breadcrumb.js
- src/widgets/range-input/__tests__/range-input-test.js
- src/widgets/range-input/range-input.js
**Summary**
Both widgets `RangeInput` & `Breadcrumb` still have some references on `react` / `react-dom` instead of using the `preact-compat` import. When the lib is used with a bundler (ex: Webpack) an error is thrown.
```
Uncaught Error: Cannot find module "react"
```
This PR aims to fix the reference of React inside the both widgets.
> fix: React reference

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test-2.js
Fix #2616 
This modifies the first steps of IS so that the stalled search
behaviour is not triggered before the first rendering.
> fix(core): search is stalled at init

- docgen/layouts/instantsearch.pug
- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test-integration.js
- src/lib/__tests__/__snapshots__/InstantSearch-test.js.snap
Fix #1585
Adds an event that is emitted when an error is received in place of results.
> feat(core): add an error event to monitor error from Algolia

- dev/app/builtin/init-stories.js
- dev/app/builtin/stories/refreshcache.stories.js
- dev/app/builtin/stories/reload.stories.js
- src/lib/InstantSearch.js
**Summary**
Give the ability to the user to clear the cached answers from Algolia.
(see #1050)
**Result**
The user can now clear the cache by calling `clearCache()` on his/her `search` instance.
See the results in the `RefreshCache` story on dev-novel (network tab).
> feat(reload): add a reload method on the InstantSearch component

- dev/app/builtin/stories/pagination.stories.js
- src/components/Pagination/Pagination.js
- src/components/Pagination/Paginator.js
- src/components/Pagination/__tests__/Pagination-test.js
- src/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap
Fix #2014 
This only occurs if `autoHideContainer` is set to `false`. In such case, the button for next / last etc. should be disabled and we should display that the current page is the page 1, when there are no results.
> fix(pagination): disable buttons if not results

- dev/app/builtin/stories/reload.stories.js
- src/lib/InstantSearch.js
> feat: rename reload to refresh (vue-instantsearch consistency)

- dev/app/builtin/stories/hits.stories.js
- dev/style.css
- src/lib/__tests__/escape-highlight-test.js
- src/lib/escape-highlight.js
**Summary**
The test sample was not correctly structure so the implementation worked with the test but not with the actual Algolia response. I add a story with the same dataset that React InstantSearch use in Storybook. 
**Before**
**After**
You can also play with the example on [`dev-novel`](https://deploy-preview-2646--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=Hits.with%20highlighted%20array).
> Fix: escape highlight

- index.es6.js
- scripts/build.sh
**Summary**
There was too much whitespace and a typo in the es6 build and a typo in the build script: 
```js
Object.defineProperty(instantSearchFactory, 'widgets', {
get: function get() {
throw new ReferenceError('\n      You can\'t access to \'instantsearch.widgets\' directly from the ES6 build.\n      Import the widgets this way "import { searchBox } from \'instantsearch.js/es/widgets\'"\n    ');
}
});
Object.defineProperty(instantSearchFactory, 'connectors', {
get: function get() {
throw new ReferenceError('\n      You can\'t access to \'instantsearch.connectors\' directly from the ES6 build.\n      Import the connectors this way "import { connectSearchBox } from \'instantsearch.js/es/connectors\'"\n    ');
}
});
```
**Result**
```js
Object.defineProperty(instantSearchFactory, …
```
> docs: fix typos in index es6 and build script

- package.json
- src/components/RangeInput/__tests__/RangeInput-test.js
- src/components/RefinementList/__tests__/RefinementListItem-test.js
- src/components/RefinementList/__tests__/__snapshots__/RefinementListItem-test.js.snap
- src/components/Stats/__tests__/Stats-test.js
- src/components/Stats/__tests__/__snapshots__/Stats-test.js.snap
- src/decorators/__tests__/__snapshots__/autoHideContainer-test.js.snap
- src/decorators/__tests__/autoHideContainer-test.js
**Summary**
We're using `toMatchJSX` and imported `expect` and `sinon` in the tests. It's easier to rely on what Jest already provides with snapshots and `jest.spyOn`. 
**Result**
1. added the enzyme snapshot format
2. use enzyme in `RefinementListItem`
3. use enzyme in `Stats`
4. use enzyme and modern Jest in `autoHideContainer`
This obviously isn't all tests, but it isn't a straightforward process because of the things renamed in `import expect from "expect"` vs. `global.expect`. For that reason I think it's best to keep this iterative and just use modern techniques in new tests, update tests when we reach them, since there's still quite a lot of them using `toEqualJSX` (39)
> chore: modernise some tests

- docgen/src/widgets.md
This is pretty self explanatory, but the URL for the Common Widgets API is incorrect. This PR fixes it.
> Correct invalid URL

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Since https://github.com/algolia/instantsearch-templates we now have a
good way to share code templates while being able to have them in GIT
for easy local development and linking.
> docs(CodeSandbox): link to our CodeSandbox templates

- docgen/src/stylesheets/components/_documentation.sass
**Summary**
See discussion in #2685.
**Result**
Images in the documentation container are restricted to `max-width: 100`.
Let me know if this is not the right way to solve this.
> fix(doc): add maximum width to images (fix #2685)

- docgen/layouts/widget-showcase.pug
- docgen/src/examples/getting-started-boilerplate/index.html
- docgen/src/getting-started.md.hbs
- docgen/src/guides/usage.md.hbs
- package.json
We can reduce the urls we give to users for the JavaScript package by
informing jsDelivr what's the right default file to serve when nothing
provided after the @version.
This is also handy as it does not ties the user and us to a particular
schema to follow over time, if we ever decide to move our build, change
it and rename things, it would be transparent for the user.
For v2 that's "too late" but still good to use it for documentation and
ease of use.
For the theme and style ideally it would be in another package too
("IS.css?" :D)
> chore(pkg): use jsDelivr default file feature

- docgen/CONTRIBUTING.md
- docgen/assets/js/bindRunExamples.js
- docgen/middlewares.js
- docgen/plugins/searchConfig.js
This PR adds support for new frontmatter attributes to run code samples on specific Algolia indices depending on the page you're on.
*EDIT: as frontmatter attributes are not documented anywhere, I added a contributing guide explaining what each of them is used for.*
Code snippets in the documentation can be run when we detect some patterns like `/widgets.(\S+)\(/g`. They are run on a hard coded Algolia index called `instant_search` on the `latency` app ([see code](https://github.com/algolia/instantsearch.js/blob/5cd002b0c2442cc952d59cecab335a55e61cbd35/docgen/assets/js/bindRunExamples.js#L8)).
Sometimes, you'd like your code snippet to be run on another index, or even another app. This is the case for my guide [Create a Calendar Widget](https://github.com/algolia/instantsearch.js/pull/2687 …
> Support search config override per documentation page

- src/components/Template.js
- src/components/__tests__/Template-test.js
- src/components/__tests__/__snapshots__/Template-test.js.snap
- src/lib/__tests__/utils-test.js
- src/lib/utils.js
- src/widgets/search-box/search-box.js
**Summary**
This PR extract the behaviour of the template processing from `<Template>` to `utils`. We can take leverage of the same logic without using the component. It means that non React widget can use the same function for processing the template (ex: SearchBox, Geo).
Still some questions about the usage of `compileOptions`. We do not provide a way to override it properly from `InstantSearch` except:
```js
const search = instantsearch(...)
search.templateConfig.compileOptions = { ... }
```
I didn't find any documentation / issue on the subject , so maybe get rid of this option in the next major release. It will also simplify the `prepareTemplates` function.
> refactor: move Hogan logic to utils

- src/components/Template.js
- src/components/__tests__/Template-test.js
- src/components/__tests__/__snapshots__/Template-test.js.snap
**Summary**
With the current implementation the `<Template>` is always wrapped with a `<div>` element. But in some cases it can lead to incorrect DOM nesting. e.g. When we use the `<Template>` inside a `<label>` or a `<button>` the `<div>` element is forbidden inside those elements. 
By providing a `rootTagName` props we can specify which element the root will be. In the previous example we can use a `<span>` since it's a valid child element for `<label>` & `<button>`.
> feat(Template): add props for the tagName

- docgen/assets/js/main.js
- docgen/layouts/connector.pug
- docgen/layouts/mixins/documentationjs/widget-category-showcase.pug
- docgen/layouts/widget.pug
- docgen/plugins/documentationjs-data.js
- docgen/plugins/helpers.js
- docgen/syntaxHighlighting.js
**Summary**
Right now we don't have to possibility to expose static code example in the documentation. We always have the `run` button in header preview. For some cases it might be interesting to support static code example (e.g. GeoSearch - we don't want to load Leaflet in the page just for the connector example). 
This PR adds a new JSDoc annotation called `@staticExample` to allow this kind of example. This annotation behaves the same way as `@example`, except that the example won't have the `run` button. 
Note that for now we don't support both example types at the same time. It works but the structure of the HTML page will be a bit weird since we duplicate the `h2`. We can probably merge them into only one, but lets interate on that when the needs occur.
fixes #2694
> docs: allow static example

- dev/app/builtin/stories/menu.stories.js
- dev/app/builtin/stories/toggle.stories.js
- docgen/layouts/widget.pug
- docgen/plugins/documentationjs-data.js
- src/widgets/analytics/analytics.js
- src/widgets/breadcrumb/breadcrumb.js
- src/widgets/clear-all/clear-all.js
- src/widgets/current-refined-values/current-refined-values.js
- src/widgets/geo-search/geo-search.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/hits-per-page-selector/hits-per-page-selector.js
- src/widgets/hits/hits.js
- src/widgets/infinite-hits/infinite-hits.js
- src/widgets/menu/menu.js
- src/widgets/numeric-refinement-list/numeric-refinement-list.js
- src/widgets/numeric-selector/numeric-selector.js
- src/widgets/pagination/pagination.js
- src/widgets/price-ranges/price-ranges.js
- src/widgets/range-input/range-input.js
- src/widgets/range-slider/range-slider.js
- src/widgets/refinement-list/refinement-list.js
- src/widgets/search-box/search-box.js
- src/widgets/sort-by-selector/sort-by-selector.js
- src/widgets/star-rating/star-rating.js
- src/widgets/stats/stats.js
- src/widgets/toggle/toggle.js
**Summary**
This PR adds a "Live example" section in the documentation of the widgets. You can enable the DevNovel link by adding the annotation: `@devNovel NameOfTheWidgetInDevNovel`.
**Before**
**After**
> docs: add DevNovel link

- dev/app/builtin/stories/geo-search.stories.js
This PR adds an API Key for Google Maps to avoid the service to blocked in DevNovel. The key has some domain restrictions so an external user should not be able to use it.
> fix(GeoSearch): add API Key for Google Maps

- docgen/layouts/connector.pug
**Summary**
In the connectors layout we forgot to pass the `relatedTypes` to the `struct` mixin. This leads to empty types in the documentation.
**Before**
> https://community.algolia.com/instantsearch.js/v2/connectors/connectGeoSearch.html
**After**
> https://deploy-preview-2780--algolia-instantsearch.netlify.com/v2/connectors/connectgeosearch
> fix(docgen): pass the relatedTypes to the struct mixin in connectors layout

- src/connectors/breadcrumb/connectBreadcrumb.js
**Summary**
Use the correct type for the `BreadcrumbItem`.
**Before**
**After**
*Waiting preview...*
> fix(connectBreadcrumb): update typo in property type items

- package.json
- yarn.lock
Apparently 3.3.2 was unpublished.
> chore(deps): rollback enzyme-to-json to 3.3.1

- src/widgets/hierarchical-menu/hierarchical-menu.js
- src/widgets/menu-select/menu-select.js
- src/widgets/menu/menu.js
**Summary**
[*] used to mean "not required", but wasn't very obvious (we had two internal questions about it recently) and wasn't applied everywhere.
**Result**
No more `[*]` in the docs
> docs(tokens): remove [*] which were confusing

- scripts/release.js
The motivation is that conventional changelog is based on tags to generate the latest changelog. The problem is that in our new setup we have two concurrent versions that could add to the changelog. If both did (2.x and develop) then when you have to merge and you will end with interlaced releases because of the data sorting. This is messy and the betas don't matter that much for most of the users.
The proposal prevents the tags from being done so that we ensure that we have a nice automatic changelog for actual releases. Beta releases will still be comited, and we will be able to see them.
> chore: publish beta without tags

- dev/app/init-unmount-widgets.js
- src/connectors/breadcrumb/connectBreadcrumb.js
- src/widgets/breadcrumb/breadcrumb.js
**Summary**
I got errors while implementing this widget in Vue InstantSearch, so I assume this widget was merged after the adding of `unmountFn`/`dispose`. 
I checked all other connectors, and this was the only one with this missing
**Result**
1. added `unmountFn`
2. nothing at all
There's no implementation of the dispose, since you could imagine someone not showing the breadcrumb anymore, but it's acting on the same info as the hierarchical menu, and you don't want to unrefine that one when you only want to stop showing the breadcrumb
> fix(connectBreadcrumb): allow unmounting

- scripts/release.js
These kind of scripts better have `shell.echo` to give info for consistency and eslint complaining
this should fix the build
> chore(scripts): make sure there's no `console`

- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/geo-search.js
**Summary**
With the current implementation the widget doesn't remove the component when the dispose function is called. This PR fixes the issue by providing an unmount function to the widget that unmount the component created by `preact` & remove all the children of the container.
> fix(GeoSearch): correctly unmount the widget

- src/connectors/geo-search/__tests__/connectGeoSearch-test.js
- src/connectors/geo-search/connectGeoSearch.js
**Summary**
Right now there are two issues with the connector when the `dispose` function is called. The first one is that the parameter `insideBoundingBox` is not reset. The second one is that we always reset the parameters on the provided `state` argument instead of resetting the parameters on the new created value. It means that only the latest call will be reflected on the `SearchParameters`.
The PR fixes those two issues.
> fix(connectGeoSearch): correctly dispose the connector

- package.json
- yarn.lock
This was because rheostat (our preact version) was using incompatible
versions from ours (preact and preact-compat). 
This PR makes sure that we are using the same exact version as the min.
for rhoestat in order to end up with the same dependencies when resolving
the dependencies.
> fix(rangeSlider): handles were blocked

- src/lib/InstantSearch.js
I'm using the `removeWidget` API for Angular InstantSearch when the app need to unmount a widget.
If the page is unmounting all the widgets, it will call `removeWidget()` for every widget present on the page and this will result of make multiple requests to Algolia even thought we are unmounting the whole page.
In order to workaround this issue, I'm deferring the execution of the condition `this.widgets.length > 0` on the next tick so every widgets would have been removed.
This is an easy-fix for now until we can maybe think about a better API with InstantSearch core 👍
> fix(removeWidget): check for widgets.length on next tick

- dev/app/builtin/stories/pagination.stories.js
- src/widgets/pagination/pagination.js
**Summary**
Close #2864 
I also removed the default value for the padding in the widget since we already have it in the connector. No need to have this information twice.
**Before**
**After**
See the results on [DevNovel](url).
> fix: pagination padding

- dev/app/builtin/stories/geo-search.stories.js
- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/geo-search-test.js
**Summary**
On the current implementation of the GeoSearch there is an issue when there are no results. The map will not move on the first time when you click the zoom button. It's because we don't check that the map has moved (or not) when we trigger the initial position. The PR fixes this issue.
**Before**
**After**
You can also try it in [DevNovel](https://deploy-preview-2870--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=GeoSearch.without%20results).
> fix(geosearch): avoid reset map when it already moved

- docgen/package.json
fix #2863 
Renovate is lost when two package.json have configuration for it.
> chore(renovate): fix config

- src/lib/routers/history.js
- src/lib/stateMappings/simple.js
The API between createURL and parseURL was not symetric. Also it add too much parameters for it to be nice.
> fix(history): provide location and use named parameters

- CONTRIBUTING.md
- docgen/src/data/communityHeader.json
- docgen/src/examples/calendar-widget/app.js
- docgen/src/examples/e-commerce/search.js
- docgen/src/examples/media/search.js
- docgen/src/examples/tourism/search.js
- docgen/src/guides/no-result.md
- docgen/src/guides/routing.md
- src/lib/InstantSearch.js
- src/lib/main.js
This PR includes:
- the `routing` guide, [review it live](https://deploy-preview-2879--algolia-instantsearch.netlify.com/v2/guides/routing.html)
- deprecation of the urlSync option via console.warn
- minor change to CONTRIBUTING for dev on examples
- routing for all examples (simple one)
- minor fix for no-results guide
> docs(routing): add a routing guide

- src/lib/RoutingManager.js
- src/lib/__tests__/RoutingManager-test.js
When using the `searchFunction`, the URL should be updated if it adds some parameters during the execution of this function. This was done, but the stateMapping was not applied which lead to initial non-expected URLs.
>  fix(routing): should apply stateMapping when doing initial write

- docgen/layouts/instantsearch.pug
- docgen/src/stylesheets/vendors/bootstrap/_code.scss
- src/lib/InstantSearch.js
- src/lib/main.js
I fixed some inconsistencies I went through when reading the [InstantSearch API](https://community.algolia.com/instantsearch.js/v2/instantsearch.html) page.
* Deprecate `urlSync`
* Add a CSS rule to avoid empty `code` tags to display ([see "widget" here](https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-addWidget)).
> docs(api): Rewrite some content on the InstantSearch API page

- docgen/src/data/communityHeader.json
- docgen/src/guides/prepare-for-v3.md
- docgen/src/guides/routing.md
This PR adds the guide "[Prepare for v3](https://deploy-preview-2905--algolia-instantsearch.netlify.com/v2/guides/prepare-for-v3.html)" to ease the migration towards InstantSearch 3 with search clients.
> docs(guide): Add guide "Prepare for v3"

- docgen/assets/js/main.js
- docgen/layouts/archetypes/content-with-menu.pug
This PR improves the GitHub issue template when a user opens an issue clicking on the "[Open an issue](https://github.com/algolia/instantsearch.js/issues/new?title=Question%20on%20the%20page%20%22Customize%20widgets%22&body=Hi!%20I%20have%20a%20documentation%20issue%20on%20InstantSearch.js.%20I%20could%20not%20find%20what%20I%20was%20looking%20for%20on%20the%20page%20%22[Customize%20widgets](https://community.algolia.com/instantsearch.js/v2/guides/customization.html)%22.%0A%0A%3C!--%20Describe%20what%20you%27re%20looking%20for%20here.%20--%3E&labels=Doc:%20question)" link on the documentation website.
* The `title` has been retrieved from the article frontmatter
* The page location has been retrieved in JavaScript with `window.location.href`
* The new label `Doc: question` has been …
> docs(website): Improve GitHub issue template from documentation link

- docgen/src/getting-started.md.hbs
**Documentation Typo Fix**
It seems that the attributeName for the refinementList widget with the given example is categories instead of category.
> fix attributeName for refinementList widget

- docgen/src/getting-started.md.hbs
The current getting started example will throw a warning about `urlSync` being deprecated in favor of `routing`. This will update the doc to use the `routing` in the examples instead.
> docs(routing): Replace urlSync with routing

- src/connectors/clear-all/__tests__/connectClearAll-test.js
- src/connectors/clear-all/connectClearAll.js
- src/connectors/current-refined-values/__tests__/connectCurrentRefinedValues-test.js
- src/connectors/current-refined-values/connectCurrentRefinedValues.js
- src/lib/__tests__/utils-test.js
- src/lib/utils.js
- src/widgets/clear-all/__tests__/clear-all-test.js
- src/widgets/current-refined-values/__tests__/current-refined-values-test.js
When clearsQuery and excludeAttributes are used together, we can clear the excluded attributes when the query is not empty
http://extra-small-group.surge.sh
- select a brand (note that the clearall button does not activate)
- add some text in the search box (clear all button is activable)
- click clear all
- the query AND the brand are cleared
brand should not be cleared.
The problem is that fixing only this initial bug had an impact on `currentRefinedValues`. Both widget use the same utility function to provide the clear all feature but they have two opposite list system for excluding attributes: one is a white list, and the other a black list.
This patch refactors the utilities, baking the support of the two types of list in a single place. 
A next step for this could be to use a single …
> fix(clear-all): apply excludeAttribute correctly with clearsQuery

- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.js
- src/connectors/infinite-hits/connectInfiniteHits.js
When there is a slow network, the stalled search mechanics will trigger a new render with the same content. This has generally no impact. However the infinite builds up a list of all the results, and there was no mechanics in place to check if the same page has been already received.
To test, you can use dev-novel and with the performance set to slow 3g, you can see that there are no duplicates.
Fix #2928 
Might also be a patch for #2938 (need confirmation)
>  fix(connectInfiniteHits): fix #2928 

- scripts/release.js
NPM doesn't seem to responde to `npm owner add`, this implements
an alternative way to check if the currently logged NPM user is in
the list of contributors on NPM.
> chore(release): fix release script

- dev/app/index.js
- dev/style.css
This PR adds tabs on top of dev-novel so that we can easily switch between the different kinds of stories: built-in widgets, connectors + jQuery, unmountable widgets. Those stories were there, but you had to know the URL in order to access them.
It is [available on the preview](https://deploy-preview-2947--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=Analytics.default)
> docs(dev-novel): add tabs to switch between kinds of stories

- src/widgets/infinite-hits/__tests__/infinite-hits-test.js
- src/widgets/infinite-hits/infinite-hits.js
The infinite hits widget is based internally on the hits widget which
accepts the `allItems` template. However this template is not usable for
the purpose of the infinite hits widget.
In order to prevent users from using this buggy and yet accepted option
this PR generates a exception if we detect this particular template.
Fix #2543
> fix(infinite-hits): throw with allItems

- src/connectors/configure/connectConfigure.js
Before we were merging the full SearchParameters object with the methods on it then firing a new request to Algolia, so the request was wrong.
Now we ensure we only merge the actual state of the search.
cc @Haroenv
> fix(connectConfigure): ensure we do not extend `SearchParameters`

- docgen/src/guides/custom-backend.md
As @olance pointed out, we shouldn't advocate for necessarily normalizing data with a custom backend. The previous example fetched a user's profile based on its ID retrieved from Algolia.
This new example takes advantage of the real-time data on a custom server that Algolia can't always provide: we store the availability of a product on Algolia but retrieve the exact remaining stock on the server.
🔗 [**Link to the section**](https://deploy-preview-2957--algolia-instantsearch.netlify.com/v2/guides/custom-backend.html#going-further-enriching-data-from-the-backend)
> docs(guide): Update example in Custom Backend

- docgen/src/widgets-common-api.md
Some syntax in moustache isn't supported in hogan, so we should add some info that it's really hogan.
> docs(common): add note about mustache/hogan

- src/connectors/refinement-list/__tests__/connectRefinementList-test.js
- src/connectors/refinement-list/connectRefinementList.js
**Summary**
We correctly check display the usage in case of incorrect rendering but not when the provided parameters are wrong. The message is not correctly pass to the function that throw the error.
**Before**
**After**
> fix(connectRefinementList): throw error with usage

- scripts/build.sh
When IS.js is inserted with     <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2"></script>
Then the sourcemap url is not the right one (it was
"instantsearch.min.js.map") now it will be
/dist/instantsearch.min.js.map which will work in every cases.
This will ease a lot debugging live websites.
> fix(sourcemap): provide good url

- src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
- src/connectors/hits-per-page/connectHitsPerPage.js
Fix #2732 
Reproducible here: https://codesandbox.io/s/8qo2m8n89
With the fix: http://splendid-discussion.surge.sh/
Test case:
- select 3 hits per page
- select the empty entry in the menu
- use the searchbox: the search is broken
What you can notice is that the empty value doesn't fall back to the search parameters value. This is because the correct way to set a default value is to use the `default: true` option. We should maybe not support the empty choice (to be discussed)
> fix(connectHitsPerPage): default value should not break the API 

- README.md
- docgen/layouts/example.pug
- docgen/src/guides/usage.md.hbs
- functional-tests/app/index.html
- src/components/Slider/Pit.js
- src/connectors/numeric-refinement-list/connectNumericRefinementList.js
FIX #3001
**Summary**
Demos are broken on IE11 when loading a URL that has priceRanges. Such as:
https://community.algolia.com/instantsearch.js/v2/examples/e-commerce/?priceRanges[price]=1%3A10
**Result**
https://deploy-preview-3021--algolia-instantsearch.netlify.com/v2/examples/e-commerce/?priceRanges%5Bprice%5D=1%3A10
> docs: IE11 support (example + mentions)

- docgen/src/guides/migrate-instantsearchcss.md
- src/components/Stats/Stats.js
- src/components/Stats/__tests__/Stats-test.js
- src/components/Stats/__tests__/__snapshots__/Stats-test.js.snap
- src/widgets/stats/__tests__/__snapshots__/stats-test.js.snap
- src/widgets/stats/defaultTemplates.js
- src/widgets/stats/stats.js
This PR implements:
[Specification](https://instantsearch-css.netlify.com/widgets/stats/)
[Story](https://deploy-preview-3023--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=Stats.default)
> feat(stats): implement is.css

- src/widgets/menu-select/menu-select.js
The documentation considered the `limit` option of the `menuSelect` widget as a `string` although it should be a `number`.
> docs(menuSelect): Change `limit` type to `number`

- dev/app/utils/wrap-with-hits.js
This changes replace the current implementation of the state logger in the dev-novel with a new one using the router.
There is a bug in the logger. This has to be fixed in dev-novel directly.
> docs(dev-novel): use the router for logging state

- package.json
- src/components/CurrentRefinedValues/__tests__/__snapshots__/CurrentRefinedValues-test.js.snap
- src/components/PriceRanges/__tests__/__snapshots__/PriceRanges-test.js.snap
- src/components/__tests__/__snapshots__/MenuSelect-test.js.snap
- src/decorators/__tests__/__snapshots__/headerFooter-test.js.snap
- src/widgets/range-slider/__tests__/__snapshots__/range-slider-test.js.snap
- yarn.lock
- Jest 23 introduces method [`.toHaveBeenNthCalledWith()`](https://jestjs.io/docs/en/expect.html#tohavebeennthcalledwithnthcall-arg1-arg2-) which is handy for our tests ([example of test that can be simplified](https://github.com/algolia/instantsearch.js/blob/e782ab85c348c7c3954eaf113245abebc3885029/src/connectors/clear-all/__tests__/connectClearAll-test.js#L34-L38))
- Jest now ignores `undefined` props in snapshots (facebook/jest#6162)
>  chore(deps): update dependency jest to v23.4.2

- scripts/release.js
When we enforce 2-factor auth on our accounts, NPM will asks for the OTP
which requires an interactive terminal. This is only achievable using
child_process as per the shellJS FAQ: https://github.com/shelljs/shelljs/wiki/FAQ#running-interactive-programs-with-exec
This also reorders the commands so that we can do the rollback without
making the code more complex that it is already.
> fix(release): provide interactive TTY for npm publish

- src/connectors/numeric-refinement-list/connectNumericRefinementList.js
**Summary**
This PR updates the error message that list the `transformItems` prop as required. The other change update the type of the provided items. The item contains a `value` attribute not `start` & `end`.
https://github.com/algolia/instantsearch.js/blob/2c5bfdd2844041226a911cd4f5174387ba3c1405/src/connectors/numeric-refinement-list/connectNumericRefinementList.js#L143-L148
> docs(connectNumericRefinementList): update docs

- src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
- src/connectors/breadcrumb/connectBreadcrumb.js
**Summary**
The current implementation of `connectBreadcrumb` never checked that the `facetValues.data` attribute is an array. But it might happen that this value is `null` (in case of no results for example). Currently the connector throws an error, this PR fixes this issue.
**Before**
**After**
You can test the widget in [DevNovel](https://deploy-preview-3067--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=Breadcrumb.default).
> fix(connectBreadcrumb): ensure that data is an array

- scripts/ci/validate-commit-msgs.sh
**Summary**
We have the test with [semantic-pull-requests](https://github.com/probot/semantic-pull-requests) which takes care of the PR title as well. This test is still useful to see if `develop` has wrong commits for example
**Result**
Don't run our own commit messages check on Travis on PRs
Another option is to remove it all together, but that would only be a good idea if develop is a protected branch (I don't think it is?)
> chore(ci): don't do the commit messages check on a PR

- src/components/Stats/Stats.js
This removes the implementation of shouldComponentUpdate. This can be seen as a regression but given that it's a pretty simple widget, the impact shouldn't be noticeable.
Fix #3056
> fix(Stats): let the widget render on all values

- docgen/src/guides/prepare-for-v3.md
This section documents the move to transformItems in "prepare for v3". It's also a good time to think if we want deprecate all transforrmData? And how?
> docs(transformItems): add a section in prepare for v3

- README.md
The file is named `LICENSE` (I used [Markdown reference links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)).
I detected many more broken links in our Markdown files and documentation website with a tool I'm building. I will try to automate this and take care of fixing them all.
> docs(readme): Fix license link

- CONTRIBUTING.md
Dev Novel is accessible at `/v2/dev-novel` for quite some time, not `/dev-novel`.
> docs(contributing): fix dev-novel link on deploy

- src/connectors/autocomplete/connectAutocomplete.js
Not sure if jsdoc will take this in account, but can be changed if necessary once I see the deploy preview
**Summary**
`indices` on `connectAutoComplete` expects an array of label/value and not a string
> docs(autocomplete): indices is an object array, not a string array

- dev/app/builtin/stories/hits.stories.js
- dev/app/builtin/stories/infinite-hits.stories.js
- dev/app/init-unmount-widgets.js
- docgen/src/guides/v3-migration.md
- src/components/Hits.js
- src/components/InfiniteHits.js
- src/components/__tests__/Hits-test.js
- src/components/__tests__/InfiniteHits-test.js
- src/components/__tests__/__snapshots__/Hits-test.js.snap
- src/components/__tests__/__snapshots__/InfiniteHits-test.js.snap
- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/hits/connectHits.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.js
- src/connectors/infinite-hits/connectInfiniteHits.js
- src/widgets/hits/__tests__/__snapshots__/hits-test.js.snap
- src/widgets/hits/hits.js
- src/widgets/infinite-hits/__tests__/__snapshots__/infinite-hits-test.js.snap
- src/widgets/infinite-hits/__tests__/infinite-hits-test.js
- src/widgets/infinite-hits/infinite-hits.js
* Hits: https://instantsearch-css.netlify.com/widgets/hits/
* InfiniteHits: https://instantsearch-css.netlify.com/widgets/infinite-hits/
> feat(hits): implement InstantSearch.css

- scripts/ci/validate-commit-msgs.sh
Travis puts the PR number, not `"true"` if it's a PR. See: https://docs.travis-ci.com/user/environment-variables/#convenience-variables
> ci(commit-msgs): correct the conditional detecting PRs

- src/components/RangeInput/RangeInput.js
- src/widgets/range-input/__tests__/__snapshots__/range-input-test.js.snap
- src/widgets/range-input/__tests__/range-input-test.js
- src/widgets/range-input/defaultTemplates.js
- src/widgets/range-input/range-input.js
- The widget don't have any templates anymore
- Use `classnames` to concatenate CSS classes
https://instantsearch-css.netlify.com/widgets/range-input/
https://deploy-preview-3128--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=RangeInput.default
> fix(range-input): remove templates to match InstantSearch.css specs

- dev/app/builtin/stories/hits.stories.js
- index.es6.js
- src/helpers/__tests__/snippet-test.js
- src/helpers/index.js
- src/helpers/snippet.js
- src/lib/__tests__/__snapshots__/InstantSearch-test.js.snap
- src/lib/createHelpers.js
- src/lib/main.js
This PR add functionalities to snippet hits without manipulating the Algolia response object (`_snippetResult`). It provides two ways to snippet a hit.
```js
instantsearch.snippet({ attribute, highlightedTagName, hit })
// => <mark class="ais-Snippet-highlighted">Amazon</mark> - Fire TV Stick with Alexa Voice Remote - Black
```
```js
{{#snippet}}{ "attribute": "name", "highlightedTagName": "mark" }{{/snippet}}
// => <mark class="ais-Snippet-highlighted">Amazon</mark> - Fire TV Stick with Alexa Voice Remote - Black
```
[See specs →](https://instantsearch-css.netlify.com/widgets/snippet/)
- [Function](https://deploy-preview-3134--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=Hits.with%20snippet%20function)
- [Helper](https://deploy-preview-3134--algolia-instantsearch.netlify. …
> feat(snippet): implement InstantSearch.css

- src/connectors/numeric-selector/connectNumericSelector.js
Waiting for the netlify build
Conditions of the bug:
- routing
- default undefined value (first one in the list)
Can be reproduced in the dev-novel.
> fix(numericselector): default value can be undefined

- docgen/assets/js/bindRunExamples.js
This PR fixes the `searchConfig` object on the community website when it is `undefined`.
I also took the opportunity to refactor the way we extract the search configuration and made it possible to override the whole object (as it was before).
> fix(community): fix search config

- dev/app/builtin/stories/geo-search.stories.js
- dev/template.html
- docgen/src/guides/v3-migration.md
- src/components/GeoSearchControls/GeoSearchControls.js
- src/components/GeoSearchControls/__tests__/GeoSearchControls-test.js
- src/components/GeoSearchControls/__tests__/__snapshots__/GeoSearchControls-test.js.snap
- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/defaultTemplates.js
- src/widgets/geo-search/geo-search.js
https://instantsearch-css.netlify.com/widgets/geo-search/
https://deploy-preview-3138--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=GeoSearch.default
> feat(GeoSearch): implement InstantSearch.css

- src/lib/__tests__/utils-test.js
- src/lib/utils.js
**Summary**
This PR introduces a function to display warnings on the page only once (cached by message). I didn't update all the usage of `console.warn` across the codebase to avoid conflict with the 3.0 branch. We can move on latter once the next version is released.
> feat(utils): add warn function

- src/lib/__tests__/InstantSearch-test-2.js
**Summary**
For disjunctive requests we need to have two results.
**Before**
**After**
> test(InstantSearch): use two results for disjunctive requests

- dev/app/builtin/stories/hierarchical-menu.stories.js
- src/components/RefinementList/RefinementList.js
- src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/widgets/hierarchical-menu/__tests__/__snapshots__/hierarchical-menu-test.js.snap
- src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
- src/widgets/hierarchical-menu/defaultTemplates.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
This adds the show more feature to the hierachical menu as per the instantsearch.css spec. It does not update the markup and only does the strict minimum in order to have the feature working.
https://deploy-preview-3151--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=HierarchicalMenu.with%20show%20more
> feat(hierarchical-menu): implement show more feature

- src/components/Pagination/Pagination.js
- src/components/Pagination/PaginationLink.js
- src/components/Pagination/__tests__/Pagination-test.js
- src/connectors/pagination/__tests__/connectPagination-test.js
- src/widgets/pagination/__tests__/pagination-test.js
- src/widgets/pagination/pagination.js
- Remove unused `cx()`
- Use functional functional components when possible
- Enforce prop types for class names
- Use Enzyme over React Test Renderer
- Convert Sinon to Jest
> refactor(pagination): refactor widget

- docgen/src/guides/routing.md
Since we don't check for "all", like in the other example, we'd prefer this parameter to go away when not relevant :)
also fix an unclosed "`"
> docs(routing): stateToRoute for brands don't use "all"

- src/components/Breadcrumb/Breadcrumb.js
- src/components/Breadcrumb/__tests__/Breadcrumb-test.js
- src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb-test.js.snap
- src/widgets/breadcrumb/__tests__/__snapshots__/breadcrumb-test.js.snap
- src/widgets/breadcrumb/breadcrumb.js
- src/widgets/breadcrumb/defaultTemplates.js
- Remove unused `cx()`
- Use functional functional components when possible
- Enforce prop types for class names
- Use Enzyme over React Test Renderer
- Convert Sinon to Jest
> refactor(breadcrumb): refactor widget

- dev/app/builtin/stories/geo-search.stories.js
- src/components/GeoSearchControls/GeoSearchControls.js
- src/components/GeoSearchControls/__tests__/GeoSearchControls-test.js
- src/components/GeoSearchControls/__tests__/__snapshots__/GeoSearchControls-test.js.snap
- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/geo-search.js
**Summary**
This PR implements the static map support for the geo-search widget. Previously it was not possible to use the widget for display purpose only. You were always force to use the refinement capabilities of the map. We now have the option `enableRefine` that disable the refinement from the map.
**Result**
You can play with the live example in [DevNovel](https://deploy-preview-3160--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=GeoSearch.with%20refine%20disabled).
> refactor(geo): implement static map [PART-6]

- dev/app/builtin/stories/geo-search.stories.js
- src/components/GeoSearchControls/GeoSearchControls.js
- src/components/GeoSearchControls/__tests__/GeoSearchControls-test.js
- src/components/GeoSearchControls/__tests__/__snapshots__/GeoSearchControls-test.js.snap
- src/connectors/geo-search/__tests__/connectGeoSearch-test.js
- src/connectors/geo-search/connectGeoSearch.js
- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/geo-search.js
**Summary**
This PR implements the routing for the geo-search connector. Here is the shape for the uiState:
```js
const uiState = {
query: 'studio',
geoSearch: {
boundingBox: '10, 12, 12, 14',
},
};
```
We use an object `geoSearch` rather than a direct attribute on the uiState because we may want to persist more information in the future (e.g. `enableRefineOnMapMove`). It's not implemented because it can be inconsistent. The sync with the URL is trigger each time the helper trigger a change event. The click on the Control component doesn't trigger this event. At the end it means that the URL state will be outdated at some point.
**Result**
> refactor(geo): implement routing [PART-5]

- dev/app/builtin/stories/geo-search.stories.js
- src/components/GeoSearchControls/GeoSearchControls.js
- src/components/GeoSearchControls/__tests__/GeoSearchControls-test.js
- src/components/GeoSearchControls/__tests__/__snapshots__/GeoSearchControls-test.js.snap
- src/connectors/geo-search/__tests__/connectGeoSearch-test.js
- src/connectors/geo-search/connectGeoSearch.js
- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/geo-search.js
**Summary**
This PR revamp the GeoSearch renderer to use a "controlled" map. We leverage the provided `currentRefinement` to (almost) always render the map from a bounding box. It simplify a lot the workflow of the widget - we don't rely anymore on complicated conditions to init the position. This refactor also allow us to implement a proper support for the URLSync.
> refactor(geo): implement controlled map [PART-4]

- dev/app/builtin/stories/geo-search.stories.js
- src/components/GeoSearchControls/GeoSearchControls.js
- src/components/GeoSearchControls/__tests__/GeoSearchControls-test.js
- src/components/GeoSearchControls/__tests__/__snapshots__/GeoSearchControls-test.js.snap
- src/connectors/geo-search/__tests__/connectGeoSearch-test.js
- src/connectors/geo-search/connectGeoSearch.js
- src/lib/__tests__/utils-test.js
- src/lib/utils.js
- src/widgets/geo-search/GeoSearchRenderer.js
- src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/geo-search.js
**Summary**
This PR implement the support of `currentRefinement` in the geo-search connector. We now provide the current bounding box to the render function. We can leverage this information to implement a map widget that is "controlled" (i.e. almost always rely on the bounding box to set the map position).
> refactor(geo): implement currentRefinement [PART-3]

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
**Summary**
The current implementation of `addWidgets` **always** trigger a search even without any widgets to add on InstantSearch. We should prevent this behaviour to avoid useless request each time a user call `addWidgets` without anything. 
This issue pops out with a dynamic facetting use case (see example below) - we get an infinite loop because we always call `addWidgets` without checking the length of the widgets to add. It should be the default behaviour.
```js
// We should not have to do this check inside user code
if (addWidgets.length) {
search.addWidgets(addWidgets.map(item => item.widget));
}
```
> https://codesandbox.io/s/nnpvp2x8r4
> fix(InstantSearch): avoid useless search on addWidgets

- src/connectors/breadcrumb/connectBreadcrumb.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/connectors/hits-per-page/connectHitsPerPage.js
- src/lib/utils.js
- src/widgets/hits-per-page/__tests__/hits-per-page-test.js
- src/widgets/pagination/__tests__/pagination-test.js
Use the `warn` utility function instead of the native `console.warn`.
> feat(widgets): use warn utils

- dev/app/builtin/stories/refinement-list.stories.js
- docgen/src/guides/v3-migration.md
- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/widgets/refinement-list/__tests__/__snapshots__/refinement-list-test.js.snap
- src/widgets/refinement-list/__tests__/refinement-list-test.js
- src/widgets/refinement-list/defaultTemplates.js
- src/widgets/refinement-list/defaultTemplates.searchForFacetValue.js
- src/widgets/refinement-list/refinement-list.js
This PR flattens the templates to the top-level `templates` option.
https://instantsearch-css.netlify.com/widgets/refinement-list/
https://deploy-preview-3179--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=RefinementList.default
> feat(refinement-list): implement InstantSearch.css (2)

- docgen/src/guides/v3-migration.md
- src/connectors/index.js
- src/connectors/range-slider/connectRangeSlider.js
`connectRangeSlider` has been deprecated for a long time. The next major version is the opportunity to remove it completely.
> fix(connectRangeSlider): remove deprecated connector

- docgen/src/guides/customization.md
Fix the syntax error when somebody copy & pastes the provided example code.
> docs: add missing plus sign

- docgen/src/guides/migration.md
**Summary**
Changed broken links from `(../widgets` to `(widgets`. For example, [the "hitsPerPageSelector" link in "use the hitsPerPageSelector widget"](https://community.algolia.com/instantsearch.js/v2/guides/migration.html#no-more-hitsperpage-in-hits-and-infinitehits)
**Result**
The link was changed to be similar to [the routing page links](https://github.com/algolia/instantsearch.js/blob/develop/docgen/src/guides/routing.md) that are within the same `src/guides` folder level. For example, [the "searchBox" link under the "User friendly urls" heading](https://community.algolia.com/instantsearch.js/v2/guides/routing.html#user-friendly-urls).
> docs(migration): fix widget links

- dev/app/builtin/stories/current-refined-values.stories.js
- src/connectors/current-refined-values/__tests__/connectCurrentRefinedValues-test.js
- src/lib/__tests__/utils-test.js
- src/lib/utils.js
- src/widgets/current-refined-values/__tests__/__snapshots__/defaultTemplates-test.js.snap
- src/widgets/current-refined-values/__tests__/defaultTemplates-test.js
- src/widgets/current-refined-values/defaultTemplates.js
**Summary**
- added attributeName to fix issue https://github.com/algolia/instantsearch.js/issues/3205 and related
- added tests
- added example showcasing onlyListedAttributes on current-refined-values (maybe unnecessary)
**Result**
> fix(getRefinements): provide attributeName for query

- src/components/InfiniteHits/InfiniteHits.js
- src/components/InfiniteHits/__tests__/__snapshots__/InfiniteHits-test.js.snap
**Summary**
The current implementation invert the condition for the disabled className. I've also updated how we render the button, now we always render the same element only the props change.
**Before**
**After**
> fix(InfiniteHits): correctly set the class for last page

- dev/app/builtin/stories/sort-by.stories.js
- dev/app/init-unmount-widgets.js
- dev/app/jquery/stories/sort-by.stories.js
- docgen/src/guides/v3-migration.md
- src/connectors/sort-by/__tests__/connectSortBy-test.js
- src/connectors/sort-by/connectSortBy.js
- src/widgets/sort-by/__tests__/sort-by-test.js
- src/widgets/sort-by/sort-by.js
For consistency, this renames the `sortBy` items `name` property to `value`.
Related commit in Vue InstantSearch: algolia/vue-instantsearch@be4247149646beba89fcc12d8d26a4c1460a2a3b.
> feat(sortBy): rename item `name` to `value`

- docgen/src/guides/v3-migration.md
- src/components/RangeInput/RangeInput.js
- src/components/RangeInput/__tests__/RangeInput-test.js
- src/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
- src/widgets/range-input/__tests__/__snapshots__/range-input-test.js.snap
- src/widgets/range-input/range-input.js
Related: algolia/instantsearch-specs#92
> fix(range-input): fix button classname

- src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.js
- src/connectors/current-refinements/connectCurrentRefinements.js
- src/lib/utils.js
- src/widgets/current-refinements/__tests__/__snapshots__/current-refinements-test.js.snap
This removes the alphabetic sorting of refinements in CurrentRefinement items. The refinements are sorted based on when the user refines them (default behavior).
Note that the CurrentRefinements items sorting is determined by the order of the [`getRefinements` statements](https://github.com/algolia/instantsearch.js/blob/011d47909894837f2c2da5088bc81803135d201b/src/lib/utils.js#L249). The query being lastly added.
The tests ignore the order of the CurrentRefinement items because there's no specifications for that.
> fix(current-refinements): remove alphabetic sorting

- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/hits/connectHits.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.js
- src/connectors/infinite-hits/connectInfiniteHits.js
This applies the items transformation after escaping. It fixes issues when we transform highlighted values.
An example could be that the highlighted value gets uppercased, and therefore changes the default tag `__ais-highlight__` to `__AIS-HIGHLIGHT__` which doesn't get caught by the regex to be replaced by a `mark` tag.
The fix is implemented for both Hits and InfiniteHits connectors.
Closes #3250
> Note: the other connectors apply `transformItems` as last step already.
> fix(hits): transform items after escaping

- docgen/src/getting-started.md.hbs
The original link to the `https://community.algolia.com/instantsearch.js/documentation/` from the `Mustache` word looks strange, this PR changes the link to lead to the Mustache docs instead.
> docs(getting-started): fix mustache link

- docgen/src/guides/routing.md
** Summary **
1. Relative routing does not work as expected because there is `<base href="/v2/" />` at the top.
Added routing.html in the url path to fix it
2.  `#history-router-api` was not the correct anchor. Replaced it with `#instantsearchroutershistory-api`
> fix(docs): fix dead links in routing.html

- docgen/src/getting-started.md.hbs
- docgen/src/guides/usage.md
This adds a warning when using the jsDelivr CDN.
The message was taken from our [official documentation](https://www.algolia.com/doc/tutorials/getting-started/quick-start-with-the-api-client/javascript/?language=javascript#script-tag-using-cdns).
I also renamed `usage.md.hbs` to `usage.md` (`.hbs` was unnecessary).
(`getting-started.md.hbs` remains un-renamed because the documentation build system seems to need a `.hbs` file to compile).
- Getting started: https://deploy-preview-3266--instantsearchjs.netlify.com/v2/getting-started.html#from-a-cdn
- Usage: https://deploy-preview-3266--instantsearchjs.netlify.com/v2/guides/usage.html#directly-in-your-page
> docs: warn jsDelivr usage

- docgen/src/getting-started.md.hbs
- functional-tests/app/app.js
- src/connectors/pagination/connectPagination.js
- src/widgets/pagination/__tests__/__snapshots__/pagination-test.js.snap
- src/widgets/pagination/__tests__/pagination-test.js
- src/widgets/pagination/pagination.js
- storybook/app/init-unmount-widgets.js
- storybook/app/utils/wrap-with-hits.js
This renames the previous `maxPages` to `totalPages` ([see Pagination spec](https://instantsearch-css.netlify.com/widgets/pagination/)).
> fix(pagination): rename `maxPages` to `totalPages`

- src/widgets/breadcrumb/breadcrumb.js
This adds documentation for the `rootPath` option in the `breadcrumb` widget.
> docs(breadcrumb): document `rootPath`

- docgen/src/guides/v3-migration.md
- src/components/Breadcrumb/Breadcrumb.js
- src/components/Breadcrumb/__tests__/Breadcrumb-test.js
- src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb-test.js.snap
- src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
- src/connectors/breadcrumb/connectBreadcrumb.js
- src/widgets/breadcrumb/__tests__/__snapshots__/breadcrumb-test.js.snap
This renames the breadcrumb items `name` property to `label`.
This is the naming we're going for in v3, as well as [the current naming in React InstantSearch](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectBreadcrumb.js#L20).
> fix(breadcrumb): rename item's "name" to "label"

- src/connectors/breadcrumb/connectBreadcrumb.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/connectors/hits-per-page/connectHitsPerPage.js
- src/lib/InstantSearch.js
- src/widgets/hits-per-page-selector/__tests__/hits-per-page-selector-test.js
This is an extension of the PR #3246, removing the prefix `"[Warning]"` from the `console.warn` call (because of redundancy).
This PR is now meant to be merged on `develop`.
> chore(InstantSearch): use warn utility function

- src/components/Breadcrumb/Breadcrumb.js
- src/components/Breadcrumb/__tests__/Breadcrumb-test.js
- src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb-test.js.snap
- src/widgets/breadcrumb/__tests__/__snapshots__/breadcrumb-test.js.snap
- src/widgets/breadcrumb/breadcrumb.js
The CSS class was wrongly named `noRefinement` instead of `noRefinementRoot`.
> fix(breadcrumb): rename noRefinement to noRefinementRoot

- src/widgets/range-input/__tests__/__snapshots__/range-input-test.js.snap
- src/widgets/range-input/range-input.js
- src/widgets/stats/__tests__/__snapshots__/stats-test.js.snap
- src/widgets/stats/stats.js
- storybook/app/builtin/stories/range-input.stories.js
- storybook/app/builtin/stories/range-slider.stories.js
This removes the remaining `collapsible` options in the widgets `rangeInput` and `stats`, as well as stories using `collapsible`.
The `clearRefinements` widget remains untouched because it will be addressed in another PR.
> fix(widgets): remove `collapsible` option

- docgen/src/guides/v3-migration.md
- src/components/InfiniteHits/InfiniteHits.js
- src/components/InfiniteHits/__tests__/InfiniteHits-test.js
- src/components/InfiniteHits/__tests__/__snapshots__/InfiniteHits-test.js.snap
- src/widgets/infinite-hits/__tests__/__snapshots__/infinite-hits-test.js.snap
- src/widgets/infinite-hits/__tests__/infinite-hits-test.js
- src/widgets/infinite-hits/defaultTemplates.js
- src/widgets/infinite-hits/infinite-hits.js
- storybook/app/builtin/stories/infinite-hits.stories.js
This moves the `loadMoreLabel` option of the `infiniteHits` widget to `templates.showMore`.
https://deploy-preview-3300--instantsearchjs.netlify.com/stories/?selectedStory=InfiniteHits.default
> fix(infiniteHits): move `loadMoreLabel` option to templates

- docgen/src/guides/v3-migration.md
- index.es6.js
- src/lib/__tests__/main-test.js
- src/lib/main.js
This wasn't used for anything, nor documented, so can safely be removed. I didn't document that you can import it directly from the helper, since we don't plan to keep that long-term.
I added it to the migration guide
BREAKING CHANGE
> chore(url): remove createQueryString

- docgen/src/guides/v3-migration.md
1. heading level for the new/old usage inside InstantSearch section
2. add frontmatter to make it show up on the right places on the website
3. some typos I spotted
4. syntax highlighting
see /v2/guides/v3-migration.html for the difference
> docs(migration): some fixes

- docgen/src/guides/v3-migration.md
- src/components/ToggleRefinement/ToggleRefinement.js
- src/connectors/toggleRefinement/__tests__/connectToggleRefinement-test.js
- src/connectors/toggleRefinement/connectToggleRefinement.js
- src/widgets/toggleRefinement/__tests__/__snapshots__/currentToggle-test.js.snap
- src/widgets/toggleRefinement/toggleRefinement.js
- storybook/app/builtin/stories/toggleRefinement.stories.js
> The default template uses the `name` attribute but it’s not provided to the template. It renders something blank on the page. We should find a “good“ default value or we make the `template.labelText` required. Previously it was to the label that was a required option.
> – @samouss 
We pass the attribute (called `name`) to the value passed by the connector `connectToggleRefinement`. The refinement now has a `name` property usable in the template.
If your attribute is called `free_shipping`, the default template will display "free_shipping". You will then need to specify `templates.labelText` to change it to "Free shipping".
https://deploy-preview-3303--instantsearchjs.netlify.com/stories/?selectedStory=ToggleRefinement.default
> fix(toggleRefinement): provide `name` to templates

- .travis.yml
The complex branch patterns for running Travis are unnecessary and make it hard to run the CI on v3 branches.
Closes #3305
> ci: run Travis on all branches

- src/connectors/geo-search/connectGeoSearch.js
`createInternalToggleRefinementonMapMove` -> `createInternalToggleRefinementOnMapMove`, super tiny, but noticed this was autocompleted wrong a while ago
Just making this PR so the branch can be removed
> refactor(GeoSearch): fix typo in name

- docgen/src/guides/v3-migration.md
- src/components/RangeInput/RangeInput.js
- src/components/RangeInput/__tests__/RangeInput-test.js
- src/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
- src/widgets/range-input/__tests__/__snapshots__/range-input-test.js.snap
- src/widgets/range-input/__tests__/range-input-test.js
- src/widgets/range-input/range-input.js
- storybook/app/builtin/stories/range-input.stories.js
This moves the `labels` option to the `templates`:
| Before             | After                     |
| ------------------ | ------------------------- |
| `labels`           | `templates`               |
| `labels.separator` | `templates.separatorText` |
| `labels.submit`    | `templates.submitText`    |
https://instantsearch-css.netlify.com/widgets/range-input/
https://deploy-preview-3312--instantsearchjs.netlify.com/stories/?selectedStory=RangeInput.with%20templates
> fix(rangeInput): convert labels to templates

- src/widgets/search-box/__tests__/search-box-test.js
- src/widgets/search-box/search-box.js
This fixes the issues where the `loadingIndicator` and `reset` templates throw when the nodes cannot be found.
This is now covered by a test by actually rendering the widget.
> fix(searchbox): fix `loadingIndicator` and `reset` templates

- docgen/src/guides/v3-migration.md
- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/__tests__/RefinementList-test.js
- src/components/RefinementList/__tests__/__snapshots__/RefinementList-test.js.snap
- src/widgets/hierarchical-menu/__tests__/__snapshots__/hierarchical-menu-test.js.snap
- src/widgets/hierarchical-menu/defaultTemplates.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
@samouss and I decided to merge `showMoreActive` and `showMoreInactive` by creating a `showMoreText` template which is passed the argument `isShowingMore`.
```js
instantsearch.widgets.hierarchicalMenu({
// ...
templates: {
showMoreActive: 'Show less',
showMoreInactive: 'Show more',
},
});
```
```js
instantsearch.widgets.hierarchicalMenu({
// ...
templates: {
showMoreText: `
{{#isShowingMore}}
Show less
{{/isShowingMore}}
{{^isShowingMore}}
Show more
{{/isShowingMore}}
`,
},
});
```
https://deploy-preview-3318--instantsearchjs.netlify.com/stories/?selectedStory=HierarchicalMenu.with%20show%20more
> feat(hierarchicalMenu): merge showMore templates

- docgen/src/guides/v3-migration.md
- src/widgets/rating-menu/__tests__/__snapshots__/rating-menu-test.js.snap
- src/widgets/rating-menu/__tests__/rating-menu-test.js
- src/widgets/rating-menu/defaultLabels.js
- src/widgets/rating-menu/defaultTemplates.js
- src/widgets/rating-menu/rating-menu.js
- storybook/app/builtin/stories/rating-menu.stories.js
- storybook/app/init-unmount-widgets.js
This merges the labels and the templates for the widget `ratingMenu`.
We now pass the templates to the templates themself to access `templates.andUp`.
> feat(ratingMenu): merge labels and templates

- docgen/src/guides/v3-migration.md
- src/widgets/geo-search/__tests__/__snapshots__/geo-search-test.js.snap
- src/widgets/geo-search/__tests__/geo-search-test.js
- src/widgets/geo-search/defaultTemplates.js
- src/widgets/geo-search/geo-search.js
- storybook/app/builtin/stories/geo-search.stories.js
> The PR **must** be merged before: https://github.com/algolia/instantsearch.js/pull/3319
**Summary**
This PR flatten the template of the `HTMLMarker` inside the `templates` options. It feels a bit odd at first but since we do it in the other widgets it's better to apply the pattern here too. Here is difference in term of usage:
```diff
search.addWidget(
instantsearch.widgets.geoSearch({
// ...
-    customHTMLMarker: {
-       template: `
-        <div class="my-custom-marker">
-          {{price_formatted}}
-        </div>
-      `,
-    },
+    templates: {
+      HTMLMarker: `
+        <div class="my-custom-marker">
+          {{price_formatted}}
+        </div>
+      `,
},
})
);
```
The main difference now is that the widget will use the `HTMLMarker` when:
-  `customHTMLMarker` is …
> refactor(GeoSearch): flatten templates

- docgen/src/guides/v3-migration.md
- src/components/Hits/__tests__/Hits-test.js
- src/connectors/autocomplete/connectAutocomplete.js
- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/hits/connectHits.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.js
- src/connectors/infinite-hits/connectInfiniteHits.js
- src/connectors/refinement-list/__tests__/connectRefinementList-test.js
- src/connectors/refinement-list/connectRefinementList.js
- src/helpers/__tests__/highlight-test.js
- src/helpers/__tests__/snippet-test.js
- src/helpers/highlight.js
- src/helpers/snippet.js
- src/lib/escape-highlight.js
- src/widgets/infinite-hits/__tests__/infinite-hits-test.js
**Summary**
With the current implementation we update the source of the highlight two times:
- the first time is inside the connector where we call `escapeHits` only when `escapeHTML` is provided. This operation replace the placeholder `__ais-highlight__` with the tag `mark` recursively on all the hits.
- the second time is either in user-land or inside the default template with the `highlight` or `snippet` function (though the inline template or a function template). This operation replace the tag `em` with the provided `highlightedTagName`. The issue is at this point we don't have a tag `em` anymore because we replace it the first time with `mark` we escape the value. 
It means that the replace inside `highlight` & `snippet` is never executed. This PR aims to fix this issue. We now have …
> fix(highlight): avoid to ignore highlightedTagName

- docgen/src/guides/v3-migration.md
- src/components/Pagination/Pagination.js
- src/components/Pagination/__tests__/Pagination-test.js
- src/widgets/pagination/__tests__/__snapshots__/pagination-test.js.snap
- src/widgets/pagination/pagination.js
- storybook/app/builtin/stories/pagination.stories.js
This renames `labels` to `templates` in the `pagination` widget for consistency with other widgets.
> feat(pagination): rename labels to templates

- docgen/src/guides/v3-migration.md
- src/widgets/menu/__tests__/__snapshots__/menu-test.js.snap
- src/widgets/menu/defaultTemplates.js
- src/widgets/menu/menu.js
- storybook/app/builtin/stories/menu.stories.js
This implements #3318 for the `menu` widget.
https://deploy-preview-3328--instantsearchjs.netlify.com/stories/?selectedStory=Menu.with%20show%20more%20and%20templates
> feat(menu): merge showMore templates

- src/connectors/index.js
This exports the `connectPoweredBy` connector to users of the library.
> fix(poweredBy): export connectPoweredBy connector

- src/connectors/powered-by/connectPoweredBy.js
- src/widgets/powered-by/powered-by.js
- storybook/app/builtin/stories/powered-by.stories.js
This disables setting the `url` from the widget `poweredBy`, but only from the connector.
> feat(poweredBy): disable setting URL from widget

- src/connectors/configure/__tests__/connectConfigure-test.js
- src/connectors/configure/connectConfigure.js
- src/widgets/configure/configure.js
This makes the render and unmount lifecycle functions optional for the `configure` widget. It's more straightforward to use `connectConfigure`.
> fix(configure): make lifecycle functions optional

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
**Summary**
lodash/forEach was used there I found out by accident, and thought: this one doesn't need to be there!
1. figure out if `this.widgets` is ever an object -> no
2. figure out if `this.widgets` is ever undefined -> no (initialised with empty array)
3. find that the error message on start can not be called -> removed it
expected outcome: tiny bit smaller code 🙏 
**Result**
1. removed impossible warning
2. added new test that proved warning is impossible
3. removed lodash/forEach from that file
> chore(core): remove lodash/foreach from main

- src/widgets/panel/panel.js
The `panel` API reference was missing. The website didn't generate any documentation for the widget.
Documentation: https://deploy-preview-3353--instantsearchjs.netlify.com/widgets/panel.html
> docs(panel): add API reference

- src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
- src/widgets/breadcrumb/breadcrumb.js
The separator used in the records was never overridable from the widget. This passes the `separator` value to the connector.
> feat(breadcrumb): allow custom separators

- src/widgets/geo-search/geo-search.js
This adds `transformItems` documentation for the `geoSearch` widget on the v2 website.
I keep merging the `develop` branch changes to the `v3` so it'll get replicated on the v3 website.
> docs(geoSearch): document transformItems

- src/connectors/hierarchical-menu/__tests__/__snapshots__/connectHierarchicalMenu-test.js.snap
- src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
- src/widgets/hierarchical-menu/hierarchical-menu.js
- storybook/app/builtin/stories/hierarchical-menu.stories.js
- The show more button displays when the option `showMore` is `true`
- `limit` defaults to 10 (no change)
- `showMoreLimit` defaults to 20
- Throw an error if `showMoreLimit <= limit`
>  feat(hierarchicalMenu): update "show more" behavior

- docgen/src/guides/v3-migration.md
- src/connectors/autocomplete/__tests__/connectAutocomplete-test.js
- src/connectors/autocomplete/connectAutocomplete.js
- Rename `escapeHits` to `escapeHTML`
- Default `escapeHTML` to true
> feat(autocomplete): default escapeHTML to true

- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/hits/connectHits.js
- src/widgets/hits/hits.js
This makes `connectHits` `escapeHTML` default to `true` at the connector level rather than at the widget level.
It escapes by default the custom hits user implementations.
> fix(connectHits): default escapeHTML to true

- docgen/layouts/example.pug
- docgen/src/examples/calendar-widget/app.js
- docgen/src/examples/calendar-widget/index.html
- docgen/src/examples/calendar-widget/main.css
- docgen/src/guides/calendar-widget.md
This uses the latest beta version for now (https://cdn.jsdelivr.net/npm/instantsearch.js@beta).
Demo: https://deploy-preview-3351--instantsearchjs.netlify.com/examples/calendar-widget/
> chore(examples): migrate Calendar Widget example

- src/connectors/menu/__tests__/connectMenu-test.js
- src/connectors/menu/connectMenu.js
- src/widgets/menu/__tests__/__snapshots__/menu-test.js.snap
- src/widgets/menu/__tests__/menu-test.js
- src/widgets/menu/menu.js
- storybook/app/builtin/stories/menu.stories.js
Implements #3343 fixes for `menu`.
> fix(menu): update "show more" behavior

- src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
- src/connectors/hits-per-page/connectHitsPerPage.js
The `createURL` parameter was missing from `connectHitsPerPage`.
> feat(hitsPerPage): expose createURL to render function

- src/widgets/panel/panel.js
- storybook/app/builtin/stories/panel.stories.js
All widget's methods need to be bound to not lose the `this` context when called from the `panel` widget.
We need to check the type of the widget's attributes before binding them because some are not methods.
An example of a previously failing widget using `panel` is `ratingMenu`.
Closes #3347.
> fix(panel): bind widget methods from panel

- docgen/layouts/example.pug
- docgen/src/examples/tourism/index.html
- docgen/src/examples/tourism/main.scss
- docgen/src/examples/tourism/search.js
Move the example to `instantsearch.js@3.0.0`. Note that depending the size of the page the map can zoom out. It's a know issue that we have with Google Maps and float dimensions (see [#1737](https://github.com/algolia/react-instantsearch/issues/1737)). It's possible to fix it with fixed (integer) dimension. We gonna try to fix it directly inside the lib but we didn't have the time to take a look yet.
> https://deploy-preview-3373--instantsearchjs.netlify.com/examples/tourism
> feat(tourism): migrate example

- package.json
Although the development bundle is not limited to any size, it's useful to add it to the tracked bundles in order to see how the bundle size changes in PRs compared to the production bundle.
[See result →](https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A92160%2C%22path%22%3A%22.%2Fdist%2Finstantsearch.production.min.js%22%2C%22size%22%3A86482%2C%22compression%22%3A%22gzip%22%2C%22master%22%3A86563%7D%2C%7B%22maxSize%22%3Anull%2C%22path%22%3A%22.%2Fdist%2Finstantsearch.development.js%22%2C%22size%22%3A227360%2C%22compression%22%3A%22gzip%22%7D%5D%2C%22repo%22%3A%22algolia%2Finstantsearch.js%22%2C%22branch%22%3A%22ci%2Fbundlesize-development%22%2C%22commit_message%22%3A%22build(ci)%3A%20run%20bundlesize%20on%20development%20bundle%5Cn%5CnAlthough%20the%20dev …
> build(ci): run bundlesize on development bundle

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
This can not immediately cause any bugs; but in Vue InstantSearch we were manually calling `render` before `init` gets called. Since `render` itself (obviously) assumes the search is already done, it uses helper functions of past-search.
This fix prevents such a situation, since `started` would be false as long as the next search has not yet been done
see also https://github.com/algolia/vue-instantsearch/pull/607
> fix(core): make sure instance.dispose sets started flag

- package.json
There are inconsistencies in how Bundlesize CLI and Bundlesize GitHub integration (showing `NaN`) behave so I added a size limit to the development bundle.
The development bundle will decrease when removing the JSDoc and hopefully increase when we add more warnings.
> chore(bundlesize): set max size for development bundle

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
**Summary**
We recently updated the `dispose` function to set the `helper` to `null`. It's indeed the right approach but it might happen that a `render` occurs after the `dispose` e.g `start` → `dispose` right after the start. The search is async so the render is called after we set the helper to null and it throws an error. To avoid this issue we have to remove the listeners on the helper before we lose his reference.
> fix(InstantSearch): remove event listeners

- src/lib/InstantSearch.js
This is a remaining comment from #1097 that should have been removed some time ago.
It was about an `algoliasearch` import that is not present anymore.
> style(InstantSearch): remove remaining comment on Meteor.js issue

- src/widgets/breadcrumb/__tests__/breadcrumb-test.js
**Summary**
The PR drops the usage of Rewire for the Breadcrumb tests.
> test(Breadcrumb): drop Rewire usage

- src/widgets/clear-refinements/__tests__/__snapshots__/clear-refinements-test.js.snap
- src/widgets/clear-refinements/__tests__/clear-refinements-test.js
**Summary**
The PR drops the usage of Rewire for the ClearRefinements tests.
> test(ClearRefinements): drop Rewire usage

- src/widgets/current-refinements/__tests__/current-refinements-test.js
**Summary**
The PR drops the usage of Rewire for the CurrentRefinements tests.
> test(CurrentRefinements): drop Rewire usage

- src/widgets/hierarchical-menu/__tests__/__snapshots__/hierarchical-menu-test.js.snap
- src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
**Summary**
The PR drops the usage of Rewire for the HierarchicalMenu tests.
> test(HierarchicalMenu): drop Rewire usage

- src/widgets/hits-per-page/__tests__/__snapshots__/hits-per-page-test.js.snap
- src/widgets/hits-per-page/__tests__/hits-per-page-test.js
**Summary**
The PR drops the usage of Rewire for the HitsPerPage tests.
> test(HitsPerPage): drop Rewire usage

- src/widgets/infinite-hits/__tests__/__snapshots__/infinite-hits-test.js.snap
- src/widgets/infinite-hits/__tests__/infinite-hits-test.js
**Summary**
The PR drops the usage of Rewire for the InfiniteHits tests.
> test(InfiniteHits): drop Rewire usage

- src/widgets/stats/__tests__/__snapshots__/stats-test.js.snap
- src/widgets/stats/__tests__/stats-test.js
This removes the usage of Rewire in the Stats tests.
> test(Stats): drop Rewire usage

- src/widgets/sort-by/__tests__/__snapshots__/sort-by-test.js.snap
- src/widgets/sort-by/__tests__/sort-by-test.js
This removes the usage of Rewire in the SortBy tests.
> test(SortBy): drop Rewire usage

- src/widgets/range-slider/__tests__/__snapshots__/range-slider-test.js.snap
- src/widgets/range-slider/__tests__/range-slider-test.js
This removes the usage of Rewire in the RangeSlider tests.
> test(RangeSlider): drop Rewire usage

- src/widgets/toggleRefinement/__tests__/__snapshots__/toggleRefinement-test.js.snap
- src/widgets/toggleRefinement/__tests__/toggleRefinement-test.js
This removes the usage of Rewire in the ToggleRefinement tests.
I also renamed the file `currentToggle-test.js` → `toggleRefinement-test.js`.
> test(ToggleRefinement): drop Rewire usage

- src/widgets/hits/__tests__/__snapshots__/hits-test.js.snap
- src/widgets/hits/__tests__/hits-test.js
**Summary**
The PR drops the usage of Rewire for the Hits tests.
> test(Hits): drop Rewire usage

- src/widgets/menu-select/__tests__/menu-select-test.js
**Summary**
The PR drops the usage of Rewire for the MenuSelect tests.
> test(MenuSelect): drop Rewire usage

- src/widgets/numeric-menu/__tests__/__snapshots__/numeric-menu-test.js.snap
- src/widgets/numeric-menu/__tests__/numeric-menu-test.js
**Summary**
The PR drops the usage of Rewire for the NumericMenu tests.
> test(NumericMenu): drop Rewire usage

- src/widgets/powered-by/__tests__/powered-by-test.js
**Summary**
The PR drops the usage of Rewire for the Breadcrumb tests.
> test(PoweredBy): drop Rewire usage

- src/widgets/menu/__tests__/menu-test.js
**Summary**
The PR drops the usage of Rewire for the Menu tests.
> test(Menu): drop Rewire usage

- src/widgets/rating-menu/__tests__/__snapshots__/rating-menu-test.js.snap
- src/widgets/rating-menu/__tests__/rating-menu-test.js
This removes the usage of Rewire in the RatingMenu tests.
> test(RatingMenu): drop Rewire usage

- .babelrc
- package.json
- yarn.lock
**Summary**
The PR drops the Rewire plugin from the Babel configuration and dependencies.
> chore: drop Rewire

- src/components/CurrentRefinements/CurrentRefinements.js
- src/components/CurrentRefinements/__tests__/CurrentRefinements-test.js
- src/connectors/current-refinements/connectCurrentRefinements.js
- src/widgets/current-refinements/__tests__/__snapshots__/current-refinements-test.js.snap
**Summary**
The reason why you'd want a key like this is if you e.g. want to rename a single key or transform all keys to be upper case, without actually changing which attribute will be changed.
**Result**
A new root key `label`, this will always be identical to the attribute, and will be the thing which will be displayed.
> feat(connectCurrentRefinements): add a root label (PART 1)

- src/connectors/toggleRefinement/__tests__/connectToggleRefinement-test.js
- src/connectors/toggleRefinement/connectToggleRefinement.js
**Summary**
If `off` is passed a falsy value, before this change the helper would store the string "undefined", instead of the actual falsy value.
This behaviour likely broke in v2 -> v3, since with v2 this works.
**Result**
1. check wether `widgetParams#on` and `widgetParams#off` are possible values (not undefined), instead of doing a ternary on their value
2. added new tests for this behaviour
The new "(falsy)" tests fail without my change.
This should be released in a patch before Vue InstantSearch stable releases 👍
> fix(connectToggleRefinement): keep user provided, but falsy values

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/__tests__/__snapshots__/search-client-test.js.snap
This updates the `InstantSearch` errors, links to the new documentation and add tests.
> fix(instantsearch): update usage errors

- src/widgets/search-box/search-box.js
The `unmount` function in the `searchBox` widget wasn't updated correctly since we moved the component to Preact.
This is a remaining of #3489.
> fix(searchbox): unmount component on dispose

- global.d.ts
This replicates the `__DEV__` global set by ESLint for TypeScript files.
> chore(typescript): declare environment globals

- src/types/connector.ts
- src/types/index.ts
- src/types/instantsearch.ts
- src/types/widget.ts
> This is the 1st PR in the series "Merchandized Query Rules".
This adds basic InstantSearch types necessary for the `connectQueryRules` connector.
These types are meant to be completed over time.
> chore(types): add basic InstantSearch types

- src/components/Panel/Panel.js
- src/components/Panel/__tests__/Panel-test.js
- src/widgets/panel/__tests__/panel-test.js
- src/widgets/panel/panel.js
- stories/panel.stories.js
**Summary**
There's an issue where Preact loses the `bodyRef` ref when the widget re-renders because it cleans the tree. This issue exists with both `preact` and `preact-compat` (version < `10.0.0`) but not with `react` (tested by @samouss).
This problem makes the collapsible option impossible to implement in the panel. It also causes other issues:
- [Go to this sandbox](https://codesandbox.io/s/2379j3jv2n)
- Decrease the max price
- Select a filter (e.g. "Machine Washable")
The input range width loses the reference of its container.
**Result**
This solution doesn't rely on `ref`s but on plain DOM manipulation. It inserts the body when the Preact component is mounted.
Note that this solution inserts another `div` inside `div.ais-Panel-body` (this is a recurring issue encountered in the …
> fix(panel): append panel body as a child element

- src/connectors/current-refined-values/connectCurrentRefinedValues.js
Closes #3237.
This documentation fix only targets the v2 documentation website. Will be fixed when we decide to deploy it.
> docs(connectCurrentRefinedValues): fix example with find method

- .travis.yml
- src/lib/utils/capitalize.ts
- src/lib/utils/documentation.ts
- src/lib/utils/prefixKeys.ts
I realized that the CI matrix scripts run with `yarn` were not actually executed since #3481 (for two weeks)... Quotes are needed for the scripts to be run (it ran only `yarn`).
I linted the files that didn't pass at the same time.
Once this PR is merged, please rebase/merge your PRs against `develop` so that CI checks are effective again.
_Lesson to self: always check the CI tests when the configuration changes, even when they pass._
:facepalm:
> build(travis): fix matrix scripts

- src/lib/InstantSearch.js
- src/lib/__tests__/InstantSearch-test.js
**Summary**
Update the UA from `instantsearch.js ${version}` to `instantsearch.js (${version})`
> fix(ua): Update the User-Agent to use the new format

- src/lib/utils/checkRendering.ts
- src/widgets/index.js
- src/widgets/query-rule-context/__tests__/query-rule-context-test.ts
- src/widgets/query-rule-context/query-rule-context.tsx
- stories/query-rule-context.stories.ts
_This is the 3rd PR in the series "Merchandized Query Rules"._
This **headless** widget sets the rule contexts (called [`ruleContexts`](https://www.algolia.com/doc/api-reference/api-parameters/ruleContexts/)) of the search parameters based on the filters.
Query rules are by default _generic_ when not provided any context. If you provide a context, they become _contextual_ and are only triggered when the context is matched.
```js
instantsearch.widgets.queryRuleContext({
container,
trackedFilters: {
genre: () => ['Thriller', 'Drama'],
},
});
```
This will set the following `ruleContexts` dynamically:
- `ais-genre-Thriller`
- `ais-genre-Drama`
> `object` – no default
The filters to track to add rule contexts.
> `string[] ⇒ string[]` – defaults to identity function
The function to apply to …
> feat(queryRules): add queryRuleContext widget

- src/connectors/query-rules/__tests__/connectQueryRules-test.ts
- src/connectors/query-rules/connectQueryRules.ts
- src/lib/utils/getRefinements.ts
- src/widgets/index.js
- src/widgets/query-rule-context/__tests__/query-rule-context-test.ts
- src/widgets/query-rule-context/query-rule-context.tsx
- stories/query-rule-context.stories.ts
This adds context-related features to the `connectQueryRules` connector. This allows to set rule contexts (called `ruleContexts`) of the search parameters based on active filters.
Query rules are by default _generic_ when not provided any context. If you provide a context, they become _contextual_ and are only triggered when the context is matched.
<p align="center">
</p>
This interface can create the following rules:
- `ais-rating-4`
- `ais-rating-5`
- `ais-brand-Samsung`
- `ais-brand-Apple`
The maximum number of rule contexts handled by the engine is 10. Above that limit, the engine returns an error because it slows down data processing. The connector therefore slices the number of rules created to 10.
The `trackedFilters` option sets rules for the specified filters. If the user refines …
> feat(queryRules): add context features to connectQueryRules

- src/lib/RoutingManager.js
**Summary**
This PR removes dead code inside the `RoutingManager`. Here is the changes:
- [L66-72](https://github.com/algolia/instantsearch.js/blob/ca8ae5018b93b98e663b623c2ba829b01a7f2861/src/lib/RoutingManager.js#L66-L71): It was previously used inside the [`URLSync`](https://github.com/algolia/instantsearch.js/blob/v2.10.4/src/lib/url-sync.js#L164-L169) implementation to avoid useless search + render. Inside the previous implementation, it was working fine because both values were objects ([`getState`](https://github.com/algolia/algoliasearch-helper-js/blob/eafd4cfd3e78b49bb5425784bab413f0702cbc04/src/algoliasearch.helper.js#L819-L821) with a filter function returns a plain object). With the `routing` system it's not the case. We compare a plain object with an instance of …
> refactor(RoutingManager): remove dead code

- src/lib/RoutingManager.js
- src/lib/__tests__/RoutingManager-test.js
**Summary**
Closes https://github.com/algolia/instantsearch.js/issues/3497
This PR aims to fix the issue related to the stale `uiState` inside the `RoutingManager` (see the issue for more information). Previously the state was only captured at the creation of the manager and never updated. Now we update it each time an update occurs (state change, router update). It means that now once a widget is added/removed the lifecycle read the up to date `uiState`.
**Before**
**After**
> fix(RoutingManager): avoid stale uiState

- src/components/QueryRuleCustomData/QueryRuleCustomData.tsx
- src/components/QueryRuleCustomData/__tests__/QueryRuleCustomData-test.tsx
- src/components/QueryRuleCustomData/__tests__/__snapshots__/QueryRuleCustomData-test.tsx.snap
- src/components/Template/Template.js
- stories/query-rule-context.stories.ts
- stories/query-rule-custom-data.stories.ts
The `QueryRuleCustomData` component passed the `items` as an array to users' templates. This made them unusable with Hogan. By passing `items` within an object, they're now accessible.
I added a story to demo how to use Hogan with these widgets.
> fix(QueryRuleCustomData): pass data as object to templates

- src/connectors/query-rules/connectQueryRules.ts
The tracked filters assumed a refinement can be a `number` or a `string`. It can also be a `boolean`.
See:
- https://github.com/algolia/react-instantsearch/pull/2258/files#diff-61853eb4221589c33badeb16d8725534R12
- https://github.com/algolia/angular-instantsearch/pull/483#discussion_r271643098
> fix(connectQueryRules): improve tracked refinement type

- src/widgets/query-rule-custom-data/__tests__/query-rule-custom-data-test.ts
- src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
- stories/query-rule-custom-data.stories.ts
This adds a default template to the `queryRuleCustomData` widget. This default template is a JSON dump of the custom data returned by the connector. It can help users understand what data structure to interact with before creating a custom template.
This is the behavior we went for in the [Vue InstantSearch implementation](https://github.com/algolia/vue-instantsearch/pull/652) and in the [Angular InstantSearch implementation](https://github.com/algolia/angular-instantsearch/pull/482).
[See story →](https://deploy-preview-3650--instantsearchjs.netlify.com/stories/?path=/story/queryrulecustomdata--without-template)
> fix(queryRuleCustomData): add default template

- package.json
- scripts/jest/config.js
- src/lib/__tests__/RoutingManager-test.js
- src/lib/routers/history.js
- yarn.lock
_This PR is a fix for #3667._
The [`windowTitle`](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/#windowtitle-functionroutestate-string) param of the routing option didn't apply on the first page load. 
I fixed this by setting the document title also in the `RoutingManager` constructor, based on the URL query parameters which represent the route state.
This feature remained untested so I added a test for the first page load.
Note that Jest doesn't support updating `window.location` in tests (see facebook/jest#890 and facebook/jest#5124). I therefore needed to introduce two new JSDom dev dependencies to change `window.location` in separate tests, which give access to `jsdom.reconfigure({ url })`. I believe these dependencies will be needed in the …
> fix(routing): apply windowTitle on first load

- src/components/QueryRuleCustomData/QueryRuleCustomData.tsx
- src/connectors/query-rules/connectQueryRules.ts
- src/widgets/query-rule-context/query-rule-context.tsx
- src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
- stories/query-rule-context.stories.ts
- stories/query-rule-custom-data.stories.ts
Until we have a proper way to provide generic types to InstantSearch.js widgets, the most accurate type that we can provide for items is `any`. The `object` type wasn't correct.
This PR now manipulates the source of the widgets in the stories, which provides typings.
> fix(queryRules): fix types and stories

- src/connectors/current-refinements/connectCurrentRefinements.js
**Summary**
_objectSpread polyfill calls Object.keys() under the hood which on IE11
does not support anything other than objects.
Reason: change in spec
ES5: https://www.ecma-international.org/ecma-262/5.1/#sec-15.2.3.14
> If the Type(O) is not Object, throw a TypeError exception.
ES6: https://www.ecma-international.org/ecma-262/6.0/#sec-object.keys
Uses ToObject, which supports booleans
> Return a new Boolean object whose [[BooleanData]] internal slot is set to the value of argument. See 19.3 for a description of Boolean objects
**Result**
No we are avoiding booleans altogether.
Nothing should change. I'll test this out in IE once it's deployed
> fix(normalizeRefinement): remove boolean values passed to `_objectSpread` in normalizeRefinement

- src/helpers/index.ts
- src/lib/main.js
**Summary**
This is mimicking the way we allow usage for `highlight` and `snippet`.
**Result**
```js
Instantsearch.widgets.hits({
// ...
templates: {
item(hit) {
return `
<h2> ${hit.name} </h2>
<button ${
Instantsearch.insights('clickedObjectIDsAfterSearch', {
eventName: "Add to favorite",
objectIDs: [hit.objectID]
})
}>
Add to favorite
</button>
`;
},
},
});
```
> feat(Insights): expose `insights`  helper on instantsearch instance

- src/types/widget.ts
**Summary**
This fixes the wrong typing of `getWidgetState`.
**Result**
`state` -> `searchParameters` in `widgetStateOptions`.
(https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/js/?language=javascript#the-widget-lifecycle-and-api)
> fix(types): fix wrong typing in getWidgetState

- src/types/utils.ts
The `Without` type is not used and conflicts with `Omit`.
> fix(types): remove unused Without type

- stories/breadcrumb.stories.js
If a separator is chosen which isn't the same as the corresponding hierarchical menu on the page, it will cause a conflict between those, and it will no longer be split correctly.
> fix(storybook): fix Hierarchical menu separator in Breadcrumb story

- package.json
- scripts/release/bump-package-version.js
- scripts/release/publish-maintenance.sh
- scripts/release/publish.js
- yarn.lock
**Summary**
It seems before 92966391b1b2d2870827f164f1046d9a0c544efb the script was run in developement env with no modules setting, which mean it defaulted to the poorly documented `auto`. https://babeljs.io/docs/en/babel-preset-env#modules
Looking at their codebase it seems `auto` is simply `commonjs`.  This explains why it worked before.
https://github.com/babel/babel/blob/8ca99b9f0938daa6a7d91df81e612a1a24b09d98/packages/babel-preset-env/src/module-transformations.js#L6
We could have used BABEL_ENV=cjs in front of the babel-node command but
I've moved this file to cjs as it's more simple and is consistent with
other release scripts.
> fix(tools): use commonjs in bump-package-version.js

- babel.config.js
- package.json
- scripts/rollup/config.js
- yarn.lock
PropTypes were still mostly present in the bundles (both UMD and ES/CJS) despite the usage of the plugin `babel-plugin-transform-react-remove-prop-types`. As opposed to React InstantSearch, there's no reasons to expose PropTypes in our bundles. This PR aims at removing those.
- For the UMD bundle, I introduced the `ignore` Rollup plugin to ignore the `prop-types` package.
- For the ES/CJS bundle, I added `{ removeImport: true }`, which defaults to `false`, to remove all traces of `prop-types` imports ([see documentation](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#removeimport)).
The PropTypes remaining come from [`preact-rheostat`](https://github.com/algolia/rheostat), which will be addressed in a later PR.
**Before the change**
``` …
```
> chore(build): remove PropTypes from builds

- src/connectors/hits-per-page/connectHitsPerPage.js
- src/widgets/hits-per-page/__tests__/hits-per-page-test.js
- stories/hits-per-page.stories.js
I stumbled across this development warning message and couldn't understand it. I tried to rephrase it.
> fix(hitsPerPage): improve warning for missing state value

- src/components/Pagination/Pagination.js
The `defaultsDeep` utility was introduced from the start in fad27202edd27c732b9fba3e8dea024b703d0e2a.
It's not necessary since we rely on React default props and only have shallow default props.
> refactor(lodash): remove defaultsDeep usage

- src/connectors/geo-search/__tests__/connectGeoSearch-test.js
- src/widgets/geo-search/__tests__/geo-search-test.js
This removes the `lodash/first` and `lodash/last` usage.
> refactor(lodash): remove first and last usage

- src/connectors/hits-per-page/connectHitsPerPage.js
This removes `lodash/some` usage.
> refactor(lodash): remove some usage

- src/lib/__tests__/main-test.js
- src/lib/utils/getRefinements.ts
- src/widgets/clear-refinements/__tests__/clear-refinements-test.js
This removes `lodash/forEach` for the native `Array.prototype.forEach` method.
> refactor(lodash): remove forEach usage

- src/connectors/numeric-menu/connectNumericMenu.js
- src/connectors/range/connectRange.js
- src/lib/utils/index.ts
- src/lib/utils/isFiniteNumber.ts
This removes `lodash/isFinite` usage.
> refactor(lodash): remove isFinite usage

- src/lib/utils/isFiniteNumber.ts
This adds documentation for our `isFiniteNumber` util function. This is a polyfill recommended by MDN and we don't test it.
See context: https://github.com/algolia/instantsearch.js/pull/3709#pullrequestreview-229522303.
> refactor(lodash): add documentation for isFiniteNumber

- src/lib/utils/getRefinements.ts
This removes `lodash/get` usage with native JavaScript.
> refactor(lodash): remove get usage

- src/connectors/configure/connectConfigure.js
- src/lib/InstantSearch.js
- src/lib/escape-highlight.ts
- src/lib/utils/__tests__/isPlainObject-test.ts
- src/lib/utils/index.ts
- src/lib/utils/isPlainObject.ts
This removes `lodash/isPlainObject` in favor of our own `isPlainObject` util. I basically copied their implementation because this is the most solid I found while testing it.
> refactor(lodash): remove isPlainObject usage

- src/lib/escape-highlight.ts
- src/lib/utils/prepareTemplateProps.js
This removes `lodash/reduce` usage and uses the native `Array.prototype.reduce` method.
> refactor(lodash): remove reduce usage

- src/lib/insights/client.ts
- src/lib/utils/__tests__/uniq-test.ts
- src/lib/utils/index.ts
- src/lib/utils/prepareTemplateProps.js
- src/lib/utils/uniq.ts
This removes `lodash/uniq` for our own `uniq` util.
> refactor(lodash): remove uniq usage

- src/components/Slider/Slider.js
- src/connectors/pagination/Paginator.js
- src/connectors/pagination/__tests__/connectPagination-test.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/utils/__tests__/range-test.ts
- src/lib/utils/index.ts
- src/lib/utils/range.ts
This removes `lodash/range` and `lodash/times` from the codebase.
I created a single custom `range` util for both functions because `lodash/times` is a subset of `lodash/range`.
I decided to change the `range` function signature to something more clear:
**Before**
`start` and `step` are optional, which makes it confusing because arguments change depending on what's given to the function.
```ts
function range(start = 0, end, step = 1): number[] | undefined;
```
**After**
```ts
type RangeOptions = {
start?: number;
end: number;
step?: number;
};
function range({ start = 0, end, step = 1 }: RangeOptions): number[];
```
> refactor(lodash): remove range and times usage

- src/components/Pagination/PaginationLink.js
- src/components/RefinementList/RefinementList.js
- src/components/RefinementList/RefinementListItem.js
- src/components/Template/Template.js
- src/connectors/breadcrumb/connectBreadcrumb.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/connectors/infinite-hits/connectInfiniteHits.js
- src/connectors/query-rules/connectQueryRules.ts
- src/connectors/refinement-list/connectRefinementList.js
- src/lib/RoutingManager.js
- src/lib/utils/__tests__/isEqual-test.ts
- src/lib/utils/index.ts
- src/lib/utils/isEqual.ts
This removes `lodash/isEqual` usage for our own custom `isEqual` function.
The `isEqual` function takes into account object references, primitive objects and nested objects. This covers all our usages.
> refactor(lodash): remove isEqual usage

- src/lib/utils/renderTemplate.js
This removes `lodash/mapValues` usage from the codebase.
> refactor(lodash): remove mapValues usage

- src/lib/escape-highlight.ts
- src/lib/utils/__tests__/escape-test.ts
- src/lib/utils/escape.ts
- src/lib/utils/index.ts
This removes `lodash/escape` usage from our codebase to use our own util. I basically copied their implementation and their test suite.
> refactor(lodash): remove escape usage

- src/lib/utils/prepareTemplateProps.js
This removes `lodash/keys` usage for the native `Object.keys()` method.
> refactor(lodash): remove keys usage

- src/lib/InstantSearch.js
This removes `lodash/union` usage and uses our own `uniq` function after spreading the arrays.
> refactor(lodash): remove union usage

- src/lib/utils/renderTemplate.js
The `lodash/curry` function was just used to create an indirection in the template helpers required by Hogan.
> refactor(lodash): remove curry usage

- src/components/MenuSelect/MenuSelect.js
- src/connectors/autocomplete/connectAutocomplete.js
- src/connectors/breadcrumb/connectBreadcrumb.js
- src/connectors/hierarchical-menu/connectHierarchicalMenu.js
- src/connectors/hits-per-page/connectHitsPerPage.js
- src/connectors/range/connectRange.js
- src/connectors/sort-by/__tests__/connectSortBy-test.js
- src/connectors/sort-by/connectSortBy.js
- src/connectors/toggleRefinement/connectToggleRefinement.js
- src/lib/insights/client.ts
- src/lib/utils/__tests__/find-test.ts
- src/lib/utils/find.ts
- src/lib/utils/getRefinements.ts
- src/lib/utils/index.ts
- src/widgets/hits-per-page/hits-per-page.js
This removes all `lodash/find` usages. We need to be careful with `undefined` collections being loop over since Lodash used to deal with that for us.
Note that we already use `Array.prototype.find` in the codebase and that we document [using a polyfill to support browsers](https://www.algolia.com/doc/guides/building-search-ui/installation/js/#browser-support).
> refactor(lodash): remove find usage

- src/connectors/range/connectRange.js
We forgot to change the `connectRange` `precision` default value to `0` in v3. This adds a major tag so that we do not forget to update it in the next major version.
> docs(connectRange): tag `precision` option for next major

- src/lib/InstantSearch.js
- src/lib/utils/__tests__/mergeDeep-test.ts
- src/lib/utils/index.ts
- src/lib/utils/mergeDeep.ts
This removes `lodash/mergeWith` usage and introduces a custom `deepMerge` util. It also simplifies the logic of the `enhanceConfiguration` function.
> refactor(lodash): remove mergeWith usage

- docgen/layouts/common/meta.pug
**Summary**
We introduce [the canonical URLs](https://github.com/algolia/instantsearch.js/pull/3576) to keep backlinks to the algolia.com/doc. But it's not enough to make the Community website disappear from the search results. We have to hide them from the search results otherwise it's confusing for users.
> chore: disable canonical link

- src/components/Slider/Pit.js
**Summary**
This adds a missing base to the [`parseInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) function.
**Result**
Before:
After:
> fix(rangeSlider): round the slider pit value

- README.md
I didn't use the official badge (https://pullreminders.com/badge.svg) because it clashed with the others visible on the page.
> docs(readme): add pull reminders badge

- src/lib/RoutingManager.ts
- src/lib/__tests__/RoutingManager-test.js
- src/types/widget.ts
This adds types for the UI state.
> fix(types): improve UiState types

- src/connectors/autocomplete/__tests__/connectAutocomplete-test.js
- src/connectors/clear-refinements/__tests__/connectClearRefinements-test.js
- src/connectors/configure/__tests__/connectConfigure-test.js
- src/connectors/configure/connectConfigure.js
- src/connectors/geo-search/__tests__/connectGeoSearch-test.js
- src/connectors/geo-search/connectGeoSearch.js
- src/connectors/query-rules/__tests__/connectQueryRules-test.ts
- src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
- src/lib/InstantSearch.js
- src/lib/voiceSearchHelper/__tests__/index-test.ts
- src/widgets/query-rule-custom-data/__tests__/query-rule-custom-data-test.ts
Since https://github.com/algolia/algoliasearch-helper-js/pull/707 getState is the same as fetching state, we decided we want to get rid of it. This makes sure InstantSearch will be ready for that change
> refactor(helper): replace .getState() by .state

- src/components/VoiceSearch/__tests__/VoiceSearch-test.tsx
- src/lib/voiceSearchHelper/__tests__/index-test.ts
- src/lib/voiceSearchHelper/index.ts
- src/widgets/voice-search/__tests__/__snapshots__/voice-search-test.ts.snap
- stories/voice-search.stories.ts
**Summary**
This makes the types of the two things non-optional.
* `isSpeechFinal`
* `transcript`
The related discussion is [here](https://github.com/algolia/react-instantsearch/pull/2316#discussion_r283886705)
> fix(types): improve types for voiceSearch

- stories/current-refinements.stories.js
**Summary**
This PR clean the `currentRefinements` stories.
- remove the duplicated widgets
- change the attribute of menu to avoid collision with the `refinementList`
**Result**
Check out the example inside [Storybook](https://deploy-preview-3781--instantsearchjs.netlify.com/stories/?path=/story/currentrefinements--default).
> refactor(currentRefinements): update stories

- src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
- src/connectors/voice-search/connectVoiceSearch.ts
- src/lib/voiceSearchHelper/__tests__/index-test.ts
- src/lib/voiceSearchHelper/index.ts
**Summary**
This removes event listeners attached to SpeechRecognition instance when the widget is disposed.
The related discussion is [here](https://github.com/algolia/react-instantsearch/pull/2316#discussion_r283821410).
**Result**
It shouldn't change any user behaviour.
> fix(voiceSearch): remove event listeners on dispose

- CHANGELOG.md
**Summary**
This merges the changelog of `3.5.0` and `3.5.1`.
Since `3.5.0` has been unpublished, this moves its content to `3.5.1` section.
> docs: merge changelog of 3.5.0 and 3.5.1

- src/connectors/search-box/connectSearchBox.js
- src/connectors/voice-search/connectVoiceSearch.ts
This PR simplify the flow to set a query and trigger a search inside `connectSearchBox` (inside `connectVoiceSearch` too because the implementation is duplicated). Here are the changes:
- drop the usage of `previousQuery`: the value used inside the closure wasn't very useful since it was the value of the previous, previous render. The feature has been introduced [a while ago](https://github.com/algolia/instantsearch.js/pull/1127) when the widget was responsible to manage both: `searchAsYouType` & `searchOnEnter`. We don't support this behavior inside the connector anymore, it's at the renderer level.
- drop support of `doSearch`: the second argument of the `refine` function isn't used anymore, it's not documented either. It has been introduced with [the first connector …
> refactor: simplify logic to setQuery & search

- src/connectors/autocomplete/connectAutocomplete.js
- src/connectors/search-box/__tests__/connectSearchBox-test.js
- src/connectors/search-box/connectSearchBox.js
- src/connectors/stats/__tests__/connectStats-test.js
- src/connectors/stats/connectStats.js
- src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
- src/connectors/voice-search/connectVoiceSearch.ts
- src/lib/__tests__/RoutingManager-test.ts
- src/lib/__tests__/search-client-test.js
- src/types/instantsearch.ts
- src/widgets/analytics/analytics.js
- stories/panel.stories.js
This PR updates the usage of the `query` attribute from the `SearchParameters`. Its value is now optional which implies that we have to fall back on a default value at the connector level. The default value is not always required though, it depends on the use case. I've tried to make as few changes as possible to stick with the current behavior.
> refactor(helper): update query usage [PART-6]

- src/connectors/autocomplete/connectAutocomplete.js
- src/connectors/geo-search/connectGeoSearch.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
- src/connectors/infinite-hits/connectInfiniteHits.ts
- src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
- src/connectors/numeric-menu/connectNumericMenu.js
- src/connectors/pagination/__tests__/connectPagination-test.js
- src/connectors/pagination/connectPagination.js
- src/connectors/search-box/__tests__/connectSearchBox-test.js
- src/connectors/search-box/connectSearchBox.js
- src/connectors/stats/__tests__/connectStats-test.js
- src/connectors/stats/connectStats.js
- src/connectors/toggleRefinement/connectToggleRefinement.js
- src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
- src/connectors/voice-search/connectVoiceSearch.ts
- src/lib/__tests__/RoutingManager-test.ts
- src/lib/__tests__/search-client-test.js
- src/types/instantsearch.ts
- src/widgets/analytics/analytics.js
- src/widgets/infinite-hits/__tests__/infinite-hits-test.ts
- src/widgets/pagination/__tests__/pagination-test.js
- stories/panel.stories.js
This PR updates the usage of the `page` attribute from the `SearchParameters`. Its value is now optional which implies that we have to fall back on a default value at the connector level. The default value is not always required though, it depends on the use case. I've tried to make as few changes as possible to stick with the current behavior.
> The CI does not pass, it's expected. It won't pass until the last PR of the stack.
> refactor(helper): update page usage [PART-5]

- src/connectors/autocomplete/connectAutocomplete.js
- src/connectors/geo-search/connectGeoSearch.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
- src/connectors/infinite-hits/connectInfiniteHits.ts
- src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
- src/connectors/numeric-menu/connectNumericMenu.js
- src/connectors/pagination/__tests__/connectPagination-test.js
- src/connectors/pagination/connectPagination.js
- src/connectors/query-rules/connectQueryRules.ts
- src/connectors/search-box/__tests__/connectSearchBox-test.js
- src/connectors/search-box/connectSearchBox.js
- src/connectors/stats/__tests__/connectStats-test.js
- src/connectors/stats/connectStats.js
- src/connectors/toggleRefinement/connectToggleRefinement.js
- src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
- src/connectors/voice-search/connectVoiceSearch.ts
- src/lib/InstantSearch.js
- src/lib/RoutingManager.ts
- src/lib/__tests__/InstantSearch-test-integration.js
- src/lib/__tests__/InstantSearch-test.js
- src/lib/__tests__/RoutingManager-test.ts
- src/lib/__tests__/search-client-test.js
- src/types/instantsearch.ts
- src/widgets/analytics/analytics.js
- src/widgets/infinite-hits/__tests__/infinite-hits-test.ts
- src/widgets/pagination/__tests__/pagination-test.js
- stories/panel.stories.js
This PR updates how we subscribe/use the listeners on the Helper. We moved away from [a list of arguments to an object](https://github.com/algolia/algoliasearch-helper-js/pull/700). The PR address those changes on the listeners. It also updates how the `error` event is emitted at the InstantSearch level. It now to match the shape of the Helper.
```js
// With list of arguments
search.on('error', error => {
console.log(error);
});
// With an object
search.on('error', event => {
console.log(event.error);
});
```
> The CI does not pass, it's expected. It won't pass until the last PR of the stack.
> refactor(helper): update listeners [PART-4]

- src/lib/utils/isPlainObject.ts
IE11: global `toString` can not be called as `Object.prototype.toString`, so we need to use the Object version, like done in lodash (not doing this initially was likely a simple omission)
fixes #3814 
references: 
- https://github.com/lodash/lodash/pull/4115 (remove core-js to test more regular code)
- https://github.com/lodash/lodash/blob/master/.internal/getTag.js#L1
> fix(getTag): use object version of toString

- src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
- src/connectors/hits-per-page/connectHitsPerPage.js
This PR fix the implementation of the `dispose` method for the connector `connectHitsPerPage`. It omits `hitsPerPage` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectHitsPerPage): clear the state on dispose

- src/connectors/autocomplete/__tests__/connectAutocomplete-test.js
- src/connectors/autocomplete/connectAutocomplete.js
This PR fix the implementation of the `dispose` method for the connector `connectAutocomplete`. It omits `query` & `highlightTags` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectAutocomplete): clear the state on dispose

- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/hits/connectHits.js
This PR fix the implementation of the `dispose` method for the connector `connectHits`. It omits `highlightTags` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectHits): clear the state on dispose

- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
- src/connectors/infinite-hits/connectInfiniteHits.ts
This PR fix the implementation of the `dispose` method for the connector `connectInfiniteHits`. It omits `page` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectInfiniteHits): clear the state on dispose

- src/connectors/pagination/__tests__/connectPagination-test.js
- src/connectors/pagination/connectPagination.js
This PR fix the implementation of the `dispose` method for the connector `connectPagination`. It omits `page` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectPagination): clear the state on dispose

- src/connectors/search-box/__tests__/connectSearchBox-test.js
- src/connectors/search-box/connectSearchBox.js
This PR fix the implementation of the `dispose` method for the connector `connectSearchBox`. It omits `query` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectSearchBox): clear the state on dispose

- src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
- src/connectors/voice-search/connectVoiceSearch.ts
This PR fix the implementation of the `dispose` method for the connector `connectVoiceSearch`. It omits `query` once the widget is removed. I also cover the rest of the `dispose` function with tests.
> feat(connectVoiceSearch): clear the state on dispose

- src/connectors/voice-search/connectVoiceSearch.ts
- src/widgets/voice-search/voice-search.tsx
**Summary**
This PR lets the connector handle the default value of `searchAsYouSpeak` when it's not given.
(The default value was given at the widget phase before).
Related to [this](https://github.com/algolia/angular-instantsearch/pull/530#discussion_r286278985)
> fix(voiceSearch): connector handles default value of searchAsYouSpeak

- src/connectors/sort-by/__tests__/connectSortBy-test.js
- src/connectors/sort-by/connectSortBy.js
- src/widgets/sort-by/__tests__/sort-by-test.js
> This PR closes #3397.
The `sortBy` connector used to throw an error when the current index wasn't listed in the `items` of the widget.
This broke some users' apps when using `routing`. If users type a URL with a wrong index name for the `sortBy` widget, it will throw straight away and break the InstantSearch lifecycle.
This PR removes the error thrown and rathers warns only in development. The initial index (from the helper) is used if that happens.
I slightly changed the implementation because we were relying on the InstantSearch instance index (`instantSearch.indexName`) and now use the helper index (`helper.getIndex()`). This shouldn't break anything and is more consistent within the connector.
The deleted tests in the widget are now covered in the connector.
> fix(connectSortBy): do not throw with wrong indexes

- src/connectors/hits/__tests__/connectHits-test.js
- src/connectors/hits/connectHits.js
- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
- src/connectors/infinite-hits/connectInfiniteHits.ts
When mapping over an array, extra non-enumerable properties don't get copied into the new array. This means that the `__escaped` gets removed due to transformItems, or addAbsolutePosition.
We fix this by setting that mark back just before calling the render function. We want transformItems to happen after escaping, so it's no option to put the mark before.
Note also that if we would put the escaping before, we would still need to capture the marker, since it will be removed by the earlier transformations.
The new tests I added fail without my modification.
See also https://github.com/algolia/vue-instantsearch/issues/639 which highlighted 😅 this issue.
> fix(escape): make sure that __escaped does not get removed

- src/connectors/autocomplete/__tests__/connectAutocomplete-test.js
- src/connectors/autocomplete/connectAutocomplete.js
This PR updates the implementation for `getConfiguration` inside `connectAutocomplete`. It adds a default `query` once the widget is mounted. This default value is useful for federated search, without the widget is **always** controlled by its parent. I also cover the rest of the `getConfiguration` function with tests.
> feat(connectAutocomplete): add default value on getConfiguration

- src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
- src/connectors/infinite-hits/connectInfiniteHits.ts
- src/widgets/infinite-hits/__tests__/infinite-hits-test.ts
This PR updates the implementation for `getConfiguration` inside `connectInfiniteHits`. It adds a default `page` once the widget is mounted. This default value is useful for federated search, without the widget is **always** controlled by its parent. I also cover the rest of the `getConfiguration` function with tests.
> feat(connectInfiniteHits): add default value on getConfiguration
