src/connectors/pagination/__tests__/connectPagination-test.js
src/connectors/pagination/connectPagination.js
src/widgets/pagination/__tests__/pagination-test.js

This PR updates the implementation for `getConfiguration` inside `connectAutocomplete`. It adds a default `page` once the widget is mounted. This default value is useful for federated search, without the widget is **always** controlled by its parent.

feat(connectPagination): add default value on getConfiguration

---

src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
src/connectors/voice-search/connectVoiceSearch.ts

This PR updates the implementation for `getConfiguration` inside `connectVoiceSearch`. It adds a default `query` once the widget is mounted. This default value is useful for federated search, without the widget is **always** controlled by its parent.

feat(connectVoiceSearch): add default value on getConfiguration

---

src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/search-box/connectSearchBox.js

This PR updates the implementation for `getConfiguration` inside `connectSearchBox`. It adds a default `query` once the widget is mounted. This default value is useful for federated search, without the widget is **always** controlled by its parent.

feat(connectSearchBox): add default value on getConfiguration

---

src/connectors/infinite-hits/connectInfiniteHits.ts
src/connectors/query-rules/connectQueryRules.ts
src/connectors/voice-search/connectVoiceSearch.ts
src/lib/insights/client.ts
src/types/connector.ts

**Summary**
This PR rename the type `RenderOptions` used at the renderer level for `RendererOptions`. Widgets   have already types called `InitOptions` & `RenderOptions`. Those types are currently non-exported but it might happen to we have to export them at some point. Anyway it's better to avoid confusion with two types with the same name with almost the same domain.

feat(types): rename RenderOptions -> RendererOptions

---

examples/e-commerce/src/app.css
examples/e-commerce/src/app.mobile.css
examples/e-commerce/src/widgets/Brands.js
examples/e-commerce/src/widgets/Categories.js
examples/e-commerce/src/widgets/FreeShipping.js
examples/e-commerce/src/widgets/PriceSlider.js
examples/e-commerce/src/widgets/Products.js
examples/e-commerce/src/widgets/Ratings.js
examples/e-commerce/src/widgets/SearchBox.js

Using our raw CSS classes specs is easier to then port the theme to other flavors without having to deal with the class mapping.
[See preview →](https://deploy-preview-3868--instantsearchjs.netlify.com/examples/e-commerce/)

chore(examples): convert `cssClasses` to raw CSS specs

---

renovate.json

**Summary**
By default, Renovate ignores the folder `examples` which means that the dependencies inside our examples are never updated (I did the same changes inside [React InstantSearch](https://github.com/algolia/react-instantsearch/pull/2043) couple of weeks ago). It was not a huge problem until now because we used the CDN version for InstantSearch which that the update was manual anyway. We switch the e-commerce example to npm which now is easy to keep up to date.

chore(renovate): support examples

---

src/lib/utils/__tests__/index-test.js
src/lib/utils/getRefinements.ts

This regression was introduced while removing Lodash from the codebase. We need to check that `facet` is defined before accessing `facet.data`, otherwise some query might fail and break InstantSearch lifecycle.
Steps to reproduce the issue:
- Select "Cameras & Camcorders" from the HierarchicalMenu
- Select "Cameras & Camcorders > Binoculars" from the HierarchicalMenu
- Type the query: "pokem"
Example on [this deployment](https://deploy-preview-3802--instantsearchjs.netlify.com/examples/e-commerce).

fix(getRefinements): check for facet before accessing its data

---

src/connectors/configure/connectConfigure.js
src/lib/InstantSearch.js
src/lib/utils/__tests__/enhanceConfiguration-test.js
src/lib/utils/enhanceConfiguration.ts
src/lib/utils/index.ts

This PR extracts `enhanceConfiguration` from `InstantSearch` to `utils`. We won't use this function inside InstantSearch anymore, it doesn't make sense to keep it there. The tests didn't change place because they were already inside `utils`.

refactor: extract enhanceConfiguration into utils

---

src/lib/utils/__tests__/defer.ts
src/lib/utils/defer.ts
src/lib/utils/index.ts

**Summary**
This PR introduce the utility function `defer`. It allows a provided function to be delayed until the next micro task i.e. `Promise.resolve()`. It also ensure that only one call to this function can occur inside the same micro task. We'll use this function to "batch" the calls to `search` and `render` in the coming PRs.  Here is an example of its usage:
```js
const fn1 = defer(() => {
console.log('Hello');
});
const fn2 = defer(() => {
console.log('Bye');
});
fn1();
fn2();
fn1();
fn2();
fn1();
fn2();
console.log('Start');
Promise.resolve().then(() => {
console.log('Done');
});
// Output:
// Start
// Hello
// Bye
// Done
```

feat(utils): implement defer

---

src/lib/InstantSearch.js
src/lib/__tests__/InstantSearch-test.js

This PR removes the `searchParameters` from the `InstantSearch` instance. We don't have to keep track of the them because we already have access to them through the `helper.state`. The PR only removes the reference on the `InstantSearch` not the usage of the `searchParameters` option.

refactor(InstantSearch): avoid to store searchParameters

---

src/connectors/hits/__tests__/connectHitsWithInsights-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHitsWithInsights-test.ts
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/lib/__tests__/InstantSearch-test.js
src/lib/__tests__/RoutingManager-test.ts
src/types/instantsearch.ts
src/types/widget.ts
src/widgets/query-rule-custom-data/__tests__/query-rule-custom-data-test.ts
src/widgets/voice-search/__tests__/voice-search-test.ts
test/mock/createAPIResponse.ts
test/mock/createInstantSearch.ts
test/mock/createSearchClient.ts
test/mock/createWidget.ts

This PR introduces mock helpers for the common types that we currently have inside our tests. Those helper functions allow us to easily change the type of one of the interface. Without them, one change inside the type has an impact on every test files that require this type. It's still the case but since the type is encapsulated inside a function we have to change it once (for most cases). Here which mock have been introduced:
- `createSearchClient`: create a `searchClient` with pre-defined response 
- `createInstantSearch`: create an InstantSearch instance
- `createWidget`: create a widget with `jest.fn()`
- `createInitOptions`: create the widget `init` options
- `createRenderOptions`: create the widget `render` options
Each one of them accepts an argument which is a `Partial` of the …

test(mock): use typed mock

---

src/types/instantsearch.ts

This PR adds a type for the `DerivedHelper`. It only adds the API that we currently use. At some point, we have to embed the definition of the `algoliasearch-helper`. The definitions hosted on DT are not 100% correct. If we want to move fast with it it's safer to embed it inside InstantSearch.

feat(types): DerivedHelper

---

src/lib/__tests__/RoutingManager-test.ts
test/utils/runAllMicroTasks.ts

This PR introduce a first test utils: `runAllMicroTasks`. We use it only once at the moment but we'll introduce some features that will require its usage in the next PRs. Basically it flushes the micro-tasks queue without relying on Jest's fake timers.

test(utils): use runAllMicroTasks

---

src/widgets/panel/__tests__/panel-test.js
src/widgets/panel/panel.js

The return value of  `dispose`  is swallowed by the `panel`. It leads to issue when a widget refined wrapped by a `panel` is removed from the search. The refined values should be removed but since the return value is ignored the refinement persist. This PR aims to fix this issue.
**Before**
**After**

fix(panel): return value from dispose

---

examples/e-commerce/index.html
examples/e-commerce/src/app.css
examples/e-commerce/src/app.mobile.css
examples/e-commerce/src/theme.css
examples/e-commerce/src/widgets/PriceSlider.css

**Summary**
This adds more styles to e-commerce mobile design.
**Result**
This PR will
- force the size for resetIcon in SearchBox as `10x10`, because in Vue-IS and Angular-IS, the sizes are hardcoded and there is no option to override them.
- have `z-index: 5` instead of `1` at `.filtering .container-filters-footer` because there was a collision between the filters footer and the slide UIs in Vue-IS and Angular-IS.
- add class names to the children of `.container-options` because `.container-options div:...` didn't select correctly at Angular-IS.
- move slider-related styles to dedicated `PriceSlider.css` file as same as the flavors are doing.

chore(examples): e-commerce mobile design part-2

---

.storybook/decorators/index.ts
.storybook/decorators/withHits.ts
.storybook/decorators/withLifecycle.ts
stories/breadcrumb.stories.js
stories/configure.stories.js
stories/geo-search.stories.js
stories/hierarchical-menu.stories.js
stories/hits-per-page.stories.js
stories/menu-select.stories.js
stories/menu.stories.js
stories/sort-by.stories.js
stories/toggleRefinement.stories.js

It's always painful to test the behavior of a widget when it's added or removed. This PR aims to fix this issue with a decorator that creates a preview to dynamically add/remove the widget. You have to call the decorator inside the `withHits` decorator. I didn't implement a way to chain them because they don't have the same signature (we'll have to implement an adapter for the last one). This approach keeps the flexibility.
I added the `withLifecycle` to the stories when it's relevant: 
- when the `dispose` function actually does something (remove the refinements)
- when the previewed widget does not conflict with the one of the playground
**Usage**
```js
storiesOf("searchBox", module).add(
"with add/remove",
withHits(({ search, container, instantsearch }) => {
withLifecycle(search, …
```

chore(storybook): add stories with lifecycle

---

src/widgets/range-input/__tests__/range-input-test.js
src/widgets/range-input/range-input.js

The `rangeInput` was not able to be removed. The unmount function was not provided. The PR fix this issue.
Note that even without the unmount function the widget should not throw. An error is raised because we don't provide a default value to the unmount function or check the value for the unmount function. This issue concern most of the connectors, that's why I didn't address it inside the PR.
**Before**
**After**

fix(rangeInput): unmount component

---

src/widgets/menu-select/__tests__/__snapshots__/menu-select-test.js.snap
src/widgets/menu-select/__tests__/menu-select-test.js
src/widgets/menu-select/menu-select.js

The `menuSelect` was not able to be removed. The unmount function was not provided. The PR fix this issue.
Note that even without the unmount function the widget should not throw. An error is raised because we don't provide a default value to the unmount function or check the value for the unmount function. This issue concern most of the connectors, that's why I didn't address it inside the PR.
**Before**
**After**

fix(menuSelect): unmount component

---

examples/e-commerce/src/app.css

**Summary**
This adds style to `app.css` to wrap words.
It fixes the glitches (1) and (2) from [here](https://github.com/algolia/angular-instantsearch/pull/629#issuecomment-506790740).
**Result**
- [Without it](https://develop--instantsearchjs.netlify.com/examples/e-commerce/?refinementList%5Bbrand%5D%5B0%5D=HP&refinementList%5Bbrand%5D%5B1%5D=Speck&refinementList%5Bbrand%5D%5B2%5D=Epson): ← open it on small browser.
- [With it](https://deploy-preview-3913--instantsearchjs.netlify.com/examples/e-commerce/?refinementList%5Bbrand%5D%5B0%5D=HP&refinementList%5Bbrand%5D%5B1%5D=Speck&refinementList%5Bbrand%5D%5B2%5D=Epson): ← open it on small browser.

chore(examples): add app style for word wrap in e-commerce demo

---

.storybook/playgrounds/default.ts
stories/index.stories.ts

This PR adds a minimal story to work on the `index` widget. We can review the design later, right now it's mostly to be able to have a playground to work on. The current feature set is limited to only display a static list of hits (it trigger the correct number of requests). We only take into account the local `helper` of the `index` which means that parent widgets are ignored. We'll cover that soon.
~~**Currently the story does not work because the previous branches are not correctly rebased.**~~
> https://deploy-preview-3914--instantsearchjs.netlify.com/stories/?path=/story/index--default

feat(index): add story [PART-3]

---

package.json
yarn.lock

**Summary**
This version removes the requirement to type return parameters.
**Result**
#3917 will no longer have linting errors

chore(deps): eslint-config-algolia 13.4.0

---

src/lib/InstantSearch.js
src/lib/__tests__/InstantSearch-test.js
test/mock/createSearchClient.ts

Some operations are now asynchronous, which means that we have to clean up those operations when the `InstantSearch` instance is disposed. Otherwise, the functions are called and might refer to props that have been pruned. This PR "cancel" the pending operations on `dispose`.

fix(InstantSearch): cancel scheduled operations

---

src/lib/InstantSearch.js
src/lib/__tests__/InstantSearch-test.js
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

The `index` assumes that the `lastResults` prop is set which is not always the case. The issue arises only when the stalled render kicks in. The previous implementation (without `index`) fixed this issue by turning the default value of `_isSearchStalled` to `true` to avoid extra `render` until we have results (https://github.com/algolia/instantsearch.js/pull/2623). This fix does not work anymore since we don't have a single Helper. 
This PR revert the change to a default value of `false` which makes more sense (it's not stalled by default). Only the `index` is aware that we have results or not, then the condition belongs to its render function.
**Before**
**After**

fix(index): prevent render without results

---

src/lib/utils/__tests__/defer.ts
src/lib/utils/defer.ts

This PR fixes an issue when the deferred function throws an error. The next calls to the function shouldn't be impacted by the error that happens inside a previous call. Previously it was the case because the value of `progress` was reset only if the call to the callback succeeds. It's not the case anymore the value is always reset whether or not the call succeeds.

fix(defer): recover from error

---

src/lib/utils/__tests__/resolveSearchParameters-test.ts
src/lib/utils/index.ts
src/lib/utils/resolveSearchParameters.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
stories/index.stories.ts

This PR introduces a function to resolve the parent `SearchParameters` from the `index`. It allows the index to find the list of parameters that it will have to merge. Currently, the function to merge those parameters is not merged yet that's why we have a naive implementation. We'll migrate to the correct function once it's available.
At the moment the function to resolve the `SearchParameters` is fairly simple: it recursively bubbles up the hierarchy to find the root `index`. At each iteration, we collect the current state of the `index` where we are. Note that we have to expose the `parent` on the `index` instance otherwise we're not able to retrieve the parents' state.
The [examples](https://deploy-preview-3937--instantsearchjs.netlify.com/stories/?path=/story/index--default) now …

feat(index): resolve parent SearchParameters

---

src/connectors/geo-search/__tests__/connectGeoSearch-test.js
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
src/connectors/hits/__tests__/connectHits-test.js
src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
src/connectors/pagination/__tests__/connectPagination-test.js
src/connectors/range/__tests__/connectRange-test.js
src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/sort-by/__tests__/connectSortBy-test.js
src/connectors/stats/__tests__/connectStats-test.js
src/connectors/toggleRefinement/__tests__/connectToggleRefinement-test.js
src/lib/InstantSearch.js
src/lib/RoutingManager.ts
src/types/instantsearch.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
src/widgets/rating-menu/__tests__/rating-menu-test.js
test/mock/createInstantSearch.ts
test/mock/createWidget.ts

This PR drops the support for `onHistoryChange`. This API have been introduced to fix [an issue with the `searchBox`](https://github.com/algolia/instantsearch.js/issues/729). The codebase has evolve since then and we don't use the option anymore. The options is not documented on [algolia.com/doc](https://www.algolia.com/doc/), IMO it's safe enough to remove it on the next major.

feat: drop support for onHistoryChange

---

examples/media/index.html
examples/media/src/app.css

**Summary**
- This PR fixes the problem where the backgroud of the button was not visible on desktop Chrome.
- This PR hides the button when the filter modal is open.

chore(examples): fix back-to-top button

---

src/connectors/range/__tests__/connectRange-test.js
src/connectors/range/connectRange.js

> This PR is targeting the `next` branch.
In the next major, `connectRange`'s default `precision` should be `0` to be consistent with other flavors.
We'll need to update the documentation when we release InstantSearch.js 4 (noted on my side).

feat(connectRange): default `precision` to 0

---

src/connectors/autocomplete/connectAutocomplete.js
src/connectors/breadcrumb/connectBreadcrumb.js
src/connectors/clear-refinements/connectClearRefinements.js
src/connectors/current-refinements/connectCurrentRefinements.js
src/connectors/geo-search/connectGeoSearch.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/connectors/hits-per-page/connectHitsPerPage.js
src/connectors/hits/connectHits.js
src/connectors/menu/connectMenu.js
src/connectors/numeric-menu/connectNumericMenu.js
src/connectors/pagination/connectPagination.js
src/connectors/powered-by/connectPoweredBy.js
src/connectors/range/connectRange.js
src/connectors/rating-menu/connectRatingMenu.js
src/connectors/refinement-list/connectRefinementList.js
src/connectors/search-box/connectSearchBox.js
src/connectors/sort-by/connectSortBy.js
src/connectors/stats/connectStats.js
src/connectors/toggleRefinement/connectToggleRefinement.js

**Summary**
Many of the connectors doesn't have default value of `unmountFn`. When users create custom widget using the connectors and if they don't provide `unmountFn`, removing the widget will throw an error.
So this PR adds `noop` as the default value of `unmountFn` to all the connectors.
**Result**
All the connectors have `noop` as default value of `unmountFn`.

fix: pass noop as default value to unmountFn at connectors

---

src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/menu/connectMenu.js

If a menu is added while the search is being stale, we will  recieve undefined (currently an error), so we can not fetch `.data` from it.
requires https://github.com/algolia/algoliasearch-helper-js/pull/720 to make a difference here, because otherwise an error gets thrown before the old code or the new code gets executed 
related: https://github.com/algolia/instantsearch.js/issues/3084
~~tests will fail until #3940 is merged~~

fix(menu): prevent error on stale search

---

src/lib/RoutingManager.ts
test/mock/createAPIResponse.ts

This is a follow-up on #3940 requested by @samouss
- correct the type for `getAllSearchParameters`
- move defaults  in response mock to not have intermediary variables
- consistent function style in mock
sorry for the 3-in-1 PR, but wasn't really worth splitting IMO

chore(routing): correct types

---

jest.config.js

When running Jest in watch mode and editing the stories, the tests unnecessarily rerun although the source files didn't change. The same happens when building the library. This results in slowing down the feedback loop when actually editing the source.
The PR adds folders to ignore while running Jest in watch mode with the [`watchPathIgnorePatterns `](https://jestjs.io/docs/en/configuration#watchpathignorepatterns-array-string) option.

chore(jest): ignore path patterns in watch mode

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
src/connectors/breadcrumb/connectBreadcrumb.js
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
stories/breadcrumb.stories.js
stories/hierarchical-menu.stories.js

This PR fixes the `getConfiguration` lifecycle for `hierarchicalMenu` & `breadcrumb`. The previous implementation ignores the different `rootPath`, which leads to issues when both widgets are mounted with different values. One of the two value is picked but what should happen is a warning + ignore the current configuration like the other options.
**Before with `rootPath` only on the `hierarchicalMenu`:**  
- the value should not be refined
- a warning should be displayed
- only the level of the `rootPath` should be displayed
**After: with `rootPath` only on the `hierarchicalMenu`**
- the value is not refined
- a warning is displayed
- only the level of the `rootPath` is displayed

fix(hierarchicalFacets): prevent different rootPath on same attribute

---

src/lib/InstantSearch.js
src/lib/__tests__/enhanceConfiguration-test.js
src/lib/utils/__tests__/findIndex-test.ts
src/lib/utils/findIndex.ts
src/lib/utils/index.ts

Fixes #3278
This PR backport the merge of the `hierarchicalFacets` from [`mergeSearchParameters`](https://github.com/algolia/instantsearch.js/blob/6153a72066fed259a4eae30b4062894d2c86fbcc/src/lib/utils/mergeSearchParameters.ts#L38-L52) inside the implementation of `enhanceConfiguration`. It (finally) remove the issue with duplicated facets inside the request. This part of the code will be removed with the next major version in favor of the merge function. It ensures that the version 3.x.x won't have this issue anymore which implies Vue & Angular too.
**Before**
**After**

fix(enhanceConfiguration): deduplicate the hierarchicalFacets

---

examples/e-commerce/tsconfig.json
tsconfig.json

This wasn't possible before because the array generated from spreading a form element got transformed into .slice which it didn't have. If downlevelIteration is true & dom.iterable is true the code will work however!
see https://github.com/codesandbox/codesandbox-client/issues/2166#issuecomment-513210419
you can verify this fix by comparing:
https://codesandbox.io/s/github/algolia/instantsearch.js/tree/develop/examples/e-commerce
to the fixed version:
https://codesandbox.io/s/github/algolia/instantsearch.js/tree/docs/fix-codesandbox/examples/e-commerce

docs(examples): make sure e-commerce example can be ran on codeSandBox

---

src/connectors/configure/connectConfigure.js
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
src/connectors/voice-search/connectVoiceSearch.ts
src/lib/RoutingManager.ts
src/lib/utils/__tests__/enhanceConfiguration-test.js
src/lib/utils/enhanceConfiguration.ts
src/types/instantsearch.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

follow-up on #3945, enhanceConfiguration now accepts a SearchParameters, and all usages have been changed to instantiate this helper themselves.
I wonder if we could force the result of getConfiguration be a SearchParameters too so we can avoid that instantiation? 🤔

chore(enhanceConfiguration): prevent helper to be superfluously created

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
stories/index.stories.ts

This adds support for resetting pagination for child indexes whenever the state changes in a parent (except when only the `page` search parameter changes). This information is given by the helper `change` event: `isPageReset`.
This is done recursively so that we reset the pagination for _all_ child index widgets. Note that this is a noop when the pagination is not set in the children (because we base the condition on `isPageReset`).
```
GIVEN
index1: page 1
index2: page 3
index3: page 4
index4: page 2
WHEN
query performed on index2
THEN
index1: page 1
index2: page 0
index3: page 0
index4: page 2
```
[See preview →](https://deploy-preview-3962--instantsearchjs.netlify.com/stories/?path=/story/index--with-nested-levels)

feat(index): reset page of child indexes

---

src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
test/mock/createWidget.ts

This introduces the concept of _scoped results_ during the `render` hook.
Since InstantSearch.js now handles multi-index search, we will need to revisit the behavior of some widgets:
- `autocomplete` may need to access the scope of its current index, as well as all the siblings and children
- `currentRefinements` may need to show the refinements coming from the current index and all its siblings/children
- `clearRefinement` may need to reset the refinements coming from the current index and all its siblings/children
An index now has access to all its children and siblings (+ siblings children) results. As illustrated in the image below, the lower in the tree, the fewer results the index has access to.
The more transparent a level is, the less view it has on the global results.
This …

feat(index): provide scoped results to render hook

---

src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/search-box/connectSearchBox.js

This fixes the lifecycle of `connectSearchBox`.

fix(searchBox): update lifecycle state

---

src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
src/connectors/hits-per-page/connectHitsPerPage.js
src/widgets/hits-per-page/__tests__/hits-per-page-test.js

This fixes the lifecycle of `connectHitsPerPage`.

fix(hitsPerPage): update lifecycle state

---

src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
src/connectors/voice-search/connectVoiceSearch.ts

This fixes the lifecycle of `connectVoiceSearch`.
- `getConfiguration` supports previous queries
- `getConfiguration` tests check the `SearchParameters` type returned

fix(voiceSearch): update lifecycle state

---

src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts

This fixes the lifecycle of `connectInfiniteHits`.
- `getConfiguration` support previously set `page` parameter
- `getConfiguration` tests check that the returned type is `SearchParameters`

fix(infiniteHits): update lifecycle state

---

package.json
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
src/connectors/toggleRefinement/__tests__/__snapshots__/connectToggleRefinement-test.js.snap
src/connectors/toggleRefinement/__tests__/connectToggleRefinement-test.js
yarn.lock

Some tests needed to be changed, but only because they relied on internals of the helper, but it doesn't change any changes that are not already covered by work to do in IFW-874
The main change included in this version is https://github.com/algolia/algoliasearch-helper-js/pull/738, which is required for #3976 to work fully, as well as a change in typings required for #3984

chore(helper): update to latest beta

---

src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
src/connectors/rating-menu/connectRatingMenu.js
src/widgets/rating-menu/__tests__/rating-menu-test.js

This fixes the lifecycle of `connectRatingMenu`.
- `getConfiguration` returns a search parameter object
- `getConfiguration` support previously set disjunctive facets refinements
- `getFacetValues()` fallbacks to an empty array
- `dispose` doesn't call `removeDisjunctiveFacetRefinement()`

fix(ratingMenu): update lifecycle state

---

src/connectors/toggleRefinement/__tests__/connectToggleRefinement-test.js
src/connectors/toggleRefinement/connectToggleRefinement.js
src/widgets/toggleRefinement/__tests__/toggleRefinement-test.js

This fixes the lifecycle of `connectToggleRefinement`.
- `getConfiguration` sets default `disjunctiveFacetsRefinements`
- `getFacetValues` falls back to an empty array

fix(toggleRefinement): update lifecycle state

---

src/connectors/configure/__tests__/connectConfigure-test.js
src/connectors/configure/connectConfigure.js

This fixes the lifecycle of `connectConfigure`.
- `refine` relies on `mergeSearchParameters` directly instead of passing a virtual widget to `enhanceConfiguration`
- `removeSearchParameters` was removed from the widget scope to not pollute it
- `connectConfigure` tests now also check that search parameters are resolved correctly (e.g. with facets as an array)

fix(configure): update lifecycle state

---

src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/refinement-list/connectRefinementList.js
src/widgets/refinement-list/__tests__/refinement-list-test.js

IFW-875
**Summary**
RefinementList no longer sets any type of refinements to an empty object, always keeping this attribute as an empty array in refinements.
- getConfiguration sets empty array to XRefinement
- getConfiguration reads from existing state to set value from other identical widgets in index
- getConfiguration returns a SearchParameters
- getFacetValues should have a fallback
- Refine (via toggleXRefinement in https://github.com/algolia/algoliasearch-helper-js/pull/738) doesn’t remove refinement if empty (helper)
- Dispose removes XRefinement, using only helper.removeXFacet
**Result**
~~tests will fail until https://github.com/algolia/algoliasearch-helper-js/pull/738 is used here~~
Dispose & get Configuration work as expected

feat(federated): keep a consistent state in the RefinementList life cycle

---

src/connectors/search-box/__tests__/__snapshots__/connectSearchBox-test.js.snap
src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/search-box/connectSearchBox.js

This PR updates the lifecycle `getWidgetSearchParameters` to `connectSearchBox` to take the add the default value without `uiState`. We don't apply the previous value on purpose, the `uiState` drives completely the `SearchParameters`.
I've not removed the `getConfiguration` lifecycle (yet) to avoid breaking everything. Once we've made the switch to `getWidgetSearchParameters` we'll remove them.

feat(connectSearchBox): update getWidgetSearchParameters

---

src/connectors/search-box/__tests__/__snapshots__/connectSearchBox-test.js.snap
src/connectors/search-box/__tests__/connectSearchBox-test.js

This removes a snapshot with an inline assertion, since it's very small, and avoids the indirection. In the future if we don't want to write an assertion, I'd suggest the following flow:
1. add toMatchInlineSnapshot
2. change snapshot to real assertion
3. profit

 test(searchbox): remove needless snapshot

---

src/connectors/sort-by/__tests__/connectSortBy-test.js
src/connectors/sort-by/connectSortBy.js

We've updated the `sortBy` inside a recent [PR](https://github.com/algolia/instantsearch.js/pull/3824). We indeed fix an issue with it but we also introduced one. We've removed the `currentIndex` to always use the `initialIndex`. But the two value aren't the same. The `currentIndex` is the current value, which might come from the top-level options or the URLSync. The `initialIndex` is **always** the one provided at the top-level options. 
The `getWidgetState` function compares both values to determine whether or not the current value should go inside the `uiState`. We never push the value of the `initialIndex` to avoid to pollute the URL. But if the value depends on the one provided at `init` we'll lose the information inside the `uiState` since now the `initialIndex` is equal to the …

fix(connectSortBy): never update the initial index

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/autocomplete/connectAutocomplete.ts

autocomplete is acting just like search box, but also sets the parameters for highlighting from hits. This is a copy-paste from the tests & code of searchbox (#4002), but with the tags added.
This has an impact on routing (it used to not be synchronised if you type in an autocomplete, but now it will be).

feat(autocomplete): participate in routing

---

package.json
yarn.lock

1. https://github.com/algolia/instantsearch.js/pull/4000#discussion_r311457169 is fixed by https://github.com/algolia/algoliasearch-helper-js/pull/742
This requires #4000 to be updated to remove the @ts-ignore
2. https://github.com/algolia/algoliasearch-helper-js/pull/743 fixes https://github.com/algolia/instantsearch.js/pull/4024 & https://github.com/algolia/instantsearch.js/pull/4027
This change doesn't require any subsequent changes because the tests are new in those PRs

chore(deps): update helper to latest canary

---

src/components/CurrentRefinements/CurrentRefinements.tsx
src/components/CurrentRefinements/__tests__/CurrentRefinements-test.tsx
src/components/CurrentRefinements/__tests__/__snapshots__/CurrentRefinements-test.tsx.snap
src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/types/widget.ts
src/widgets/current-refinements/__tests__/__snapshots__/current-refinements-test.ts.snap
src/widgets/current-refinements/__tests__/current-refinements-test.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
stories/current-refinements.stories.js
test/mock/createWidget.ts

This implements multi-index context in `CurrentRefinements` leveraging `scopedResults` (#3964).
A `CurrentRefinements` widget now displays the refinements coming from its siblings and its children.
The `index` now calls the `render` hook with an enhanced `scopedResults` containing the helper for this index. This is needed to call `refine` on each item coming from the `CurrentRefinements`. Otherwise, calling `setState` on the helper doesn't change the correct helper state (and thus breaks).
The new structure is:
```ts
interface ScopedResult {
indexId: string;
results: SearchResults;
helper: Helper;
}
```
A new property `indexName` is added to the CurrentRefinements items. This property is given to the renderer. This `indexName` can be used to display the index where the attribute is coming …

feat(currentRefinements): support multiple indices

---

src/connectors/infinite-hits/connectInfiniteHits.ts
src/types/widget.ts
src/widgets/infinite-hits/infinite-hits.tsx

This removes the outdated JSDoc and leverages TypeScript's documentation for the `infiniteHits` stack.

docs(infiniteHits): update documentation

---

examples/e-commerce/src/ui.ts
examples/e-commerce/src/widgets/HitsPerPage.ts
examples/e-commerce/src/widgets/SortBy.ts

**Summary**
This PR fixes some compatibility issues on IE11 for the e-commerce demo:
* Spreading a NodeList does not work on IE11 (https://github.com/babel/babel/issues/9993): fixed by replacing it with `Array.prototype.slice.call(NodeList)`.
* `Array.prototype.includes` is not available on IE11: fixed by replacing it with `Array.prototype.indexOf` .
Both issues could have been fixed by updating Babel configuration to add the required polyfills but FMPOV it would have made the resulting bundles heavier for little to no benefits.

fix(examples): fix IE11 compatibility for e-commerce demo

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
src/connectors/breadcrumb/connectBreadcrumb.js

This PR updates the lifecycle `getWidgetSearchParameters` in `connectBreadcrumb` to add the configuration of facets.
I've not removed the `getConfiguration` lifecycle (yet) to avoid breaking everything. Once we've made the switch to `getWidgetSearchParameters` we'll remove them.

feat(connectBreadcrumb): update getWidgetSearchParameters

---

src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/menu/connectMenu.js

This PR updates the lifecycle `getWidgetSearchParameters` in `connectMenu` to add the configuration of facets and default value. We don't apply the previous value on purpose, the `uiState` drives completely the `SearchParameters`.
I've not removed the `getConfiguration` lifecycle (yet) to avoid breaking everything. Once we've made the switch to `getWidgetSearchParameters` we'll remove them.

feat(connectMenu): update getWidgetSearchParameters

---

src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
src/connectors/voice-search/connectVoiceSearch.ts

This PR updates the lifecycle `getWidgetSearchParameters` in `connectVoiceSearch` to add the  default value. We don't apply the previous value on purpose, the `uiState` drives completely the `SearchParameters`.
I've not removed the `getConfiguration` lifecycle (yet) to avoid breaking everything. Once we've made the switch to `getWidgetSearchParameters` we'll remove them.

feat(connectVoiceSearch): update getWidgetSearchParameters

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

The indexid is used in the already existing `getIndexId` function, so all that was needed to be done there was to add a new test to ensure the usage is correct.
There can still be conflicts within a scope, but that would be if an indexId is shared
IFW-930
I didn't make a story highlighting this use, since it only has an effect in the route state, which isn't yet being listened to for nested indices, so is hard to see in effect for now

feat(index): accept indexId

---

src/lib/__tests__/InstantSearch-test.js
src/lib/__tests__/RoutingManager-test.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
This PR replaces the usage of `getConfiguration` for `getWidgetSearchParameters`. The widgets are now driven by the `uiState`. Note that widgets that don't implement the lifecycle can still write on `SearchParameters`, but if a widget that implements the lifecycle use the same parameter it will be always overridden.
The lifecycle is now called on `init`, `add` (when the instance is started), `remove` (when the instance is started). On `init` we currently always provide an empty `uiState` (but it will change soon). On `add`/`remove` we provide the local `uiState` of the index to drive the `SearchParameters`.

feat(index): use uiState driven SearchParameters

---

src/connectors/hits-per-page/__tests__/__snapshots__/connectHitsPerPage-test.js.snap
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
src/connectors/hits-per-page/connectHitsPerPage.js
src/widgets/hits-per-page/__tests__/__snapshots__/hits-per-page-test.js.snap
src/widgets/hits-per-page/__tests__/hits-per-page-test.js
stories/hits-per-page.stories.js

In InstantSearch.js, we don't enforce a default value in the [`hitsPerPage`](https://www.algolia.com/doc/api-reference/widgets/hits-per-page/js/#widget-param-items) widget. This means that we pick the first in the list when no `default` is specified.
The problem with not always having a default value is that it's not deterministic with multi-indexing: `getWidgetSearchParameters`' `hitsPerPage` value can be inherited from the parent index whereas we want it to be self contained (see #4038).
This PR enforces a default value (and a single one).
Long term, we can think moving toward an API similar to the [React version](https://www.algolia.com/doc/api-reference/widgets/hits-per-page/react/#widget-param-defaultrefinement), where another option (e.g. `defaultValue`) picks the right item in the …

feat(hitsPerPage): enforce default value

---

src/connectors/hits-per-page/__tests__/__snapshots__/connectHitsPerPage-test.js.snap
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
src/connectors/hits-per-page/connectHitsPerPage.js
src/widgets/hits-per-page/__tests__/__snapshots__/hits-per-page-test.js.snap
src/widgets/hits-per-page/__tests__/hits-per-page-test.js
stories/hits-per-page.stories.js

This updates `hitsPerPage` lifecycle methods to support the new routing system.
This method ignores previous UI state values. Otherwise, new values gets skipped.
This is only a refactor.
---
_`getConfiguration` will be removed later to not break everything._

feat(hitsPerPage): support new routing system

---

examples/e-commerce/index.html

**Summary**
Some IE11 compatibility issues on the e-commerce demo remains even after https://github.com/algolia/instantsearch.js/pull/4049 due to some missing polyfills.
This PR adds the polyfill suggested in [the documentation](https://www.algolia.com/doc/guides/building-search-ui/installation/js/#browser-support).

fix(examples): fix missing polyfill in e-commerce demo

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
stories/instantsearch.stories.js
test/mock/createInstantSearch.ts
test/mock/createWidget.ts

**Summary**
This PR introduces the `initialUiState` option at the `InstantSearch` level. The option allows users to provide an `uiState` used for the initial request. Only for the **initial request**. I've chosen to name the option `initialXXX` rather than `uiState` to have a clear intent. At some point, we might want to introduce the concept of controlled state (like React InstantSearch) that could use the option `uiState`.
At the moment the type definitions are incorrect. We have only one type that defines the `uiState` but we have to define two different types. The first is one is the "global" `uiState` and the second one is the "local" to each index. The "global" `uiState` is built on multiple "local" `uiState`. We'll update the definition in a separate PR.
**Usage**
```js
const …
```

feat: introduce initialUiState option

---

src/lib/RoutingManager.ts
src/lib/__tests__/InstantSearch-test.js
src/lib/__tests__/RoutingManager-test.ts
src/lib/stateMappings/__tests__/simple-test.ts
src/lib/stateMappings/simple.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

This PR updates the type definitions to match the new format of the `UiState`. We introduce a new type called `IndexUiState`. The `UiState` is the global structure that represents the InstantSearch instance with each indices. The `IndexUiState` is the previous version of the `UiState`, it represents the state of an "index". Here is their definitions:
```ts
export type IndexUiState = {
query?: string;
hitsPerPage?: number;
// ...
};
export type UiState = {
[indexId: string]: IndexUiState;
};
```
The introduction of this type mainly impact the `StateMapping` & `RoutingManager`. Both have been updated. The changes applied to `RoutingManager` are there to make the tests pass don't pay too much attention to them since we'll rework this part soon.
**Note**: Name are just a proposition, we could …

feat: update UiState definition

---

examples/e-commerce/src/widgets/Products.ts

There can only be one main element per page:
> A document mustn't have more than one <main> element that doesn't have the hidden attribute specified.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main
Found  this running an audit on the demo: 
(to check, do we use `main` in css? let's see in the preview)

docs(example): fix html for hits

---

.eslintrc.js
.storybook/decorators/withHits.ts
src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
stories/breadcrumb.stories.js
stories/clear-refinements.stories.js
stories/current-refinements.stories.js
stories/geo-search.stories.js
stories/hierarchical-menu.stories.js
stories/infinite-hits.stories.js
stories/instantsearch.stories.js
stories/query-rule-context.stories.ts
test/mock/createInstantSearch.ts

This PR drops the support of `searchParameters` for `initialUiState`. Here is the changes:
- `InstantSearch`: remove the support of the option
- `index`: remove the logic for the option
- `stories`: replace the usage of `searchParamters` by `initialUiState` when applicable
- `stories`: replace the usage of `searchParamters` by `configure` when applicable

feat: drop support of searchParameters for initialUiState

---

src/connectors/configure/__tests__/connectConfigure-test.ts
src/connectors/configure/connectConfigure.ts

This PR uses the `mergeSearchParameters` for `getWidgetSearchParameters` within `configure`. With the changes introduced recently, we don't merge the parameters auto-magically. This logic is now managed by each widget itself. For `configure` this behavior was handy because it allowed us to use it for initial refinement. 
It's not possible anymore because we use `setQueryParameters` which overrides the previous parameters. The facets configuration of the current widget is erased and we're not able to refine anymore. To ease the transition between the two versions and keep the widget powerful enough we'll mimic the previous implementation.

fix(configure): merge with the previous parameters

---

src/lib/InstantSearch.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
test/mock/createInstantSearch.ts

**Summary**
IFW-932
Implement the (for now empty) `onStateChange` method on `InstantSearch`.
This method is called by the `index` widget every time its `localUiState` is updated and will in the future notify the middlewares (like the routing) of any change in the widgets state.
The tests for the `index` widget were updated to check if `onStateChange` was called as expected.

feat(instantsearch): add onStateChange method

---

src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.js
src/connectors/hits-per-page/connectHitsPerPage.js

This PR avoid to sync the default value into the `uiState`. This behavior is consistent with the one from `sortBy`. The default value doesn't have to be inside the `uiState` because as the name suggests it's the default one. The option is defined statically, it can't change.

fix(hitsPerPage): avoid sync default value

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

This PR replicates [the hack](https://github.com/algolia/instantsearch.js/blob/509513c0feafaad522f6f18d87a441559f4aa050/src/lib/RoutingManager.ts#L113-L130) implemented inside `RoutingManager` for the `searchFunction`. The `uiState` is now a first-class citizen so we have to apply this logic to the index. I've tried to keep the same process: the update is triggered once all the widgets of the index are rendered like it was the case inside the manager (since it was always the last widget).
At the moment the call to notify the instance that a change occurs isn't implemented because we don't expose the function (yet). Once the API is available I'll update the PR. The pieces that need to be updated are commented.

feat(index): replicate searchFunction hack

---

src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
src/connectors/numeric-menu/connectNumericMenu.js

This PR fixes a regression we introduced with the new behaviour of the Helper. We now preserve the empty state to avoid the parent to override the refinement when the widget is mounted. The `numericMenu` was relying on the previous behaviour to pick the "no value" element. We now check that every operator is empty.
**Before**
**After**
You check the behaviour on the Storybook with [the `currentRefinement` stories](https://deploy-preview-4084--instantsearchjs.netlify.com/stories/?path=/story/currentrefinements--with-numericmenu).

fix(numericMenu): take array into account for empty state

---

src/lib/InstantSearch.ts
src/lib/RoutingManager.ts
src/lib/__tests__/RoutingManager-test.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
IFW-935
This change removes RoutingManager from the render process, therefore it is no longer a widget. Updating state on external route update (popState) was not implemented, it will be done later in IFW-936.
List of changes:
* Remove all widget related methods from `RoutingManager`.
* Remove the hack to always have the `RoutingManager` widget last in the widget list.
* Replace https://github.com/algolia/instantsearch.js/pull/4078 by another fix (https://github.com/algolia/instantsearch.js/compare/next...feat/fs-routingmanager?expand=1#diff-1fc36c4ea042d2ecb5a498416e5e0357R366-R369. The reason is that with the original fix there was an issue with the configure widget (present in `firstRenderState` but absent from `localUiState`) forcing the URL to always be updated.
* Remove …

 feat(RoutingManager): remove RoutingManager from the render process 

---

src/lib/InstantSearch.ts
src/lib/RoutingManager.ts
src/lib/__tests__/RoutingManager-test.ts

**Summary**
This PR add the event listener to update the state on any route change and keep both synchronized. It also re-add the related unit tests that were removed in https://github.com/algolia/instantsearch.js/pull/4099.

feat(RoutingManager): update state on route update

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js

**Summary**
When initializing the `mainIndex` we're using `initialUIState` as initial state. It can be an empty object (default) or a user defined object (see https://github.com/algolia/instantsearch.js/pull/4074).
The issue is that after this initialization we apply the state from the route to all indexes **without triggering a change event**. https://github.com/algolia/instantsearch.js/blob/448146c4dabbd659e6735f4fb25b50fc4f8fe135/src/lib/RoutingManager.ts#L56-L58
Since no events were triggered, the `mainIndex` still has the `initialUIState` value as `localUiState` and is no longer in sync with the widgets state.
This issue was identified in https://github.com/algolia/instantsearch.js/pull/4074#issuecomment-525649188.
This PR fix this by using the route state as the `initialUIState`, so …

fix(InstantSearch): fix initialUIState when refinements are already present in the route

---

src/connectors/range/__tests__/connectRange-test.js
src/connectors/range/connectRange.js
src/widgets/range-slider/__tests__/range-slider-test.js
stories/range-input.stories.js
stories/range-slider.stories.js

This PR fixes a regression we've introduced with the migration to `getWidgetSearchParameters`. The widget accepts `min`/`max` options that represent the lower/upper bound for the attribute. Those bounds were ignored with our new implementation.
I've changed one behavior that is a breaking change but shouldn't impact most of our users. The widget can accept a `max` option lower than `min`. With such configuration, the widget ignores the options. Now it does throw an error, it makes no sense to provide such options.

fix(range): apply min/max to getWidgetSearchParameters

---

src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
IFW-980
This PR fix multiple pagination reset issues with InfiniteHits:
* When requesting the `SearchParameters` from the InfiniteHits widget the page was always reset to `0` if `showPrevious` was `false`. We now return the original `searchParameters` (like it was the case before https://github.com/algolia/instantsearch.js/pull/4040).
* When comparing the currentState with the prevState (to know if we need to reset the widget internal cache) we now exlude `hierarchicalFacets`, `disjunctiveFacets` and filter `hierarchicalFacetsRefinements` and `disjunctiveFacetsRefinements` content to only keep the actual refinements. This is very hacky :nauseated_face: . Any idea to make this cleaner and/or more reliable is welcome :wink: .

fix(connectInfiniteHits): fix page state when adding or removing widgets

---

src/widgets/hits-per-page/__tests__/hits-per-page-test.js
src/widgets/numeric-menu/__tests__/numeric-menu-test.js

These messages do not do anything, and have been here since the migration towards jest (our previous test suite used the messages).
https://github.com/algolia/instantsearch.js/pull/4105#discussion_r321186048
TODO: rebase when fs-clearRefinements is merged

chore(test): remove unused messages on assertions

---

src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
src/connectors/voice-search/connectVoiceSearch.ts
src/lib/voiceSearchHelper/index.ts
src/widgets/voice-search/voice-search.tsx
stories/voice-search.stories.ts

Two new arguments:
- `additionalQueryParameters: () => Partial<SearchParameters>` (only applied when voice search is mounted)
- `language: string` (iso 639-1), the parameter sent to Algolia will be always the short version
known limitation: additional query parameters will stay applied as long as the Voice Search widget is mounted, meaning they can cause stale values if you switch input method without unmounting (limitation of the architecture of InstantSearch)

feat(voice): add additional query parameters

---

MIGRATION.md

This is a temporary location, but will allow us to link towards it until it's in the main documentation.

docs(v4): add migration guide

---

src/lib/InstantSearch.ts

We used to notice users coming from InstantSearch v2 that `urlSync` was replaced by `routing` in v3. We can remove this error in InstantSearch v4.

fix(urlSync): remove outdated `urlSync` error

---

MIGRATION.md
src/lib/InstantSearch.ts
src/lib/RoutingManager.ts
src/types/instantsearch.ts

This PR removes the dependency of `Widget` on the type `Router`. The only method that both have in common is `dispose` but with a different signature. The `Router` doesn't have to receive `Helper`, `State`. The only data structures it has to care about are: `UiState`, `RouteState`. 
The update of the signature is indeed a breaking change but it shouldn't have an impact on user-land. The implementation of a custom router is rare. The usage of the arguments of `dispose` would be even rarer.

refactor(router): remove widget dependency

---

src/lib/InstantSearch.ts
src/lib/RoutingManager.ts
test/mock/createInstantSearch.ts

This updates how the `RoutingManager` and `InstantSearch` interact together. 
`InstantSearch` is aware of `stateMapping` and `RouteState` which should not be the case. The only part that is concerned by those details is `RoutingManager`. The `InstantSearch` instance only cares about `UiState`. The `write` part of the  `router` is correctly abstracted behind a `write` method. We have now a `read` function exposed by the manager to avoid manipulate `router` and `stateMapping`.
The subscription to `onUpdate` function is a side effect of `RoutingManager` constructor. While it might be ok, it blocks us to move the declaration of the manager earlier inside the constructor. We already subscribe to the router a bit earlier than before but we don't want to subscribe if the instance does not start. …

refactor(InstantSearch): RoutingManager integration

---

src/lib/__tests__/RoutingManager-test.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

This PR fixes an issue where the initial index name is not correctly set. When a widget manages the `index` (e.g. `sortBy`),  the first computation of the `SearchParameters` could be incorrect. This is because the `Helper` **always override** the `index` provided by the last argument (see [L124](https://github.com/algolia/algoliasearch-helper-js/blob/5a0352aa233c5ea932df6b054a16989c8d302404/src/algoliasearch.helper.js#L124)). The value set by the widget will be overridden anyway.
We now first compute the `SearchParameters` from the widgets with an initial value that contains the top-level `indexName`. If one of the widgets overrides it the return value will contain the correct index if not the original index is preserved (this is not true at the moment, `connectSortBy` will be fixed in a …

fix(index): ensure that we always use the index set by widgets

---

src/connectors/sort-by/__tests__/connectSortBy-test.js
src/connectors/sort-by/connectSortBy.js

This PR ensures that the `sortBy` widget always return a value for `index` (or at least don't remove the current one). The call to `getWidgetSearchParameters` might happen once before the `init` step. The current implementation relies on the `init` step (`this.initialIndex`) when no value is found in the `uiState`. When the widget is not initialized the value set is `undefined` which means that it removes the current index.
To avoid this problem we fall back on the current index when none of the conditions are met. It's the responsibility of the widget to set a value. It doesn't make sense to return `SearchParameters` without an index.

fix(sortBy): ensure a return value for getWidgetSearchParameters

---

src/lib/InstantSearch.ts
src/lib/RoutingManager.ts
src/lib/__tests__/InstantSearch-test.js
src/lib/__tests__/RoutingManager-test.ts

**Summary**
This PR removes a useless walk on the indices to apply the `SearchParameters`, it also removes a useless duplicate request (since we walk two times, we call search two times). At the `init` step we walk on the tree of indices to create each instance with their `uiState` and `SearchParameters`. It means that the state is already set, we don't have to trigger another walk.
The extra walk was called with the result of `read` which is not correct. Inside the constructor we already merge both `initialUiState` & `read`. If an `initialUiState` is present with refinements they are all overridden by `read`. With Storybook we mock the router to always return an empty object. It means that we always remove the `initialUiState` (see below).
You can also see the difference for the …

fix(InstantSearch): remove useless walk/duplicate request

---

src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
This PR fix multiple issues that were spotted after the merge of https://github.com/algolia/instantsearch.js/pull/4104:
* Set `page` to `0` by default so the widget does not get controlled by its parent (fixes https://github.com/algolia/instantsearch.js/pull/4104#discussion_r324602461).
* Excludes `facets`, `maxValuesPerFacet` and filter `facetsRefinements` when comparing the currentState with the prevState (fixes https://github.com/algolia/instantsearch.js/pull/4104#discussion_r324602609).

fix(connectInfiniteHits): fix state when navigating or adding/removing widgets

---

src/lib/__tests__/RoutingManager-test.ts
src/lib/routers/history.ts

**Summary**
This PR fixes an issue with the `historyRouter` + `simpleStateMapping`. They push an empty query string into the URL. The problem arise because we now always have an object with at least on key which is the top level index. The condition to add or not the query string is done on the `routeState` but it could be done on the query string itself since we already have computed it.
**Before**
**After**

fix(history): avoid empty query string

---

src/components/Pagination/Pagination.js
src/components/Pagination/__tests__/Pagination-test.js
src/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap

_This targets the `next` branch because this is a breaking change._
The logic behind the `noRefinement` CSS class differs from one flavor to another. Right now, `noRefinement` is added when on the first page of the search. This doesn't make sense and is incorrect. We want to add the CSS class when no refinements are possible (i.e. there's a single page).
Aligning these behaviors will make creating CSS themes easier because we can hide the pagination widget in CSS when there's no refinement possible. This is a request that we've had several times and using a Panel is necessary for this in InstantSearch.js. We should align these behaviors before next major releases.
There are inconsistencies in the way we consider Pagination to be refinable in our flavors.
- InstantSearch.js: we add the …

fix(pagination): update no refinement behavior

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/autocomplete/connectAutocomplete.ts

This PR adds the `indexId` attribute to the `indices` provided by `autocomplete`.
Only the `indexName` was provided but its value is not stable. The value changes when the index changes e.g. with `sortBy`. A possible use case for stable value is a list of labels. Users might want to have labels on their indices. Without stable values, you can't predict which label you'll have.  The `indexId` solve this problem.

feat(autocomplete): provide indexId

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js

An `index` widget returns its own reference when calling `addWidgets()` and `removeWidgets()`. This makes chainable calls possible.
https://github.com/algolia/instantsearch.js/blob/443cb0610e77ff87b9d054e3b3bf43586fc31810/src/widgets/index/index.ts#L53-L54
However, `instantsearch` widgets methods didn't return the search instance, which was not intuitive when you're used to the `index` behavior.
This PR returns the search instance when calling these methods, so that this becomes possible:
```ts
const search = instantsearch({ /* ... */ });
search
.addWidgets(widgets)
.start();
```

fix(instantsearch): return instance in widgets methods

---

src/components/RefinementList/RefinementList.js
src/components/RefinementList/__tests__/RefinementList-test.js

⚠️ this is port of #4025 on the next branch, to be released in 4.x
**Summary**
The RefinementList is the component used for rendering of the HierarchicalMenu widget.
When a given item of the HierarchicalMenu has children, the RefinementList is recursively called, with the same cssClasses prop.
As a result, the `cssClasses.root` is appearing on every list of children.
This change is proposed because:
1. This is not the specified behaviour.
2. This is not the behaviour observed on InstantSearch V2.
see difference between [InstantSearch V3](https://codesandbox.io/s/ais-ecommerce-demo-app-8snic) and [InstantSearch V2](https://codesandbox.io/s/instantsearchjs-template-7q78t)
In V2, the `cssClasses.root` belonged to the [headerFooter HOC](https://github.com/algolia/instantsearch.js/blob/v2/src/d …

fix(RefinementList 4.x): remove root css class on sublists

---

src/lib/__tests__/InstantSearch-test.js
src/types/widget.ts
src/widgets/index/index.ts

This adds a development warning when the UI state is inconsistent with the widgets mounted on the instance.
We often have users not understanding why certain parameters are not sent to the API. The reason is because widgets drive search parameters. Certain widgets need to be added to the instance for some search parameters to be applied. See a typical issue in #4129.
On support, we often advise to create "virtual widgets" to activate the search parameter, without displaying the widget on the page. This development warning is meant for them to understand why something might look like broken, *and* provide a solution for them.
I suspect this error to happen even more often with InstantSearch.js v4, where UI state is a predominant concept. My hope is that such a warning reduces to support …

fix(index): warn for inconsistent UI state in development mode

---

.storybook/decorators.ts
src/lib/InstantSearch.js
src/lib/__tests__/InstantSearch-test.js

> This PR targets the `develop` branch, thus InstantSearch.js 3.
This displays a development warning when using `searchParameters` on InstantSearch.js 3. This option doesn't exist anymore on v4 and therefore it's better to warn users before reading the migration guide. We instead advise for using the `configure` widget.

fix(instantsearch): warn deprecated usage of `searchParameters`

---

babel.config.js
package.json
scripts/babel/__tests__/wrap-warning-with-dev-check-test.js
scripts/babel/wrap-warning-with-dev-check.js
scripts/rollup/config.js

This fixes warnings being part of the production bundle. This usage is similar to how React strips their warnings in production.
Rollup couldn't infer from the `warning` usage that they should be stripped from the bundle. This PR adds a Babel plugin for wrapping the `warning` calls with the `__DEV__` check, that our tools evaluate to `false` in production and therefore strip in the bundle.
This fix can get backported to v3 so that next versions' bundles are also smaller.

fix: display warnings only in development

---

src/connectors/range/__tests__/connectRange-test.js
src/connectors/range/connectRange.js
src/lib/utils/__tests__/clearRefinements-test.ts
src/lib/utils/clearRefinements.ts

`connectRange` does not clear its UI state when it receives empty refinements, but it only does when it _doesn't_ receive refinements.
1. Go to a [previous deployment](https://deploy-preview-4150--instantsearchjs.netlify.com/examples/e-commerce/search/?brands=Samsung&price=500%3A2000)
2. Notice "Samsung" and "Price" are refined in the URL
3. Click on "Clear filters"
4. **Price range is still in the URL**
In the `clearRefinements` tests, [we did not add the numeric filter attributes in the `disjunctiveFacets`](https://github.com/algolia/instantsearch.js/blob/67dee4ef8fa75d39f8a03d59a65a3a39ad8537b0/src/lib/utils/__tests__/clearRefinements-test.ts#L164-L170), which is a behavior that cannot happen in a real environment: they must be added to `disjunctiveFacets` for the Algolia API to …

fix(range): clear widget state on empty refinements

---

.storybook/static/storybook.css
package.json
src/types/widget.ts
src/widgets/index.ts
src/widgets/index/index.ts
src/widgets/places/__tests__/places-test.ts
src/widgets/places/places.ts
stories/geo-search.stories.js
yarn.lock

The [Places.js widget for InstantSearch](https://github.com/algolia/places/blob/f9f7aa47e73d46866d71dd4d32f80d31234f86f8/src/instantsearch/widget.js) was not longer compatible with InstantSearch 4 because the widget lifecycle changed.
We'll no longer maintain the widget on the Places.js repo but rather provide a Places widget as part of InstantSearch itself. The reasoning behind this decision is that the widget hosted in Place.js couldn't be updated without also bumping Place.js to a major version. We are now more in control of when to release this widget.
This is a port of the existing widget with updated lifecycles and technical stack (TypeScript).
```ts
import algoliaPlaces from 'places.js';
const search = instantsearch({
/* ... */
});
search.addWidgets([
places({
placesReference: …
```

feat(places): add Places widget

---

src/lib/__tests__/InstantSearch-test.js
src/widgets/index/index.ts

**Summary**
In v3, the helper exposed on the instance is the same helper as the one who searches. This means that lastResults is set as expected.
However, with v4 we split this up in the derived helper which actually searches and the exposed helper.
This is fixed now by just setting the last results once the search is done on the derived helper.
**Result**
`search.helper.lastResults` is defined in cases like these: https://codesandbox.io/s/instantsearchjs-app-tkp7h

fix(helper): expose .lastResults to .helper

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
For technical reason we were not able to use `index` as widget name in
the docs, so we picked instead `index-widget`.
When you misuse a widget, we output an error message with a link to the
documentation generated from the name of the widget.
**Result**
N/A

fix: widget name in documentation link for index

---

.storybook/config.ts

This sets the Storybook panel position (for addons) to the bottom instead of the right. This is easier to use and to read.

chore(stories): move panel to bottom

---

src/widgets/infinite-hits/infinite-hits.tsx
stories/infinite-hits.stories.ts

Some options types were marked as required while they were not. In the stories, we should use the direct import to make sure that we leverage our types and spot this kind of issues.

fix(infiniteHits): correct widget options types

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.js
src/connectors/clear-refinements/__tests__/connectClearRefinements-test.js
src/connectors/geo-search/__tests__/connectGeoSearch-test.js
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hits/__tests__/connectHits-test.js
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.js
src/connectors/pagination/__tests__/connectPagination-test.js
src/connectors/powered-by/__tests__/connectPoweredBy-test.js
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/range/__tests__/connectRange-test.js
src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/sort-by/__tests__/connectSortBy-test.js
src/connectors/stats/__tests__/connectStats-test.js
src/connectors/toggle-refinement/__tests__/connectToggleRefinement-test.js
src/connectors/voice-search/__tests__/connectVoiceSearch-test.js
src/lib/utils/__tests__/getObjectType-test.ts
src/lib/utils/checkRendering.ts
src/lib/utils/getObjectType.ts
src/lib/utils/index.ts
src/widgets/panel/__tests__/panel-test.js
src/widgets/panel/panel.js

This PR a follow-up on https://github.com/algolia/instantsearch.js/pull/4233#discussion_r354507001 and aims at displaying more accurate error messages when users don't provide right data types in widgets.
The way we extract the object types is similar to what [Redux Devtools does](https://github.com/reduxjs/redux-devtools/blob/03d1448dc3c47ffd75a8cf07f21399b86d557988/packages/react-json-tree/src/objType.js).

fix(core): display correct object types in messages

---

.circleci/config.yml
package.json
tsconfig.checkjs.json

**Summary**
Following https://github.com/algolia/instantsearch.js/pull/4220 this change adds a new `type-check:js` command that run `tsc` on all TypeScript and JavaScript files. This will allow us to see the remaining errors in the JavaScript files and fix them progressively (by updating the JSDocs or migrating JS files to TS).
This command is run by the CI and always pass ([We cannot allow a test to fail on CircleCI](https://discuss.circleci.com/t/can-we-allow-a-job-to-fail-in-a-workflow/23343)) so we do not block the CI with the existing errors.
When all errors will be fixed the `tsconfig.checkjs.json` config will be merged with the default `tsconfig.json` and this command removed.

chore(typescript): add type-check:js command

---

src/lib/createHelpers.ts
src/lib/utils/__tests__/createHelpers-tests.ts
stories/hits.stories.js

**Summary**
This PR adds a Hogan helper for the `insights` function. 
**Result**: [story](https://5defce0140073d000882b6b5--instantsearchjs.netlify.com/stories/?path=/story/results-hits--with-insights-helper)

feat(insights): add hogan helper

---

src/lib/__tests__/InstantSearch-test.js
src/widgets/index/index.ts

The development warning about inconsistent states warned about wrong information since #4249 for the `range*` widgets. This happened because we were checking for a `$$type` of `ais.range` while they're now `ais.rangeInput` and `ais.rangeSlider`.
Since there's a bit more logic now, I included the `places` widget in the test to make sure the warning also worked with widgets that don't use a connector.

fix(index): fix warning for widgets sharing connectors

---

src/index.es.ts

We never exported the `insights` helper in the ESM build, so the function was never usable. This fixes it by exporting the `insights` helper as we do for `highlight` and `snippet`.

fix(insights): export Insights helper in the ESM build

---

src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test-bridge.ts
src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test.ts
src/connectors/configure-related-items/connectConfigureRelatedItems.ts

This changes how we exclude the `objectID` when using `ConfigureRelatedItems`.
`objectID`s can contain many special characters:
- `\`
- `"`
- `<`
- `>`
- `\n`
- etc.
These special characters don't play well with the `filters` search parameter because they cannot be escaped without the engine to interpret them differently.
Escaping is challenging and somehow impossible when excluding a refinement using [`filters`](https://www.algolia.com/doc/api-reference/api-parameters/filters/):
```
{ filters: NOT objectID:123 }
```
The SQL-like syntax makes the engine less flexible as to what characters to accept.
Using [`facetFilters`](https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/) makes it easier because the syntax is less ambiguous:
```
{ facetFilters: ['objectID:-123'] }
``` …

fix(configureRelatedItems): use `facetFilters` to exclude `objectID`

---

src/lib/__tests__/insights-client-test.ts
src/lib/insights/client.ts
src/lib/insights/listener.tsx
src/widgets/infinite-hits/__tests__/__snapshots__/infinite-hits-test.ts.snap
stories/hits.stories.js

**Summary**
Prior to this change, this error was fired in the click listeners. As a result, users who used a custom component (and therefore a custom listeners) could never see it (they saw instead: insights is `TypeError: insights is not a function`).
Now the insightsClient wrapper itself is responsible for throwing this error.
This also fixes a bug introduced in https://github.com/algolia/instantsearch.js/pull/4197 when the `if (!props.insights) { ... }` was accidentaly brought on top of the handler.
This is not breaking change.
fixes #4269 
**Result**
[View Story →](https://deploy-preview-4254--instantsearchjs.netlify.com/stories/?path=/story/results-hits--with-insights-helper-when-insightsclient-has-not-been-provided)

fix(insights): move 'insightsClient not provided error' to wrapper level

---

package.json
ship.config.js
yarn.lock

**Summary**
Previously I put a wrong reviewer config in the `ship.config.js` file.
And Ship.js was handling it in a wrong way as well.
It turned out the API from GitHub takes separate parameters: `reviewers` & `team_reviewers`.
This way, the new release PRs will have the team automatically assigned as team_reviewers.

chore(release): put correct reviewer config on release PRs

---

ship.config.js

**Summary**
Fix link to release in slack notification as in 
https://github.com/algolia/shipjs/pull/609

chore: use tagName instead of releaseTag in link to release in slack notification

---

src/connectors/geo-search/connectGeoSearch.js

This should go from `hasMapMoveSinceLastRefine` to `hasMapMovedSinceLastRefine`, but changing that now would be a breaking change.

chore(major): add a dev comment to hasMapMoveSinceLastRefine

---

CONTRIBUTING.md
package.json
scripts/release/build-experimental-typescript.js
ship.config.js
yarn.lock

**Summary**
This PR updates the release flow to publish `experimental-typescript` build by default after publishing a normal version.
The addition in `ship.config.js` is the following:
```js
afterPublish: ({ exec }) => {
exec('./scripts/release/build-experimental-typescript.js');
exec(
`yarn publish --no-git-tag-version --non-interactive --tag experimental-typescript`
);
},
```
If you want, you can run `./scripts/release/build-experimental-typescript.js` on your computer. It will create a build with the typescript definition files.
To actually publish it, you can run either
`yarn publish --no-git-tag-version --non-interactive --tag experimental-typescript`
or
`npm publish --tag experimental-typescript`
We normally use yarn, so I put the yarn version in `ship.config.js`.

chore(release): publish `experimental-typescript`

---

ship.config.js

if not given, its default value is:
```js
testCommandBeforeRelease: ({ isYarn }) =>
isYarn ? 'yarn test' : 'npm run test',
```

chore: do not run test again before publish

---

CONTRIBUTING.md
ship.config.js

**Summary**
This PR updates the contributing guide for maintenance and next versions. The changes in the `CONTRIBUTING.md` isn't much, and the following is my rationale behind the changes.
If we check out `maintenance-v3` branch, there is no Ship.js, but there is still `publish-maintenance.sh`. So we can continue to use it. I don't know how many times we will publish the old versions. But, if you think we need Ship.js for `v3`, let me know. I will create another PR to add Ship.js to `maintenance-v3` branch.
For now, the major is v4. If we start preparing v5, and we want to release v5 in alpha or beta, then we will need Ship.js. There is nothing much to do for that. I updated `ship.config.js` like this:
```js
mergeStrategy: { toSameBranch: ['master'] },
// to
mergeStrategy: { toSameBranch: …
```

chore: update contributing guide for maintenance and next versions

---

package.json
scripts/release/build-experimental-typescript.js
ship.config.js
yarn.lock

**Summary**
This PR fix the release flow to include `VERSION` env var before `yarn build`.
https://unpkg.com/instantsearch.js@4.2.0/dist/instantsearch.production.min.js
> /*! InstantSearch.js UNRELEASED (Thu, 23 Jan 2020 15:32:51 GMT) | © Algolia, Inc. and contributors; MIT License | https://github.com/algolia/instantsearch.js */
With the lack of `VERSION`, the last version was released with `UNRELEASED` comment at the top of the bundle.
Now it's attached to both normal release and experimental-typescript release.
**One question**:
Do we just want to throw an error at rollup when `VERSION` is not given?
Or, do we still need `UNRELEASED` for some reason? If so, what is a valid case for that?

chore: add VERSION env var before yarn build

---

package.json
scripts/rollup/config.js
ship.config.js
yarn.lock

**Summary**
This PR actually does two things but they're small enough, so I put it in a same PR and both of them depends on the new update of Ship.js@0.15.0.
When SHIPJS=true and VERSION is undefined, rollup will throw an exception to prevent having a `UNRELEASE` comment in released bundle.
https://unpkg.com/instantsearch.js@4.2.0/dist/instantsearch.production.min.js
When it's a patch release and if there are only chores but no fixes, then `yarn release:prepare` will skip and won't create a PR. What do you think of this behavior? With rules like this, we can later automate `yarn release:prepare`.

chore: validate conditions before release

---

package.json
yarn.lock

**Summary**
This PR updates `algoliasearch-helper` to v3.1.1. This is required for us to build and distribute the UMD package with the latest `algoliasearch-helper` version.
**Result**
This update fixes a case where refinements for a facets with a name that matches a substring of another one could be cleared by mistakes. For more information see the original PR in `algoliasearch-helper` https://github.com/algolia/algoliasearch-helper-js/pull/760

chore(deps): update dependency algoliasearch-helper to v3.1.1

---

CHANGELOG.md
CONTRIBUTING.md
package.json
src/lib/version.ts

Reverts algolia/instantsearch.js#4336 due to an error in the release process.

Revert "chore: release v4.3.0"

---

src/components/RefinementList/RefinementList.js
src/components/RefinementList/__tests__/RefinementList-test.js
src/widgets/refinement-list/__tests__/__snapshots__/refinement-list-test.js.snap
src/widgets/refinement-list/defaultTemplates.js

There's a security issue with the [`refinementList`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/) widget when relying on its default template and routing.
[Security issue demonstration →](https://instantsearchjs.netlify.com/examples/e-commerce/search/?brands=Samsung%22%3E%3Ciframe%2fonload%3dalert%28%22xss%22%29%3E)
**Malicious users could inject some JavaScript code** via the URL to get specific information. This is [Cross-Site Scripting](https://en.wikipedia.org/wiki/Cross-site_scripting) (XSS) vulnerability.
We use `{{{highlighted}}}` in the default [`item` template of the `refinementList` widget](https://github.com/algolia/instantsearch.js/blob/933d9ffb3c0a396a047eeb4b44733b17aa31d081/src/widgets/refinement-list/defaultTemplates.js#L7). The triple braces in …

fix(refinementList): prevent XSS via routing

---

examples/e-commerce/src/routing.ts
src/components/Panel/Panel.tsx
src/connectors/autocomplete/connectAutocomplete.ts
src/connectors/configure-related-items/connectConfigureRelatedItems.ts
src/connectors/configure/connectConfigure.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/connectors/numeric-menu/connectNumericMenu.ts
src/connectors/query-rules/connectQueryRules.ts
src/connectors/voice-search/connectVoiceSearch.ts
src/lib/createHelpers.ts
src/lib/suit.ts
src/lib/utils/getRefinements.ts
src/middleware/createRouter.ts
src/middleware/index.ts
src/types/algoliasearch.ts
src/types/instantsearch.ts
src/types/widget.ts
src/widgets/current-refinements/current-refinements.tsx
src/widgets/infinite-hits/infinite-hits.tsx
src/widgets/panel/panel.tsx
src/widgets/places/places.ts
src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
src/widgets/voice-search/__tests__/voice-search-test.ts
src/widgets/voice-search/voice-search.tsx

This pull request replaces `interfaces` by `types` on the IS type system. The main reason is to be consistent across all the code base.

chore(favours-types): replaces interfaces by types

---

stories/range-slider.stories.js

This updates the [`rangeSlider`](https://www.algolia.com/doc/api-reference/widgets/range-slider/js/) stories to make them more representative of what the widget offers:
- remove non-existant `templates.header` option
- remove custom `tooltips` option by default
- update the `step` value to be more usable and remove `pips` for the story so that it's less confusing (the step is not aligned with the pip)

docs(rangeSlider): update story

---

src/connectors/autocomplete/connectAutocomplete.ts
src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test.ts
src/connectors/configure-related-items/connectConfigureRelatedItems.ts
src/connectors/configure/__tests__/connectConfigure-test.ts
src/connectors/configure/connectConfigure.ts
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/connectors/hits-per-page/connectHitsPerPage.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/connectors/numeric-menu/connectNumericMenu.ts
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/query-rules/connectQueryRules.ts
src/connectors/voice-search/connectVoiceSearch.ts
src/lib/__tests__/insights-client-test.ts
src/lib/insights/client.ts
src/lib/utils/checkRendering.ts
src/types/connector.ts
src/types/widget.ts
src/widgets/configure-related-items/configure-related-items.ts
src/widgets/configure/configure.ts
src/widgets/current-refinements/current-refinements.tsx
src/widgets/hits-per-page/hits-per-page.tsx
src/widgets/infinite-hits/infinite-hits.tsx
src/widgets/panel/panel.tsx
src/widgets/places/places.ts
src/widgets/query-rule-context/query-rule-context.tsx
src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
src/widgets/voice-search/voice-search.tsx

This pull request reduces a little bit the number of types needed while migrating a connector to typescript. In addition, it also makes a the minimum amount of work to have widgets in this new type system.
Note that some new lines are comments to uncommented types before.

chore(ts-migration): refactors connector types

---

.eslintignore

This pull request fixes the reason why `yarn lint` takes a year to lint the project. The reason is because it was trying to linting the ecommerce example.

chore(fixes-yarn-lint-hangs): adds ecommerce example to eslintignore

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/lib/InstantSearch.ts
src/lib/utils/__tests__/clearRefinements-test.ts
src/types/algoliasearch.ts
src/types/instantsearch.ts
src/widgets/index/index.ts
src/widgets/infinite-hits/__tests__/infinite-hits-test.ts

This pull request makes explicit the client type used along instantsearch. Also improves a little bit the type itself, saying that the `addAlgoliaAgent` is optional.

chore(ts-migration): renders explicit the client type

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js

Before releasing the new set of APIs to control the UI state, we mark them as experimental to gather feedback and change their APIs in a next minor if needed.
The warning only happens in `setUiState` because `onStateChange` relies on `setUiState`.
- API documentation: algolia/doc#4352

fix(setUiState): display experimental warning

---

tsconfig.json

This pull request makes the command `yarn type-check` ignore the build folder that contains the type definitions.

chore(tsconfig): ignores build folder that contains type definitions

---

src/components/Breadcrumb/Breadcrumb.tsx
src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/breadcrumb/connectBreadcrumb.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/connectors/hits-per-page/connectHitsPerPage.ts
src/connectors/numeric-menu/connectNumericMenu.ts
src/lib/InstantSearch.ts
src/types/connector.ts
src/widgets/breadcrumb/__tests__/__snapshots__/breadcrumb-test.ts.snap
src/widgets/breadcrumb/__tests__/breadcrumb-test.ts
src/widgets/breadcrumb/breadcrumb.tsx
src/widgets/hits-per-page/hits-per-page.tsx
stories/breadcrumb.stories.js

This pull request migrates breadcrumb ( connectors and widget ) to typescript. Please take in consideration my comments on the pull request.
Internally it also adds new types to make refactor easy: TransformItems, and CreateURL.

chore(ts-migration): migrates breadcrumb files content

---

.eslintignore
.gitignore
api-extractor.json
scripts/build/api-extractor.json
scripts/build/types.js

This pull request improves the current api extrator implementation, creating a temporary single public file API with:
```
export * from '../es/';
export * from '../es/connectors';
export * from '../es/middleware';
export * from '../es/types';
export * from '../es/widgets';
```
Previously, since we were validating file by file, the file `connectors/index.d.ts` was complaining that  'types' folder contains types that are not exported at `connectors/index.d.ts` ( the root level for api extrator ).
With this change, we are creating a temporary single file public api, and api extrator will no longer report those false positives.
@Haroenv We can't avoid the temporary folder in this case, as node don't have rights to write on the root system.

chore(ts-migration): improves validating of types with api extractor

---

src/widgets/configure/configure.ts

This pull request fixes the types on the configure widget, they aren't exported and the name was incorrect.

chore(ts-migration): fixes configure widget types

---

src/lib/routers/__tests__/history.test.ts
src/lib/routers/history.ts

**Summary**
Every write puts a history entry, we never want to write the same as what's already written to the URL.
Demonstration of the bug being fixed in user land: https://codesandbox.io/s/vigilant-mayer-u3lyd?file=/src/app.js:2097-2279 (note that this searchFunction is very similar to the default one in Shopify)
The history router didn't have tests yet, so I added just one for this case, as not to lose time writing tests for existing cases.
**Result**
condition around pushing the URL, meaning it won't write if the URL is already the same. In theory a createURL could give a non-qualified URL, but that would make this condition a lot more complicated, so I'm ok with that caveat.
Also fixed the typescript of the class wrapper a bit

fix(router): don't write an existing URL

---

src/components/InfiniteHits/InfiniteHits.tsx
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/lib/insights/client.ts
src/types/instantsearch.ts
src/widgets/infinite-hits/infinite-hits.tsx

This pull request migrates infinite hits contents.
I have a problem tho, I would like to pass a type to transform items:
```
const widget = makeWidget({
transformItems: <MYSPECIALTYPEHERE>(items) =>
items.map(item => ({
...item,
_highlightResult: {
name: {
value: item._highligh¨tResult.name.value.toUpperCase(),
},
},
})),
escapeHTML: true,
```
Going to try to solve this problem on top with @yannickcr

chore(ts-migration): migrates infinite hits contents

---

src/lib/utils/__tests__/range-test.ts
src/lib/utils/range.ts

**Summary**
The range was incorrectly calculated when a step was set and the start value was not 0. This was due to a small error in the range calculation (misplaced parenthesis).
For example with `{ start: 1300, end: 1350, step: 5 }` the calculation would have been `(1300 + 0) * 5` instead of `1300 + 0 * 5`, making the steps to start at `6500` instead of `1300`.
Helpscout ticket: https://secure.helpscout.net/conversation/1147259825/250436
**Result**
The range is now correctly calculated. I added a new test to validate the fix and also updated the result for the `rounds decimal array lengths` one (the previous result seems incorrect, the new result with the fix seems more correct to me).

fix(range): fix range calculation when step is set

---

.github/ISSUE_TEMPLATE/config.yml

This leverages the [GitHub Template Chooser](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) to direct people to the right platform based on their intentions.
- Bug report → GitHub Issue with the Bug Report template
- Feature Request → GitHub discussion to better leverage threads and the Discussions feature
- Question → GitHub discussion to better leverage threads and the Discussions feature
When opening an issue, you would have this screen:

chore(github): update template chooser

---

package.json
yarn.lock

**Summary**
This PR updates the `instantsearch-e2e-tests` dependency to v1.3.0.
See the CHANGELOG: https://github.com/algolia/instantsearch-e2e-tests/blob/master/CHANGELOG.md#130-2020-04-17

chore(deps): update dependency instantsearch-e2e-tests to v1.3.0

---

CONTRIBUTING.md
api-extractor.json
package.json
scripts/build/types.js
scripts/release/build-experimental-typescript.js

This pull request is the last one of my mission. And it just reverts some work optimistic work done at the beginning that I thought we could deliver 100% this quarter. 
Some important notes:
- I have re-tested all 45% connectors/widgets migrated in this mission using a real instant-search project in typescript with the snippets from the docs.
- API Extractor shows tons of warnings while validating types as they are tons of missing exports, I guess we are going to address them once we have 100% connectors/widgets migrated.
- Running `tsc` with a project that requires `4.4.1-experimental-typescript.0` still shows 5 errors ( 7 prior to this mission ). Would be cool to address that soon.

chore(ts-migration): improves build

---

src/connectors/configure-related-items/connectConfigureRelatedItems.ts

These methods have been typed since then:
- https://github.com/algolia/algoliasearch-helper-js/pull/753
- https://github.com/algolia/algoliasearch-helper-js/pull/754

chore(helper): remove outdated helper comments

---

.circleci/config.yml
CONTRIBUTING.md
package.json

**Summary**
This PR simplifies the command we run to prepare a release.
- Before: `yarn run release:prepare`
- After: `yarn run release`
On CircleCI, it used to run `yarn run release:trigger`, but now it runs `yarn shipjs trigger`.

chore: update release script name

---

src/components/RangeInput/RangeInput.js

This PR fixes a regression which disabled floating numbers in rangeInput widget.
**Before this PR**
```js
onInput = name => event => {
this.setState({
[name]: Number(event.currentTarget.value),
});
};
```
When user wants to type "10.34", that callback will be fired with the following `event.currentTarget.value` values:
- `1`
- `10`
- `10.`
- `10.3`
- `10.34`
When it had "10.", `Number("10.")` returns `10` which makes the input value back to `10`. So people never can get to "10.3".
So I removed `Number()` function there (which was the case before the regression). And I used `Number()` when refining.
* [The working example from this branch](https://codesandbox.io/s/instantsearchjs-0d34s?file=/src/app.js:382-470)
* [The failing example from …

fix(rangeInput): fix a bug that floating number cannot be typed

---

src/components/Pagination/Pagination.js
src/components/Pagination/__tests__/Pagination-test.js
src/connectors/pagination/Paginator.js
src/connectors/pagination/__tests__/Paginator-test.js

fixes https://github.com/algolia/vue-instantsearch/issues/785
**Summary**
This is discovered by @dotboris. When there are no pages, this.total === 0, so this.currentPage - 1 will be -1 instead of 0, and falsely indicate it's not the last page.
**Result**
isLastPage is true when there's no results.

fix(pagination): isLastPage when there's no pages

---

src/connectors/toggle-refinement/__tests__/connectToggleRefinement-test.js
src/connectors/toggle-refinement/connectToggleRefinement.js
src/lib/utils/__tests__/toArray-test.ts
src/lib/utils/index.ts
src/lib/utils/toArray.ts
src/widgets/toggle-refinement/toggle-refinement.js

Hi :wave: 
This PR is a proposal for #2182 which add support for multiples values on `on`/`off` for the toggle refinement connector.
See #2182 for more information.
**Result**
It allow us to use the toggle refinement connector with multiple values:
```js
connectToggleRefinement()({
attribute: 'whatever',
on: ['my', 'values'],
off: ['something', 'else']
});
```
and the toggle refinement widget:
```js
search.addWidget(instantsearch.widgets.toggleRefinement({
container: '#toggle',
attribute: 'whatever',
on: ['my', 'values'],
off: ['something', 'else']
}));
```
On [the playground](https://codesandbox.io/s/instantsearchjs-y5pyp), I've used:
```js
toggleRefinement({
container: '#toggle',
attribute: 'brand',
on: ['Sony', 'Incipio'],
}),
```
and you can see it toggle both values.
What do you …

feat(connectToggleRefinement): add support for array values

---

src/components/RangeInput/RangeInput.js
src/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap

**Summary**
This PR fixes `RangeInput` component to correctly clear `<input>` when the state becomes nullish.
Once it's rendered, when either `state.min` or `state.max` becomes nullish (undefined or null, e.g. when "clearRefinements" is clicked), it doesn't remove the value, because `<input>` doesn't take nullish value. Instead, we need to pass an empty string.
**Result**
* [This example](https://codesandbox.io/s/instantsearchjs-0sdrc?file=/index.html) is built with the `v4.6.0`. If you refine, then clear it, the inputs won't be reset.
* [This example](https://codesandbox.io/s/instantsearchjs-y4xd1?file=/index.html) is built with the version in this pull-request. In this case, the inputs get reset correctly.
**Snapshots**
Some snapshots changed which I think will barely affect users. What …

fix(rangeInput): clear input when refinement is cleared

---

examples/e-commerce/src/routing.ts

In #4408, we updated the e-commerce example and casted the type of the `page` URL parameter to `string`, which when `undefined`, became `"undefined"`.
This causes a bug that you can reproduce with these steps:
- Go to https://deploy-preview-4408--instantsearchjs.netlify.app/examples/e-commerce/
- Select a brand
- Notice `?page=undefined` in the URL
You can try the above steps in this PR deployment, which works as expected.

docs(examples): fix undefined pagination in e-commerce demo

---

src/widgets/index/index.ts

In #4359, we introduced an unnecessary code branch that never gets executed (and is not covered by any tests).
We reset the `page` `localUiState` but then reassign the whole `localUiState`.

refactor(index): remove unnecessary `page` UI state reset branch

---

src/lib/utils/checkIndexUiState.ts

**Summary**
If a custom connectRange widget is used, the uiState for that widget would always show as "incorrect" and show the dev warning; while it wasn't needed
fixes #4437 
**Result**
https://github.com/algolia/instantsearch.js/blob/master/src/widgets/range-input/range-input.js#L170 e.g. edits the $$type (see #4227), but that means that the base type was no longer accepted, which is fixed here
cc @yonguelink

fix(dev): don't show a warning for connectRange

---

src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/widgets/index/index.ts

fixes https://github.com/algolia/instantsearch.js/issues/4409
This PR fixes some bugs around controlled mode.
https://codesandbox.io/s/instantsearchjs-xr81o?file=/src/app.js
load some pages, refresh, and click "Show previous". It won't work correctly.
https://codesandbox.io/s/instantsearchjs-x713i?file=/src/app.js
cannot load more page.
- ✅ [showPrevious + onStateChange](https://codesandbox.io/s/instantsearchjs-pb4hc?file=/src/app.js)
- ✅ [showPrevious](https://codesandbox.io/s/instantsearchjs-ykjr9?file=/src/app.js)
- ✅ [onStateChange](https://codesandbox.io/s/instantsearchjs-737yh?file=/src/app.js)
- ✅ [normal](https://codesandbox.io/s/instantsearchjs-fhz1e)
- ✅ [onStateChange without pagination](https://codesandbox.io/s/instantsearchjs-yi2j1)
With the example `showPrevious + …

fix(infiniteHits): work with controlled mode

---

.codesandbox/ci.json

**Summary**
This PR updates the CodeSandbox CI configuration.
It now runs `yarn run build`, but if it runs only `yarn run build:es` it can reduce the build time.
**Result**
Same, but faster.

chore: update buildCommand for CodeSandbox CI

---

src/connectors/toggle-refinement/__tests__/connectToggleRefinement-test.js
src/connectors/toggle-refinement/connectToggleRefinement.js

**Summary**
I was working on #4445 and I found a bug introduced by myself in #4420. :neutral_face: 
The bug is in `render` method, where `onFacetValue` and `offFacetValue` could be wrong when using arrays for `on` or `off`.
I've added a failing test: 
**Result**
`render` method now handle `onFacetValue` and `offFacetValue` correctly when using arrays for `on` and `off` options.
Thanks!

fix(connectToggleRefinement): fix onFacetValue/offFacetValue on render when using arrays for on/off

---

package.json
yarn.lock

**Summary**
This PR updates the version of `algoliasearch-helper` from 3.1.1 to 3.2.1.
There is not much of difference between `^3.1.1` and `^3.2.1`, but when I tried to test something specific from 3.2.0, CodeSandbox wrongly resolved 3.1.1, probably because of the yarn.lock file inside InstantSearch.js.

chore(deps): bump algoliasearch-helper from 3.1.1 to 3.2.1

---

package.json
src/connectors/search-box/__tests__/connectSearchBox-test.js
src/connectors/search-box/connectSearchBox.js
src/lib/InstantSearch.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
src/widgets/search-box/__tests__/search-box-test.js
test/mock/createInstantSearch.ts
test/mock/createWidget.ts

> This is part 2 of the series "[Render State](https://github.com/algolia/instantsearch-rfcs/pull/38)".
- algolia/instantsearch-rfcs#38
- algolia/instantsearch.js#4454
This introduces the widget lifecycle hook `getWidgetRenderState` and implements it for `connectSearchBox`.
The `getWidgetRenderState` method allows to accumulate and store the global render state of the widgets tree. This render state has a similar structure to the UI state but stores the render params.
When you mount a widget in the InstantSearch tree, you may want to use its render params (e.g., `refine` function) in another widget to create richer and more interactive interfaces.
In InstantSearch.js, it requires using the JavaScript helper, which means that you get out of the InstantSearch API. In React InstantSearch, …

feat(core): introduce `getWidgetRenderState` (2/n)

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/autocomplete/connectAutocomplete.ts
src/types/widget.ts

This implements the `getWidgetRenderState` widget lifecycle hook in `autocomplete`.
⚠️ The following line throws a [TypeScript error](https://app.circleci.com/pipelines/github/algolia/instantsearch.js/4567/workflows/9954690f-500b-42af-8d85-4c986dc45b1e/jobs/19424/parallel-runs/0/steps/0-107) that I plan to fix in a later PR to move forward with this widget API (any help is welcome):
https://github.com/algolia/instantsearch.js/blob/3639991ce5f32199710d1bc9d685b88793465178/src/types/widget.ts#L147-L152

feat(autocomplete): implement `getWidgetRenderState`

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/breadcrumb/connectBreadcrumb.ts
src/types/widget.ts
stories/breadcrumb.stories.js

This implements the `getWidgetRenderState` widget lifecycle hook in `breadcrumb`.

feat(breadcrumb): implement `getWidgetRenderState`

---

src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/clear-refinements/connectClearRefinements.ts
src/types/widget.ts

This implements the `getWidgetRenderState` widget lifecycle hook in `clearRefinements`.

feat(clearRefinements): implement `getWidgetRenderState`

---

src/connectors/configure/__tests__/connectConfigure-test.ts
src/connectors/configure/connectConfigure.ts
src/types/widget.ts

This implements the `getWidgetRenderState` widget lifecycle hook in `configure`.

feat(configure): implement `getWidgetRenderState`

---

src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/types/widget.ts

This implements the `getWidgetRenderState` widget lifecycle hook in `currentRefinements`.

feat(currentRefinements): implement `getWidgetRenderState`

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/breadcrumb/connectBreadcrumb.ts
src/types/widget.ts

This fixes the `breadcrumb` widget where the attribute was missing in the render state.

fix(breadcrumb): add attribute to render state

---

package.json
scripts/build/types.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/connectors/hits-per-page/connectHitsPerPage.ts
src/connectors/hits/connectHitsWithInsights.ts
src/connectors/infinite-hits/connectInfiniteHitsWithInsights.ts
src/lib/voiceSearchHelper/index.ts
src/types/algoliasearch.ts
src/widgets/panel/__tests__/panel-test.ts
src/widgets/places/places.ts
yarn.lock

**Summary**
This PR fixes some miscellaneous typescript issues discovered in angular instantsearch
**Result**
- if JS client v3 is used, it's imperative that the ts-ignore comments stay present, since not the same exports are used. Solution is to double-annotate to keep the multi-line version in exposed to the d.ts (see e.g. https://github.com/microsoft/TypeScript/issues/39520)
- similar in places.js
- when updating TypeScript, I found that api-extractor can't deal with `import()` types, so those have to be transformed
- fix stricter behaviour of tranformItems in hitsPerPage (we send the user the "render" values, not the one they entered)
- SpeechRecognitionError is no longer exported in lib.d.ts, and is a generic Event now
- updated Typescript to 3.8.3. I've tried 3.9.2 as well, but that …

fix(typescript): export correct types

---

src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test.ts
src/connectors/configure-related-items/connectConfigureRelatedItems.ts

This brings support for nested attributes in the [`configureRelatedItems`](https://www.algolia.com/doc/api-reference/widgets/configure-related-items/js/) widget.
Previously, an attribute like `hierarchicalCategories.lvl0` was considered as non-existant because we were accessing it as `hit[hierarchicalCategories.lvl0]`. We now access it with our `getPropertyByPath` which correctly picks up the attribute.
Implement the same fix in React InstantSearch.
- [Slack message](https://algolia.slack.com/archives/C2XP6HBKQ/p1597715211006100)

fix(configureRelatedItems): support nested attributes

---

.eslintrc.js
src/components/RefinementList/__tests__/__snapshots__/RefinementList-test.js.snap
src/components/SearchBox/SearchBox.js
src/components/SearchBox/__tests__/SearchBox-test.js
src/components/SearchBox/__tests__/__snapshots__/SearchBox-test.js.snap

**Summary**
React and Preact differ slightly in how they pass attributes / properties. Therefore it seems like the correct value (although https://github.com/preactjs/preact/issues/485 says otherwise, that must have changed in preact X). This was causing `spellcheck` not to be applied.
see: https://github.com/preactjs/preact/blob/020d5e599b8b84745932f092a835f494b1dd2261/src/jsx.d.ts#L711
ref: https://discourse.algolia.com/t/how-to-add-spellcheck-property-to-search-box-widget/10741
**Result**
The `spellcheck` property is actually on the dom node for input.
I have checked, and the other properties on the input are present.

fix(searchBox): pass "spellcheck" property correctly to input

---

babel.config.js

**Summary**
While the prop-type values were removed, the package itself wasn't removed
**Result**
removed the `prop-types` package import as well
bundle size pre:
```
PASS  ./dist/instantsearch.production.min.js: 63.84KB < maxSize 64KB (gzip)
PASS  ./dist/instantsearch.development.js: 148.86KB < maxSize 160KB (gzip)
```
bundlesize post:
```
PASS  ./dist/instantsearch.production.min.js: 62.39KB < maxSize 64KB (gzip)
PASS  ./dist/instantsearch.development.js: 146.19KB < maxSize 160KB (gzip)
```
The change is 1.45KB or 2% of our size (in production)
I inspected the built files thoroughly, and apart from 1041 other rename changes (because minified), the only change is that the `prop-types` code base no longer was present.

fix(bundlesize): remove prop-type imports

---

src/widgets/refinement-list/__tests__/__snapshots__/refinement-list-test.js.snap
src/widgets/refinement-list/defaultTemplates.js

**Summary**
I had a look at the source map explorer, and found that the refinementList had a big defaultTemplates file.
Since the refinementList already uses searchBox, this doesn't add any new code if you're not using searchBox.
**Result**
Slightly smaller bundle size, but not so significant after gzip (.04KB)

chore(refinementList): reuse templates from searchBox

---

src/connectors/hits-per-page/connectHitsPerPage.ts

**Summary**
Replaces a link to the docs on the old website with one on the new one.
**Result**
A developer would see v4 docs instead of v2.

fix(hitsPerPage): update link to hitsPerPage widget

---

src/lib/insights/listener.tsx

**Summary**
This PR fixes the regression introduced since 4.8.0 where InstantSearch didn't send Insights events implemented with `instantsearch.insights()` in `hits` or `infiniteHits` widgets.
**Result**
It sends events now.
**Test**
If you run this [example ->](https://codesandbox.io/s/throbbing-worker-5or8z?file=/src/app.js), it will correctly send events when you click buttons. However if you change the version of InstantSearch to 4.8.0, it won't any more.

fix(insights): fix the regression that it didn't send events with instantsearch.insights()

---

package.json
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/refinement-list/connectRefinementList.js

We cap the [`maxFacetHits`](https://www.algolia.com/doc/api-reference/api-parameters/maxFacetHits/) value to 100 because the Algolia API doesn't support a greater number.
An Enterprise customer has faced this issue in Vue InstantSearch and it's challenging to fix user-land.
Closes #4521.

fix(refinementList): cap `maxFacetHits` to 100 for SFFV

---

src/helpers/__tests__/get-insights-anonymous-user-token-test.ts
src/helpers/__tests__/insights-test.ts
src/helpers/get-insights-anonymous-user-token.ts
src/helpers/index.ts
src/helpers/insights.ts
src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js
src/lib/insights/__tests__/client-test.js
src/lib/insights/client.ts
src/middlewares/createInsightsMiddleware.ts
src/widgets/analytics/__tests__/analytics-test.ts
src/widgets/analytics/analytics.ts

**Summary**
This PR deprecates and shows warning messages for the following things:
- `getInsightsAnonymousUserToken()`
- `InstantSearch({ insightsClient })` ← `insightsClient` prop
- `analytics` widget

fix(insights): show deprecation warnings for old insights related properties and functions

---

src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/types/widget.ts

This implements the `getWidgetRenderState` widget lifecycle hook in `hits`.

feat(hits): implement `getWidgetRenderState`

---

src/connectors/range/__tests__/connectRange-test.js
src/connectors/range/connectRange.js
src/types/widget.ts

This implements the `getRenderState` and `getWidgetRenderState` widget lifecycle hooks in `range`.

feat(range): implement `getRenderState` and `getWidgetRenderState`

---

src/connectors/infinite-hits/connectInfiniteHits.ts
src/widgets/infinite-hits/__tests__/infinite-hits-integration-test.ts

**Summary**
This PR fixes an issue where `connectInfiniteHits` was caching the `cachedHits` internally. Even if the cache gets cleared, the connector cannot know it. It's an unnecessary double layer of caches.
fixes #4531 
**Result**
After the cache gets invalidated, the connect should read hits correctly from the results.
The following example works:
https://codesandbox.io/s/dreamy-forest-eofp6?file=/src/app.js

fix(infiniteHits): do not cache the cached hits inside the connector

---

src/connectors/autocomplete/connectAutocomplete.ts
src/connectors/hits-per-page/connectHitsPerPage.ts
src/lib/__tests__/insights-client-test.ts
src/types/widget.ts
src/widgets/analytics/analytics.ts
src/widgets/breadcrumb/breadcrumb.tsx
src/widgets/configure-related-items/configure-related-items.ts
src/widgets/configure/configure.ts
src/widgets/places/places.ts

**Summary**
This PR fixes a bunch of type errors in `feat/render-state` branch. This PR is not fixing all the type errors, because there will be separate PRs for connectors and corresponding widgets.
**TODO**

fix(types): fix type errors

---

src/connectors/configure/connectConfigure.ts
src/lib/__tests__/InstantSearch-integration-test.ts

**Summary**
This PR fixes the bug `configure` connector didn't pass the latest state to `onStateChange` when `refine` happened from it.
fixes #4421
**Result**
`onStateChange` receives the latest state. It's addressed in the integration test.

fix(configure): pass the latest state to onStateChange

---

src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/menu/connectMenu.js

This implements the `getRenderState` and `getWidgetRenderState` widget lifecycle hooks in `menu`.
I'm not too sure about the tests but as usual, any help is welcome!

feat(menu): implement `getRenderState` and `getWidgetRenderState`

---

src/components/Panel/Panel.tsx
src/widgets/panel/__tests__/panel-test.ts
src/widgets/panel/panel.tsx
stories/panel.stories.ts

this kinda works @eunjae-lee, although some parts still seem to be inferred as any. The public API works though
I also made a small change: not using widgetRenderState as key, but spreading the renderer. This way the usage is so much smoother (and you can use it for the templates too, which comes up from time to time)

feat(panel): smoother accessing of widgetRenderState

---

src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/configure/__tests__/connectConfigure-test.ts
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts

**Summary**
This PR adds the missing tests for `getWidgetRenderState` at connectClearRefinements, connectConfigure and connectCurrentRefinements.

test(renderState): add tests for getWidgetRenderState at connectClearRefinements, connectConfigure and connectCurrentRefinements

---

src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/search-box/__tests__/connectSearchBox-test.js

**Summary**
This PR adds the missing tests for getWidgetRenderState at connectHierarchicalMenu and connectSearchBox.

test(renderState): add tests for getWidgetRenderState at connectHierarchicalMenu and connectSearchBox

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts

**Summary**
This PR adds the missing tests for `getWidgetRenderState` at `connectAutocomplete`.
DX-1356

test(renderState): add tests for getWidgetRenderState at connectAutocomplete

---

src/connectors/sort-by/__tests__/connectSortBy-test.js
src/connectors/sort-by/connectSortBy.js

This implements the `getRenderState` and `getWidgetRenderState` widget lifecycle hooks in `sortBy`.

feat(sortBy): implement `getRenderState` and `getWidgetRenderState`

---

src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/connectors/powered-by/connectPoweredBy.ts

**Summary**
This PR fixes two minor issues:
1. In `connectHits`, it didn't return `sendEvent` and `bindEvent` in some condition. Now it does.
2. Casting an empty object as `typeof widgetParams` in `connectPoweredBy`.
Both discovered by `yarn type-check`.

fix(hits): provide `sendEvent` and `bindEvent` to `init`

---

src/connectors/sort-by/connectSortBy.js

This prevent double computation while getting the `currentIndex` in `init`

fix(sortBy): get `currentIndex` from `getWidgetRenderState`

---

src/connectors/stats/__tests__/connectStats-test.js
src/connectors/stats/connectStats.js

This implements the `getRenderState` and `getWidgetRenderState` widget lifecycle hooks in `stats`.

feat(stats): implement `getRenderState` and `getWidgetRenderState`

---

src/types/connector.ts
src/types/widget.ts
src/widgets/analytics/analytics.ts
src/widgets/places/places.ts

**Summary**
fix typing of widgetParams in the context of connectors & getWidgetRenderState 
**Result**
wdigetParams in the context of getWidgetRenderState is different in the two contexts:
- in connectors it's connectorparams & twidgetparams (they pass all arguments from widgetParams through to widgetParams in getWidgetRenderState)
- in widgets it's actually only connectorparams (they don't pass all arguments through to the connector, and set defaults)

chore(ts): update typing of widgetParams

---

src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts
src/types/insights.ts
test/mock/createInsightsClient.ts

There is a bug where an error is thrown when sending events right after creating `insights` middleware.
It happens only when:
- The UMD version of `search-insights` is used.
- The `search-insights` is not loaded yet at the time of creation of `insights` middleware.
In `insights` middleware, the way it intializes `insightsClient` is asynchronous. If it happens too late (normally it happens when the library itself hasn't loaded yet), sending event will throw an error saying "the insightsClient is not intialized yet".
So, in this PR, we change to initialize `insightsClient` synchronously without checking if it was already initialized before.
Before this PR, userToken that was set before creating insights middleware was ignored. However since this PR, that has to  change, because although …

fix(insights): do not throw when sending event right after creating insights middleware

---

src/middlewares/createInsightsMiddleware.ts

In #4575 we introduced a regression in IE because we used the native `find` method instead of our internal util.
- https://algolia.slack.com/archives/C2XP6HBKQ/p1605624265187700
- https://secure.helpscout.net/conversation/1340807801/309760?folderId=3647171

fix(insights): use internal `find` util method

---

src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/numeric-menu/connectNumericMenu.ts

**Summary**
This PR intializes `connectorState` before `init`. Since `refine` and `createURL` was initialized in `init`, it threw an exception when `getRenderState` was called inside `index` widget.
It's fixed with a regression test.

fix(renderState): initialize connectorState before init

---

src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
src/connectors/rating-menu/connectRatingMenu.js

**Summary**
Similar to https://github.com/algolia/instantsearch.js/pull/4579, this PR moves the `sendEvent` initialization into `getRenderState` so it is properly initialized if it gets called before `init`.
The `init` calls were also removed from the `getRenderState` and `getWidgetRenderState` tests and the tests were splitted (with and without results).

fix(renderState): initialize sendEvent before init

---

babel.config.js
package.json
src/lib/utils/find.ts
yarn.lock

**Summary**
We want to avoid polyfills to be needed for eg. Array.find, since it's not supported on IE11 and avoid issues like https://github.com/algolia/instantsearch.js/pull/4580
**Result**
adds a new babel plugin for umd compilation only which is normally meant for injecting polyfills, but we use to error when a polyfill would be needed
In theory we could write our own polyfill provider ([docs](https://github.com/babel/babel-polyfills/blob/main/docs/polyfill-provider.md)), but that seems more complicated that using the existing es-shims one.
Thanks @ljharb for helping me out on the babel slack with understanding this!

ci(polyfills): enfore no unwanted polyfills are used

---

src/helpers/__tests__/highlight-test.ts
src/helpers/__tests__/snippet-test.ts
src/helpers/highlight.ts
src/helpers/snippet.ts
src/lib/utils/__tests__/getPropertyByPath-test.ts
src/lib/utils/getPropertyByPath.ts

React InstantSearch already supports this form for attribute, and it gets documented in https://github.com/algolia/doc/pull/5141
In a future major we can drop the string form for a safer access to the values (especially if eg. the value contains dots)

feat(highlight): accept array for attribute

---

src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/refinement-list/connectRefinementList.js
src/types/widget.ts

This implements the `getRenderState` and `getWidgetRenderState` widget lifecycle hooks in `refinementList`.

feat(refinement-list): implement `getRenderState` and `getWidgetRenderState`

---

src/lib/InstantSearch.ts
src/middlewares/createRouterMiddleware.ts

**Summary**
Since we have added the router middleware, InstantSearch has gained the setUiState function which does practically the same (except it also warns for invalid state, which is useful for routing!).
**Result**
There's a couple existing tests on this behaviour that fail if the onUpdate code is removed
Bundle size should be slightly smaller, but likely not significantly

chore(router): deduplicate uiState setting code

---

package.json
yarn.lock

**Summary**
This PR updates `algoliasearch-helper` to 3.3.4 to warn users about invalid userToken.
related: https://github.com/algolia/algoliasearch-helper-js/pull/802

fix: warn about invalid userToken

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
This is useful for recreating what an index widget does when it renders, see ssr in Vue, as well as poc/telemetry2
I think in the future we might want a function to retrieve the parameters given to render / init.
**Result**
index exposes the scoped `createURL` function to be used in render / init / getWidgetRenderState etc.

feat(index): expose createURL

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
like #4603, scoped results is also useful to be exposed for Vue InstantSearch & telemetry
**Result**
new function on index widgets: `getScopedResults` which is used in render for all widgets already.

feat(index): expose scoped results getter

---

src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/menu/__tests__/connectMenu-test.js
src/connectors/refinement-list/__tests__/connectRefinementList-test.js
src/connectors/toggle-refinement/connectToggleRefinement.js
src/lib/utils/__tests__/createSendEventForFacet-test.ts
src/lib/utils/createSendEventForFacet.ts

**Summary**
The values for personalisation are meant to be identical to those of the engine, otherwise they show up twice
**Result**
Values to send to insights are no longer stringified

fix(insights): don't quote values

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
The warning for usage of getWidgetState was slightly too aggressive, and would trigger for index widgets as well (since they have getWidgetState on top of getWidgetUiState).
We no longer warn if there's both a getWidgetState and getWidgetUiState. 
As an alternative, we could also check widget's $$type and avoid warning specifically for index
**Result**
No longer a warning when an index widget is a child of an index widget (aka index widget is used at all

fix(index): do not warn for nested index widget

---

src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts

**Summary**
Without this, if init is called multiple times (like in Vue InstantSearch), multiple event listeners are attached, as well as the helper being recreated. This causes the references from the first init call to no longer being correct later in the instance.
Since we save the references in the very first call of getWidgetRenderState in most widgets (`if (!refine) refine =`), the helper reference needs to stay stable.
**Result**
This fixes https://github.com/algolia/vue-instantsearch/issues/911 by avoiding to have a different helper instance when init gets called multiple times.

fix(index): only set listeners on init once

---

src/connectors/clear-refinements/connectClearRefinements.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/query-rules/connectQueryRules.ts
src/lib/utils/getRefinements.ts

**Summary**
this use case came up in a support ticket, they wanted to add a query rule when the query _did not_ match something. The engine only has positive matches, so negative matches need to be done frontend.
**Result**
Before that use case was implemented like this: https://codesandbox.io/s/dynamically-deactivate-rule-forked-wouf8?file=/src/app.js 
With this PR it can be implemented like this: https://codesandbox.io/s/dynamically-deactivate-rule-forked-h9w20?file=/src/app.js
(still a bit longer than I wanted, but that's because you can't transform inside trackedFilters, and enabling it would be a breaking change)

feat(queryRuleContext): allow to make refinements based on query

---

package.json
yarn.lock

**Summary**
Updates babel from 7.8.3 to 7.9.6 to support Node.js 14.x+ (including 13.x) as development environment.
https://babeljs.io/blog/2020/03/16/7.9.0
Increases the prod package size by 0.15 kB (cf. the previous increment: 734b2f46)
**Result**
Closes #4639 
Replaces #4640

chore(build): update babel from 7.8.3 to 7.9.6

---

src/connectors/numeric-menu/connectNumericMenu.ts
stories/voice-search.stories.ts

**Summary**
remove needless references to window in the source code
**Result**
remaining references to window:
- analytics (but this widget is deprecated)
- geoSearch (but this is up to the user)
- sessionStorage (but this is feature-checked and has no alternative for node)
- poweredBy (but it's feature-checked)
- routing (this should likely be rethought with server side rendering in mind, for now people use custom routers)
fixes #4650

fix(compat): remove references to window

---

src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts

**Summary**
helper.setQueryParameter resets the page, unlike helper.state.setQueryParameter
Also added a new test for the correct state of the page in both cases of setQueryParameter.
see https://github.com/algolia/vue-instantsearch/issues/888 (doesn't fix that issue, but this issue is uncovered there)
**Result**
using insights middleware no longer resets the page

fix(insights): don't reset page

---

package.json
src/connectors/index.ts
src/widgets/index.ts

**Summary**
This PR exports the `smartSort` widget and the `connectSmartSort`, which was missed in the previous PR.
**Result**
Users can import and use them.

fix(smartSort): export the widget and the connector

---

package.json
yarn.lock

**Summary**
This PR updates the dependency `algoliasearch` to 4.8.6, which updates the type for Answers widget.
related: https://github.com/algolia/algoliasearch-client-javascript/pull/1258

chore(deps): update Answers type (bump algoliasearch to 4.8.6)

---

src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/helpers/__tests__/insights-test.ts
src/helpers/insights.ts
src/lib/__tests__/insights-listener-test.tsx
src/lib/insights/listener.tsx
src/lib/utils/__tests__/createSendEventForHits-test.ts
src/lib/utils/createSendEventForHits.ts
src/lib/utils/index.ts
src/lib/utils/serializer.ts

This PR updates the way we serialize & deserialize payloads for `bindEvent`. It's internal and users never got to deserialize by themselves, so it's not a breaking change.
Since ["add hits and attributes to InsightsEvent" PR](https://github.com/algolia/instantsearch.js/pull/4667), `bindEvent` method now serializes `hits` as well. And `hits` can contain special characters unlike the payloads that we used to have in insights middleware.
For example, 
```
btoa('™')
> Uncaught DOMException: String contains an invalid character
```
but
```
btoa(encodeURIComponent('™'))
> "JUUyJTg0JUEy"
decodeURIComponent(atob("JUUyJTg0JUEy"))
> "™"
```
It's actually not about this PR, but about the previous ["add hits and attributes to InsightsEvent" PR](https://github.com/algolia/instantsearch.js/pull/4667). …

fix(bindEvent): escape payload correctly

---

src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts

We need to declare the type to jest.fn() so that the return type of getInitializedWidget doesn't get tainted and becomes any[]
This may need to be done in other widgets too

test(connectNumericMenu): avoid implicit any

---

src/lib/utils/createSendEventForHits.ts

**Summary**
Fix circular dependency in createSendEventForHits
```
src/lib/utils/index.ts -> src/lib/utils/createSendEventForHits.ts -> src/lib/utils/index.ts
```

fix(utils): circular dependency in createSendEventForHits

---

scripts/rollup/config.js

**Summary**
The `build` command should fail when a circular dependency is detected, other warnings will be treated as before.
Related: https://github.com/algolia/instantsearch.js/pull/4680#issuecomment-801794688
Resources: [rollup doc](https://rollupjs.org/guide/en/#onwarn)
This PR should be merged after https://github.com/algolia/instantsearch.js/pull/4680 so that it can prove that it works

chore(ci): make build fail when circular dependency is detected

---

src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts

**Summary**
implements canRefine in connectCurrentRefinements as true when items exist.
DX-1311
**Result**
currentRefinements now has a canRefine

feat(currentRefinements): implement canRefine

---

src/connectors/breadcrumb/connectBreadcrumb.ts
src/connectors/hierarchical-menu/connectHierarchicalMenu.js
src/connectors/hits-per-page/connectHitsPerPage.ts
src/connectors/menu/connectMenu.ts
src/connectors/rating-menu/connectRatingMenu.js
src/connectors/refinement-list/connectRefinementList.ts
src/connectors/toggle-refinement/connectToggleRefinement.js
src/widgets/hierarchical-menu/__tests__/hierarchical-menu-test.js
src/widgets/rating-menu/__tests__/rating-menu-test.js

**Summary**
createURL didn't reset the page because it uses SearchParameter methods vs. helper methods which get the page reset automatically.
**Result**
fixes https://github.com/algolia/vue-instantsearch/issues/932
all createURLs now reset the page as expected

fix(createURL): correctly remove page in state

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.js
src/lib/__tests__/RoutingManager-test.ts
src/widgets/index/__tests__/index-test.ts
test/mock/createInstantSearch.ts

currently if you call setUiState, the localUiState in index widgets doesn't get updated to prevent middlewares being called multiple times, but that means if you call setUiState multiple times, the local state doesn't change

fix(setUiState): make sure previous ui state is stored

---

src/connectors/relevant-sort/__tests__/connectRelevantSort-test.ts
src/connectors/relevant-sort/connectRelevantSort.ts

**Summary**
implements canRefine in connectRelevantSort as true when nbHits > 0 and it's a virtual replica.
**Result**
relevantSort now has a canRefine

feat(relevantSort): implement canRefine

---

src/connectors/range/__tests__/connectRange-test.ts
src/connectors/range/connectRange.ts

**Summary**
implements canRefine in connectRange as true when the resulting range's start and end are identical
DX-1307
**Result**
range now has a canRefine

feat(range): implement canRefine

---

src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.js
src/connectors/hierarchical-menu/connectHierarchicalMenu.js

**Summary**
implements canRefine in connectHierarchicalMenu as true when more than 0 items are possible available (a single item can still refine, even if the value of that is small, this way it's consistent with breadcrumb)
DX-1305
**Result**
hierarchicalMenu now has a canRefine

feat(hierarchicalMenu): implement canRefine

---

src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/clear-refinements/connectClearRefinements.ts

**Summary**
implements canRefine in connectClearRefinements as true when there are current refinements
DX-1310
**Result**
clearRefinements now has a canRefine

feat(clearRefinements): implement canRefine

---

src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
This PR fixes the wrong behavior of `showPrevious` and `showMore` because the functions were created at `init` with `cachedHits`. It means `showPrevious` and `showMore` always have wrong (empty) `cachedHits` object. Instead, we need to read from `cache` every time.
fixes https://github.com/algolia/vue-instantsearch/issues/945
**Reproduction of the issue from Vue InstantSearch**
https://fyn4y.csb.app/?instant_search[page]=4 (https://codesandbox.io/s/instantsearchjs-forked-fyn4y?file=/src/app.js)
- Click "Show more results" and you will see more results.
- Click "Show previous results" and you expect previous hits to be added, but nothing happens.
- Click "Show previous results" again, and it works now.
And the following is the same example with the InstantSearch.js version from …

fix(infiniteHits): fix wrong behavior of showPrevious regarding cachedHits

---

src/widgets/voice-search/defaultTemplates.ts

**Summary**
this file wasn't converted yet
**Result**
voice search widget's default templates are TS now

chore(ts): convert voice search default templates

---

examples/e-commerce/src/widgets/Ratings.ts
src/widgets/rating-menu/__tests__/__snapshots__/rating-menu-test.ts.snap
src/widgets/rating-menu/__tests__/rating-menu-integration-test.ts
src/widgets/rating-menu/__tests__/rating-menu-test.ts
src/widgets/rating-menu/defaultTemplates.ts

**Summary**
this is the cause of the from time to time failing e2e test, basically sometimes the event.preventDefault didn't apply, which causes the page to refresh to / instead of the right url.
The actual url is `url`, and not in `href`, so this means that before now it always was wrong.
The docs are correct and use `url`: https://www.algolia.com/doc/api-reference/widgets/rating-menu/js/#templates
**Result**
url in ratingMenu now is actually correct, e2e tests will pass

fix(ratingMenu): use url in default template

---

src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts
src/types/insights.ts
test/mock/createInsightsClient.ts

**Summary**
This PR replaces `_get` with `getUserToken`. At the time of writing the insights middleware, I wasn't aware of `getUserToken` method. 
**Result**
It works the same.

fix(insights): use getUserToken method instead of _get

---

src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts
src/types/insights.ts
test/mock/createInsightsClient.ts

**Summary**
This PR adds `insights-middleware` to the user agent in ~both **search call** and~ **insights call** when the `insights` middleware is subscribed.
There can be another way to check the usage of the `insights` middleware other than this, but this seems to be quick and harmless.
If we already had a dozen public middlewares and wanted to track which middlewares are used, this method wouldn't be appropriate. But it's not the case, so the user agent seems okay.

chore(insights): add user agent

---

src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts
src/types/insights.ts

**Summary**
This PR prevents `insights` middleware from throwing when `userToken` is not given yet.
_(The previous description wasn't clear and I was confused myself too.)_
Adding the `insights` middleware to InstantSearch and assigning a userToken could happen at the same time, or not. For example, although InstantSearch is loaded, the user is not logged in, so there may not be a userToken to set (let's assume this customer is not using anonymous user token from cookie).
Without this PR, we can guide like
> Add the middleware only after you have a user token. Otherwise, the middleware will throw errors without the token. Oh, and when a user logs out and you want to call `aa('setUserToken', '')` to remove the user token, you need to unuse the middleware. Otherwise it will throw errors …

fix(insights): do not throw when userToken is not given

---

src/lib/__tests__/RoutingManager-test.ts
src/lib/__tests__/insights-client-test.ts
src/types/connector.ts
src/types/render-state.ts
src/types/ui-state.ts
src/types/utils.ts
src/types/widget-factory.ts
src/types/widget.ts
test/mock/createWidget.ts

**Summary**
sets up Widget, Connector and WidgetFactory to accept a `WidgetDescription` generically instead of the TRenderState now
**Result**
note: CI will be failing until the final PR here (panel, #4738)

refactor(types): new WidgetDescription setup

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.ts
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.ts
src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/__tests__/connectHitsWithInsights-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHitsWithInsights-test.ts
src/connectors/menu/__tests__/connectMenu-test.ts
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/pagination/__tests__/connectPagination-test.ts
src/connectors/powered-by/__tests__/connectPoweredBy-test.ts
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/range/__tests__/connectRange-test.ts
src/connectors/rating-menu/__tests__/connectRatingMenu-test.ts
src/connectors/refinement-list/__tests__/connectRefinementList-test.ts
src/connectors/search-box/__tests__/connectSearchBox-test.ts
src/connectors/sort-by/__tests__/connectSortBy-test.ts
src/connectors/stats/__tests__/connectStats-test.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
src/widgets/menu-select/__tests__/menu-select-test.ts
src/widgets/panel/__tests__/panel-test.ts
src/widgets/query-rule-custom-data/__tests__/query-rule-custom-data-test.ts
test/mock/createWidget.ts

**Summary**
If the widget is conditionally adding widgets to the parent in init & render, it needs to be able to remove those on dispose.
**Result**
`dispose` is called with `parent` too. Updated all tests to use the existing helper `createDisposeOptions`

feat(widget): add access to "parent" in dispose

---

src/connectors/range/__tests__/connectRange-test.ts
src/connectors/range/connectRange.ts

**Summary**
when in #4446 the insights middleware was introduced, range was refactored from helper.addNumericRefinement to state.addNumericRefinement. The helper method resets the page and sets the state, while the state method does not do that. Therefore we need to manually reset the page.
**Result**
1. Go to the [story](https://deploy-preview-4760--instantsearchjs.netlify.app/stories/?path=/story/refinements-rangeslider--default)
2. set the page to non-zero
3. refine the range slider
A similar test can be done for range input
fixes #4759

fix(range): reset the page on refine

---

package.json
src/lib/createHelpers.ts
src/lib/utils/__tests__/renderTemplate-test.ts
src/lib/utils/prepareTemplateProps.ts
src/lib/utils/renderTemplate.ts
src/types/templates.ts
yarn.lock

DX-2017
**Summary**
converts the utility `renderTemplate` to TS (its test was already converted in #4769)
**Result**
- adds @types/hogan to avoid any
- migrates that file
- update some usage to be simplified

refactor(ts): migrate renderTemplate

---

.circleci/config.yml
package.json
tsconfig.checkjs.json

**Summary**
Since all output files are now TypeScript, we no longer need to allow JavaScript in our configuration!
(Before this PR the test still failed, but that was due to a small inconcistency in the geo search renderer, that we aren't migrating ATM)
**Result**
One less test on CI, and no more configuration for checkJS, allowJS in typescript. This means CI is now finally fully green again

ci(ts): remove test for ts-in-js

---

src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/clear-refinements/connectClearRefinements.ts

**Summary**
This PR prevents connectClearRefinement from throwing an error when widgetParams is not given.
When it's used with the official clearRefinement widget, then normally at least `container` is there, but if it's used in a custom widget or in Vue InstantSearch, there could be no widgetParams at all.

fix(clearRefinements): do not throw when widgetParams is not given

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.tsx

**Summary**
In Vue InstantSearch server side rendering, we set a mainHelper https://github.com/algolia/vue-instantsearch/blob/118e0a39b8a047930520220da757ff0175cec12d/src/util/createServerRootMixin.js#L234-L235 before the instance is started.
This worked fine with existing fixes done, except for in routing, because every place that changes the state uses helper from the index, which is derived of the helper that's created before start. Routing and middleware however uses the helper which gets created in start, and thus don't trigger a search on the helper that actually searches.
To avoid these issues, we prevent recreation of the main helper if it's already set (by Vue InstantSearch for example). Whenever we will add the proper API for server side rendering in InstantSearch, we can …

fix(mainHelper): allow a mainHelper to be set before start

---

src/widgets/relevant-sort/relevant-sort.tsx

This type cannot be imported from other projects, as opposed to other widgets.

fix(relevantSort): export `RelevantSortWidgetParams` type

---

src/widgets/index/index.ts

This type cannot be imported from other projects, as opposed to other widgets.

fix(index): export `IndexWidgetParams` type

---

src/connectors/sort-by/__tests__/connectSortBy-test.ts
src/connectors/sort-by/connectSortBy.ts

**Summary**
Without this check, if a route state is read (eg. in ssr) with the default value, it will be persisted in the URL, as the refinement is the default refinement, and the ui state was kept as-is, instead of being cleared.
**Result**
fixes https://github.com/algolia/vue-instantsearch/issues/1005

fix(sortBy): do not write the default state

---

package.json
src/widgets/geo-search/createHTMLMarker.ts
yarn.lock

https://www.npmjs.com/package/@types/googlemaps is deprecated in favor of https://www.npmjs.com/package/@types/google.maps

chore: update google maps types

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-integration-test.ts

This wrong behaviour was originally introduced in https://github.com/algolia/instantsearch.js/pull/4699 by removing onInternalStateChange, since I assumed the helper state change event would call the middleware, but it doesn't happen in all cases.
This means that now onInternalStateChange gets called one more time in certain situations, but that's not really an issue, as it's deferred anyway.
I've checked and the integration test written by @tkrugg indeed starts failing on #4699 
Fixes #4795

fix(onStateChange): propagate change to middleware

---

package.json
yarn.lock

**Summary**
In 6.10.1, qs became triple the size ((https://bundlephobia.com/package/qs@6.10.1 / https://github.com/ljharb/qs/issues/404)
), becoming a huge part of the bundlesize of InstantSearch.js. While we could fix this by not relying on a third-party anymore for this code, the least we can do is forcing the older version
**Result**
While this means it will be deduplicated less if people do use the later version of qs, it means a significant bundle size impact if we would have upgraded to 6.10+

fix(deps): force a lower version of qs

---

scripts/release/build-experimental-typescript.js

**Summary**
At the moment failing build types are not being surfaced to circle ci. See for example this [build](https://app.circleci.com/pipelines/github/algolia/instantsearch.js/6416/workflows/3398a5d9-002b-4220-8263-6d45d98cf33d/jobs/30500), step `Trigger a release if the latest commit is a release commit` should have failed but it didn't.
This is because [`yarn built:types`  is run via `shell.exec`](https://github.com/algolia/instantsearch.js/blob/4ff0392767bfc7a2398b649b2f9362ddb9a8cc75/scripts/release/build-experimental-typescript.js#L23) and the return code of 1 is ignored, instead of passed to calling process.
Per [exec](https://www.npmjs.com/package/shelljs#examples) docs, it's the caller's reponsibility to read the exit code and exit or continue.
```js
// Run external tool …
```

fix(build): ensure build fails when types building fails

---

src/widgets/dynamic-widgets/dynamic-widgets.ts
src/widgets/query-rule-context/query-rule-context.tsx
src/widgets/query-rule-custom-data/query-rule-custom-data.tsx
src/widgets/relevant-sort/relevant-sort.tsx
src/widgets/voice-search/voice-search.tsx

**Summary**
Not all widgets export their type correctly, which means it is harder to use
**Result**
all types are exported from their respective file for widgets, not yet from the indexes

fix(types): export widget's types

---

package.json
src/connectors/answers/__tests__/connectAnswers-test.ts
src/connectors/answers/connectAnswers.ts
src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test.ts
src/connectors/configure/__tests__/connectConfigure-test.ts
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.ts
src/connectors/hierarchical-menu/connectHierarchicalMenu.ts
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.ts
src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/__tests__/connectHitsWithInsights-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHitsWithInsights-test.ts
src/connectors/menu/__tests__/connectMenu-test.ts
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/pagination/__tests__/connectPagination-test.ts
src/connectors/powered-by/__tests__/connectPoweredBy-test.ts
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/range/__tests__/connectRange-test.ts
src/connectors/refinement-list/__tests__/connectRefinementList-test.ts
src/connectors/voice-search/connectVoiceSearch.ts
src/lib/__tests__/insights-client-test.ts
src/widgets/answers/__tests__/answers-test.ts
src/widgets/menu-select/__tests__/menu-select-test.ts
src/widgets/menu/__tests__/menu-test.ts
src/widgets/relevant-sort/__tests__/relevant-sort-test.ts
yarn.lock

ts-expect-error will error if it's no longer needed, so it's better in almost all cases. There's some moments where we need to keep ts-ignore though:
- things that fail only with algoliasearch v3 or v4
- optional packages (places)
- code that doesn't always error
At the same time updated the algoliasearch-helper to a version that includes `showParentLevel` in the typings
part of DX-2299

chore(ts): avoid more ts-ignores

---

src/connectors/hits/connectHits.ts
src/connectors/infinite-hits/connectInfiniteHits.ts

The types `Hit` and `AlgoliaHit` are mostly the same.
https://github.com/algolia/instantsearch.js/blob/21b6c53d4b1a3f3dd3a2375a5cfe0a31bef6ded6/src/types/results.ts#L60-L63
As of today, the hits exposed via results indeed [contain __position and __queryID](https://github.com/algolia/instantsearch.js/blob/21b6c53d4b1a3f3dd3a2375a5cfe0a31bef6ded6/src/connectors/hits/connectHits.ts#L158).
While trying use `InfiniteHitsRenderState` in Angular InstantSearch I noticed how `hits` and `results` while being [part of the state expored by`connectInfiniteHits`](https://github.com/algolia/instantsearch.js/blob/master/src/connectors/infinite-hits/connectInfiniteHits.ts#L331-L342) are not actually visible on the type.

fix(types): fixing hits and results types in connectHits and connectInfiniteHits

---

src/index.es.ts
src/lib/InstantSearch.ts
src/lib/__tests__/RoutingManager-test.ts
src/lib/main.ts
src/lib/routers/__tests__/history.test.ts
src/lib/routers/history.ts
src/lib/stateMappings/__tests__/simple-test.ts
src/lib/stateMappings/__tests__/singleIndex-test.ts
src/lib/stateMappings/simple.ts
src/lib/stateMappings/singleIndex.ts
src/middlewares/createRouterMiddleware.ts
src/types/middleware.ts
src/types/router.ts
src/widgets/index/index.ts

```ts
import algoliasearch from 'algoliasearch/lite';
import instantsearch from 'instantsearch.js/es';
import { history } from 'instantsearch.js/es/lib/routers';
import { StateMapping, UiState } from 'instantsearch.js/es/types';
type SwagIndexUiState = { swag: boolean };
type SwagUiState = { [indexName: string]: SwagIndexUiState };
// can also be written inline, no need for the type then
const stateMapping: StateMapping<SwagUiState, SwagUiState> = {
stateToRoute(uiState) {
return Object.keys(uiState).reduce(
(state, indexId) => ({
...state,
[indexId]: { swag: uiState[indexId].swag },
}),
{}
);
},
routeToState(routeState = {}) {
return Object.keys(routeState).reduce(
(state, indexId) => ({
...state,
[indexId]: routeState[indexId],
}),
{}
);
},
};
instantsearch<SwagUiState, SwagUiState>({ …
```

feat(ts): allow custom ui state and route state in routing

---

scripts/build/api-extractor.json
scripts/build/tsconfig.declaration.json
scripts/build/types.js

The entry point used to be:
```ts
// this is wrong!!!
export { default } from './index.es';
export * from './connectors';
export * from './helpers';
export * from './types';
export * from './widgets';
export * from './lib/routers';
```
While really the entry point should be the same as index.es.ts, as otherwise the js bundle doesn't match the declaration.
This commit fixes that by no longer generating an entry point, and renaming index.es.d.ts to index.d.ts in the built files.
In the same commit I also move the declaration-related configuration files to the subfolder to make the root a little cleaner

fix(ts): correct entry point

---

src/lib/utils/__tests__/createSendEventForHits-test.ts
src/lib/utils/createSendEventForHits.ts

**Summary**
Mapping over the hits isn't heavy, but it's not required, as .slice also removes the __escaped key on hits
**Result**
replaced .map(identity) with .slice() to clone the hits

refactor(sendEventForHits): remove __escaped more efficiently

---

src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/helpers/insights.ts
src/lib/insights/listener.tsx
src/lib/utils/__tests__/createSendEventForHits-test.ts
src/lib/utils/createSendEventForHits.ts
src/lib/utils/serializer.ts

**Summary**
the backend api doesn't allow > 20 hits per event, so we split the sendEvent calls up into multiple if > 20 DX-2379
**Result**
edited sendEvent and bindEvent to both split up the vents in arrays where it makes sense, and calling sendEvent multiple times.
We choose to split at this level and not inside the events listener, as you can't know what method is used, and you'd need a lot of conditional code to handle all chunking

fix(sendEvent): split > 20 objects in multiple calls

---

.codesandbox/ci.json
scripts/typescript/api-extractor.json
scripts/typescript/extract.js

**Summary**
Exposes the entry point for umd for each of the umd entry points.
This is achieved using the dtsRollup feature of api-extractor, which isn't needed for the es build, as local files work perfectly fine in that case.
Make sure to check the generated files when reviewing this PR
**Result**
A situation like https://github.com/algolia/create-instantsearch-app/pull/464 is done easier by simply declaring what's import from the umd

feat(ts): expose built files in umd

---

src/components/Panel/Panel.tsx
src/widgets/panel/__tests__/panel-test.ts
src/widgets/panel/panel.tsx

**Summary**
Before this PR the initial render happens *before* widget init. This doesn't have a huge effect, although it got rendered with just an empty object. This makes things needlessly dynamic (more than the types were saying even, because the Template isn't super strict), and would make a template like `header({ widgetParams }) { return widgetParams.attribute }` throw, even though with this PR it is possible without conditionals or flashing.
Under very strict conditions this could be construed as a breakign change, although it's closer to a fix, therefore I have classified it as a new feature.
**Result**
panel's templates always get called with render state, but also with init options. Before this PR it got called with either results or an empty object

feat(panel): render templates on init with render state

---

src/connectors/dynamic-widgets/__tests__/connectDynamicWidgets-test.ts
src/connectors/dynamic-widgets/connectDynamicWidgets.ts
src/widgets/dynamic-widgets/__tests__/dynamic-widgets-test.ts
src/widgets/dynamic-widgets/dynamic-widgets.ts
stories/dynamic-widgets.stories.ts

**Summary**
adds a `fallbackWidget` key to dynamicWidgets to allow usage when you don't know in advance what the attributes will be
**Result**
- new key: "fallbackWidget" that gets used and instantiated when the attribute is slated for mounting
- no longer automatically adding widgets on init
To investigate: does this break routing?
To do: update tests if it turns out the mounting wasn't needed

feat(dynamicWidgets): add fallbackWidget

---

src/lib/InstantSearch.ts
src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts

**Summary**
In #4849, we introduced a regression that insights middleware throws when `setUserToken` is called twice before `search.start()`.
In the revised implementation of the insights middleware either adds a configure widget with userToken or calls `refine` function of renderState. However when instantSearchInstance is not started yet, even though configure widget is added, there is no renderState. That's why it's failing.

fix(insights): handle multiple setUserToken call before search.start()

---

src/connectors/dynamic-widgets/__tests__/connectDynamicWidgets-test.ts
src/widgets/dynamic-widgets/__tests__/dynamic-widgets-test.ts
stories/dynamic-widgets.stories.ts

**Summary**
in #4899 dynamic widgets became stable, but I forgot to update some of the tests and the stories to the new name
**Result**
no more usage of `EXPERIMENTAL_(connect)dynamicWidgets` outside of the export

chore(dynamicWidgets): use non-deprecated form in examples

---

src/lib/utils/getAppIdAndApiKey.ts
src/middlewares/__tests__/createInsightsMiddleware.ts
src/middlewares/createInsightsMiddleware.ts
src/widgets/hits/__tests__/hits-integration-test.ts
src/widgets/infinite-hits/__tests__/infinite-hits-integration-test.ts

**Summary**
When api or appId is missing, an error gets thrown by search insights, but that doesn't explain *why* that error gets thrown.
Ideally this would also clarify what the next step is (usually making sure to spread the previous search client, or leaving all properties in place, but i'm not too sure how to word that.
This doesn't add a new error where there wasn't already one, as the search-insights library threw an error in this case already.
**Result**
An error that explains when the search client doesn't match insights' expectation

fix(insightsMiddleware): throw an error when credentials can't be extracted

---

src/connectors/answers/__tests__/connectAnswers-test.ts
src/connectors/answers/connectAnswers.ts
src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/widgets/hits/__tests__/hits-test.ts
src/widgets/infinite-hits/__tests__/__snapshots__/infinite-hits-test.ts.snap
src/widgets/infinite-hits/__tests__/infinite-hits-test.ts

**Summary**
Since we introduced getWidgetRenderState, transformItems gets called two times. On its own this isn't problematic, however if the transformItems "mutates" a key, it will receive next the "mutated" hits instead of the ones that come from the results
One thing which is debatable about this PR is which parts should be saved to `results.hits`. I opted for just the escaped hits, but i wonder if there's any use cases for considering the query id and position as part of the hits directly.
However, I feel like if we want this behaviour, it shouldn't be hits and infiniteHits mutating results, but rather something global that gets called right after the results get returned. In fact, I also think it makes more sense to escape hits there than in hits.
I don't think removing the …

fix(infinite/hits): stop saving the transformed results in cache

---

src/index.es.ts

**Summary**
We deprecated the properties added to instantsearch in #4814, but the deprecation does not mention the solution
**Result**
The same solution as at runtime is given by typescript, importing from ./helpers

fix(es): add warning to typescript declaration of keys to be imported from helpers

---

src/connectors/toggle-refinement/connectToggleRefinement.ts
src/lib/utils/__tests__/getWidgetAttribute-test.ts

**Summary**
This was added in the migration from render to getWidgetRenderState, but actually getWidgetSearchParameters already takes this in account, and i can't find any situations where "off" gets erased.
Added a test to make sure getWidgetAttribute works when "off" is given, but it's straightforward now
**Result**
Nothing really changes, except toggle with an off works in dynamic widgets works now and a little bit less code

fix(toggleRefinement): don't set off value in getWidgetRenderState

---

src/connectors/autocomplete/connectAutocomplete.ts
src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/connectors/pagination/connectPagination.ts
src/connectors/search-box/connectSearchBox.ts
src/connectors/sort-by/connectSortBy.ts
src/connectors/stats/connectStats.ts
src/connectors/toggle-refinement/connectToggleRefinement.ts
src/widgets/toggle-refinement/__tests__/__snapshots__/toggle-refinement-test.ts.snap
src/widgets/toggle-refinement/__tests__/toggle-refinement-test.ts
test/mock/createWidget.ts

This changes how **we provide the widgets' render state from the helper state to the retrieved state** (`renderOptions.helper.state` vs. `renderOptions.state`).
This is required to support React InstantSearch Hooks SSR[^1] to avoid flashes between SSR and CSR[^2] when hydrating.
As opposed to Vue InstantSearch SSR, React InstantSearch Hooks SSR works in a single data flow pass. We rely on a single helper (the one created by InstantSearch.js), to provide the search state and the search results to the widgets.
By design, InstantSearch.js computes the search parameters from the mounted widgets (e.g., `searchBox` controls the `query` search parameter). As soon as you start setting a search parameter that is not yet controlled by a widget (this happens when a child index inherits from its …

feat: rely on `state` in `getWidgetRenderState`

---

package.json
src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.tsx
src/types/results.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
test/mock/createInstantSearch.ts

This adds supports for initial results in InstantSearch.js. This API is required to implement the React InstantSearch Hooks SSR API (see [RFC](https://github.com/algolia/instantsearch-rfcs/blob/843996b214aee8dcb389bcad46135f90dd51ebda/accepted/react-instantsearch-ssr/react-instantsearch-ssr.md)).
This private API is released silently at first. It doesn't expose a public API as an option, but support the private `_initialResults` field attached to the search instance. We'll silently release it to keep room for changes before introducing the official InstantSearch.js SSR API.
When initial results are provided, we don't trigger an initial search (which skips the initial network request on the browser), but directly inject the results to each index' helper and render. We're able to skip this …

feat: support initial results

---

package.json

The dependency algoliasearch-helper [declares algoliasearch as a peer dependency](https://github.com/algolia/algoliasearch-helper-js/blob/develop/package.json#L103) [1], but instantsearch.js does not declare it as a dependency nor a peer dependency.
This can cause undefined issues during peer dependency resolution, and triggers warnings when using yarn v2+.
The commit adds algoliasearch as a peer dependency.

Add missing peer dependency from algoliasearch-helper

---

src/connectors/dynamic-widgets/__tests__/connectDynamicWidgets-test.ts
src/connectors/dynamic-widgets/connectDynamicWidgets.ts

`transformItems` implementations can get complicated and if you're not
cautious, it's very easy to have it return something other than an
array.
When this happens, the errors you get are not insightful on where the
mistake is.
```
TypeError: Cannot read property 'forEach' of undefined
```
This change helps the user identify this type of mistakes.
It adds a check on `transformItems` output to make sure it returns an
array.
closes FX-608

feat(DynamicWidgets): throw when transformItems returns a non array

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/breadcrumb/connectBreadcrumb.ts

**Summary**
**Result**
This PR fixes an error we had implementing the hook `useBreadcrumb` in React InstantSearch Hooks.
It also fixes an error when refine to `null` is called (usually used when you click on the "Home" link to clear the current refinement) when no `hierarchicalFacets` exist.

fix(connectBreadcrumb): returns an empty array if no hierarchicalFacets exist

---

package.json

**Summary**
some (older) versions of rollup (like the one we use in react instantsearch) don't look at the root package.json, but only at the closest for sideEffects, and thus this change added in #4971 caused a regression in bundle size (notably from Hogan being included)
**Result**
The package.json for /es now is marked as side-effect free
No new test was added, as I couldn't think of something, but maybe in the future we could run the React/Vue InstantSearch test suite based on every PR to InstantSearch?

fix(es): mark inner package.json as side-effect free

---

src/connectors/search-box/__tests__/connectSearchBox-test.ts
src/connectors/search-box/connectSearchBox.ts

**Summary**
I don't understand yet how this is working, but somehow if `_clear` is defined only once, refine('') starts actually clearing, even if that function doesn't use `_clear` itself
**Result**
fixes #4979

fix(searchbox): make sure setting query to the initial doesn't cause a stale state

---

package.json
yarn.lock

I updated to 0.8.4, not yet 0.8.5, as it doesn't appear in the changelog yet.
This prevents the node deprecation warnings when you run `yarn build` or similar:
```
(node:98762) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:98762) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:98762) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:98762) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:98762) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:98762) Warning: Accessing …
```

chore(devDeps): update shelljs

---

src/helpers/__tests__/highlight-test.ts
src/helpers/__tests__/reverseHighlight-test.ts
src/helpers/__tests__/reverseSnippet-test.ts
src/helpers/__tests__/snippet-test.ts
src/helpers/highlight.ts
src/helpers/reverseHighlight.ts
src/helpers/reverseSnippet.ts
src/helpers/snippet.ts

**Summary**
This PR shows a helpful warning in dev environment when an attribute cannot be highlighted or snippeted.
It's an adaptation from a similar message in the custom highlight implementation in Angular.
**Result**

fix(helpers): display warning if attribute is cannot be highlighted/snippeted

---

src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
src/connectors/breadcrumb/connectBreadcrumb.ts
src/connectors/clear-refinements/__tests__/connectClearRefinements-test.ts
src/connectors/clear-refinements/connectClearRefinements.ts
src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
src/connectors/current-refinements/connectCurrentRefinements.ts
src/connectors/dynamic-widgets/__tests__/connectDynamicWidgets-test.ts
src/connectors/dynamic-widgets/connectDynamicWidgets.ts
src/connectors/geo-search/__tests__/connectGeoSearch-test.ts
src/connectors/geo-search/connectGeoSearch.ts
src/connectors/hierarchical-menu/__tests__/connectHierarchicalMenu-test.ts
src/connectors/hierarchical-menu/connectHierarchicalMenu.ts
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.ts
src/connectors/hits-per-page/connectHitsPerPage.ts
src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/connectors/menu/__tests__/connectMenu-test.ts
src/connectors/menu/connectMenu.ts
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/numeric-menu/connectNumericMenu.ts
src/connectors/query-rules/__tests__/connectQueryRules-test.ts
src/connectors/query-rules/connectQueryRules.ts
src/connectors/refinement-list/__tests__/connectRefinementList-test.ts
src/connectors/refinement-list/connectRefinementList.ts
src/connectors/sort-by/__tests__/connectSortBy-test.ts
src/connectors/sort-by/connectSortBy.ts
src/types/widget.ts
src/widgets/dynamic-widgets/__tests__/dynamic-widgets-test.ts

**Summary**
This PR adds a secondary parameter to `transformItems` on all connectors that support it. It currently exposes the search results from Algolia.
**Result**
Search results can now be used in transformItems for various applications. For example, you can show the number of hits in the last segment of a breadcrumb widget:
```js
// ...
instantsearch.widgets.breadcrumb({
container: breadcrumbDiv,
attributes: [
'hierarchicalCategories.lvl0',
'hierarchicalCategories.lvl1',
'hierarchicalCategories.lvl2',
],
transformItems: (items, { results }) => {
const lastCrumb = items.pop();
return [
...items,
{
...lastCrumb,
label: `${lastCrumb.label} (${results.nbHits} hits)`,
},
];
},
}),
// ...
```

feat(connectors): expose search results to `transformItems` when available

---

src/middlewares/__tests__/createMetadataMiddleware.ts
src/middlewares/createMetadataMiddleware.ts

This ensures user agent detection doesn't break in non-browser environments.
In React Native, `window.navigator` is [polyfilled with a custom `product` property](https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/Libraries/Core/setUpNavigator.js), and doesn't have other properties traditionally exposed in the browser.
This change ensures this code path doesn't yield a runtime error regardless of the environment.

fix(metadata): ensure safe user agent detection

---

src/connectors/hits/connectHits.ts
src/connectors/infinite-hits/connectInfiniteHits.ts
src/types/results.ts
src/widgets/infinite-hits/__tests__/infinite-hits-integration-test.ts

**Summary**
Allows Hits and InfiniteHits connectors to be constructed with a generic Hit
**Result**
It doesn't make the connectors themselves generic (yet), but allows you to cast the connector as one with this generic

feat(ts): allow Hits related connectors to be generic

---

src/connectors/hits/__tests__/connectHits-test.ts
src/connectors/hits/connectHits.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
This PR fixes the order of sending view events and rendering in connectors.
fixes #5013
**Result**
At the time of view events being sent, the DOM is already updated.

fix(insights): send view events after rendering

---

src/connectors/hierarchical-menu/connectHierarchicalMenu.ts
src/connectors/menu/connectMenu.ts
src/connectors/refinement-list/connectRefinementList.ts
src/types/widget.ts

This fixes type issues for the `sortBy` option which is exposed on `connectRefinementList`, `connectHierarchicalMenu`, and `connectMenu`.
The `SortBy` type takes more string-based options than specified in the type. Some of them are even [specified in the InstantSearch.js documentation](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-sortby), but were missing from the type.
The value passed to `sortBy` isn't the same one that's passed to `transformItems`. This is visible when passing a `sort` function (see console output in following examples).
- [`refinementList`](https://codesandbox.io/s/serene-bouman-01on2p?file=/src/app.js)
- [`hierarchicalMenu`](https://codesandbox.io/s/trusting-keldysh-vfjorp?file=/src/app.js)
- …

fix: fix types of `sortBy` option

---

package.json
src/connectors/infinite-hits/connectInfiniteHits.ts
yarn.lock

**Summary**
Only cache the hits in infiniteHits if it's a "real" set of results
**Result**
in React InstantSearch Hooks, where we call getWidgetRenderState with fake results (empty hits), we need to ensure that those don't get cached.
> An alternative is to skip caching for `transformedHits.length === 0`, as those should not have an effect on the page, but this could have unintended effects

feat(infiniteHits): avoid caching artificial results

---

src/lib/__tests__/routing/duplicate-url-test.ts
src/lib/__tests__/routing/spa-replace-state-test.ts
src/lib/routers/history.ts

**Summary**
We've given this from time to time as workarounds for customer issues, where due to state desync or other external influence the URL is already changed to the one InstantSearch would navigate to.
The specific state I test and am fixing here however is with `stateMapping` (described in https://github.com/algolia/instantsearch.js/discussions/5044) removing a piece of the state that still changes, and thus would cause duplicate writes of the same URL before this PR.
**Result**
The same URL will not be written twice subsequently
I had to change the test for replaceState a bit, as the cleaned URL being the same as the replaceState navigated URL being the same was hiding the issue we have that test for.

fix(routing): prevent writing the same URL twice

---

src/connectors/autocomplete/__tests__/connectAutocomplete-test.ts
src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
src/connectors/refinement-list/__tests__/connectRefinementList-test.ts
src/lib/InstantSearch.ts
src/lib/__tests__/RoutingManager-test.ts
src/lib/utils/__tests__/createSendEventForHits-test.ts
src/lib/utils/__tests__/escape-highlight-test.ts
src/lib/utils/escape-highlight.ts
src/lib/utils/getAppIdAndApiKey.ts
src/lib/utils/safelyRunOnBrowser.ts
src/widgets/hits-per-page/__tests__/hits-per-page-test.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/range-input/__tests__/range-input-test.ts

**Summary**
In a lot of cases, more sound patterns than casting into `any` are possible.
I didn't find an alternative for a remaining part of the code, so I'm not sure if I should find an eslint (or similar) rule to forbid "as any", or if it's good just being improved like this.
**Result**
many `as any` instances are gone, but nothing is enforced

refactor(ts): avoid `as any`

---

src/connectors/dynamic-widgets/connectDynamicWidgets.ts
src/lib/utils/__tests__/resolveSearchParameters-test.ts
src/types/widget.ts
src/widgets/index/__tests__/index-test.ts
src/widgets/index/index.ts
test/mock/createWidget.ts

**Summary**
The only case init is called with `parent: null`  is inside InstantSearch for the main index, and thus it shouldn't leak every widget implementation
**Result**
the types for `widget.init` and `getWidgetRenderState` no longer accept `null` for `parent`
As this is only types and fairly internal, as well as the behaviour of calling a widget with parent: null isn't useful, this isn't a breaking change

fix(types): only allow `null` for parent if widget is an index

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-integration-test.ts
src/lib/__tests__/InstantSearch-test.tsx

> **Note**
> This is in the PR series that brings support for React 18 in React InstantSearch Hooks.
This updates the behavior of the `start()` method to only schedule a search when there are widgets statically added beforehand. Scheduling a search without widget is a unnecessary operation because there are no listeners at this point to use the search results.
This behavior is required for React InstantSearch Hooks with React 18 to support new concurrent features. We don't have any certainty about the order of execution of our effects anymore in `<InstantSearch>` and `useConnector()`, so we would sometimes end up triggering a single network request, or sometimes two (from `start()`, and then from `addWidgets()`).
This eliminates the problem altogether because our framework-based flavors …

feat(core): don't schedule search without widgets

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.tsx

**Summary**
This allows someone with custom widgets to still use setUiState etc. without type errors
**Result**
all places `UiState` is used in the InstantSearch instance are now generic and use TUiState.
There are still places left in individual widgets, middleware which aren't generic, but that can be solved in a different PR
A sandbox showing the fixed problem: https://codesandbox.io/s/instantsearch-js-forked-m8nm7s?file=/src/app.ts:1152-1262

fix(types): make all usages of UiState in InstantSearch generic

---

package.json
yarn.lock

**Summary**
This PR updates **algoliasearch-helper** which now allows the `hierarchicalMenu` widget to retrieve and display the full list of a refined item's parents values.
**Result**
Fixes #5053

fix(hierarchicalMenu): show full hierarchical parent values

---

src/index.es.ts

Our depreciation message advised to import `createInfiniteHitsSessionStorageCache()` from `instantsearch.js/es/helpers` but it's exported from `instantsearch.js/es/lib/infiniteHitsCache`.
- [CR-1389](https://algolia.atlassian.net/browse/CR-1389?atlOrigin=eyJpIjoiOWNlMzAzZjE4NDJjNDZlMTk0NTA4MjIwZTQxY2NhOWQiLCJwIjoiaiJ9)

fix(es): update path for InfiniteHits cache in depreciation message

---

src/connectors/rating-menu/connectRatingMenu.ts

**Summary**
If the results are artificial (react instantsearch hooks), `maxValuesPerFacet` can evaluate to 0, as it's not necessarily set by another widget, thus isn't in the result.
Before this fix there's a useless warning if you use useConnector(connectRatingMenu)
**Result**
using useRatingMenu in React InstantSearch Hooks doesn't warn on first use

fix(ratingMenu): don't warn if results are artificial

---

src/connectors/geo-search/connectGeoSearch.ts
src/types/results.ts

**Summary**
I noticed Intellisense completing `_geoLoc` instead of `_geoloc` when working on my code sample for Geo search in RISH. This PR correctly writes the property.
**Result**
The property is correctly written and correspond to the actual type of a `GeoHit`.

fix(types): use correct case for `_geoloc` property

---

src/lib/InstantSearch.ts

**Summary**
If you're using the v4 client, the errors (unfortunately) are fake errors, see https://github.com/algolia/algoliasearch-client-javascript/blob/3aec216a9704f818b4faaa8b97d988ec2794f9da/packages/transporter/src/errors/createRetryError.ts for example. When those errors get thrown, you get `"Uncaught, unspecified \"error\" event. ([object Object])"` still.
cfr errors like https://github.com/algolia/react-instantsearch/issues/3534 which have more clear errors (usually wrong api keys, network issues)
**Result**
no more "object Object" errors for search client errors

fix(errors): rethrow error as error if it's an object

---

src/connectors/geo-search/connectGeoSearch.ts

**Summary**
[As mentioned here](https://algolia.atlassian.net/browse/FX-1569), we would like to make `GeoHit` and `GeoSearchConnector` generic akin to how it works for the `Hits` widget.
**Result**
Similarly as `Hits`, it allows users to type their `GeoSearch` hits, for example on React : 
```typescript
type UseGeoSearchProps<THit extends BaseHit> =
GeoSearchConnectorParams<THit>;
function useGeoSearch<THit extends BaseHit>(
props?: UseGeoSearchProps<THit>
) {
return useConnector<
GeoSearchConnectorParams<THit>,
GeoSearchWidgetDescription<THit>
>(connectGeoSearch as GeoSearchConnector<THit>, props);
}
type Airport = { airport_name: string };
function GeoSearch() {
const { items } = useGeoSearch<Airport>();
//      ^ items: Array<GeoHit<Airport>>
}
```

feat(geo-search): make `GeoHit` type generic

---

package.json
src/connectors/hits-per-page/__tests__/connectHitsPerPage-test.ts
src/connectors/hits-per-page/connectHitsPerPage.ts
src/connectors/numeric-menu/__tests__/connectNumericMenu-test.ts
src/connectors/numeric-menu/connectNumericMenu.ts
src/connectors/rating-menu/__tests__/connectRatingMenu-test.ts
src/connectors/rating-menu/connectRatingMenu.ts
src/connectors/sort-by/__tests__/connectSortBy-test.ts
src/connectors/sort-by/connectSortBy.ts

**Summary**
[FX-740](https://algolia.atlassian.net/browse/FX-740)
We want to encourage users to use `canRefine` instead of `hasNoResults`, and to provide them with more meaningful and easier ways to show users if a widget should be interacted with.
**Result**
- *hits-per-page*: `canRefine` is `true` when `hasNoResults` is `false` and vice-versa, no need to check if `items > 0` as it's done beforehand
- *numeric-menu*: `canRefine` can be true even if `hasNoResults` is true, in the case where a refinement has been applied since we can refine to "All"
- *rating-menu*: `canRefine` can be true even if `hasNoResults` is true when a rating is selected
- *sort-by*: `canRefine` is `true` when there are results and at least 1 item

feat(connectors): deprecate `hasNoResults` in favor of `canRefine`

---

src/connectors/rating-menu/__tests__/connectRatingMenu-test.ts
src/connectors/rating-menu/connectRatingMenu.ts

**Summary**
On RISH, if you create a custom RatingMenu widget (based on [this example](https://www.algolia.com/doc/api-reference/widgets/rating-menu/react-hooks/) on the doc) using `useConnector` and `connectRatingMenu` from IS.js and use it with the `useDynamicWidgets` hook, it throws an error as you can see on [this sandbox](https://codesandbox.io/s/fx-1706-ratingmenu-connector-issue-j99rth?file=/src/Refinements.tsx:390-495).
This PR fixes the error in IS.js by making sure the facet values are not `undefined` before reading their length.
[FX-1706](https://algolia.atlassian.net/browse/FX-1706)
**Result**
The rating menu connector doesn't throw any error when used with RISH.

fix(ratingMenu): fix `undefined` facet values error when `disjunctiveFacets` is empty

---

src/components/CurrentRefinements/CurrentRefinements.tsx
src/components/CurrentRefinements/__tests__/CurrentRefinements-test.tsx
src/components/CurrentRefinements/__tests__/__snapshots__/CurrentRefinements-test.tsx.snap
src/widgets/current-refinements/__tests__/__snapshots__/current-refinements-test.ts.snap
src/widgets/current-refinements/current-refinements.tsx

**Summary**
This PR adds a `noRefinementRoot` css class to `currentRefinements`, to match with the InstantSearch CSS specs and allow for more customization depending on the state this widget can have.
**Result**
The `currentRefinements` widget now has a `ais-CurrentRefinements--noRefinement` class name when no refinements are active, and it can be further customized with the new `noRefinementRoot` key in `cssClasses`.
[FX-1729](https://algolia.atlassian.net/browse/FX-1729)

fix(currentRefinements): implement noRefinementRoot modifier class

---

src/middlewares/createInsightsMiddleware.ts

**Summary**
infer `insightsClient` as `null` or `InsightsClient` inside the `onEvent` callback
If the insightsClient is given in the arguments, we also know that it's no longer optional in `onEvent`
this came to my attention through #5129
**Result**
no need to assert `aa!` in `onEvent` as when you're using it, it's already set

fix(insightsMiddleware): infer type of insightsClient for onEvent

---

src/lib/InstantSearch.ts
src/lib/__tests__/InstantSearch-test.tsx
src/lib/__tests__/status.test.ts

The default number of listeners before it's warned of an infinite loop is 10, however you can easily have that many render listeners using useInstantSearch. I've increased the number to 100 in this PR
FX-1626

fix(events): prevent warning on low number of listeners

---

src/helpers/get-insights-anonymous-user-token.ts
src/middlewares/__tests__/createInsightsMiddleware.ts

**Summary**
search-insights is compatible with react-native or other environments without document, but the insights plugin wasn't. This PR fixes that.
I've searched and outside of widgets there's no other occurrences of `document`, but didn't yet find a way to make sure it's a failing test if document is used. We can do that after InstantSearch would be split probably.
**Result**
fixes #5148
FX-1926
createInsightsMiddleware supports environments without `document` or `document.cookie`

fix(insights): check before usage of `document`

---

src/connectors/index.ts
src/widgets/index.ts

While the answers feature still works, it no longer has any difference from a regular search, and therefore no longer needs its own specialised widget.
Even though it's marked as experimental, I still don't think it's a good idea to delete without major version, as it's used in the downstream packages

fix(answers): mark as deprecated

---

packages/instantsearch.js/src/connectors/answers/__tests__/connectAnswers-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/correct-urls.test.ts
packages/instantsearch.js/src/lib/__tests__/routing/dispose-start-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/duplicate-url-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/external-influence-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/modal-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/spa-debounced-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/spa-replace-state-test.ts
packages/instantsearch.js/src/lib/__tests__/routing/spa-test.ts
packages/instantsearch.js/src/widgets/answers/__tests__/answers-test.ts

**Summary**
It seems that in some cases the unit tests which wait for a timeout to "definitely have happened" don't wait long enough. AFAICT this is because setTimeout doesn't have an implicit ordering, if the timer in the code is delayed (setTimeout argument is a minimum), it's possible that the timer in the test already has expired, and thus trying to assert too fast.
I could not find other patterns to replace these type of tests with, so added a decent chunk of extra timeout, hoping that these tests from now on no longer are flaky!
**Result**
unit tests should no longer be flaky after this PR. I've ran the CI a couple times to confirm. Results:
- Run 1: [passed](https://app.circleci.com/pipelines/github/algolia/instantsearch.js/7763/workflows/bdd9918c-35d4-4019-ae5d-64bee11f0cfc/jobs/37 …

tests(unit): delay "wait" for more stability

---

.circleci/config.yml

When refactoring this in #5162 this part wasn't run, so it didn't error on CI
FX-2087

ci(circle): fix configuration of autorelease task

---

package.json
packages/instantsearch.js/scripts/rollup/rollup.config.js

Fixes the build script in prod mode for InstantSearch.js

chore(bundling): don't require "version" env variable

---

examples/js/calendar-widget/env.js
examples/js/calendar-widget/index.html
examples/js/e-commerce/index.html
examples/js/e-commerce/src/env.js
examples/js/media/index.html
examples/js/media/src/env.ts
examples/js/tourism/env.js
examples/js/tourism/index.html

Examples no longer worked in dev mode after the move to the monorepo because of how Parcel works in such configurations. This is a problem we fixed in the [Autocomplete monorepo](https://github.com/algolia/autocomplete) with `env.{js,ts}` files that override constants otherwise undefined (see [example](https://github.com/algolia/autocomplete/blob/next/examples/github-notification-filters/env.ts)).

docs(examples): override undefined constants in examples

---

specs/src/components/WidgetContent.astro

**Summary**
This PR changes the wording used on the InstantSearch.css website to better reflect when a widget doesn't have any translations.
**Result**
Before, on a widget's page that has no translations:
> Note: there are no CSS classes for this widget
After:
> Note: there are no translations for this widget

chore(specs-website): update string used when widget has no translations

---

website/_redirects

There was an infinite loop on these before, because the last redirect also was valid for /examples/react-hooks/ for example and caused infinite redirects before

fix(website): redirect examples/:flavor

---

.gitignore
scripts/website/package.json
ship.config.js

**Summary**
These tags get used to determine the next version number, and as we can't get rid of version number (yarn wouldn't include the package into the dependencies otherwise), that's required to be correct.
This also fixes a little error in one example package accidentally set to public
**Result**
every package will get a git tag, to make sure the next version number will be correct.

ci(shipjs): also push tags of non-published packages 

---

babel.config.js
examples/js/e-commerce/package.json
examples/js/media/package.json
examples/js/tourism/package.json
examples/react-hooks/default-theme/package.json
examples/react-hooks/e-commerce/package.json
package.json
yarn.lock

Small changes in examples:
- babel file will skip the constant elements transform in both webpack and parcel (both behave wrong)
- correct peer dependencies for parcel deps

chore(examples): correct peer dependencies

---

website/_redirects

if you have multiple redirects on the same page, netlify can get confused. We're making sure here only to redirect the previous examples that could still have links in the wild.

docs(website): focused redirects to avoid infinite loop

---

examples/vue/nuxt/package.json
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js
packages/vue-instantsearch/src/util/createServerRootMixin.js

**Summary**
Currently, for SSR, we compute `initialResults` on the server using the helper results. This is used for initial rendering as well as for hydration. Because nested indices inherit from their parent, they are set with a merged state which prevent correct inheritance behavior later on, when interacting with InstantSearch client-side.
This PR instead relies on the index's helper "request" state, which isn't merged and allows expected behavior.
[CR-2516](https://algolia.atlassian.net/browse/CR-2516)
fixes https://github.com/algolia/instantsearch/issues/5383

fix(vue-instantsearch): compute initial state from helper instead of results

---

packages/react-instantsearch-hooks-server/src/__tests__/getServerState.test.tsx
packages/react-instantsearch-hooks-server/src/getServerState.tsx

**Summary**
What happens is that a synchronous error (as we had in the test, but not really in real life) gets caught by the derived helper as it happens before the response, but an async (regular) error happens in the response parsing, and thus before the derived helper even receives the result.
It gets rethrown by InstantSearch, but we also catch the errors in the main helper, just in case there's another case not covered here.
**Result**
fixes https://github.com/algolia/instantsearch/issues/5233
Any type of error in the flow of getServerState rejects the promise, allowing people to handle the error as they want.
In a future iteration we may consider catching the errors there to let the client gracefully correct, but for now that's not yet required.

fix(getServerState): correctly forward asynchronous errors

---

.circleci/config.yml

This PR uses a larger docker environment to run the e2e tests job. While it still takes a while to run (which could be attributed in part to our saucelabs opensource plan), the tests seem to run more reliably (no retries) and the CPU usage doesn't hit 100%.

ci: run e2e job on bigger environment

---

packages/instantsearch.js/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-dom/package.json
packages/react-instantsearch-hooks/package.json
packages/vue-instantsearch/package.json
tests/mocks/package.json
yarn.lock

**Summary**
The vulnerability comes up when user-defined search parameters have a malicious key `constructor`. An error then will be thrown, so the search will no longer be active, but any prototype injection would still happen, causing people to be vulnerable.
More info in https://github.com/algolia/algoliasearch-helper-js/issues/922
With default implementations of InstantSearch, this isn't reachable, as `searchParameters` aren't a direct parameter, except for `configure`.
**Result**
No prototype pollution vulnerability through search parameters.

fix(dependencies): update helper requirement for minor PP vulnerability

---

.circleci/config.yml
package.json
packages/create-instantsearch-app/package.json
yarn.lock

**Summary**
From this version onwards, we'll have annotated tags.
**Result**
https://github.com/algolia/shipjs/pull/989

ci(release): update shipjs

---

ship.config.js

**Summary**
As we don't publish everything anymore (since tags now get annotated https://github.com/algolia/instantsearch/pull/5420), we need to ensure we only try to tag what is taggable.
**Result**
no failure in CI on release task, as only packages that have changed (same as `lerna version`) will be tagged.

ci(release): publish only tags that have changed

---

packages/react-instantsearch-hooks/src/connectors/__tests__/useStats.test.tsx
packages/react-instantsearch-hooks/src/connectors/useStats.ts

**Summary**
Add a hook for `useStats` to `react-instantsearch-hooks`.
The goal is to be able to use use this hook to provide a widget, as well as replace the 'not implemented' documentation: https://www.algolia.com/doc/api-reference/widgets/stats/react-hooks/#about
**Result**
Review added test for basic functionality / expectation.
**Next Steps**
- Add a widget to `react-instantsearch-hooks`
- Update examples
- Update documentation

feat(react-instantsearch-hooks): Add useStats hook

---

packages/instantsearch.js/src/connectors/hits/connectHits.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts
packages/instantsearch.js/src/lib/utils/__tests__/createSendEventForHits-test.ts
packages/instantsearch.js/src/lib/utils/createSendEventForHits.ts

**Summary**
This cleans up the logic of sendEventForHits/bindEventForHits and always skips payload if search is not idle for both bindEvent and sendEvent (before this PR only sendEvent had this logic)
**Result**
bindEvent won't add keys to the dom when the search is currently not idle **for view events**, as you can't view something when it's not the initial view.

fix(bindEvent): skip view event if search isn't stable

---

packages/instantsearch.js/src/__tests__/common.test.tsx
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/react-instantsearch-hooks-web/src/__tests__/common.test.tsx
packages/vue-instantsearch/src/__tests__/common.test.js
tests/common/widgets/hierarchical-menu/optimistic-ui.ts
tests/common/widgets/menu/optimistic-ui.ts
tests/common/widgets/pagination/optimistic-ui.ts
tests/common/widgets/refinement-list/optimistic-ui.ts

**Summary**
going a step further than #5429, we want to also when there's an error revert to the last known good state.
**Result**
This goes back to the previous (non-optimistic) behaviour when an error happens, with a caveat that the state will be fully consistent. That means UiState and the URL also update back to the previous state

feat(rendering): revert search state on error

---

packages/instantsearch.js/src/lib/templating/renderTemplate.ts
packages/instantsearch.js/src/lib/utils/createSendEventForHits.ts
packages/instantsearch.js/src/types/templates.ts

**Summary**
sendEvent is only passed in cases bindEvent is as well (hits, infinitehits), and this means  `?.` in the docs can be removed before sendEvent
**Result**
when using `sendEvent` in a template, you  no longer need a conditional (`sendEvent?.(` -> `sendEvent`), as it was never actually required

fix(sendEvent):  correct types in template

---

packages/instantsearch.js/src/types/templates.ts
packages/instantsearch.js/stories/hits.stories.ts
packages/instantsearch.js/stories/infinite-hits.stories.ts

**Summary**
it doesn't work with `html`, so there's no point in continuing to have examples using it.
**Result**
bindEvent is no longer used in examples

docs(stories): remove bindEvent from examples

---

packages/react-instantsearch-hooks-web/src/ui/HierarchicalMenu.tsx
packages/react-instantsearch-hooks-web/src/ui/__tests__/HierarchicalMenu.test.tsx
packages/vue-instantsearch/src/components/HierarchicalMenuList.vue
packages/vue-instantsearch/src/components/__tests__/HierarchicalMenu.js
packages/vue-instantsearch/src/components/__tests__/__snapshots__/HierarchicalMenu.js.snap

**Summary**
This happens when the item is refined, but there's no items in the lower level. In InstantSearch.js and React InstantSearch Dom, we avoid adding the class in this case already:
https://github.com/algolia/instantsearch/blob/f84c01b2f66ac279f7e33fafe5f1cd559436edef/packages/instantsearch.js/src/components/RefinementList/RefinementList.tsx#L175-L179
https://github.com/algolia/instantsearch/blob/f84c01b2f66ac279f7e33fafe5f1cd559436edef/packages/react-instantsearch-dom/src/components/List.js#L64-L75
detected in https://github.com/algolia/instantsearch/discussions/5456
**Result**
`ais-HierarchicalMenu-item--parent` is not applied when children are empty, even if it is refined. This makes React InstantSearch Hooks and Vue InstantSearch consistent with the other flavours.

fix(HierarchicalMenu): don't give --parent class if data is empty

---

packages/instantsearch.js/src/types/instantsearch.ts

**Summary**
this isn't needed now, but i needed in a different iteration of a PR. It's probably interesting if it's exposed
**Result**
InstantSearchStatus type is exposed from InstantSearch.js root (so you don't have to do `InstantSearch['status']`

fix(types): expose InstantSearchStatus

---

examples/vue/e-commerce/src/App.vue
packages/vue-instantsearch/src/components/HitsPerPage.vue
packages/vue-instantsearch/src/components/__tests__/HitsPerPage.js
packages/vue-instantsearch/src/components/__tests__/SortBy.js
packages/vue-instantsearch/stories/HitsPerPage.stories.js

**Summary**
fixes https://github.com/algolia/instantsearch/issues/5397
Slight improvement in the HitsPerPage + SortBy tests, as it was relying on Vue state instead of the DOM
I wanted both to be exactly the same, but SortBy doesn't have isRefined on the items apparently.
Workaround in the example to make HitsPerPage responsive to the URL is also removed.
**Result**
This makes HitsPerPage responsive to the URL, as expected like other widgets.

fix(HitsPerPage): compute selected from isRefined

---

.github/workflows/release-templates.yml

**Summary**
We didn't `cd` into the proper build folder so this action was failing : https://github.com/algolia/instantsearch/actions/runs/4173320532/jobs/7225507147

fix(templates): cd into proper build dir

---

packages/react-instantsearch-hooks-server/README.md

remove the experimental warning for React InstantSearch Hooks server

fix(readme): remove experimental warning

---

packages/instantsearch.js/src/__tests__/common.test.tsx
packages/instantsearch.js/src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
packages/instantsearch.js/src/connectors/breadcrumb/connectBreadcrumb.ts
packages/react-instantsearch-hooks-web/src/__tests__/common.test.tsx
packages/vue-instantsearch/src/__tests__/common.test.js
tests/common/index.ts
tests/common/widgets/breadcrumb/index.ts
tests/common/widgets/breadcrumb/optimistic-ui.ts

**Summary**
If a breadcrumb widget gets "its" hierarchical menu added dynamically, there will be a render where getFacetValues returns `undefined`.
I checked, and all other cases of `getFacetValues` guard already for its result possibly being undefined.
Also added the common test for optimistic UI for breadcrumb, as it's a related fix.
**Result**
No error when hierarchical menu for a breadcrumb gets added dynamically

fix(breadcrumb): guard against undefined facets

---

packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts

**Summary**
When the insights middleware is instantiated, it will attempt to extract or load a search-insights client.
**Result**
- insights middleware makes `insightsClient` optional
- first it checks if there's an unlinked existing insights client
- then it loads search-insights from jsDelivr
- if there's an error in this loading, nothing happens
FX-2244

feat(insights): automatically load search-insights if not passed

---

packages/instantsearch.js/src/lib/InstantSearch.ts

**Summary**
onStateChange has the same capabilities, but has the advantage of not being linked to search parameters.
**Result**
a warning is given when you use the `searchFunction` prop.

fix(core): deprecate searchFunction

---

packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts

instead of passing your own middleware, where timing could be tricky, to disable the internal middleware you pass `insights: false` to InstantSearch. Note that the internal middleware will still be removed when a different middleware is passed to allow easy customisation
FX-2250

feat(insights): option to disable automatic insights middleware

---

packages/instantsearch.js/src/types/index.ts
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/react-instantsearch-hooks/src/lib/useIndexContext.ts
packages/react-instantsearch-hooks/src/lib/useSearchState.ts

**Summary**
This function is visible in useInstantSearch, so it has potential to supplant the usage of `helper.setState().search` in the future.
**Result**
- adds index.setIndexUiState
- use index.setUiState in useInstantSearch
- allow IndexWidget type to be generic

feat(index): introduce setIndexUiState

---

packages/instantsearch.js/src/lib/routers/history.ts
packages/instantsearch.js/src/lib/stateMappings/simple.ts
packages/instantsearch.js/src/lib/stateMappings/singleIndex.ts
packages/instantsearch.js/src/middlewares/__tests__/createMetadataMiddleware.ts
packages/instantsearch.js/src/middlewares/createMetadataMiddleware.ts
packages/instantsearch.js/src/middlewares/createRouterMiddleware.ts
packages/instantsearch.js/src/types/router.ts
packages/react-instantsearch-hooks-router-nextjs/src/index.ts

**Summary**
Since `$$type` and `$$internal` are added in #5488, we can use this to give some information around middleware in metadata
**Result**
A new type of `widgets` is available, with a shape like this: 
```json
{
"widgets": [{ "middleware": true, "type": "ais.insights", "internal": false }]
}
```
We don't know the parameters passed by the users, as it's defaulted early on in the arguments and there's no equivalent to getWidgetRenderState().widgetParams.
However, in the router middleware, the router and state mapping are also identified in the `$$type`
This is the same as #5491, but in the existing `widgets` key.

feat(metadata): register metadata around middleware

---

packages/react-instantsearch-hooks/src/hooks/useInstantSearch.ts

As [discussed internally](https://algolia.slack.com/archives/C03QWAMAN6P/p1677684849444629), exporting the `InstantSearchApi` is handy in consumers app to make sure that types are fully consistent.
As an example, there are a few unintended bugs on the dashboard search because they use their own `SearchResults` type for `useInstantSearch().results`, and they assumed that it can be `null` when loading. But it doesn't, RISHooks always exposes a fallback results object.
Consumer apps will now be able to rely on things like `InstantSearchApi['results']` to minimize this kind of errors.
I also defaulted the generic to `UiState` so that it can be used just like `useInstantSearch()` which is already defaulted.

feat(react): export `InstantSearchApi` type

---

packages/instantsearch.js/src/lib/utils/createSendEventForHits.ts

**Summary**
remove a needless call to `hits.slice`, as the hits are split into chunks later, and thus `hits.__escaped` doesn't get serialised.
**Result**
We are splitting all events in batches of 20, so __escaped is already removed from the hits.
This is already covered by existing tests.

refactor(sendEvent): simplify code

---

.circleci/config.yml

**Summary**
This PR stops running e2e tests on every branch and instead moves the job into a scheduled pipeline. It's currently set to run daily at 9PM CET. In case of failure a notification is sent to Slack.
It also moves the existing weekly release scheduled workflow to a scheduled pipeline as well, managed through Circle CI.
**Result**
CI pipelines are now completed in less time.

ci: run e2e in a scheduled pipeline

---

.eslintrc.js
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/widgets/index/index.ts

**Summary**
We were using non-null assertions in `dispose` of InstantSearch and index widget as we were assuming start/init comes first, but that's not necessarily the case.
**Result**
No errors when disposing without calling start

fix(instantsearch): allow dispose before start

---

packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx
packages/react-instantsearch-hooks/src/components/__tests__/DynamicWidgets.test.tsx

All our documentation makes sure to use stable references, although it could also make sure to clarify that is a requirement as well.
**Summary**
When you re-render and use a fallbackComponent which isn't stable, this causes that widget to unmount and remount (as a different widget). We now prevent that by making sure (and warning when it isn't) that fallbackComponent is stable.
Note that this could be considered breaking if someone was _only_ rendering when the widget actually changed (some other state possibly), but I'd consider that code already broken personally, as a render happening when the widget doesn't change would erase the state.
fixes #5530
**Result**
- add a warning when the fallbackComponent isn't stable
- only ever use the first value of fallbackComponent

fix(DynamicWidgets): prevent non-stable fallbackComponent

---

packages/instantsearch.js/src/lib/__tests__/routing/spa-test.ts
packages/instantsearch.js/src/lib/routers/history.ts
packages/instantsearch.js/src/middlewares/createRouterMiddleware.ts
packages/instantsearch.js/src/types/router.ts

**Summary**
Previously this code considered that InstantSearch is started once, and then disposed, but if the instance is restarted (and its widgets remounted) like in React InstantSearch Hooks, routing should no longer be considered disposed
discovered in https://github.com/algolia/instantsearch/discussions/5519#discussioncomment-5226767
**Result**
- routers can have a new method "start"
- in start we make sure router is no longer considered disposed

fix(routing): allow writing when InstantSearch restarts

---

packages/instantsearch.js/src/components/CurrentRefinements/__tests__/CurrentRefinements-test.tsx
packages/instantsearch.js/src/connectors/current-refinements/__tests__/connectCurrentRefinements-test.ts
packages/instantsearch.js/src/connectors/current-refinements/connectCurrentRefinements.ts
packages/instantsearch.js/src/widgets/current-refinements/__tests__/__snapshots__/current-refinements-test.ts.snap
packages/react-instantsearch-hooks/src/connectors/__tests__/useCurrentRefinements.test.tsx

**Summary**
The `currentRefinements` widget provides a way to transform/filter refined items to be returned, which is useful in multi-indices context, to potentially remove refinements from another index.
This works well when indices are different, but in the context of multi-indices targeting the same index with different configuration, it is impossible to easily determine which refinements are from where. 
This PR adds a `indexId` parameter to the items provided in `transformItems`, which solves this issue.

feat(current-refinements): provide indexId of refinements in transformItems

---

packages/vue-instantsearch/src/__tests__/common.test.js
packages/vue-instantsearch/src/components/Hits.vue
packages/vue-instantsearch/src/components/InfiniteHits.vue
packages/vue-instantsearch/src/components/__tests__/Hits.js
packages/vue-instantsearch/src/components/__tests__/InfiniteHits.js
packages/vue-instantsearch/src/util/vue-compat/index-vue3.js
tests/common/widgets/hits/index.ts
tests/common/widgets/infinite-hits/index.ts

it's like FX-2271, but for Vue.
I recommend you review this PR with "ignore whitespace" enabled, it's quite confusing otherwise

feat(hits/infinite-hits): send a default click event and expose sendEvent to slot

---

packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts

**Summary**
This allows passing all insights middleware options to the instantsearch constructor as well, simplifying the guide on "how to use insights", even if we choose to change the default of the insights option to `false`
**Result**
`insights` option to InstantSearch accepts options for the insights middleware.

feat(insights): allow passing options to default middleware

---

examples/react-hooks/default-theme/src/components/Refresh.tsx
packages/instantsearch.js/src/widgets/panel/panel.tsx
packages/vue-instantsearch/src/components/SearchInput.vue
packages/vue-instantsearch/src/components/__tests__/__snapshots__/RefinementList.js.snap
packages/vue-instantsearch/src/components/__tests__/__snapshots__/SearchBox.js.snap
specs/src/pages/widgets/panel.md

Browsers warn for a width/height attribute which isn't a number, as it can only be a "unitless value" (px). Despite that it does seem to work.
Components involved:
- SearchBox in Vue
- Panel in JS
- Refresh in hooks example

fix(svg): don't style width/height in attributes with unit

---

packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/instantsearch.js/src/widgets/hierarchical-menu/__tests__/hierarchical-menu.test.tsx
packages/instantsearch.js/src/widgets/hits/__tests__/hits-integration-test.ts
packages/instantsearch.js/src/widgets/infinite-hits/__tests__/infinite-hits-integration-test.ts
tests/common/widgets/hits/insights.ts
tests/common/widgets/infinite-hits/insights.ts

This attaches the Algolia credentials to each event we send, via `headers`.
The goal is to ensure events are always sent to the right app even when the Insights client is shared—for example, when using InstantSearch together with Autocomplete.
[FX-2278](https://algolia.atlassian.net/browse/FX-2278)
[FX-2278]: https://algolia.atlassian.net/browse/FX-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(createInsightsMiddleware): always pass Algolia credentials locally

---

packages/vue-instantsearch/src/components/__tests__/InstantSearch.js
packages/vue-instantsearch/src/util/createInstantSearchComponent.js

This ports the change made in https://github.com/algolia/instantsearch/pull/5563 in Vue InstantSearch.
I'm still unsure this is necessary in Vue InstantSearch, as Vue keeps track of object references between updates. Happy to drop it if we think it doesn't apply here.

feat(ais-instant-search): warn when an unstable search client is detected

---

packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts

One of the most common mistakes customers make is to provide a new instance of the search client at each re-render, often by instantiating the client inside their component. While this can sometimes be wanted (e.g., to update an ephemeral API key), this is more frequently an oversight which causes InstantSearch to dispatch more search requests than necessary.
This change adds a dev warning that lets you know of an unstable search client. I'll also update the linked docs to add a note on client stability.
If we're happy to move forward with this change, I'll do it for Vue InstantSearch as well.

feat(useInstantSearchApi): warn when an unstable search client is detected

---

packages/instantsearch.js/src/widgets/places/places.ts

**Summary**
fixes #5570
In https://github.com/algolia/instantsearch/pull/5508, we ordered the imports, but this didn't move the ts-ignore
**Result**
ts-ignore is in the right place, places.js is not required for typescript.

fix(places): don't require package to be installed

---

packages/react-instantsearch-hooks-server/src/__tests__/getServerState.test.tsx
packages/react-instantsearch-hooks-server/src/getServerState.tsx

**Summary**
In server environments, the InstantSearch instance gets passed from InstantSearchSSRProvider to InstantSearch, meaning that all child InstantSearch components have the _same_ instance, which can cause many issues.
As this already is working badly, I don't think erroring would be a breaking change, but possibly people are already relying on the current behaviour?
I considered finding a place to have this error in useInstantSearch (as it's the real root cause), I couldn't find anything that still worked with strict mode only creating one InstantSearch instance for both renders.
**Result**
fixes https://github.com/algolia/instantsearch/issues/5585
An error gets thrown if there are multiple InstantSearch components in a single call to getWidgetState

fix(server): error when multiple InstantSearch instances in getServerState

---

bundlesize.config.json
packages/react-instantsearch-hooks/src/components/InstantSearchSSRProvider.tsx
packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
packages/react-instantsearch-hooks/src/lib/InstantSearchSSRContext.ts
packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
packages/react-instantsearch-hooks/src/lib/useInstantSearchContext.ts
packages/react-instantsearch-hooks/src/lib/useWidget.ts

**Summary**
When unmounting multiple widgets at once, but not the InstantSearch widget, multiple searches were triggered. This was because every timeout leaves a moment for microtasks to be processed, and thus did not deduplicate scheduleSearch.
**Result**
This PR fixes that by adding a private timeout-based scheduler that ensures all removeWidgets calls get called synchronously.
CR-3255

fix(lifecycle): prevent extra network requests when unmounting multiple widgets

---

packages/react-instantsearch-hooks/src/components/__tests__/DynamicWidgets.test.tsx
tests/utils/widgetSnapshotSerializer.ts

When the assertions for objectContaining fail, they give a whole lot of information that isn't actually useful, as we only want to know the type.
I therefore changed it to using the snapshot serialiser we have for widgets, and the diffs are much neater when there's the wrong widgets mounted.

test(DynamicWidgets): clearer assertions for widgets

---

packages/create-instantsearch-app/README.md
packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/package.json
packages/create-instantsearch-app/scripts/release-templates.js
packages/create-instantsearch-app/src/templates/Angular InstantSearch/README.md
packages/create-instantsearch-app/src/templates/Autocomplete.js 0/README.md
packages/create-instantsearch-app/src/templates/Autocomplete/README.md
packages/create-instantsearch-app/src/templates/InstantSearch.js 2/README.md
packages/create-instantsearch-app/src/templates/InstantSearch.js 2/index.html.hbs
packages/create-instantsearch-app/src/templates/InstantSearch.js widget/README.md
packages/create-instantsearch-app/src/templates/InstantSearch.js/README.md
packages/create-instantsearch-app/src/templates/InstantSearch.js/index.html.hbs
packages/create-instantsearch-app/src/templates/JavaScript Client/README.md
packages/create-instantsearch-app/src/templates/JavaScript Helper 2/README.md
packages/create-instantsearch-app/src/templates/JavaScript Helper/README.md
packages/create-instantsearch-app/src/templates/React InstantSearch Hooks Native/README.md
packages/create-instantsearch-app/src/templates/React InstantSearch Hooks/README.md
packages/create-instantsearch-app/src/templates/React InstantSearch Hooks/src/App.tsx.hbs
packages/create-instantsearch-app/src/templates/React InstantSearch Native/README.md
packages/create-instantsearch-app/src/templates/React InstantSearch widget/README.md
packages/create-instantsearch-app/src/templates/React InstantSearch/README.md
packages/create-instantsearch-app/src/templates/React InstantSearch/src/App.js.hbs
packages/create-instantsearch-app/src/templates/Vue InstantSearch 1/README.md
packages/create-instantsearch-app/src/templates/Vue InstantSearch 1/src/App.vue
packages/create-instantsearch-app/src/templates/Vue InstantSearch 2/README.md
packages/create-instantsearch-app/src/templates/Vue InstantSearch 2/src/App.vue
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/README.md
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/src/App.vue
packages/create-instantsearch-app/src/templates/Vue InstantSearch/README.md
packages/create-instantsearch-app/src/templates/Vue InstantSearch/src/App.vue

**Summary**
This PR updates the links pointing to the monorepo for the `create-instantsearch-app` package.
**Result**
Links to the old `algolia/instantsearch.js` repo are now pointing to the `algolia/instantsearch` monorepo.
e2e test snapshots have been updated as well.

chore(create-instantsearch-app): update links to monorepo

---

packages/instantsearch.js/package.json
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/react-instantsearch-hooks/src/__tests__/insights.test.tsx
tests/common/widgets/hits/insights.ts
tests/common/widgets/infinite-hits/insights.ts
tests/mocks/createInsightsClient.ts
yarn.lock

Thanks to http://github.com/algolia/search-insights.js/pull/441 token can be set automatically, so useCookie isn't needed anymore.
Because of this, the minimum modern version of search-insights is 2.6.0
FX-2304

feat(insights): remove useCookie from default parameters

---

packages/instantsearch.js/.storybook/decorators/withHits.ts
packages/instantsearch.js/package.json
packages/instantsearch.js/src/connectors/sort-by/__tests__/connectSortBy-test.ts
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/lib/utils/render-args.ts
packages/instantsearch.js/src/widgets/dynamic-widgets/__tests__/dynamic-widgets-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/instantsearch.js/src/widgets/sort-by/__tests__/sort-by-test.ts
packages/instantsearch.js/stories/instantsearch.stories.ts
packages/react-instantsearch-core/package.json
packages/react-instantsearch-dom/package.json
packages/react-instantsearch-hooks/package.json
packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
packages/vue-instantsearch/package.json
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js
packages/vue-instantsearch/src/util/createInstantSearchComponent.js
tests/mocks/package.json
yarn.lock

requires https://github.com/algolia/algoliasearch-helper-js/pull/938
Essentially this allows us to create neat non-inheriting indices like this with only three queries sent:
```jsx
const App = (
<InstantSearch>
<Index indexName="1" indexId="1a" />
<Index indexName="1" indexId="1b" />
<Index indexName="2" />
</InstantSearch>
);
```
Combined with https://github.com/algolia/react-instantsearch/pull/3690 again, you could also create
```jsx
// 🚨 this isn't possible yet
const App = (
<InstantSearch>
<Index indexName="1">
{/* other widgets, causing no results */}
<NoResults>
<Index indexName="1" parentIndexId={null}>
{/* display stuff from a separate query,
without interference of inheritance */}
</Index>
</NoResults>
</Index>
</InstantSearch>
);
```
**Summary**
Allow for more flexible use cases …

feat(instantsearch): make root indexName optional

---

packages/instantsearch.js/src/lib/routers/__tests__/history.test.ts
packages/instantsearch.js/src/lib/routers/history.ts

**Summary**
There are two reasons we want users to create absolute URLs with `createURL` : 
- This issue which is actually mentioned in comments : #790 
- In [shouldWrite](https://github.com/algolia/instantsearch/blob/a8b5c1e5bbd6afac39fce523f7d7c2ec02f51153/packages/instantsearch.js/src/lib/routers/history.ts#L263) we expect it to match `window.location.href`.
At first I was thinking about ignoring what's before the `pathname` in `shouldWrite` but as there are other reasons we want URLs to be absolute, I think adding a warning might be what's best.
**Result**
Added a test to check that it's outputted.

feat(history): warn when `createURL` does not return an absolute URL

---

packages/react-instantsearch-hooks-router-nextjs/README.md

**Summary**
This PR adds a warning about the Next.js function `getStaticProps()` incompatibility with the `createInstantSearchRouterNext()` function using RISH.
This is related to this issue: https://github.com/algolia/instantsearch/issues/5617

docs(react-instantsearch-hooks-router-nextjs): add a warning about static rendering

---

packages/instantsearch.js/src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
In an InstantSearch implementation with dynamic widgets and a custom infinite hits cache, the latter gets overwritten incorrectly because facets are not initially known (until their relevant widgets are mounted by dynamic widgets).
This PR detects this context and prevents writing an incomplete state in the cache.
FX-1647

fix(infinite-hits): do not write cache with incomplete state caused by dynamic widgets

---

packages/create-instantsearch-app/src/templates/React InstantSearch Hooks Native/package.json
packages/create-instantsearch-app/src/templates/React InstantSearch Hooks/package.json

**Summary**
This PR removes the fixed declaration of `instantsearch.js` as a dependency from RISH templates in Create InstantSearch App. This can causes type and feature mismatch between React InstantSearch Hooks and InstantSearch.js if versions are not in sync.
Since `instantsearch.js` is already a dependency of `react-instantsearch-hooks`, this is not needed.
**Result**
In React InstantSearch Hooks templates, `instantsearch.js` will be downloaded as a dependency of `react-instantsearch-hooks` with the appropriate version.

fix(cisa): remove fixed isjs dependency from rish templates

---

examples/react-hooks/default-theme/package.json
examples/react-hooks/e-commerce/package.json
examples/react-hooks/getting-started/package.json

**Summary**
This is a quick QOL change that prevents issues on CodeSandbox that could be related to an unsupported TypeScript version.
**Result**
Now users can copy/paste code from our doc to some of our sandboxes without having issues that could be related to the default TypeScript version available in CodeSandbox.

chore(examples): set explicit typescript dev dependency for rish examples

---

packages/instantsearch.js/src/components/Hits/Hits.tsx
packages/instantsearch.js/src/components/Hits/__tests__/__snapshots__/Hits-test.tsx.snap
packages/instantsearch.js/src/components/InfiniteHits/InfiniteHits.tsx
packages/react-instantsearch-hooks-web/src/ui/Hits.tsx
packages/react-instantsearch-hooks-web/src/ui/InfiniteHits.tsx
packages/vue-instantsearch/src/components/Hits.vue
packages/vue-instantsearch/src/components/InfiniteHits.vue
tests/common/widgets/hits/insights.ts
tests/common/widgets/infinite-hits/insights.ts

From [StackOverflow](https://stackoverflowteams.com/c/algolia/questions/3359).
When insights are enabled, default click events on hits / infinite hits are not sent if a user clicks with their pointer's auxiliary button (usually the mousewheel button). The main use case is opening a product detail page on a new browser tab.
This is because our default handler is set on a `click` event, which is only triggered by actions using the pointer's primary button. Here are more information on how and when this has been implemented by browsers:
- https://developer.chrome.com/blog/auxclick/
- https://bugzilla.mozilla.org/show_bug.cgi?id=1304044
To solve this, hits and infinite hits now also handle the `auxclick` event, triggered by actions using the pointer's auxiliary buttons.
> **Alternative …

fix(insights): send default click event when using auxiliary pointer button

---

packages/create-instantsearch-app/package.json
packages/create-instantsearch-app/src/cli/index.js
packages/create-instantsearch-app/src/cli/postProcessAnswers.js
yarn.lock

**Summary**
We use both semver and latest-server, and the usage of latest-semver is actually not much simpler than semver directly.
**Result**
no more usage and dependency on latest-semver

refactor(deps): replace latest-semver with semver

---

packages/instantsearch.js/src/connectors/answers/connectAnswers.ts
packages/instantsearch.js/src/connectors/autocomplete/connectAutocomplete.ts
packages/instantsearch.js/src/connectors/hits/connectHits.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts
packages/instantsearch.js/src/lib/utils/escape-highlight.ts
packages/instantsearch.js/src/lib/utils/getHighlightedParts.ts

**Summary**
A problem we currently have (see https://github.com/algolia/instantsearch/issues/5237) is that escapeHTML is one of the slower parts of InstantSearch.
With `html``/jsx rendering without dangerousInnerHtml, we no longer need to escape by default, but for that to work, escaping and not escaping should both leave the "placeholders" in the final output.
Current workaround for the performance impact: pass `escapeHTML={false}` to every Hits/infiniteHits etc. and `<Configure highlightPreTag={TAG_REPLACEMENT.highlightPreTag} highlightPostTag={TAG_REPLACEMENT.highlightPostTag} />`
**Result**
`@MAJOR` comments on how to avoid the need for escapeHTML for hits. Facets can also be done at the same time.

chore(major): leave major comments on how to improve highlighting

---

.eslintrc.js
packages/react-instantsearch-hooks/package.json
packages/react-instantsearch-hooks/scripts/version.cjs

**Summary**
It's written in CommonJS, as that way it's the same as the other packages in the project, but it has `type: module` in the package.json, so needs to be marked as cjs.
Also changed the lint to not need ignore comments in cjs files for using cjs
**Result**
`yarn run version` in React InstantSearch Hooks works without error

chore(versions): ensure React InstantSearch Hooks version script runs in CommonJS

---

examples/js/calendar-widget/app.js
packages/instantsearch.js/stories/answers.stories.ts
packages/instantsearch.js/stories/infinite-hits.stories.ts

**Summary**
Find all usages of hit templates that aren't using the html tagged template, to encourage its usage further
**Result**
No usages for `(hit) => `, all replaced with `(hit, {html}) =>` (except in tests)

docs(examples): avoid usage of html-as-a-string

---

packages/instantsearch.js/src/__tests__/common.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common.test.tsx
packages/vue-instantsearch/src/__tests__/common.test.js
tests/common/common.ts
tests/common/index.ts
tests/common/widgets/instantsearch/algolia-agent.ts
tests/common/widgets/instantsearch/index.ts

**Summary**
In follow-up of #5662 and #5655 (under FX-2385), a test is added to ensure agents added to algoliasearch stay in sync with the respective package.jsons.
This may somewhat be overkill, but at least we'll be extra sure.
**Result**
- a new suite in common test suites for instantsearch
- a method to pass specific assertions per flavour (return of setup function)
- assertions that all versions match the respective package.jsons
In those tests, the server-specific algolia agents aren't tested or asserted upon, as they're too conditional
I used relative imports to make sure Jest doesn't mess with them too much, and used require, as that's not static, but import could easily be used too.

tests(algoliaAgent): ensure all algoliaAgents match expectation

---

packages/instantsearch.js/src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
In #5620 we added a logic to ensure cache does not get written when we expect dynamic widgets to be mounted in the future. This check was too strict and prevented writing when they're _were_ widgets, but they had no results.
I have a couple questions still that maybe should be solved:
- is this check still too strict, what if no widgets get mounted? shouldn't we also write to the cache then?
- what if there are static refinement widgets mounted outside of dynamicWidgets? Does that break this check?
I believe both of these questions can be solved after this PR
**Result**
fixup upon https://github.com/algolia/instantsearch/pull/5620
replaces https://github.com/algolia/instantsearch/pull/5668
FX-2397
Read the condition for deciding if there's any widgets mounted from the state, …

fix(infiniteHits): correctly avoid writing to cache when dynamicWidgets has no facets in the results

---

bundlesize.config.json
packages/react-instantsearch-hooks-server/src/__tests__/getServerState.test.tsx
packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts

**Summary**
This PR tracks the Next.js version by adding it as an Algolia agent when a Next.js app is detected.
To get the Next.js version:
- on the browser: `window.next.version` (e.g. `12.1.6`).
- in SSR: `process.env.NEXT_RUNTIME` (`nodejs` or `edge`).

feat(algoliaAgent): track Next.js version as Algolia agent

---

packages/instantsearch.js/src/connectors/toggle-refinement/types.ts

**Summary**
Types seems to have existed both in a types file and in the connector. I'm assuming this is an oversight from the TypeScript migration where it was migrated two times.
I did not remove the `types.ts` file in case someone depends on it, but can be removed in a next major. I did remove the duplicated types and re-export from the main file instead.
**Result**
- dead types removed in toggle-refinement/types.ts
- re-exported the types from main file, but mark them as deprecated

chore(connectToggleRefinement): remove duplicated types

---

packages/instantsearch.js/src/middlewares/__tests__/createRouterMiddleware.ts
packages/instantsearch.js/src/middlewares/createRouterMiddleware.ts

**Summary**
This PR prevents the UI state from being updated when there are no widgets mounted. This can happen intermittently with Next.js when the route is changed to an InstantSearch-enabled page.
See [CR-3772](https://algolia.atlassian.net/browse/CR-3475).
**Result**
When using routing, UI state is not updated on subscribe if widgets are not yet mounted.
[CR-3772]: https://algolia.atlassian.net/browse/CR-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(router): do not update ui state if there are no widgets

---

examples/react-hooks/getting-started/src/index.tsx
packages/react-instantsearch-hooks/src/connectors/__tests__/useGeoSearch.test.tsx
packages/react-instantsearch-hooks/src/connectors/useGeoSearch.ts

**Summary**
Adds `useGeoSearch()` hook to Reach InstantSearch Hooks
**Result**

feat(GeoSearch): expose useGeoSearch() hook in RISH

---

examples/vue/default-theme/babel.config.js
examples/vue/e-commerce/babel.config.js
examples/vue/getting-started/babel.config.js
examples/vue/media/babel.config.js

**Summary**
Since the integration of `algoliasearch-helper` into the monorepo, e2e tests fail on vue-instantsearch examples because of a runtime error.
This is due to babel not transpiling CJS dependencies into ESM when they are locally linked, which is now the case. By setting the relevant config option in babel.config.js on all applicable examples, we can force babel to transpile the helper and prevent this issue from appearing at runtime.
- https://babeljs.io/docs/options#sourcetype
- https://github.com/vuejs/vue-cli/issues/2746
**Result**
e2e tests should now work as expected, because the vue-instantsearch examples are not failing at runtime anymore.

chore(examples): update vue examples to transpile local helper dependency

---

packages/instantsearch.js/src/__tests__/common-connectors.test.tsx
packages/instantsearch.js/src/__tests__/common-shared.test.tsx
packages/instantsearch.js/src/__tests__/common-widgets.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common-connector.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common-shared.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common-widget.test.tsx
packages/vue-instantsearch/src/__tests__/common-connectors.test.js
packages/vue-instantsearch/src/__tests__/common-shared.test.js
packages/vue-instantsearch/src/__tests__/common-widgets.test.js

The common test suite tests are now moved into an object of "setups" and ran separately.
This allows for a couple things that are nice
- you can easily skip running a test or run just a single one by putting a condition in the loop
- TypeScript enforces all tests are implemented
- jest enforces all tests are implemented

test(common): validate that all tests are implemented

---

packages/react-instantsearch-hooks-web/src/ui/Stats.tsx
packages/react-instantsearch-hooks-web/src/ui/__tests__/Stats.test.tsx
packages/react-instantsearch-hooks-web/src/widgets/Stats.tsx
packages/react-instantsearch-hooks-web/src/widgets/__tests__/Stats.test.tsx
packages/react-instantsearch-hooks/src/index.ts

The `<Stats>` widget was introduced in https://github.com/algolia/instantsearch/pull/5427 but the translation name isn't consistent with the convention we agreed on in the [Translations RFC](https://github.com/algolia/instantsearch-rfcs/blob/master/implemented/translations-api-rish.md#naming).
This changes the name for something more consistent and conventional.
The change is breaking for anyone already using the `<Stats>` widget.

feat(react-instantsearch-hooks web): rename `<Stats>` translation

---

packages/instantsearch.js/src/__tests__/common-connectors.test.tsx
packages/instantsearch.js/src/__tests__/common-shared.test.tsx
packages/instantsearch.js/src/__tests__/common-widgets.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common-connectors.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common-shared.test.tsx
packages/react-instantsearch-hooks-web/src/__tests__/common-widgets.test.tsx
packages/vue-instantsearch/src/__tests__/common-connectors.test.js
packages/vue-instantsearch/src/__tests__/common-shared.test.js
packages/vue-instantsearch/src/__tests__/common-widgets.test.js
tests/common/common.ts
tests/common/connectors/current-refinements/index.ts
tests/common/index.ts

**Summary**
In a previous iteration of ensuring all common tests suites are implemented, we conceded and assumed you can't type-safe loop over multiple objects (with the same key).
This is actually possible thanks to: https://github.com/microsoft/TypeScript/issues/49506#issuecomment-1639884200
**Result**
- No more ts-ignore in the common-test suite runner
- more consistency between tests

test(common): make test loop typesafe

---

bundlesize.config.json
packages/instantsearch.js/scripts/rollup/rollup.config.js
packages/react-instantsearch-core/rollup.config.js
packages/react-instantsearch-dom-maps/rollup.config.js
packages/react-instantsearch-dom/rollup.config.js
packages/react-instantsearch-hooks-web/rollup.config.js
packages/react-instantsearch-hooks/rollup.config.js
packages/react-instantsearch/rollup.config.js
packages/vue-instantsearch/rollup.config.js

**Summary**
Since the integration of the algoliasearch-helper to the monorepo, it is locally linked to other packages that depend on it (most notably, instantsearch.js). This created an issue during the building of the UMD version of the package, where babel doesn't transpile the helper dependency because now it is locally linked thanks to lerna.
This PR adds a babel configuration option that forces the library to be transpiled.
**Result**
InstantSearch.js's UMD package now works correctly and doesn't throw an error at runtime.
[CR-3961](https://algolia.atlassian.net/browse/CR-3961)  
Closes https://github.com/algolia/instantsearch/issues/5763
[CR-3961]: https://algolia.atlassian.net/browse/CR-3961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

fix(instantsearch): keep algoliasearch-helper as external dependency during build

---

packages/algoliasearch-helper/src/SearchParameters/index.js
packages/algoliasearch-helper/src/requestBuilder.js
packages/algoliasearch-helper/test/datasets/SearchParameters/search.dataset.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/getQuery.js
packages/algoliasearch-helper/test/spec/hierarchical-facets/with-a-disjunctive-facet.js
packages/algoliasearch-helper/test/spec/requestBuilder.js

This allows a better cache hit rate, because when widgets mount and unmount, it's possible that while the filters are the same, they are requested in a different order.
This PR fixes that on two approaches:
- sorting the filters (alphabetically by value per type), which has no impact on the SearchResponse
- sorting the queries (alphabetically by facet name per type), which also needs to be taken in account for the SearchResponse (so it is implemented in SearchParameters)
fixes [CR-3813](https://algolia.atlassian.net/browse/CR-3813)
[CR-3813]: https://algolia.atlassian.net/browse/CR-3813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(caching): sort filters and queries

---

packages/react-instantsearch-hooks-router-nextjs/src/index.ts
packages/react-instantsearch-hooks-server/src/__tests__/index.test.ts
packages/react-instantsearch-hooks-server/src/index.ts
packages/react-instantsearch-hooks-web/src/__tests__/index.test.ts
packages/react-instantsearch-hooks-web/src/index.ts
packages/react-instantsearch-hooks/src/__tests__/index.test.ts
packages/react-instantsearch-hooks/src/index.ts

**Summary**
A warning on import of the packages to let people know to change packages.
**Result**
A warning on import of the root entry point of React InstantSearch Hooks, React InstantSearch Hooks web, React InstantSearch Hooks server and React InstantSearch Hooks router nextjs with the next name
The warning is dated for 9 August, to give us a day margin to definitely have released, happy to move it a little later as well if we prefer.
Note that if you're using React InstantSearch Hooks web, you'll get the warning for both React InstantSearch Hooks and React InstantSearch Hooks web, I didn't find how to avoid it
FX-2391

fix: add a future warning when the package name changes

---

examples/react-hooks/e-commerce/components/ScrollTo.tsx
packages/react-instantsearch-hooks/src/hooks/__tests__/useInstantSearch.test.tsx
packages/react-instantsearch-hooks/src/hooks/useInstantSearch.ts

**Summary**
To prevent confusion caused by the upcoming React `use()` Hook, and also to better describe the intent of our function, this PR deprecates our current `use()` function available from `useInstantSearch()` and replaces it with `addMiddlewares()`.
The API is the same.
Closes FX-2548

fix(useInstantSearch): deprecate `use` function

---

packages/react-instantsearch-dom/.storybook/webpack.config.js

**Summary**
**Result**
Same fix as for `instantsearch.js`
[CR-3986]: https://algolia.atlassian.net/browse/CR-3986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(react-storybook): exclude helper from babel config

---

packages/create-instantsearch-app/src/utils/__tests__/fetchLibraryVersions.test.js
packages/create-instantsearch-app/src/utils/fetchLibraryVersions.js
packages/create-instantsearch-app/src/utils/index.js

**Summary**
We currently rely on an Algolia index to retrieve package versions for libraries. This index currently has issues and is not up to date. We've identified that this will cause problem in our CI pipeline when we release the new version of React InstantSearch, as we replace the `react-instantsearch` package in a major, which will require setting version constraint on our CISA CLI.
**Result**
We now directly query the NPM registry to get versions for libraries, and there's an in-memory cache to optimize for multiple queries for the same package in the same CISA CLI session.

fix: use npm registry to retrieve library versions

---

packages/instantsearch.js/src/connectors/pagination/connectPagination.ts
packages/react-instantsearch/src/widgets/__tests__/Pagination.test.tsx
tests/common/connectors/pagination/routing.ts
tests/common/shared/routing.ts

**Summary**
Unlike search parameters and what's returned in pages, UiState uses 1-based pagination, during the migration in #5696 this was overlooked
**Result**
fix #5797
createURL and refine of pagination now both correctly use 0-based pagination in the argument, agreeing on the values.

fix(pagination): correctly use 1-based pagination in createURL

---

.circleci/config.yml
tests/e2e/wdio.saucelabs.conf.js

**Summary**
This PR runs the **e2e router nextjs** job without waiting for examples to be built. Examples are not necessary for this e2e test suite to run, and it will help optimize sauce labs resources by not having both e2e jobs running at the same time.
In addition, the IE11 test suite now asks to be run in a Windows 7 VM, as Sauce labs has issues with it running on Windows 10.
Passing CI: https://app.circleci.com/pipelines/github/algolia/instantsearch/9231/workflows/2cd0f56d-7cde-4460-9d1e-6b38611fb0d4

e2e: fix ie11 test suite and prevent parallel e2e jobs

---

packages/instantsearch-codemods/src/rish-to-ris.ts

**Summary**
`use` now properly gets renamed
this is used by codeshift somehow (found by trying it out in the doc-code-samples), not sure why our tests are using an old version of babel (i see `return require('../parser/babel5Compat')(options);` in node_modules)
**Result**
Unfortunately no new test for this: https://github.com/facebook/jscodeshift/issues/510

fix(use): compatibility for modern babel

---

packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts

This fixes a typing issue in the Insights middleware (and the `insights` prop of InstantSearch) where the init params type was out of sync with Search Insights. Specifically, the `userToken` param was missing.
In my case, I do need to provide `userToken` at this level because it comes from my app. If I don't provide it, then InstantSearch sends automatic events with a random user token, which is different than the one for my queries.
This is now accepted by the typings:
```tsx
<InstantSearch
searchClient={searchClient}
indexName={indexName}
insights={{
insightsInitParams: {
userToken,
},
}}
>
{/* ... */}
</InstantSearch>
```
The `InitParams` type isn't exported by Search Insights, so I inferred the init params from the `InsightsMethodMap` type.

fix(insights): use init method params type from Search Insights

---

jest.config.js
scripts/babel/__tests__/extension-resolver.test.js
scripts/babel/extension-resolver.js
tests/babel-testfixture/nested/index/index.js
tests/babel-testfixture/package.json

**Summary**
mapping all files (widgets, connectors, utils) allows us to run `jest --watch` without ever needing to build to see updates
FX-2617
**Result**
you can run `yarn jest --watch` without needing to build InstantSearch.js, even for Vue InstantSearch or React InstantSearch Hooks
Fix the babel extension resolver plugin to not assume that the package name is verbatim in the path
> Note: this PR should be rebased, not squashed, as the two commits work separately

chore(jest): use local InstantSearch.js

---

packages/react-instantsearch-nextjs/README.md
packages/react-instantsearch-nextjs/src/InstantSearchNext.tsx

**Summary**
`router.push` scrolls to the top by default, so I made this PR to disable that as we don't do this is in other flavors.
We could make it into an option but I think it's best to leave it like that, it probably makes more sense to scroll to the top depending on the widget, for example Pagination, whereas it wouldn't make sense with InfiniteHits.
Also included a small fix to the README file

fix(InstantSearchNext): do not scroll on push

---

.github/workflows/release-templates.yml

**Summary**
We recently updated the recommended node version we use in our monorepo and CI, but this change has not been repercuted to our CISA templates GitHub action. This PR changes how node version is determined, by referencing the **.nvmrc** file we use to store the version we rely on.

ci(github-actions): sync npm version from .nvmrc

---

packages/react-instantsearch-core/src/hooks/__tests__/useInstantSearch.test.tsx
packages/react-instantsearch-core/src/hooks/useInstantSearch.ts
packages/react-instantsearch-core/src/lib/__tests__/useSearchState.test.tsx
packages/react-instantsearch-core/src/lib/useSearchState.ts

**Summary**
The renderState is useful for interacting with a different widget that you know / assume is also mounted. This is good for example for refining within a hit component without adding a second refinement widget (which could have side effects if hits is conditional, despite that impact being made smaller through #5123).
Can also be useful for a reusable widget that allows the user to pass their own options to e.g. refinementList, but still expects it to be mounted by the user.
An example use case:
```js
function Hits(props) {
const { renderState } = useInstantSearch();
const { hits } = useHits();
return (
<ol>
{hits.map((hit) => (
<li key={hit.objectID}>
<button
type="button"
onClick={() => {
indexRenderState.refinementList.keyword.refine(hit.keyword);
}}
>
{hit.keyword} …
```

feat(useInstantSearch): expose renderState

---

packages/instantsearch.js/src/lib/InstantSearch.ts
packages/vue-instantsearch/src/components/InstantSearch.js

This will prepare for the addition of insights in response to a dashboard setting.
FX-2641

feat(instantsearch): make `insights` undefined by default

---

bundlesize.config.json
packages/algoliasearch-helper/index.d.ts
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/instantsearch.js/test/createInstantSearch.ts

**Summary**
When `insights` is undefined, the Insights middleware can be initialized in answer to a server setting, received with the initial results.
FX-2643

feat(instantsearch): allow the insights middleware to be added in answer to a server setting

---

README.md
packages/instantsearch.js/README.md
packages/react-instantsearch-core/README.md
packages/react-instantsearch/README.md

**Summary**
Banner in packages/instantsearch.js README is broken: https://github.com/algolia/instantsearch/tree/master/packages/instantsearch.js.
This PR updates the URL to correctly display it again: https://github.com/algolia/instantsearch/tree/chore/update-banner-image-url/packages/instantsearch.js.

chore: update banner image url

---

packages/react-instantsearch/src/ui/CurrentRefinements.tsx
packages/react-instantsearch/src/ui/__tests__/CurrentRefinements.test.tsx
packages/react-instantsearch/src/widgets/CurrentRefinements.tsx
tests/common/widgets/current-refinements/options.ts

**Summary**
I noticed by working on a CR that our React InstantSearch implementation of CurrentRefinements differs from the other flavours. Specifically, we call the `refine()` method returned by the connector when we clear a refinement value, instead of using the `refine()` method available in each item.
One use-case for this is to modify the `refine()` method through `transformItems`, allowing for example to clear all numerical refinements of an attribute at once (ie: removing the min and max of a price range).
> **Note**  
> In React InstantSearch v6 both ranges would be cleared in a numerical refinement, but in React InstantSearch v7, because we rely on the JS implementation, ranges are cleared individually. This would allow customers to easily implement the legacy behaviour if they …

fix(current-refinements): clear with the `refine` function in each item

---

examples/js/calendar-widget/package.json
examples/js/e-commerce-umd/package.json
examples/js/e-commerce/package.json
examples/js/getting-started/package.json
examples/js/media/package.json
examples/js/tourism/package.json
examples/react/default-theme/package.json
examples/react/e-commerce/package.json
examples/react/getting-started/package.json
packages/instantsearch-codemods/package.json
yarn.lock

**Summary**
This prevents cache mismatches, as well as avoids the error with `__DEV__` not found or "bundle not found", as it got confused when two parcel versions are present in node_modules.
**Result**
less node_modules, parcel works as expected in examples

chore(dependencies): use consistent parcel version

---

packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
tests/common/shared/index.ts
tests/common/shared/insights.ts

**Summary**
insights started from the search response is detectable in the events
**Result**
`instantsearch-automatic` (name obviously up for debate) is also added to `algoliaSource` for events sent through backend-enabled insights.

fix(insights): declare automatic source

---

packages/create-instantsearch-app/README.md

**Summary**
This PR updates CISA readme with a message informing users about the effects of enabling events during template creation.
FX-2658
[**Preview →**](https://github.com/algolia/instantsearch/blob/60f1ac29ae616d80db875445a8374e6d1ddf1b1a/packages/create-instantsearch-app/README.md#get-started)

chore(cisa): add note about insights option in templates

---

packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-test.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts
packages/react-instantsearch-core/src/components/__tests__/InstantSearchSSRProvider.test.tsx
packages/react-instantsearch-core/src/server/__tests__/getServerState.test.tsx
tsconfig.v3.json

**Summary**
I started making e2e tests with [wdio-intercept-service](https://webdriver.io/docs/wdio-intercept-service/) but due to limitations with selenium, there's no way to intercept requests made when the page loads reliably, only requests resulting from user actions can be tested :/
We would have to use Cypress or Puppeteer to test it then.
So this just tests the implementation itself, which is still better than nothing 😅
Also changed `Object.values` to `Object.keys` for it to build properly.
[FX-2647]: https://algolia.atlassian.net/browse/FX-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: `hydrateSearchClient` to make sure it caches results

---

tests/utils/matchers/toMatchNormalizedInlineSnapshot.ts

This updates the `toMatchNormalizedInlineSnapshot` matcher so we can normalize the root element itself as well, not just its children. This is useful when the root have inconsistencies across flavors.

chore(toMatchNormalizedInlineSnapshot): normalize whole element

---

bundlesize.config.json
packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-test.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts

**Summary**
There are discrepancies between how different versions of the search engine serialize query parameters.
This makes it so this caching solution does not work with all engines.
**Result**
We can normalize the params returned from the request so that it matches the same format as the one used by the search client.

fix(cache-hydration): normalize params returned from response

---

packages/instantsearch.js/src/connectors/dynamic-widgets/__tests__/connectDynamicWidgets-test.ts
packages/instantsearch.js/src/connectors/dynamic-widgets/connectDynamicWidgets.ts

**Summary**
This can be useful for when you want to ensure certain facets are already requested, or know the exact list of facets to request (maximally, in the right order), to still have the advantages of request deduplication without using `*`.
Idea came up as a simplification when writing https://github.com/algolia/doc/pull/8659
**Result**
dynamicWidgets accepts all arrays for `facets`, and sets those values by default.

feat(dynamicWidgets): accept strings for `facets`

---

packages/instantsearch.js/src/connectors/breadcrumb/connectBreadcrumb.ts
packages/instantsearch.js/src/connectors/hierarchical-menu/connectHierarchicalMenu.ts
packages/instantsearch.js/src/connectors/menu/connectMenu.ts
packages/instantsearch.js/src/connectors/numeric-menu/connectNumericMenu.ts
packages/instantsearch.js/src/connectors/rating-menu/connectRatingMenu.ts
packages/instantsearch.js/src/connectors/refinement-list/connectRefinementList.ts
tests/common/common.ts
tests/common/connectors/breadcrumb/routing.ts
tests/common/connectors/current-refinements/routing.ts
tests/common/connectors/hierarchical-menu/routing.ts
tests/common/connectors/hits-per-page/routing.ts
tests/common/connectors/menu/routing.ts
tests/common/connectors/numeric-menu/routing.ts
tests/common/connectors/pagination/routing.ts
tests/common/connectors/rating-menu/routing.ts
tests/common/connectors/refinement-list/routing.ts
tests/common/connectors/toggle-refinement/routing.ts

**Summary**
Since #5912, we ensure to clean the UiState from empty values, however this was done in a slightly inefficient (looping over values) and unsafe (no checking for undefined) way, as the types implied that RouteState/UiState always is completely given (if you're using TypeScript that's actually the case, you'd get an error returning `undefined` for refinementList[attribute] for example).
**Result**
- Simplified the UiState cleaning
- ensure `undefined` doesn't cause issues
- add new test to each `connectors/*/routing` where relevant (pushed the tests separately to show they fail with current implementation: https://app.circleci.com/pipelines/github/algolia/instantsearch/9831/workflows/cba7210e-6955-4459-8c82-307d77319955/jobs/47848/tests)
fixes …

fix(routing): ensure UiState is cleaned up allowing "undefined" for values

---

bundlesize.config.json
packages/instantsearch.js/src/components/SearchBox/SearchBox.tsx
packages/react-instantsearch/src/ui/SearchBox.tsx
packages/react-instantsearch/src/widgets/RefinementList.tsx
packages/react-instantsearch/src/widgets/SearchBox.tsx
packages/vue-instantsearch/src/components/SearchInput.vue
tests/common/widgets/search-box/options.ts

**Summary**
Characters entered using an IME trigger search requests although the character composition is not done. This should only happen if the character has been fully composed.
This PR stops refining on `input` when composing with an IME and instead rely on the `compositionend` event in that case.
**Result**
Characters entered using an IME do not trigger search requests until relevant.
CR-5106

fix(searchbox): only refine if composition ended when using an IME

---

bundlesize.config.json
examples/js/e-commerce-umd/src/routing.ts
examples/js/e-commerce/src/routing.ts
examples/react/e-commerce/routing.ts
examples/react/next-routing/pages/index.tsx
examples/react/next/pages/index.tsx
examples/react/ssr/src/App.js
examples/vue/default-theme/src/App.vue
examples/vue/e-commerce/src/routing.js
examples/vue/media/src/App.vue
packages/instantsearch.js/src/lib/routers/__tests__/history.test.ts
packages/instantsearch.js/src/lib/routers/history.ts

**Summary**
Currently, the InstantSearch history router cleans up the URL from refinements it added during its lifecycle when it is disposed. This can be useful when InstantSearch is disposed but no route change has occurred, but the heuristics we use to detect whether we should write to the URL or not can sometimes conflict with third-party routers (ie: Next) when route changes occur.
This PR provides a option that users can use to turn off cleaning the URL on dispose. For example, with the Next.js Router:
```jsx
<InstantSearch
routing={{
router: createInstantSearchRouterNext({
singletonRouter,
serverUrl: url,
routerOptions: {
cleanUrlOnDispose: false,
},
}),
}}
>
// ...
</InstantSearch>
```
[CR-5095](https://algolia.atlassian.net/browse/CR-5095)
[CR-5095]: …

feat(history): provide option to not clean url on dispose

---

examples/react/next-routing/pages/index.tsx

Next.js 13 changes how `<Link>` are rendered by having themselves an `<a>` tag, making implementations where `<a>` is in the userland code invalid.
This PR updates the references to `<Link>` in our examples to make them satisfy the new behaviour.
See: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor

chore(examples): update links in next example

---

packages/create-instantsearch-app/src/templates/Angular InstantSearch/package.json

**Summary**
update angular, typescript versions to avoid typescript errors
This isn't the latest Angular versions (as it requires Ivy, which isn't done), but this runs fine both built and served.
E2E templates test doesn't need to be updated, as dependencies are stripped out.
CR-5137 for the report.
**Result**
angular template now runs fine on node 16 and 18

fix(angular): update versions to avoid typescript errors

---

packages/instantsearch.js/src/__tests__/common-widgets.test.tsx
packages/instantsearch.js/src/widgets/toggle-refinement/toggle-refinement.tsx
packages/vue-instantsearch/src/components/ToggleRefinement.vue
packages/vue-instantsearch/src/components/__tests__/ToggleRefinement.js
tests/common/widgets/toggle-refinement/options.ts

**Summary**
- uses the `label` prop, casted to a template for the JS test
- fixes the type for the template in JS
- ensure the count in Vue (outlier) is tested and normalised
- remove "required" from Vue label prop (as it isn't actually required anymore since #5919)
**Result**
ToggleRefinement label is tested

test(toggle): add explicit label test

---

packages/instantsearch.js/src/connectors/search-box/__tests__/connectSearchBox-test.ts
packages/instantsearch.js/src/connectors/search-box/connectSearchBox.ts

**Summary**
searchMetadata is deprecated, so we shouldn't read it anymore. Further here we should probably also deprecate `isSearchStalled` in the render method, but not sure how to `stalled` in React then
I do wonder if all widgets should have access to `instantSearchInstance` in the render function in React after all to be able to access these global information without also using `useInstantSearch`, but that's a different conversation
**Result**
`isSearchStalled` doesn't use `searchMetadata` anymore in search box connector

chore(connectSearchBox): don't use `searchMetadata`

---

packages/create-instantsearch-app/README.md
packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/e2e/templates.test.js
packages/create-instantsearch-app/src/cli/__tests__/postProcessAnswers.js
packages/create-instantsearch-app/src/cli/getPotentialImageAttributes.js
packages/create-instantsearch-app/src/cli/index.js
packages/create-instantsearch-app/src/cli/postProcessAnswers.js
packages/create-instantsearch-app/src/templates/InstantSearch.js/src/app.js.hbs
packages/create-instantsearch-app/src/templates/JavaScript Client/src/app.js.hbs
packages/create-instantsearch-app/src/templates/JavaScript Helper/src/app.js.hbs
packages/create-instantsearch-app/src/templates/React InstantSearch/src/App.tsx.hbs
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/src/App.vue
packages/create-instantsearch-app/src/templates/Vue InstantSearch/src/App.vue

**Summary**
**Result**
- New `imageAttribute` option, takes a single string
- From the CLI it can either be a root key, or something like `images.default` or `images[0]`
- For the sake of simplicity, in interactive mode we only let them choose from root attributes with values that are strings without whitespace. Attribute keys containing `image` or `img` will be on top of the list.
- We remove `imageAttribute` from `attributesToDisplay` if it was specified in CLI, although it wouldn't make sense as `attributesToDisplay` should be in `_highlightResults`
- Templates have been updated to add a simple `img` tag with corresponding `src`, and `alt` is `attributesToDisplay[0]` as it's also mapped to a `h1` tag.
- Fixed a bug in the React InstantSearch template which was setting a `fallback` prop …

feat(cisa): can now display images by picking an attribute

---

packages/instantsearch.js/src/__tests__/common-widgets.test.tsx
packages/instantsearch.js/src/components/RefinementList/RefinementList.tsx
packages/react-instantsearch/src/__tests__/common-widgets.test.tsx
packages/vue-instantsearch/src/__tests__/common-widgets.test.js
tests/common/widgets/index.ts
tests/common/widgets/rating-menu/behaviour.ts
tests/common/widgets/rating-menu/index.ts

Handle the clicks in the RefinementList component (used by RatingMenu) when the clicked element isn't a `HTMLElement`.
The fixed behaviour is fairly finicky to reproduce, you need to click exactly on the "star image", if you click between them or on the text, no issue existed before this PR either.
The removed check was introduced in https://github.com/algolia/instantsearch/pull/4702, when translating the component to TypeScript.
This implements a barebones CTS for RatingMenu, including being fully skipped for React InstantSearch, as the widget doesn't exist.

fix(RatingMenu/RefinementList): handle clicks in svg

---

bundlesize.config.json
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
tests/common/shared/insights.ts

This supports the new `authenticatedUserToken` from Search Insights.
When provided, it takes precedence over the `userToken`. When not, or when unset, the `userToken` is used.
> [!NOTE]  
> The code and tests are getting a bit more complicated than they could, but I didn't want to make a refactor in this PR to avoid complexifying the diffs. I'll do it in a separate one.
https://algolia.atlassian.net/browse/FX-2707

feat(createInsightsMiddleware): support `authenticatedUserToken`

---

bundlesize.config.json
packages/instantsearch.js/src/lib/__tests__/server.test.ts
packages/instantsearch.js/src/lib/server.ts
packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-test.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts
packages/instantsearch.js/src/types/results.ts
packages/react-instantsearch-core/src/server/__tests__/__snapshots__/getServerState.test.tsx.snap
packages/react-instantsearch-core/src/server/__tests__/getServerState.test.tsx
packages/react-instantsearch-core/src/server/getServerState.tsx
packages/react-instantsearch-nextjs/src/InitializePromise.tsx
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js
packages/vue-instantsearch/src/util/createServerRootMixin.js

**Summary**
In an SSR context, the search request performed server-side is cached in the client-side search client to prevent sending an unnecessary duplicate request when the user interacts with refinements.
This is done by manually recomposing the cached results during hydration and adding it to the search client's cache mechanism. The key of a cached request uses the search parameters from the response, normally returned by Algolia, but customers can limit what fields are returned by setting the `responseFIelds` option. If `params` is omitted, than the app throws an error during hydration.
This PR changes slightly how the request key is crafted, by instead extracting the request search parameters from the server-side search request, and using it instead of the response search …

fix(hydration): generate cache with search parameters from server-side request

---

packages/algoliasearch-helper/src/requestBuilder.js
packages/algoliasearch-helper/test/datasets/SearchParameters/search.dataset.js

**Summary**
introduced in https://github.com/algolia/instantsearch/pull/5764, but wasn't an issue until merge/setQueryParameters doesn't make a new copy constantly of the parameters.
Essentially what's going on:
- when you build the requests, it's sorting the facet values
- this then gets updated in the parameters as well as it's the same object
- with this fix, the sorting is done non-mutating (similar to .toSorted) to avoid the sorting of the parameters for cache to have a potential impact on the UI
**Result**
tests that fail in #6006 are now passing. This commit can be reviewed separately, but really needs to be merged before.

fix(requestBuilder): sort facet refinements in a non-mutating manner

---

packages/algoliasearch-helper/src/SearchParameters/index.js
packages/algoliasearch-helper/src/requestBuilder.js
packages/algoliasearch-helper/test/datasets/SearchParameters/search.dataset.js

**Summary**
inside setQueryParameters (used in many cases), we have _parseNumbers, which is always used with the arguments of setQueryParameters or new SearchParameters. This therefore means we don't need to make a safe copy of the parameters, everything should be fine using the arguments instead.
**Result**
Note, this PR requires #6007 to be merged _before_ it. The failing test is related to that change.
better perf:
before|after
---|---

fix(perf): improve speed of setQueryParameters

---

packages/vue-instantsearch/src/util/vue-compat/index-vue3.js

**Summary**
Fixes https://github.com/algolia/instantsearch/issues/6015
There is a compatibility issue when using the Vue3 version of the Algolia InstantSearch library alongside the [@vue/compat](https://www.npmjs.com/package/@vue/compat) module during a migration from Vue 2 to 3. When attempting to run the application with the InstantSearch library in a Vue 3 environment that utilises the [@vue/compat](https://www.npmjs.com/package/@vue/compat) module for backward compatibility, the application fails to initialise properly.
```
[Vue warn]: Unhandled error during execution of render function 
at <AisInstantSearch search-client=index-name="instant_search" > 
```
**Live reproduction**
[https://codesandbox.io/p/devbox/black-glade-jrhmvc](https://codesandbox.io/p/devbox/black-glade-jrhmvc?layou …

fix(vue-compat): Ensure getDefaultSlots works with @vue/compat & Vue 3

---

.circleci/config.yml
.codesandbox/ci.json
jest.config.js
packages/instantsearch-ui-components/README.md
packages/instantsearch-ui-components/package.json
packages/instantsearch-ui-components/scripts/version.cjs
packages/instantsearch-ui-components/src/version.ts
packages/instantsearch-ui-components/tsconfig.declaration.json
tests/versions/index.js

This initializes the `instantsearch-ui-components` package with the bare minimum.
https://algolia.atlassian.net/browse/FX-2744
- I only export the ES module since this is designed for our usage only, at least for now.
- Not sure what version we want to start with, so I started with `0.1.0` ([why?](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)). Again, it's an internal package so we should be okay with breaking things as we need to, while sending the signal for anyone still willing to use it in their app that it's not stable.

feat(instantsearch-ui-components): initialize the package

---

packages/instantsearch-ui-components/src/components/Highlight.tsx
packages/instantsearch-ui-components/src/components/__tests__/Highlight.test.tsx
packages/instantsearch-ui-components/src/components/index.ts
packages/instantsearch-ui-components/src/index.ts
packages/instantsearch-ui-components/src/lib/cx.ts
packages/instantsearch-ui-components/src/lib/index.ts
packages/instantsearch-ui-components/src/types/Renderer.ts
packages/instantsearch-ui-components/src/types/index.ts

This moves the `Highlight` component from `@algolia/ui-components` to the monorepo.
https://algolia.atlassian.net/browse/FX-2745

feat(instantsearch-ui-components): introduce `Highlight` component

---

packages/create-instantsearch-app/src/cli/__tests__/postProcessAnswers.js
packages/create-instantsearch-app/src/cli/postProcessAnswers.js

**Summary**
This makes it consistent with `attributesForFaceting`. See  #6023 for more info, although it doesn't change that use case.
**Result**
`attributesToDisplay` must be an array in config.

fix(config): don't accept non-arrays for attributesToDisplay

---

packages/instantsearch.js/src/connectors/autocomplete/connectAutocomplete.ts
packages/instantsearch.js/src/connectors/geo-search/connectGeoSearch.ts
packages/instantsearch.js/src/connectors/hits/connectHits.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts
packages/instantsearch.js/src/lib/insights/__tests__/insights-listener-test.tsx
packages/instantsearch.js/src/lib/utils/__tests__/createSendEventForHits-test.ts
packages/instantsearch.js/src/lib/utils/createSendEventForHits.ts

**Summary**
When enabling insights, the event payloads include the index name from which the data comes from. Currently, this index name is provided as a string and can be incorrect when the index changes, due to a `sortBy()` for example.
This PR implements changes to always retrieve the index name during the payload creation so it always matches the current state of InstantSearch.
**Result**
Events sent always include the correct index name.
CR-5442

fix(insights): use up-to-date index name when sending events

---

babel.config.js
packages/instantsearch-ui-components/package.json
packages/instantsearch.js/scripts/rollup/rollup.config.js

This modifies the build for `instantsearch-ui-components`:
- Includes runtime helpers as in the original `@algolia/ui-components`. This notably avoids issues with inlined helpers that currently cause our polyfill checker to fail.
- Includes a CJS bundle, which is necessary for the CJS bundles of each flavor.

feat(instantsearch-ui-components): update build

---

babel.config.js

This updates the build so that the `@jsx` comment is properly stripped.

fix(instantsearch-ui-components): fix Pragma

---

packages/instantsearch-ui-components/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-nextjs/package.json
packages/react-instantsearch-router-nextjs/package.json
packages/react-instantsearch/package.json

**Summary**
This is what currently causes the `createElement is not defined` error. Basically the example builds "from source", but something in the build (minification) renames `createElement` to `e` and thus everything breaks.
In this PR I remove the `source` key to ensure no building is happening from source, everything (mainly our examples) will use the built code.
This has no (except possibly positive) impact for customers, as in all these packages `src` is not published (only dist is in `files`), so the source refers to a non-existing file.
**Result**
- examples are runnable again.
- "dead" source key is removed from package.jsons

fix(packaging): remove non-exposed "source" key

---

packages/instantsearch.js/src/connectors/autocomplete/connectAutocomplete.ts

**Summary**
scopedResults / indices has access to `indexId`, so this should be reflected in the type.
**Result**
fixes #6049

fix(autocomplete): add indexId to type

---

examples/react/next-app-router/package.json

**Summary**
Remove `react-instantsearch-router-nextjs` from **package.json** to avoid confusion for users and developers, as it's not utilized in this context.
**Result**
This package usage in the example won't cause confusion for users and developers.

fix(examples): remove unused package

---

.circleci/config.yml
tests/e2e/CONTRIBUTING.md
tests/e2e/flavors.js
tests/e2e/helpers/setSearchBoxValue.ts
tests/e2e/wdio.saucelabs.conf.js

**Summary**
This PR separates the e2e jobs into 3, so each browser target can be retried separately when there are flaky tests.
It also provides more information on how to run e2e tests locally using Sauce labs in the contributing guidelines.
<a href="https://app.circleci.com/pipelines/github/algolia/instantsearch/10250/workflows/bfd91628-69c4-49be-8fe0-03d9601855d7"><img width="1018" alt="CleanShot 2024-02-19 at 16 07 12@2x" src="https://github.com/algolia/instantsearch/assets/154633/3500713a-4f3a-4cdd-ae46-c5a8128d950a"></a>

ci: split e2e tests jobs by browser

---

tests/e2e/wdio.saucelabs.conf.js

**Summary**
No errors/retries when asking Sauce Labs to run the IE 11 tests on Windows 10 (instead of Windows 7 previously).
**Result**
https://app.saucelabs.com/tests/a147f92a64244e9ebcdff490974a4d23

ci(e2e): improve reliability on IE by running on Windows 10

---

babel.config.js
examples/js/calendar-widget/env.js
examples/js/calendar-widget/index.html
examples/js/e-commerce-umd/index.html
examples/js/e-commerce-umd/src/env.js
examples/js/e-commerce/index.html
examples/js/e-commerce/src/env.js
examples/js/getting-started/index.html
examples/js/getting-started/src/env.js
examples/js/media/index.html
examples/js/media/src/env.ts
examples/js/recommend/index.html
examples/js/recommend/src/env.js
examples/js/tourism/env.js
examples/js/tourism/index.html
examples/react/default-theme/index.html
examples/react/default-theme/src/env.js
examples/react/e-commerce/env.js
examples/react/e-commerce/index.html
examples/react/getting-started/index.html
examples/react/getting-started/src/env.js
examples/react/recommend/index.html
examples/react/recommend/src/env.js

**Summary**
This PR makes the **env.js** files in our examples unnecessary by replacing the `__DEV__` references in the InstantSearch codebase with a Babel plugin.
The main goal is to have the non Next.js React examples working again with Parcel.
I have manually tested all affected examples successfully, and the e-commerce examples still pass e2e tests.
There's still an issue with Parcel's HMR and React examples, where the Websocket receives the update command and the console is cleared, but a manual refresh is needed to see changes. If someone has an idea 🙇 .

chore(examples): remove env files

---

examples/react/default-theme/package.json
examples/react/e-commerce/package.json
examples/react/getting-started/package.json
examples/react/recommend/package.json

**Summary**
This PR adds the `@types/react` dev dependency on relevant React InstantSearch examples so Codesandbox properly interprets JSX markup in the editor.

chore(examples): add react types dev dependencies

---

packages/instantsearch-ui-components/package.json

**Summary**
The **instantsearch-ui-components** package is currently transformed during build to rely on babel runtime helpers.
This causes an issue when using **instantsearch.js** or **vue-instantsearch** with a build system, as we don't explicitly require **@babel/runtime** as a dependency.
This PR lists the dependency correctly.
Fixes #6060

fix: require @babel/runtime dependency

---

CONTRIBUTING.md
package.json
packages/instantsearch-ui-components/package.json
packages/instantsearch.js/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-nextjs/package.json
packages/react-instantsearch-router-nextjs/package.json
packages/react-instantsearch/package.json
packages/vue-instantsearch/package.json
packages/vue-instantsearch/rollup.config.js

**Summary**
This PR adds a `watch` script on almose all relevant packages in the monorepo and allows them to be run in parallel using lerna. It also updates the CONTRIBUTING.md guidelines with a description of the process.
> [!NOTE]
> **algoliasearch-helper** is omitted from this PR as it would a more significant refactoring of its build script to make it work properly in watch mode

chore: generalize watch mode in packages and document process in contributing guidelines

---

packages/react-instantsearch/src/ui/RefinementList.tsx
packages/react-instantsearch/src/ui/__tests__/RefinementList.test.tsx
packages/react-instantsearch/src/widgets/__tests__/RefinementList.test.tsx

When the `<RefinementList>` is searchable and a user searches for a facet value that doesn't exist, the root should have the class `.ais-RefinementList--noRefinement`. This was however not the case because we were relying on `canRefine` which remains `true` as long as the last search contains search results.
Now we're relying on the items returned from SFFV.
In the future, we may want to reconsider what `canRefine` means in the context of `connectRefinementList`, as the source of refinements comes from two places (main search _and_ SFFV), but this would be breaking right now so we can keep it for later.

fix(react-instantsearch): properly add `noRefinementRoot` class on `<RefinementList>`

---

packages/vue-instantsearch/src/components/RefinementList.vue
packages/vue-instantsearch/src/components/__tests__/__snapshots__/RefinementList.js.snap

Vue InstantSearch renders an empty `<ul>` when `<refinement-list>` has no items.
This fixes it by not rendering the list at all unless there are items.

fix(vue-instantsearch): only render list in `<refinement-list>` when it has items

---

packages/vue-instantsearch/src/components/RefinementList.vue
packages/vue-instantsearch/src/components/__tests__/__snapshots__/RefinementList.js.snap

In all flavors but Vue InstantSearch, we render a loading indicator when the refinement list is searchable. Note that it actually never renders anything on screen as we don't have information about SFFV being stalled, but the markup updates.
This change intends to harmonize markup across flavors for common testing purposes.
In a later iteration, we could work on actually displaying the loading indicator when SFFV is stalled.
This change doesn't update tests, because this will be done in https://github.com/algolia/instantsearch/pull/6090.

feat(vue-instantsearch): render loading indicator in `<ais-refinement-list>`

---

packages/instantsearch.js/src/connectors/refinement-list/connectRefinementList.ts
packages/vue-instantsearch/src/components/RefinementList.vue

When the <ais-refinement-list> is searchable and a user searches for a facet value that doesn't exist, the root should have the class .ais-RefinementList--noRefinement. This was however not the case because we were relying on `canRefine` which remains `true` as long as the last search contains search results.
Now we're relying on the items returned from SFFV.
In the future, we may want to reconsider what `canRefine` means in the context of `connectRefinementList`, as the source of refinements comes from two places (main search and SFFV), but this would be breaking right now so we can keep it for later.
This change doesn't update tests, because existing ones weren't testing this use case. This will be touched on in #6090.

fix(vue-instantsearch): properly add `noRefinement` class on `<ais-refinement-list>`

---

packages/react-instantsearch-nextjs/src/InstantSearchNext.tsx

**Summary**
Fixes #6086
**Result**
Starting from Next 14, pressing the back button to go back to a different page does not cause a server-side render, so `InstantSearchNext` would read the `initialResults` again even if the route has changed.
The easiest way to fix this is to delete them from window when disposing (not after reading as this may cause issues in strict mode)

fix(next-app-router): using wrong initial results when mounting on client

---

packages/instantsearch.js/src/connectors/hits/connectHits.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
Adds a major comment
**Result**
The search parameters of the highlight tags should be set globally. This has multiple advantages:
- search parameters are more static by default
- hits is allowed to be dynamically used

chore(hits): add major comment on search parameters

---

bundlesize.config.json
packages/algoliasearch-helper/index.js
packages/instantsearch.js/src/lib/__tests__/RoutingManager-test.ts
packages/instantsearch.js/src/types/widget.ts
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/instantsearch.js/src/widgets/panel/panel.tsx
packages/instantsearch.js/test/createWidget.ts

**Summary**
**Result**
- Added calls to `getWidgetParameters` in both `init` and `addWidgets` to get recommend params.
- Filter `widgetsToRender` based on whether `shouldRender` is implemented or not and if it returns `true`
[FX-2766]: https://algolia.atlassian.net/browse/FX-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(instantsearch): prepare index widget for recommend widgets

---

jest.config.js
packages/react-instantsearch-nextjs/src/InitializePromise.tsx
packages/react-instantsearch-nextjs/src/__tests__/htmlEscape.test.ts
packages/react-instantsearch-nextjs/src/htmlEscape.ts
packages/react-instantsearch-nextjs/tsconfig.declaration.json

**Summary**
**Result**
This is what Next.js does in the pages router, `JSON.parse` will unescape.
[CR-5899]: https://algolia.atlassian.net/browse/CR-5899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(next-app-router): escape injected results for hydration

---

bundlesize.config.json
packages/instantsearch.css/src/themes/algolia.scss
packages/instantsearch.css/src/themes/reset.scss
packages/instantsearch.css/src/themes/satellite.scss
specs/src/pages/widgets/frequently-bought-together.md

**Summary**
This PR adds styles for the frequentlyBoughtTogether widget, using InstantSearch naming conventions. It also adds it to the styles specs/showcase.
**Previews**
<details>
<summary>reset.css</summary>
</details>
<details>
<summary>algolia.css</summary>
</details>
<details>
<summary>satellite.css</summary>
</details>

feat: set up base CSS styles for `frequentlyBoughtTogether` widget

---

.codesandbox/ci.json

**Summary**
This is a quick PR that updates the list of sandboxes that are generated by CodeSandbox CI in our pull requests. It now generates a sandbox for each flavor's getting-started example, in addition to some specific to React InstantSearch and Next.js.

ci: update generated sandboxes in pull requests

---

bundlesize.config.json
packages/algoliasearch-helper/index.d.ts
packages/instantsearch.js/src/connectors/hits/__tests__/connectHits-test.ts
packages/instantsearch.js/src/connectors/hits/connectHits.ts
tsconfig.v3.json

**Summary**
This is the first pull request to add support for no-code banners to the Hits widget ([RFC](https://algolia.atlassian.net/wiki/spaces/MERCH/pages/4948099490/RFC+-+Rule+Visual+Editor+Banner+Consequence)). It updates the `SearchResults` type to include `renderingContent.widgets.banners` and return a new `banner` property from `connectHits` connector.
[EMERCH-1369](https://algolia.atlassian.net/browse/EMERCH-1369)
**Result**
- No UI changes
- `connectHits-test.ts` has been updated and passes (using a `// @ts-ignore-error` in the test until the algoliasearch js client types are updated)
[EMERCH-1369]: https://algolia.atlassian.net/browse/EMERCH-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(hits): return banner from connectHits

---

bundlesize.config.json
packages/instantsearch-ui-components/src/components/Hits.tsx
packages/instantsearch-ui-components/src/components/__tests__/Hits.test.tsx
packages/instantsearch.js/src/components/Template/Template.tsx
packages/instantsearch.js/src/components/Template/__tests__/Template-test.tsx
packages/instantsearch.js/src/components/Template/__tests__/__snapshots__/Template-test.tsx.snap
packages/instantsearch.js/src/widgets/hits/hits.tsx
packages/vue-instantsearch/src/util/vue-compat/index-vue2.js
packages/vue-instantsearch/src/util/vue-compat/index-vue3.js

**Summary**
This is the second pull request to add support for no-code banners to the Hits widget ([RFC](https://algolia.atlassian.net/wiki/spaces/MERCH/pages/4948099490/RFC+-+Rule+Visual+Editor+Banner+Consequence)). It updates the `Hits` `instantsearch-ui-component` to conditionally render a banner (either the default layout or a custom layout if the `bannerComponent` is included) in the DOM with the appropriate class names.
[EMERCH-1420](https://algolia.atlassian.net/browse/EMERCH-1420)
**Result**
No UI changes
- Update Hits UI component to support conditionally rendering a banner above the hits `ol`
- Update and add new snapshot tests for `banner` and `bannerComponent` props
- Update `Template` component to support Hits widget `emptyComponent` (root changed to `fragment`)
- Update Vue …

feat(hits): add banner to hit ui component

---

bundlesize.config.json
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/react-instantsearch-core/src/lib/__tests__/useSearchResults.test.tsx
packages/react-instantsearch-core/src/lib/useSearchResults.ts

**Summary**
This PR fixes an issue which returns an empty `scopedResults` through `useInstantSearch()` when the main index has no index name set.
**Result**
Scoped results are now properly returned even when the main index has no name set.
Fixes #6132

fix: provide scopedResults when main index has no index name set

---

bundlesize.config.json
packages/instantsearch-ui-components/src/components/TrendingItems.tsx
packages/instantsearch-ui-components/src/components/__tests__/TrendingItems.test.tsx
packages/instantsearch-ui-components/src/components/index.ts
packages/instantsearch.css/src/themes/algolia.scss
packages/instantsearch.css/src/themes/reset.scss
packages/instantsearch.css/src/themes/satellite.scss
specs/src/pages/widgets/trending-items.md

This moves the `TrendingItems` UI component from **@algolia/recommend** to the monorepo. It also adds the base styles in instantsearch.css and describes its expected markup in our specs.
FX-2831

feat(ui-components): introduce `TrendingItems` component

---

packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts

**Summary**
If init isn't called (this happens in React InstantSearch Next, as well as some other cases), then dispose on the actual widgets doesn't make sense to be called, because the `helper` is still null.
This does mean that some state could be considered stray (not cleaned up), but that likely doesn't matter as the index widget is removed anyway.
**Result**
fixes #6073

fix(index): allow dispose to be called before init

---

packages/react-instantsearch/src/widgets/Hits.tsx
packages/react-instantsearch/src/widgets/__tests__/Hits.test.tsx

**Summary**
This is the fourth pull request to add support for no-code banners to the Hits widget ([RFC](https://algolia.atlassian.net/wiki/spaces/MERCH/pages/4948099490/RFC+-+Rule+Visual+Editor+Banner+Consequence)). Building on the recent changes to the `Hits` `instantsearch-ui-component` it updates the `Hits` React InstantSearch widget to support a new `bannerComponent`.
[EMERCH-1421](https://algolia.atlassian.net/browse/EMERCH-1421)
There will be a follow-on PR to update React InstantSearch.
**Result**
The hits widget tests have been updated to ensure that the new optional banner component is supported. No styling was applied in the examples or to `instantsearch.css` - that will most likely come in a follow-up PR.
Additionally, the code was tested in the `getting-started` example …

feat(hits): add banner to react instantsearch hits

---

packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/test/spec/recommend.js
packages/instantsearch.js/src/connectors/frequently-bought-together/__tests__/connectFrequentlyBoughtTogether-test.ts
packages/instantsearch.js/src/connectors/frequently-bought-together/connectFrequentlyBoughtTogether.ts
packages/instantsearch.js/src/connectors/related-products/connectRelatedProducts.ts
tests/common/connectors/frequently-bought-together/options.ts
tests/common/connectors/related-products/options.ts

**Summary**
**Result**
Following the previous PR, this enables the connectors to pass multiple object IDs
[FX-2822]: https://algolia.atlassian.net/browse/FX-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(recommend): enable multiple objectIDs in connectors

---

bundlesize.config.json
packages/react-instantsearch/src/__tests__/common-widgets.test.tsx
packages/react-instantsearch/src/widgets/RelatedProducts.tsx
packages/react-instantsearch/src/widgets/TrendingItems.tsx
packages/react-instantsearch/src/widgets/__tests__/TrendingItems.test.tsx
packages/react-instantsearch/src/widgets/__tests__/__utils__/all-widgets.tsx
packages/react-instantsearch/src/widgets/__tests__/all-widgets.test.tsx
packages/react-instantsearch/src/widgets/index.ts

**Summary**
Introduces the TrendingItems React widget and its related tests. Note that the tests have the same complexity on the type as is the case in vanilla; as the facet props can only be used if they're both set, but manipulating the props as a whole loses that relation.
**Result**
FX-2853

feat(recommend): introduce TrendingItems

---

bundlesize.config.json
packages/algoliasearch-helper/src/RecommendParameters/index.js
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/test/spec/RecommendParameters/methods.js
packages/algoliasearch-helper/test/spec/recommend.js

**Summary**
**Result**
This is to make sure we don't needlessly request again when a new widget has been added.
[FX-2851]: https://algolia.atlassian.net/browse/FX-2851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(recommend): cache results per $$id

---

packages/instantsearch.js/src/types/widget.ts

**Summary**
Adding our new built-in recommend widgets to these exported types.

chore: reference recommend widgets in exported types

---

bundlesize.config.json
packages/instantsearch-ui-components/src/components/FrequentlyBoughtTogether.tsx
packages/instantsearch-ui-components/src/components/LookingSimilar.tsx
packages/instantsearch-ui-components/src/components/RelatedProducts.tsx
packages/instantsearch-ui-components/src/components/TrendingItems.tsx
packages/instantsearch-ui-components/src/components/__tests__/FrequentlyBoughtTogether.test.tsx
packages/instantsearch-ui-components/src/components/__tests__/LookingSimilar.test.tsx
packages/instantsearch-ui-components/src/components/__tests__/RelatedProducts.test.tsx
packages/instantsearch-ui-components/src/components/__tests__/TrendingItems.test.tsx
packages/instantsearch-ui-components/src/components/recommend-shared/DefaultEmpty.tsx
packages/instantsearch-ui-components/src/components/recommend-shared/index.ts
packages/instantsearch-ui-components/src/types/Recommend.ts
packages/instantsearch.js/src/widgets/frequently-bought-together/frequently-bought-together.tsx
packages/instantsearch.js/src/widgets/looking-similar/looking-similar.tsx
packages/instantsearch.js/src/widgets/related-products/related-products.tsx
packages/instantsearch.js/src/widgets/trending-items/trending-items.tsx
packages/react-instantsearch/src/widgets/FrequentlyBoughtTogether.tsx
packages/react-instantsearch/src/widgets/LookingSimilar.tsx
packages/react-instantsearch/src/widgets/RelatedProducts.tsx
packages/react-instantsearch/src/widgets/TrendingItems.tsx

This renames `fallbackComponent` into `emptyComponent` in Recommend widgets.
https://algolia.atlassian.net/browse/FX-2856

feat(recommend): rename `fallbackComponent` into `emptyComponent`

---

bundlesize.config.json
packages/react-instantsearch-core/src/components/Configure.tsx
packages/react-instantsearch-core/src/components/__tests__/Configure.test.tsx

**Summary**
Because React props are not writable, behaviour inside _parseNumbers > merge in the helper requires the configure props to be writable.
fixes #6136
See https://github.com/algolia/instantsearch/pull/6011 for the ultimate cause of this issue; _parseNumbers mutates the arguments as it's much more performant than making a copy on every interaction (this is a very hot function).
**Result**
This bug is reproducible by simply rendering `<Configure aroundRadius="all" />` or any other numeric (https://github.com/algolia/instantsearch/blob/d1aa720c8e4e1aad2d7b64e385a29b258240c7df/packages/algoliasearch-helper/src/SearchParameters/index.js#L239-L251) key as a non-number string. After this PR, the bug no longer happens.
Note that of course this has a performance penalty (or regression) …

fix(Configure): prevent aroundRadius="all" throwing

---

packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/instantsearch.js/src/connectors/frequently-bought-together/connectFrequentlyBoughtTogether.ts
packages/instantsearch.js/src/connectors/looking-similar/connectLookingSimilar.ts
packages/instantsearch.js/src/connectors/pagination/__tests__/connectPagination-test.ts
packages/instantsearch.js/src/connectors/related-products/connectRelatedProducts.ts
packages/instantsearch.js/src/connectors/trending-items/connectTrendingItems.ts
packages/instantsearch.js/src/types/widget.ts
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/instantsearch.js/test/createWidget.ts

**Summary**
This PR removes recommend parameters from the recommend state when their relevant widgets are disposed.
FX-2854

fix(recommend): clean recommend state when removing widgets

---

packages/instantsearch.js/src/__tests__/common-connectors.test.tsx
packages/instantsearch.js/src/connectors/frequently-bought-together/connectFrequentlyBoughtTogether.ts
packages/instantsearch.js/src/connectors/looking-similar/connectLookingSimilar.ts
packages/instantsearch.js/src/connectors/related-products/connectRelatedProducts.ts
packages/instantsearch.js/src/connectors/trending-items/connectTrendingItems.ts
packages/react-instantsearch/src/__tests__/common-connectors.test.tsx
packages/vue-instantsearch/src/__tests__/common-connectors.test.js
tests/common/connectors/frequently-bought-together/index.ts
tests/common/connectors/frequently-bought-together/state.ts
tests/common/connectors/looking-similar/index.ts
tests/common/connectors/looking-similar/state.ts
tests/common/connectors/related-products/index.ts
tests/common/connectors/related-products/state.ts
tests/common/connectors/trending-items/index.ts
tests/common/connectors/trending-items/state.ts

**Summary**
This PR cleans up hypothethical stale queries from recommend widgets in unmount/remount scenarios.
FX-2890

fix(recommend): ensure unicity of recommend queries

---

packages/instantsearch.js/src/connectors/frequently-bought-together/__tests__/connectFrequentlyBoughtTogether-test.ts
packages/instantsearch.js/src/connectors/frequently-bought-together/connectFrequentlyBoughtTogether.ts
packages/instantsearch.js/src/connectors/looking-similar/connectLookingSimilar.ts
packages/instantsearch.js/src/connectors/related-products/connectRelatedProducts.ts
packages/instantsearch.js/src/connectors/trending-items/connectTrendingItems.ts
packages/instantsearch.js/src/widgets/frequently-bought-together/__tests__/frequently-bought-together.test.tsx
packages/instantsearch.js/src/widgets/frequently-bought-together/frequently-bought-together.tsx
packages/instantsearch.js/src/widgets/looking-similar/__tests__/looking-similar.test.tsx
packages/instantsearch.js/src/widgets/looking-similar/looking-similar.tsx
packages/instantsearch.js/src/widgets/related-products/__tests__/related-products.test.tsx
packages/instantsearch.js/src/widgets/related-products/related-products.tsx
packages/instantsearch.js/src/widgets/trending-items/__tests__/trending-items.test.tsx
packages/instantsearch.js/src/widgets/trending-items/trending-items.tsx
packages/react-instantsearch/src/widgets/FrequentlyBoughtTogether.tsx
packages/react-instantsearch/src/widgets/LookingSimilar.tsx
packages/react-instantsearch/src/widgets/RelatedProducts.tsx
packages/react-instantsearch/src/widgets/TrendingItems.tsx
tests/common/connectors/frequently-bought-together/options.ts
tests/common/connectors/looking-similar/options.ts
tests/common/connectors/related-products/options.ts
tests/common/connectors/trending-items/options.ts
tests/common/widgets/frequently-bought-together/options.ts
tests/common/widgets/looking-similar/options.ts
tests/common/widgets/related-products/options.ts
tests/common/widgets/trending-items/options.ts

**Summary**
rename `maxRecommendations` to `limit`
**Result**
Any user-facing interface is called `limit`, but the underlying parameter (also for the helper) is still called `maxRecommendations`
This is consistent with other widgets that don't have pagination like refinementList

fix(recommend): rename maxRecommendations to limit

---

packages/algoliasearch-helper/index.d.ts
packages/instantsearch-ui-components/src/components/Hits.tsx

**Summary**
This minor PR updates makes the `url` property of the new banner type (part of `SearchResults.renderingContent.widgets.banners`) required. `link` is still optional, but if `link` _is_ present then we want to ensure that the `url` is also present.
Part of [EMERCH-1370](https://algolia.atlassian.net/browse/EMERCH-1370)
**Result**
Green CI (all tests still pass)
[EMERCH-1370]: https://algolia.atlassian.net/browse/EMERCH-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(hits): update banner link type

---

bundlesize.config.json
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-integration-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/instantsearch.js/test/createInstantSearch.ts
packages/react-instantsearch-core/src/connectors/__tests__/useRelatedProducts.test.tsx
packages/react-instantsearch-core/src/connectors/__tests__/useTrendingItems.test.tsx
packages/react-instantsearch/src/widgets/__tests__/FrequentlyBoughtTogether.test.tsx
packages/react-instantsearch/src/widgets/__tests__/LookingSimilar.test.tsx
packages/react-instantsearch/src/widgets/__tests__/RelatedProducts.test.tsx
packages/react-instantsearch/src/widgets/__tests__/TrendingItems.test.tsx

**Summary**
In index and instantsearch, keep track of which type of widgets are used, and only send a request of the right type.
**Result**
If only recommend or search widgets are present, only that request is done.
This has slight further impact to ensure that a render still happens when only recommend returns results.
FX-2892

fix(queries): prevent network request

---

bundlesize.config.json
packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/index.js
packages/algoliasearch-helper/src/RecommendResults/index.js
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/server.test.ts
packages/instantsearch.js/src/lib/server.ts
packages/instantsearch.js/src/lib/utils/__tests__/hydrateRecommendCache-test.ts
packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-test.ts
packages/instantsearch.js/src/lib/utils/addWidgetId.ts
packages/instantsearch.js/src/lib/utils/hydrateRecommendCache.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts
packages/instantsearch.js/src/lib/utils/index.ts
packages/instantsearch.js/src/types/results.ts
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts
packages/react-instantsearch-core/src/components/InstantSearchSSRProvider.tsx
packages/react-instantsearch-core/src/hooks/__tests__/useConnector.test.tsx
packages/react-instantsearch-core/src/hooks/useConnector.ts
packages/react-instantsearch-core/src/lib/InstantSearchSSRContext.ts
packages/react-instantsearch-core/src/lib/getIndexSearchResults.ts
packages/react-instantsearch-core/src/lib/useSearchResults.ts
packages/react-instantsearch-core/src/server/__tests__/getServerState.test.tsx
packages/react-instantsearch-core/src/server/getServerState.tsx
packages/react-instantsearch-nextjs/src/InitializePromise.tsx
packages/react-instantsearch-nextjs/src/TriggerSearch.ts
packages/react-instantsearch-nextjs/src/__tests__/InitializePromise.test.tsx
tsconfig.v3.json

**Summary**
**Result**
- Made `_rawResults` scoped for `RecommendResults` to avoid bloating multi-index with same results
- Typed and renamed `recommendCache` to `_recommendCache` as it's private
- It will also be hydrated to avoid requests on the client
- `waitForResults` wait for either recommend or search, or both if needed
- Changes to `hydrateSearchClient` needed as search results are now optional
[FX-2895]: https://algolia.atlassian.net/browse/FX-2895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(recommend): enable server-side rendering

---

packages/instantsearch.css/src/themes/algolia.scss
packages/instantsearch.css/src/themes/satellite.scss

**Summary**
This PR updates the theme CSS for the new banner portion of the `Hits` widget. Both `satellite.scss` and `algolia.scss` were updated to include the following rulesets:
```css
.ais-Hits-banner {
display: flex;
justify-content: center;
}
.ais-Hits-banner-image {
max-width: 100%;
}
```
[EMERCH-1479](https://algolia.atlassian.net/browse/EMERCH-1479)
**Result**
When the banner is wider than the Hits container, `max-width: 100%` restricts the width.
When the banner is narrower than the Hits container, it is centered horizontally.
[EMERCH-1479]: https://algolia.atlassian.net/browse/EMERCH-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(hits): update css templates to style hits banner

---

packages/react-instantsearch-nextjs/src/InitializePromise.tsx
packages/react-instantsearch-nextjs/src/InstantSearchNext.tsx
packages/react-instantsearch-nextjs/src/__tests__/InitializePromise.test.tsx
yarn.lock

**Summary**
Customers who follow [Next.js' guide for implementing CSP rules](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) to their application can define a nonce that flags inline scripts as allowed. This is properly handled with Next.js' own inline scripts, but not yet with **react-instantsearch-nextjs**.
This PR retrieves the nonce value and applies it to the injected script tag added by `<InitializePromise>`.
**Result**
InstantSearch does not trigger an error in Next.js applications where a middleware define CSP rules and apply nonces.
CR-6159

fix(next-app-router): set nonce in injected script when provided

---

packages/react-instantsearch-nextjs/src/InstantSearchNext.tsx

**Summary**
This PR fixes a side-effect introduced in #6223 , which tries to retrieve a `nonce` value from headers to apply it to the injected script tag. It unconditionally called Next's `headers()` in SSR and CSR, which caused the implementation to throw an error at the first CSR search interaction, because `headers()` are obviously not retrievable from a client environment.
The `header()` function is now only called in SSR.

fix(next-app-router): do not retrieve headers in csr

---

packages/instantsearch-codemods/README.md
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/global.input.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/global.output.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/imported.input.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/imported.output.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/mixed.input.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/mixed.output.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/remove.input.js
packages/instantsearch-codemods/__testfixtures__/addWidget-to-addWidgets/remove.output.js
packages/instantsearch-codemods/__tests__/addWidget-to-addWidgets.test.js
packages/instantsearch-codemods/src/addWidget-to-addWidgets.ts
packages/instantsearch-codemods/src/codeshift.config.js
packages/instantsearch.js/scripts/transforms/README.md
packages/instantsearch.js/scripts/transforms/addWidget-to-addWidgets.js

Move the "addWidgets" codemod to the dedicated instantsearch-codemods package
This is done so we can update the documentation etc. to only use instantsearch-codemods and we can remove this folder in a next major version
Left an alias and the original tests in place

refactor(codemods): move addWidgets to instantsearch-codemods package

---

packages/algoliasearch-helper/index.d.ts
packages/instantsearch-ui-components/src/components/Hits.tsx
packages/instantsearch.js/src/connectors/hits/connectHits.ts
packages/instantsearch.js/src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
Following on from the recent addition of the rules controlled banner to `Hits`, we're adding the same to `InfiniteHits`. This first PR returns banner information with `connectInfiniteHits`.
https://algolia.atlassian.net/browse/EMERCH-1509
**Result**
Updated and passing test (no UI changes)

feat(infinite-hits): return banner info with connectInfiniteHits

---

packages/instantsearch.js/src/connectors/hits/__tests__/connectHits-test.ts

**Summary**
This PR updates `connectHits-test.ts` to expect banner info directly from `getWidgetRenderState()` rather than indirectly from `getRenderState()`.
Related to https://algolia.atlassian.net/browse/EMERCH-1509
**Result**
Green CI

test(hits): banners in getWidgetRenderState - not getRenderState

---

packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/src/SearchResults/index.js
packages/algoliasearch-helper/test/spec/SearchResults/getFacetValues-facetOrdering.js

**Summary**
Adds support for hiding facet values if set in the configuration.
JIRA ticket: https://algolia.atlassian.net/browse/EMERCH-1438
**Result**
If you have set up facets to be "hidden", they will not display. This does not increment the maxValuesPerFacet setting, so it's possible that you receive less values than the limit if you hide many values.

feat(facets): allow hiding values through renderingContent

---

packages/algoliasearch-helper/src/SearchResults/index.js
packages/algoliasearch-helper/src/requestBuilder.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/derive/empty-index.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/findAnswers.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/getQuery.js
packages/algoliasearch-helper/test/spec/requestBuilder.js
packages/instantsearch.js/src/connectors/configure-related-items/__tests__/connectConfigureRelatedItems-test.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-integration-test.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/lib/__tests__/server.test.ts
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/react-instantsearch-core/src/components/__tests__/InstantSearch.test.tsx
packages/react-instantsearch-core/src/server/__tests__/__snapshots__/getServerState.test.tsx.snap
packages/react-instantsearch-core/src/server/__tests__/getServerState.test.tsx
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js
tests/common/widgets/toggle-refinement/options.ts

**Summary**
In the first request, we are sending `facets: []` and `tagRefinements: ''` when there are no values for those queries, this isn't needed, and removed in this pull request.
This came from an assumption that we could skip queries that have no refinements, but that's not true if you're for example _only_ displaying hits
**Result**
Slightly more minimal request sent, consistent with the other parameters

fix(helper): don't send empty "tagRefinements" and "facets" parameters

---

packages/instantsearch.js/src/__tests__/common-widgets.test.tsx
packages/react-instantsearch/src/__tests__/common-widgets.test.tsx
packages/vue-instantsearch/src/__tests__/common-widgets.test.js
tests/common/widgets/dynamic-widgets/index.ts
tests/common/widgets/dynamic-widgets/options.ts
tests/common/widgets/index.ts

**Summary**
**Result**
Tried to test as much as possible, but we're limited due to the implems being very different, notably the lack of `fallback` mechanism in Vue.
Still these test the order to render widgets, whether a widget should render or not, and makes sure that certain params are correctly forwarded to the search request.
I didn't remove any pre-existing tests for now.
[FX-2510]: https://algolia.atlassian.net/browse/FX-2510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(dynamic-widgets): common test suite

---

packages/algoliasearch-helper/types/algoliasearch.d.ts

I can't manage to reproduce this locally, even if i update everything to 5.4.5, but in a fresh Next.js example (like  https://codesandbox.io/s/47fy7c) `hitsPerPage` isn't accepted to Configure (because PlainSearchParameters is any)
This is I believe linked to https://github.com/microsoft/TypeScript/pull/56004, maybe also to https://github.com/sindresorhus/type-fest/issues/846 (although the case seems different).
Essentially before this change the types like `ClientLiteV5` were evaluated to `any` instead of `unknown`, poisoning the entire type and turning everything into any.
The solution is to first check if `typeof AlgoliaSearchLite` is any, and if it is any we don't even evaluate the rest of teh type. Of course if it isn't any it works correctly for v5 still.
Again, unfortunately this …

fix(types): make algoliasearch detection compatible with TS 5.4.5

---

bundlesize.config.json
packages/algoliasearch-helper/src/RecommendParameters/index.js
packages/algoliasearch-helper/test/spec/RecommendParameters/methods.js
packages/algoliasearch-helper/test/spec/recommend.js
packages/instantsearch.js/src/lib/__tests__/InstantSearch-integration-test.ts

**Summary**
**Result**
The v5 of the API client does not do extra logic like it did before for ease of maintenance, so for now we have to do this on our end.
[FX-2926]: https://algolia.atlassian.net/browse/FX-2926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(algoliasearch): v5 does not default threshold to 0

---

packages/instantsearch.css/src/themes/algolia.scss
packages/instantsearch.css/src/themes/satellite.scss
packages/instantsearch.js/src/components/InfiniteHits/InfiniteHits.tsx
packages/instantsearch.js/src/components/InfiniteHits/__tests__/InfiniteHits-test.tsx
packages/instantsearch.js/src/components/InfiniteHits/__tests__/InfiniteHits.test.tsx
packages/instantsearch.js/src/widgets/infinite-hits/__tests__/infinite-hits.test.tsx
packages/instantsearch.js/src/widgets/infinite-hits/infinite-hits.tsx
packages/react-instantsearch/src/ui/InfiniteHits.tsx
packages/react-instantsearch/src/ui/__tests__/InfiniteHits.test.tsx
packages/react-instantsearch/src/widgets/InfiniteHits.tsx
packages/react-instantsearch/src/widgets/__tests__/InfiniteHits.test.tsx
packages/vue-instantsearch/src/__tests__/common-widgets.test.js
tests/common/widgets/hits/options.ts
tests/common/widgets/infinite-hits/options.ts

**Summary**
A series of PRs recently added a top banner to the `Hits` widget (visibility is controlled by rules that update `renderingContent` for a given query). This PR implements the same feature, but for the `InfiniteHits` widget.
This was done by:
1. updating `connectInfiniteHits` (previous PR)
2. updating `InfiniteHits` JS component
3. updating `infinite-hits` JS widget
4. updating `InfiniteHits` React component
5. updating `InfiniteHits` React widget
6. updating `satellite.scss` and `algolia.scss`
Related tickets:
- https://algolia.atlassian.net/browse/EMERCH-1501
- https://algolia.atlassian.net/browse/EMERCH-1502
- https://algolia.atlassian.net/browse/EMERCH-1503
- https://algolia.atlassian.net/browse/EMERCH-1505
**Result**
JS Hits, default banner:
JS InfiniteHits, default banner: …

feat(infinite-hits): add top banner to InfiniteHits widget

---

packages/instantsearch.js/src/components/Template/Template.tsx
packages/instantsearch.js/src/components/Template/__tests__/Template-test.tsx
packages/instantsearch.js/src/components/Template/__tests__/__snapshots__/Template-test.tsx.snap

**Summary**
This fixes https://github.com/algolia/instantsearch/pull/6243#discussion_r1649444124
**Result**
We didn't see that with Hits because [all templates remount regardless, as they are not memoized](https://github.com/algolia/instantsearch/blob/762e6335692bc0f05243edbf168f1be0b8d31f0c/packages/instantsearch.js/src/widgets/hits/hits.tsx#L83-L93).
There might be a way to solve this only with `componentDidUpdate` but I think there would be more duplicate code, probably fine to keep as is until we get rid of Hogan.

fix(RawHtml): force component to remount

---

packages/instantsearch.js/src/connectors/pagination/Paginator.ts
packages/instantsearch.js/src/connectors/pagination/__tests__/Paginator-test.ts
tests/common/widgets/pagination/options.ts

**Summary**
If the page is outside the range, it should behave like the 0th or last page. This disables the relevant buttons and links, which makes more sense UX-wise, and avoids creating pages that don't exist when you start from an invalid URL.
[CR-6249]
**Result**
- Page >= limit page is considered last page
- negative page or page 0 is considered first page
[CR-6249]: https://algolia.atlassian.net/browse/CR-6249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(pagination): any page outside the range is also first or last

---

examples/vue/default-theme/package.json
examples/vue/e-commerce/package.json
examples/vue/getting-started/package.json
examples/vue/media/package.json
packages/vue-instantsearch/package.json

**Summary**
It seems during last release the vue examples were not provided the right version for instantsearch.js, making the package an actual dependency instead of being linked from the monorepo.

chore(examples): set instantsearchjs monorepo version in vue examples

---

examples/js/e-commerce-umd/package.json
examples/js/e-commerce/package.json
examples/js/media/package.json

**Summary**
Small PR that marks **typescript** as an explicit dev dependency to help Codesandbox interpret TypeScript appropriately in our example sandboxes.
**Result**
No more problem with `type` being an unknown keyword and other similar errors.

chore(examples): explicitly set typescript dev dependency to prevent issues on CSB

---

package.json
packages/instantsearch.js/src/lib/utils/__tests__/getAppIdAndApiKey-test.ts
packages/instantsearch.js/src/lib/utils/getAppIdAndApiKey.ts
packages/react-instantsearch-core/package.json
packages/react-instantsearch/package.json
packages/vue-instantsearch/package.json
scripts/legacy/downgrade-algoliasearch-dependency.js
tsconfig.v3.json
yarn.lock

**Summary**
**Result**
We fallback to `baseHeaders` and `baseQueryParameters` if `headers` or `queryParameters` do not exist.
Updated all remaining peer deps to mark compatibility with v5.
[FX-2928]: https://algolia.atlassian.net/browse/FX-2928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(algoliasearch): correctly retrieve headers for v5

---

packages/instantsearch.js/package.json
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/react-instantsearch-core/src/__tests__/insights.test.tsx
tests/common/shared/insights.ts
tests/common/widgets/hits/insights.ts
tests/common/widgets/infinite-hits/insights.ts
tests/mocks/createInsightsClient.ts
yarn.lock

**Summary**
Updates search-insights to 2.15.0 which contains features to simplify query id tracking from clicks for use in conversion events.
**Result**
Updated usage in the insights middleware as well as the local dependency

fix(deps): update dependency search-insights to 2.15.0

---

packages/instantsearch.js/src/lib/__tests__/server.test.ts
packages/instantsearch.js/src/lib/server.ts
packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-test.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts
packages/instantsearch.js/src/types/results.ts
packages/react-instantsearch-core/src/server/__tests__/__snapshots__/getServerState.test.tsx.snap
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js

**Summary**
Fixes part of #6258 and #6259 
**Result**
- A single index may cause up to 3 requests at once, if it has facets applied or hierarchical facets, so request params should be an array.
- Shape of a cached request is `{ method: 'search', args: [Array<QueryParams>] }`, not `{ method: 'search', args: Array<Array<QueryParams>> }` as it takes a single argument which is an array of params.
[FX-2938]: https://algolia.atlassian.net/browse/FX-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cache): support multi-index and multiple queries per index

---

packages/vue-instantsearch/src/util/__tests__/renderCompat.test.js
packages/vue-instantsearch/src/util/vue-compat/index-vue2.js

**Summary**
This was causing an issue for https://github.com/algolia/instantsearch/pull/6281
**Result**
When the tag is a string, we pick the actual vue2 props and assume the rest are attributes. We still have to pass `attrs` if passed for compatibility with actual vue render functions.
Now the function should be compatible with both `createElement` and Vue's `h` signatures

fix(vue2): `augmentedCreateElement` should pass HTML attributes

---

bundlesize.config.json
packages/vue-instantsearch/src/__tests__/common-widgets.test.js
packages/vue-instantsearch/src/components/InfiniteHits.vue
packages/vue-instantsearch/src/components/__tests__/InfiniteHits.js
packages/vue-instantsearch/src/components/__tests__/__snapshots__/InfiniteHits.js.snap
tests/common/widgets/infinite-hits/options.ts

**Summary**
This PR adds the new top banner to the Vue `InfiniteHits` widget and updates associated tests. The top banner feature has already been added to `Hits` and `InfiniteHits` for the JS and React flavors of InstantSearch.
This widget is slightly different from the React version by using a `showBanner` prop (defaulted to `true`) since relying on whether a parent component passed included content with the banner slot could be difficult. I'm open to changing this implementation if anyone has a recommended approach though.
[Jira issue](https://algolia.atlassian.net/browse/EMERCH-1560)
**Result**
Getting Started example app:

feat(infinite-hits): add banners to vue flavor

---

packages/algoliasearch-helper/src/requestBuilder.js
packages/instantsearch.js/src/lib/__tests__/server.test.ts

**Summary**
Fixes last comment in #6258
**Result**
Instead of explicitly setting it to `undefined`, we delete it so that it matches the serialized params

fix(cache): support nested hierarchical refinements

---

.circleci/config.yml
packages/algoliasearch-helper/types/algoliasearch.d.ts
scripts/legacy/downgrade-algoliasearch-v4.js

**Summary**
**Result**
We run the same tests and type checking as for v5 as they were written for v4 anyway, it does work
[FX-2929]: https://algolia.atlassian.net/browse/FX-2929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: add downgrade script for algoliasearch v4 and steps

---

packages/react-instantsearch-core/rollup.config.js
packages/react-instantsearch-core/src/lib/useIndex.ts
packages/react-instantsearch-core/src/lib/useIndexContext.ts
packages/react-instantsearch-core/src/lib/useInstantSearchContext.ts
packages/react-instantsearch-core/src/lib/useStableValue.ts
packages/react-instantsearch-core/src/server/getServerState.tsx
packages/react-instantsearch/rollup.config.js
packages/vue-instantsearch/rollup.config.js

**Summary**
A circular dependency can cause issues, which is happening here because getServerState is importing from the index, but it's also exported from that same index.
**Result**
fixes #6292
also copied the code we have in InstantSearch.js to prevent circular dependency into react and vue instantsearch. Before the fix the build failed thanks to these onwarn changes.
This PR removes the circular dependency and also goes through all imports in React InstantSearch core and makes sure they're consistent (but the only circle was in getServerState).

fix(imports): prevent circular import

---

packages/instantsearch.js/src/types/results.ts

**Summary**
fixes https://github.com/algolia/instantsearch/issues/6295
`params` is declared [here](https://github.com/algolia/instantsearch/blob/60c3f2066bc24d7af7884094b3f7293bf77d5d2a/packages/instantsearch.js/src/lib/server.ts#L105). As `JSON.parse` can never return `undefined`, this value can never be `undefined` either.
**Result**
I manually changed the type inside of the node_module in a Remix project and there was no type complaint anymore

fix(typescript): make recommendResults.params non-nullable

---

packages/instantsearch.js/src/lib/routers/__tests__/history-integration.test.ts
packages/instantsearch.js/src/lib/routers/history.ts

**Summary**
In real situations, it seems like #5966 forgot to account for `write` being called through `onInternalStateChange`, which is deferred and thus called after the dispose of the middleware/router.
**Result**
This PR solves that situation by ensuring the router never writes after dispose if this option is set to `false`.
ref: https://github.com/algolia/instantsearch/discussions/6304

fix(history): cleanUrlOnDispose also prevents write after dispose

---

bundlesize.config.json
packages/instantsearch.js/src/lib/InstantSearch.ts

**Summary**
Import `index` from its entry point, not from the `widgets` file
This avoids side effects or other widgets being imported when only the InstantSearch component is imported.
**Result**
fixes #6309
This was introduced by accident in https://github.com/algolia/instantsearch/commit/89dd7ae4d45dea4dafbe451e55b01f2e45caf07e#diff-ab6f88a95338456e6f91ca8aa8699155153f09b67f8b2aab1bca4708e47eb9bfR10

fix: import `index` from its specific file

---

packages/vue-instantsearch/stories/Panel.stories.js

Something is wrong with the webpack setup in storybook, where it transpiles https://github.com/algolia/instantsearch/blob/18959b47f2f541f410e091a0cb7140f40e0956c2/packages/vue-instantsearch/src/mixins/panel.js#L28-L32
```js
// from
this.emitter.on(PANEL_CHANGE_EVENT, (value) => {
this.updateCanRefine(value);
});
// to
this.emitter.on(PANEL_CHANGE_EVENT, function (value) {
this.updateCanRefine(value);
});
```
Which is obviously wrong (`this` is undefined instead of the component). This bundling fail isn't happening in any other components, stories or examples, so just avoiding the issue is best
reported in: https://algolia.slack.com/archives/C2XP6HBKQ/p1722600762388799

chore(storybook): fix vue panel

---

bundlesize.config.json
packages/instantsearch.js/src/connectors/configure-related-items/connectConfigureRelatedItems.ts
packages/instantsearch.js/src/connectors/index.ts
packages/instantsearch.js/src/widgets/configure-related-items/configure-related-items.ts
packages/instantsearch.js/src/widgets/index.ts

**Summary**
Deprecate ConfigureRelatedItems, its API is fairly confusing and we never saw significant usage. Instead what you can do is:
- use relatedItems or connectRelatedItems (this uses recommend instead of search, but fits all use cases better)
- use a regular configure with `filters: 'attributeName:attributeValue<score=i>'` fetched from the object
If you're using configureRelatedItems, please reach out and we can find a suitable alternative for you.
**Result**
EXPERIMENTAL_configureRelatedItems and its connector are marked as deprecated and will be removed in a next minor version

fix(ExperimentalConfigureRelatedItems): deprecate in favor of RelatedItems

---

bundlesize.config.json
packages/instantsearch-ui-components/src/components/Carousel.tsx
packages/instantsearch-ui-components/src/components/__tests__/Carousel.test.tsx
packages/instantsearch.js/src/__tests__/index-es-test.ts
packages/instantsearch.js/src/__tests__/index-test.ts
packages/instantsearch.js/src/index.es.ts
packages/instantsearch.js/src/index.ts
packages/instantsearch.js/src/templates/__tests__/carousel.test.tsx
packages/instantsearch.js/src/templates/carousel/carousel.tsx
packages/instantsearch.js/src/templates/index.ts
packages/instantsearch.js/src/widgets/frequently-bought-together/__tests__/frequently-bought-together.test.tsx
packages/instantsearch.js/src/widgets/frequently-bought-together/frequently-bought-together.tsx
packages/instantsearch.js/src/widgets/looking-similar/__tests__/looking-similar.test.tsx
packages/instantsearch.js/src/widgets/looking-similar/looking-similar.tsx
packages/instantsearch.js/src/widgets/related-products/__tests__/related-products.test.tsx
packages/instantsearch.js/src/widgets/related-products/related-products.tsx
packages/instantsearch.js/src/widgets/trending-items/__tests__/trending-items.test.tsx
packages/instantsearch.js/src/widgets/trending-items/trending-items.tsx

This introduces the `carousel` template and implements the `layout` template in Recommend widgets.
https://algolia.atlassian.net/browse/FX-2818

feat(instantsearch.js): introduce `carousel` template

---

packages/instantsearch-ui-components/src/components/FrequentlyBoughtTogether.tsx
packages/instantsearch-ui-components/src/components/LookingSimilar.tsx
packages/instantsearch-ui-components/src/components/RelatedProducts.tsx
packages/instantsearch-ui-components/src/components/TrendingItems.tsx
packages/instantsearch-ui-components/src/components/__tests__/FrequentlyBoughtTogether.test.tsx
packages/instantsearch-ui-components/src/components/__tests__/LookingSimilar.test.tsx
packages/instantsearch-ui-components/src/components/__tests__/RelatedProducts.test.tsx
packages/instantsearch-ui-components/src/components/__tests__/TrendingItems.test.tsx
packages/instantsearch-ui-components/src/components/recommend-shared/List.tsx
packages/instantsearch-ui-components/src/components/recommend-shared/index.ts
packages/instantsearch-ui-components/src/types/Recommend.ts
packages/instantsearch.js/src/widgets/frequently-bought-together/frequently-bought-together.tsx
packages/instantsearch.js/src/widgets/looking-similar/looking-similar.tsx
packages/instantsearch.js/src/widgets/related-products/related-products.tsx
packages/instantsearch.js/src/widgets/trending-items/trending-items.tsx

This renames the `view` prop used in the Recommend UI components into `layout` to fit the API we chose for templating.

refactor(instantsearch-ui-components): rename `view` prop into `layout`

---

examples/js/getting-started/index.html
examples/js/getting-started/package.json
examples/js/getting-started/products.html
examples/js/getting-started/src/app.css
examples/js/getting-started/src/app.js
examples/js/getting-started/src/products.js

This uses the new `carousel` template in the **Getting Started** example for InstantSearch.js.

docs(instantsearch.js): use `carousel` template

---

packages/instantsearch.js/package.json
packages/instantsearch.js/src/widgets/geo-search/GeoSearchRenderer.d.ts
packages/instantsearch.js/src/widgets/geo-search/__tests__/geo-search-test.ts
yarn.lock

**Summary**
change MarkerOption from `typeof` to a direct access.
This isn't really exposed to the user, but I believe this broke when they moved from a namespace to an interface.
**Result**
No type error in examples provided in the original issue
Still using Marker, not AdvancedMarker (despite Marker being deprecated), changing this would likely be a breaking change.
fixes #6253

fix(geoSearch): correct type of MarkerOptions

---

examples/js/getting-started/src/app.css
examples/js/getting-started/src/app.js
examples/js/getting-started/src/products.js
packages/instantsearch.js/src/templates/__tests__/carousel.test.tsx
packages/instantsearch.js/src/templates/carousel/carousel.tsx
packages/instantsearch.js/src/widgets/frequently-bought-together/__tests__/frequently-bought-together.test.tsx
packages/instantsearch.js/src/widgets/frequently-bought-together/frequently-bought-together.tsx
packages/instantsearch.js/src/widgets/looking-similar/__tests__/looking-similar.test.tsx
packages/instantsearch.js/src/widgets/looking-similar/looking-similar.tsx
packages/instantsearch.js/src/widgets/related-products/__tests__/related-products.test.tsx
packages/instantsearch.js/src/widgets/related-products/related-products.tsx
packages/instantsearch.js/src/widgets/trending-items/__tests__/trending-items.test.tsx
packages/instantsearch.js/src/widgets/trending-items/trending-items.tsx

This fixes an issue where the widget classes for the list and items weren't properly forwarded to the layout.
I only pass the `list` and `item` ones because the other ones aren't necessary, and because the `root` one isn't supposed to be added to the layout root.

fix(instantsearch.js): forward widget classes to carousel

---

.circleci/config.yml

**Summary**
This PR persists the built version of algolia experiences to the workspace so it can be used to build the website examples.
**Result**
CI does not fail at the `examples` step anymore.

chore(ci): persist algolia experiences bundles for other jobs

---

packages/instantsearch.js/src/lib/utils/__tests__/hydrateSearchClient-test.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts

**Summary**
in 5.2.5 of algoliasearch, a change in the code is made, and `client.search` needs to be called with the correct `this`, which isn't the case if you say `const search = client.search`
**Result**
fixes #6350
fixes algolia/algoliasearch-client-javascript#1549
possibly also solves #6348, to investigate afterwards

fix(client): ensure client.search is bound

---

packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/pendingSearch.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/searchForFacetValues.js
packages/algoliasearch-helper/types/algoliasearch.d.ts
packages/instantsearch.js/src/widgets/refinement-list/__tests__/refinement-list.test.tsx

**Summary**
v5 has a `searchForFacetValues` function, but it's single-index only. We thus need to detect it and use `client.search` directly. In a future major we can change this and only use `client.search`
**Result**
- v5 allows sffv in the type for the full client (repro: https://github.com/WavyWalk/reproduce-algolia-v5/blob/typing-5-3-0/src/App.tsx#L11)
- sffv isn't called in v5, but client.search instead
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1550

fix(client): use client.search in sffv for v5

---

packages/instantsearch.js/src/lib/templating/__tests__/renderTemplate.test.ts
packages/instantsearch.js/src/lib/templating/renderTemplate.ts
packages/instantsearch.js/src/types/templates.ts

**Summary**
I think simple strings can be very useful in panels, or other simple templates. We should of course warn if there's html-looking text, as that's likely a mistake in migration.
**Result**
simple strings in templates are passed as text nodes; a warning is given if that text has a `<` in it

feat(templates): re-introduce simple strings as text

---

examples/js/algolia-experiences/package.json
packages/algolia-experiences/src/__tests__/render.test.ts
packages/algolia-experiences/src/render.tsx

**Summary**
This adds a default Carousel layout for recommend widgets in experiences
Additionally, dependencies have been added to the experiences example to fix the build order in `yarn build`
[FX-3109]
[FX-3109]: https://algolia.atlassian.net/browse/FX-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(experiences): add a default layout carousel for recommend widgets

---

examples/js/algolia-experiences/package.json

fix the version used in the example, to avoid accidentally relying on the package from npm

chore(examples): fix version

---

packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/test/createInstantSearch.ts

Instead you can use `use` to add a middleware
BREAKING CHANGE: EXPERIMENTAL_use function is replaced with use function

fix(instantsearch): remove EXPERIMENTAL_use

---

packages/react-instantsearch-nextjs/src/InitializePromise.tsx

**Summary**
Fixes #6393 
Thought this might help in mitigating memory leaks but it doesn't seem to do anything. So instead of fixing the error we night as well just remove the `dispose` call.

fix(next-app-router): remove search.dispose

---

packages/instantsearch.js/src/components/RefinementList/RefinementList.tsx
packages/instantsearch.js/src/components/RefinementList/__tests__/RefinementList-test.tsx
tests/common/widgets/refinement-list/options.ts

**Summary**
In InstantSearch.js, focus is lost when toggling a facet value in a refinement list. This is because the component is destroyed and re-created during re-render, and [Preact does not explicitly refocus the newly created component](https://github.com/preactjs/preact/issues/3242) (whereas React does it).
This PR adds code that stores the last refined value and applies focus to its DOM element on re-render.
CR-6976

fix(refinement-list): re-apply focus on facet checkbox after render

---

bundlesize.config.json
packages/instantsearch.js/src/lib/__tests__/InstantSearch-integration-test.ts
packages/instantsearch.js/src/lib/utils/uuid.ts
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/instantsearch.js/src/types/insights.ts
packages/react-instantsearch-core/src/server/__tests__/getServerState.test.tsx
tests/common/shared/insights.ts

[FX-2955]
**Summary**
Double queries happen when the state of instantsearch and insights no longer matches at the time of the first query on page load.
- The `search-insights` `onUserTokenChange` and `onAuthenticatedUserTokenChange` callbacks are not able to set the `user-token` by the time the first search query is sent. When the `user-token` is changed by these callbacks, the state has changed from the first query. If a new query is scheduled after this(for example with dynamic widgets), the cache misses due to the changed state and second query is made.
- When `useCookie` is set to true, insights needs to create a anonymous token and save it as a cookie. Instantsearch would have the token updated with the callback from before, but this does not happen in time for the first query. So …

fix(instantsearch.js): fix user token not being set in time for the first query

---

.circleci/config.yml
.codesandbox/ci.json
.eslintrc.js
babel.config.js
jest.config.js
packages/instantsearch-core/CHANGELOG.md
packages/instantsearch-core/README.md
packages/instantsearch-core/package.json
packages/instantsearch-core/scripts/version.cjs
packages/instantsearch-core/src/index.ts
packages/instantsearch-core/src/version.ts
packages/instantsearch-core/tsconfig.declaration.json
packages/instantsearch-core/types/algoliasearch.d.ts
packages/instantsearch-core/types/index.cjs
packages/instantsearch-core/types/index.d.ts
packages/instantsearch-core/types/index.mjs
packages/instantsearch-core/types/insights.d.ts
packages/instantsearch-core/types/results.d.ts
packages/instantsearch-core/types/utils.d.ts
packages/instantsearch.js/package.json
packages/instantsearch.js/src/connectors/dynamic-widgets/__tests__/connectDynamicWidgets-test.ts
packages/instantsearch.js/src/index.es.ts
packages/instantsearch.js/src/types/algoliasearch.ts
packages/instantsearch.js/src/types/connector.ts
packages/instantsearch.js/src/types/index.ts
packages/instantsearch.js/src/types/middleware.ts
packages/instantsearch.js/src/types/widget.ts
packages/instantsearch.js/src/widgets/dynamic-widgets/__tests__/dynamic-widgets-test.ts

This creates a new `instantsearch-core` and extracts a first set of easy-to-migrate types.
The process will be iterative with small PRs to avoid a huge diff.
The moved types are still re-exported, as they are useful for users of the library, and all types are already exported in current instantsearch.js. We can if needed establish a pattern for internal types later, but that's likely not needed initially.
[FX-3094]
[FX-3095]
[FX-3094]: https://algolia.atlassian.net/browse/FX-3094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-3095]: https://algolia.atlassian.net/browse/FX-3095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: introduce `instantsearch-core`

---

packages/instantsearch.js/stories/autocomplete.stories.ts

This also avoids the deprecated `instantsearch.highlight` function.
PR made to master as it's already an example showing how to migrate before next is ready

chore(stories): avoid innerHTML

---

bundlesize.config.json
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
tests/common/widgets/hits/insights.ts
tests/common/widgets/infinite-hits/insights.ts

**Summary**
[CR-6960](https://algolia.atlassian.net/browse/CR-6960)
Fixes #5442
**Result**
Only did it for view events because they're the only ones that we got issues for.
Tried to make it a bit more future proof for when we implement it with intersection observer, we look for differences between what we try to send vs what was already sent.
It resets when we receive a new query.
[CR-6960]: https://algolia.atlassian.net/browse/CR-6960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(insights): deduplicate view events

---

packages/algolia-experiences/src/__tests__/get-configuration.test.ts
packages/algolia-experiences/src/__tests__/get-information.test.ts
packages/algolia-experiences/src/get-configuration.ts
packages/algolia-experiences/src/get-information.ts

**Summary**
This PR makes it easier to switch API environments by setting an `environment` parameter in `algolia-configuration`. It defaults to `prod`.

feat(experiences): add `environment` setting and default to prod

---

.github/workflows/enforce-do-not-merge-label.yml

**Summary**
Small utility job that prevents merging PRs when they have the "DO NOT MERGE" label applied. Copied from AlgoliaWeb.

ci: prevent PR with "do not merge" label from being merged

---

packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx

**Summary**
prevent explicitely passing an `index` widget while `compositionID` is defined.
[EMERCH-1747](https://algolia.atlassian.net/browse/EMERCH-1747)
[EMERCH-1747]: https://algolia.atlassian.net/browse/EMERCH-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: don't allow index widget when in composition mode

---

bundlesize.config.json
packages/vue-instantsearch/src/components/InstantSearch.js
packages/vue-instantsearch/src/util/createInstantSearchComponent.js

**Summary**
this PR leverages what's put in place in #6437 to make it available in vue flavor
[EMERCH-1748](https://algolia.atlassian.net/browse/EMERCH-1748)
[EMERCH-1748]: https://algolia.atlassian.net/browse/EMERCH-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make composition compatible with vue

---

packages/instantsearch-core/src/instantsearch.ts
packages/instantsearch-core/src/types/instantsearch.ts
packages/instantsearch-core/test/createInstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/stories/hits.stories.ts
packages/instantsearch.js/stories/infinite-hits.stories.ts
packages/instantsearch.js/test/createInstantSearch.ts
packages/vue-instantsearch/.storybook/addons.js
packages/vue-instantsearch/src/components/InstantSearch.js
packages/vue-instantsearch/src/components/__tests__/InstantSearch.js
packages/vue-instantsearch/stories/Hits.stories.js
packages/vue-instantsearch/stories/InfiniteHits.stories.js
packages/vue-instantsearch/stories/utils.js

The `insightsClient` prop is a remnant of an older implementation of insights, and no longer is needed. In this PR it's removed.
BREAKING CHANGE: use `insights` prop of instantsearch instead of `insightsClient`

refactor: remove insightsClient prop

---

bundlesize.config.json
examples/js/e-commerce-umd/src/widgets/ClearFiltersEmptyResults.ts
examples/js/e-commerce-umd/src/widgets/Pagination.ts
examples/js/e-commerce/src/widgets/ClearFiltersEmptyResults.ts
examples/js/e-commerce/src/widgets/Pagination.ts
packages/instantsearch.js/src/connectors/autocomplete/connectAutocomplete.ts
packages/instantsearch.js/src/connectors/clear-refinements/connectClearRefinements.ts
packages/instantsearch.js/src/connectors/current-refinements/connectCurrentRefinements.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts
packages/instantsearch.js/src/lib/insights/__tests__/insights-client-test.ts
packages/instantsearch.js/src/lib/utils/getRefinements.ts
packages/instantsearch.js/src/lib/utils/render-args.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/instantsearch.js/src/types/widget.ts
packages/instantsearch.js/src/widgets/analytics/analytics.ts
packages/instantsearch.js/stories/panel.stories.ts
packages/react-instantsearch-core/src/lib/useSearchResults.ts

**Summary**
In some cases `results` in `render` can be null:
- no index name passed (https://github.com/algolia/instantsearch/blob/a896774b873ff5d046c1e736680bce8c48661e54/packages/algoliasearch-helper/src/algoliasearch.helper.js#L1503-L1510)
- stalled render (already handled)
In the vast majority of cases we already handled `results` being `null` or `undefined` just in case, but now i've changed the type to ensure we always catch this problem
**Result**
null is handled in all cases for results
This issue doesn't have a reproduction, but i believe it now guards for all possible cases of "no results", so: 
fixes #6441
[CR-7353]
[CR-7353]: https://algolia.atlassian.net/browse/CR-7353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(rendering): ensure resilience against "null" results

---

packages/algoliasearch-helper/src/SearchParameters/RefinementList.js
packages/algoliasearch-helper/src/SearchParameters/index.js
packages/algoliasearch-helper/src/SearchResults/index.js
packages/algoliasearch-helper/test/spec/SearchResults/getFacetValues.js
packages/algoliasearch-helper/test/spec/SearchResults/getFacetValues/disjunctive-non-exhaustive.json
packages/algoliasearch-helper/test/spec/SearchResults/getFacetValues/hierarchical-non-exhaustive.json

**Summary**
Use the values of the main facet in disjunctive facets
This is relevant in two cases:
- second query is non-exhaustive
- second query is not correct due to facet count after distinct
There's still more edge cases left (first query non exhaustive, but second isn't, but that's unlikely) and those are not worse after this PR.
**Result**
disjunctive facets read the count from the first query over the ones from the second query. This is already the case for hierarchical facets.

fix(disjunctive): prefer values of main query for facet count

---

bundlesize.config.json
examples/react/next-app-router/app/Search.tsx
examples/react/next-app-router/app/page.tsx
examples/react/next-app-router/lib/client.tsx
examples/react/next-routing/pages/index.tsx
examples/react/next-routing/pages/test.tsx
examples/react/next/pages/index.tsx
examples/react/ssr/src/searchClient.js
examples/react/ssr/src/server.js
packages/algoliasearch-helper/index.d.ts
packages/instantsearch.js/src/lib/__tests__/server.test.ts
packages/instantsearch.js/src/lib/server.ts
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts
packages/react-instantsearch-core/src/server/__tests__/__snapshots__/getServerState.test.tsx.snap
packages/react-instantsearch-core/src/server/__tests__/getServerState.test.tsx
scripts/legacy/downgrade-algoliasearch-v4.js
yarn.lock

- in insights middleware: ensure we read from the _initialResults (as insights starts before index is init'ed and the parameters aren't in the index, but in the main index)
- in getInitialResults: add the parameters to every index explicitly (it's not ui state so was missing otherwise)
other changes in this PR:
- something in the dependencies to prevent https://github.com/babel/babel/issues/16689
- use a cache in the server side react examples
- type `userToken` in SearchParameters
related to [CR-6992]
[CR-6992]: https://algolia.atlassian.net/browse/CR-6992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(insights): ensure the same token is used when rendered multiple times server side

---

packages/instantsearch-core/src/__tests__/RoutingManager.test.ts
packages/instantsearch-core/src/__tests__/instantsearch-integration.test.ts
packages/instantsearch-core/src/__tests__/instantsearch.test.tsx
packages/instantsearch-core/src/__tests__/server.test.ts
packages/instantsearch-core/src/__tests__/status.test.ts
packages/instantsearch-core/src/routing/__tests__/correct-urls.test.ts
packages/instantsearch-core/src/routing/__tests__/dispose-start.test.ts
packages/instantsearch-core/src/routing/__tests__/duplicate-url.test.ts
packages/instantsearch-core/src/routing/__tests__/external-influence.test.ts
packages/instantsearch-core/src/routing/__tests__/modal.test.ts
packages/instantsearch-core/src/routing/__tests__/spa-debounced.test.ts
packages/instantsearch-core/src/routing/__tests__/spa-replace-state.test.ts
packages/instantsearch-core/src/routing/__tests__/spa.test.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.ts

these were still in instantsearch.js but actually are for the "core" domain now.

chore(core): move tests to core

---

packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/src/requestBuilder.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/events.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/pendingSearch.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/searchForFacetValues.js
packages/algoliasearch-helper/types/algoliasearch.d.ts
packages/instantsearch-core/src/connectors/__tests__/connectRefinementList.test.ts
packages/instantsearch-core/src/widgets/__tests__/index-widget.test.ts
packages/instantsearch.js/src/widgets/refinement-list/__tests__/refinement-list.test.tsx
packages/react-instantsearch/src/widgets/__tests__/RefinementList.test.tsx
tests/common/widgets/refinement-list/options.ts
tests/mocks/createSearchClient.ts

This signature is the easiest to detect and makes the required signature of the searchClient simpler (only `search`, `getRecommendations` and `addAlgoliaAgent` are now used).
In this PR I also fix the signature of `search` in `SearchClient` type to make this usage fit reality
BREAKING CHANGE: in `helper.searchForFacetFalues` only the method `client.search` is used, none of the previous fallbacks.

fix(searchForFacetValues): only call client.search

---

packages/react-instantsearch-nextjs/src/InstantSearchNext.tsx
packages/react-instantsearch-nextjs/src/__tests__/InstantSearchNext.test.tsx

**Summary**
This is a follow-up to https://github.com/algolia/instantsearch/pull/6452 which provides a better way to handle more use cases, adding one where route changes to a non-InstantSearch implementation, and navigates back to it.
**Result**
Search is performed properly when a user navigates back to an InstantSearch implementation.

fix(next-app-router): better detection of route change

---

packages/instantsearch-core/src/types/widget.ts
packages/instantsearch-core/src/widgets/__tests__/index-widget.test.ts
packages/instantsearch-core/src/widgets/index-widget.ts
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js

The old method has long been deprecated and has no usage inside instantsearch outside of running a warning.
[FX-3197]
BREAKING CHANGE: rename getWidgetState to getWidgetUiState in your custom widgets or connectors.
[FX-3197]: https://algolia.atlassian.net/browse/FX-3197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(index): remove getWidgetState

---

examples/js/e-commerce-umd/src/routing.ts
examples/js/e-commerce/src/routing.ts
examples/react/e-commerce/routing.ts
examples/react/ssr/src/App.js
examples/react/ssr/src/server.js
examples/vue/e-commerce/src/routing.js
packages/instantsearch-core/src/__tests__/RoutingManager.test.ts
packages/instantsearch-core/src/routing/__tests__/historyRouter.test.ts
packages/instantsearch-core/src/routing/historyRouter.ts
packages/react-instantsearch-core/src/components/__tests__/InstantSearch.test.tsx
packages/react-instantsearch-core/src/components/__tests__/InstantSearchSSRProvider.test.tsx
packages/react-instantsearch-nextjs/src/useInstantSearchRouting.ts
packages/react-instantsearch-router-nextjs/src/index.ts

getCurrentURL is the alternative of getLocation in the history router. This is changed as it's possible to create a URL out of a string, but not a location. We also don't use any properties of the location that aren't also present in a URL.
[FX-3193]
BREAKING CHANGE: change from `getLocation` to `getCurrentURL`, and return a URL object.
BREAKING CHANGE: createURL createURL now receives `currentURL` instead of `location`
BREAKING CHANGE: parseURL createURL now receives `currentURL` instead of `location`
[FX-3193]: https://algolia.atlassian.net/browse/FX-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(routing): replace getLocation with getCurrentURL

---

packages/vue-instantsearch/.storybook/webpack.config.js
packages/vue-instantsearch/stories/ConfigureRelatedItems.stories.js
packages/vue-instantsearch/stories/Index.stories.js
packages/vue-instantsearch/stories/InstantSearch.stories.js
packages/vue-instantsearch/stories/RelevantSort.stories.js
packages/vue-instantsearch/stories/utils.js

**Summary**
This PR fixes a few issues that prevented [the deployed Vue Storybook](https://instantsearchjs.netlify.app/stories/vue/) from being properly available.

fix(storybook): update algoliasearch import statement in vue stories

---

packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/src/SearchResults/index.js
packages/algoliasearch-helper/test/datasets/SearchParameters/search.dataset.js
packages/algoliasearch-helper/test/spec/SearchResults/getFacetValues.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/searchOnce.js
packages/algoliasearch-helper/test/spec/hierarchical-facets/simple-usage.js
packages/algoliasearch-helper/test/spec/hierarchical-facets/sort-by.js
packages/instantsearch-core/src/__tests__/instantsearch.test.tsx
packages/instantsearch-core/src/instantsearch.ts
packages/instantsearch-core/src/types/instantsearch.ts
packages/instantsearch-core/src/widgets/__tests__/index-widget.test.ts

BREAKING CHANGE: the option persistHierarchicalRootCount no longer exists. The default behaviour is now the same as used to be with persistHierarchicalRootCount: true
[FX-3185]
[FX-3185]: https://algolia.atlassian.net/browse/FX-3185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(helper): persistHierarchicalRootCount: true

---

packages/algoliasearch-helper/src/requestBuilder.js

**Summary**
implement disjunctive facets for composition API
[EMERCH-1744](https://algolia.atlassian.net/browse/EMERCH-1744)
[related backend RFC](https://algolia.atlassian.net/wiki/spaces/CMP/pages/5193465937/RFC+-+Feature+facets+in+Composition+API)
[EMERCH-1744]: https://algolia.atlassian.net/browse/EMERCH-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: handle disjunctive facets with composition API

---

bundlesize.config.json
packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/instantsearch.js/src/lib/InstantSearch.ts

**Summary**
adding support for `SearchForFacetValues` when using Composition API
[EMERCH-1745](https://algolia.atlassian.net/browse/EMERCH-1745)
**Result**
there is a small bug on the API side which result in highlighting not working as expecting in the facet values, but that doesn't affect the implementation as the fix should be transparent API-wise
[EMERCH-1745]: https://algolia.atlassian.net/browse/EMERCH-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add searchForFacetValues for composition

---

packages/instantsearch-core/src/connectors/__tests__/connectHits.test.ts
packages/instantsearch-core/src/connectors/__tests__/connectInfiniteHits.test.ts
packages/instantsearch-core/src/connectors/connectHits.ts
packages/instantsearch-core/src/connectors/connectInfiniteHits.ts
packages/instantsearch-core/src/lib/infiniteHitsCache/__tests__/sessionStorage-key.test.ts
packages/instantsearch-core/src/lib/infiniteHitsCache/__tests__/sessionStorage.test.ts
packages/instantsearch-core/src/lib/infiniteHitsCache/sessionStorage.ts
packages/instantsearch-core/src/widgets/__tests__/index-widget.test.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts
packages/react-instantsearch-core/src/connectors/__tests__/useHits.test.tsx
packages/react-instantsearch-core/src/connectors/__tests__/useInfiniteHits.test.tsx
tests/common/widgets/infinite-hits/options.ts

In the past we have added an `items` alias for the previously added `hits`, so that all widgets are more consistent and the same widget would be usable between hits and relatedItems connectors for example. This is now continued with:
- hits render property removed
- infinite hits cache "write" receives `{ page, items }` instead of hits
[FX-3207]
BREAKING CHANGE: connectHits: `hits` property from render is replaced with `items`
BREAKING CHANGE: connectInfiniteHits: `hits` property from render is replaced with `items`
BREAKING CHANGE: infiniteHits: the cache.write function gets called with `{ page, items }` instead of `{ page, hits }`
[FX-3207]: https://algolia.atlassian.net/browse/FX-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(connectors): replace hits for items

---

examples/react/next/pages/index.tsx
packages/create-instantsearch-app/e2e/__snapshots__/templates.test.js.snap
packages/create-instantsearch-app/src/templates/InstantSearch.js/src/app.js.hbs
packages/create-instantsearch-app/src/templates/React InstantSearch/src/App.tsx.hbs
packages/create-instantsearch-app/src/templates/Vue InstantSearch with Vue 3/src/App.vue
packages/instantsearch-core/src/instantsearch.ts
packages/instantsearch-core/src/types/instantsearch.ts
packages/instantsearch-core/src/widgets/__tests__/index-widget.test.ts
packages/instantsearch-core/src/widgets/index-widget.ts

With preserveSharedStateOnUnmount behavior, UI State is the source of truth, when a widget gets removed, the UI State is evaluated again and the parameters result out of that.
[FX-3192]
Not done in this PR yet:
- changed the signature of dispose (no more helper and state)
- implement a similar behavior for recommend
BREAKING CHANGE: The option `future.preserveSharedStateOnUnmount` is removed and now behaves as if it was set to `true`
[FX-3192]: https://algolia.atlassian.net/browse/FX-3192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(state): change behaviour of preserveSharedStateOnUnmount

---

packages/instantsearch.js/src/lib/utils/__tests__/getAppIdAndApiKey-test.ts
packages/instantsearch.js/src/lib/utils/getAppIdAndApiKey.ts

**Summary**
In the insights middleware / getAppIdAndApiKey function we quickly fall back to the brittle logic with transporter. I've made a PR to the client (https://github.com/algolia/api-clients-automation/pull/4285) to expose appId and apiKey directly on the object, so newer v5 will mostly use this logic. 
**Result**
in v5 we use `appId` and `apiKey` from the client, which can also be a good way to be documented for custom clients

fix(insights): detect appId and apiKey from client directly in v5

---

examples/react/default-theme/src/components/NumericMenu.tsx
packages/instantsearch-core/src/connectors/__tests__/connectClearRefinements.test.ts
packages/instantsearch-core/src/connectors/__tests__/connectHitsPerPage.test.ts
packages/instantsearch-core/src/connectors/__tests__/connectNumericMenu.test.ts
packages/instantsearch-core/src/connectors/__tests__/connectRatingMenu.test.ts
packages/instantsearch-core/src/connectors/__tests__/connectSortBy.test.ts
packages/instantsearch-core/src/connectors/connectClearRefinements.ts
packages/instantsearch-core/src/connectors/connectHitsPerPage.ts
packages/instantsearch-core/src/connectors/connectNumericMenu.ts
packages/instantsearch-core/src/connectors/connectRatingMenu.ts
packages/instantsearch-core/src/connectors/connectSortBy.ts
packages/instantsearch.js/src/components/ClearRefinements/ClearRefinements.tsx
packages/instantsearch.js/src/widgets/clear-refinements/__tests__/clear-refinements.test.tsx
packages/instantsearch.js/src/widgets/clear-refinements/clear-refinements.tsx
packages/react-instantsearch-core/src/connectors/__tests__/useClearRefinements.test.tsx
packages/react-instantsearch-core/src/connectors/__tests__/useHitsPerPage.test.tsx
packages/react-instantsearch-core/src/connectors/__tests__/useNumericMenu.test.tsx
packages/react-instantsearch-core/src/connectors/__tests__/useSortBy.test.tsx
packages/react-instantsearch/src/ui/CurrentRefinements.tsx
packages/react-instantsearch/src/ui/__tests__/CurrentRefinements.test.tsx
packages/react-instantsearch/src/widgets/CurrentRefinements.tsx
packages/vue-instantsearch/src/components/ClearRefinements.vue
packages/vue-instantsearch/src/components/__tests__/ClearRefinements.js

In the past, `canRefine` has been introduced as a consistent way to check if any widget can be refined. There were previous largely overlapping pieces of information exposed which were deprecated. These are now removed.
[FX-3195]
BREAKING CHANGE: clearRefinements: replace `hasRefinements` with `canRefine`
BREAKING CHANGE: hitsPerPage: replace `hasNoResults` with `!canRefine`
BREAKING CHANGE: numericMenu: replace `hasNoResults` with `!canRefine`
BREAKING CHANGE: ratingMenu: replace `hasNoResults` with `!canRefine`
BREAKING CHANGE: sortBy: replace `hasNoResults` with `!canRefine`
[FX-3195]: https://algolia.atlassian.net/browse/FX-3195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(connectors): don't expose duplicates of canRefine

---

packages/instantsearch-core/src/connectors/__tests__/connectRefinementList.test.ts
packages/instantsearch-core/src/connectors/connectRefinementList.ts

Before this PR `canRefine` was always true for searchable.
[FX-3190]
BREAKING CHANGE: `canRefine` is false if there are no results from searchable if there's a query.
[FX-3190]: https://algolia.atlassian.net/browse/FX-3190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(refinementList): canRefine is calculated for searchable

---

packages/instantsearch-core/src/__tests__/instantsearch.test.tsx
packages/instantsearch-core/src/instantsearch.ts
packages/instantsearch-core/test/createInstantSearch.ts
packages/instantsearch.js/test/createInstantSearch.ts

BREAKING CHANGE: use removeWidgets, addWidgets instead of removeWidget, addWidget

fix(instantsearch): remove addWidget, removeWidget methods

---

examples/js/e-commerce-umd/src/routing.ts
examples/js/e-commerce/src/routing.ts
examples/react/e-commerce/routing.ts
examples/react/next-routing/pages/index.tsx
examples/react/next-routing/pages/test.tsx
examples/react/next/pages/index.tsx
examples/react/ssr/src/App.js
examples/vue/default-theme/src/App.vue
examples/vue/e-commerce/src/routing.js
examples/vue/media/src/App.vue
packages/instantsearch-core/src/routing/__tests__/dispose-start-clean.test.ts
packages/instantsearch-core/src/routing/__tests__/dispose-start.test.ts
packages/instantsearch-core/src/routing/__tests__/historyRouter-integration.test.ts
packages/instantsearch-core/src/routing/__tests__/historyRouter.test.ts
packages/instantsearch-core/src/routing/__tests__/modal-clean.test.ts
packages/instantsearch-core/src/routing/__tests__/modal.test.ts
packages/instantsearch-core/src/routing/__tests__/spa-clean.test.ts
packages/instantsearch-core/src/routing/__tests__/spa-debounced-clean.test.ts
packages/instantsearch-core/src/routing/__tests__/spa-debounced.test.ts
packages/instantsearch-core/src/routing/__tests__/spa-replace-state-clean.test.ts
packages/instantsearch-core/src/routing/historyRouter.ts
packages/react-instantsearch-core/src/components/__tests__/routing-clean/dispose-start.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing-clean/external-influence.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing-clean/modal.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing-clean/spa-debounced.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing-clean/spa-replace-state.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing-clean/spa.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing/modal.test.tsx
packages/react-instantsearch-core/src/components/__tests__/routing/spa-replace-state.test.tsx

In the vast majority of cases you're either never disposing InstantSearch, or the URL already gets cleared some other way (eg. through SPA navigation). This is why the new default for cleanUrlOnDispose is `false`.
You'd still want to set this option to `true` if you're rendering instantsearch in a modal that should have the url cleared when that modal is closed.
BREAKING CHANGE: default of cleanUrlOnDispose is false
[FX-3213]
[FX-3213]: https://algolia.atlassian.net/browse/FX-3213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(routing): change default of cleanUrlOnDispose to false

---

.circleci/config.yml

**Summary**
This PR enables running e2e tests on the next branch, to ensure large codebase changes result in predicable behaviors when interacting with our test app.

ci: run e2e tests on next branch

---

packages/instantsearch-core/src/__tests__/RoutingManager.test.ts
packages/instantsearch-core/src/__tests__/instantsearch.test.tsx
packages/instantsearch-core/src/instantsearch.ts
packages/instantsearch-core/src/types/instantsearch.ts
packages/instantsearch.js/stories/instantsearch.stories.ts
packages/react-instantsearch-core/src/components/__tests__/InstantSearch.test.tsx
packages/react-instantsearch-core/src/lib/useInstantSearchApi.ts
packages/vue-instantsearch/src/components/InstantSearch.js
packages/vue-instantsearch/src/components/__tests__/InstantSearch.js
packages/vue-instantsearch/src/util/createInstantSearchComponent.js
packages/vue-instantsearch/stories/InstantSearch.stories.js

This option is deprecated and all use cases are possible with onStateChange or other methods too
[FX-3216]
BREAKING CHANGE: replace searchFunction usage with onStateChange
[FX-3216]: https://algolia.atlassian.net/browse/FX-3216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(instantsearch): remove searchFunction

---

package.json
packages/algolia-experiences/rollup.config.js
packages/instantsearch.js/scripts/rollup/rollup.config.js
packages/react-instantsearch-core/rollup.config.js
packages/react-instantsearch/rollup.config.js
yarn.lock

This is the cause of the UMD e2e failure in `next`.
Basically the flow is:
1. source code that destructures something in arguments:
```js
function fn({ one, two }) {}
```
2. esm output of source code
```js
function fn(_ref) {
let {
one,
two,
} = _ref
```
3. umd production output (using uglify)
```js
function fn(e) {
var { one: e, two: t } = e
```
note the reused variable name
4. output after import through parcel of the prod umd import
```js
function fn(e) {
var e = e.one,
t = e.two;
```
This fixes it by changing step 3 by using terser to:
```js
function fn(e) {
let { one: t, two: n } = e;
}
```
note that it doesn't reuse the `e` variable and thus no longer bugs and has this output in parcel:
```js
function fn(e) {
var t = e.one,
n = e.two;
}
```
This issue started showing up once we …

fix(build): prevent destructure with reuse of same symbol.

---

packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/types/algoliasearch.d.ts
packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/server.ts
packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts
packages/react-instantsearch-core/src/lib/useInstantSearchApi.ts
packages/react-instantsearch-nextjs/src/InitializePromise.tsx
packages/react-instantsearch-nextjs/src/TriggerSearch.ts

**Summary**
- added minimal typing for `CompositionClient` and used it where necessary → it makes our life easier (and helped me catch a case I wouldn't have catched otherwise)
- `hydrateSearchClient` method adapted to work with Composition Client → not satisfactory but I don't have a better option :/
- `TriggerSearch` adapted to work with Composition (same as in instantsearch.ts)
- `server.ts > waitForResult`
- adapted search to work with Composition (same as in instantsearch.ts)
- get `requestParamsList` from the correct place when using Composition Client
- `react-instantsearch-nextjs > InitializePromise.tsx` method adapted to work with Composition Client
[EMERCH-1746](https://algolia.atlassian.net/browse/EMERCH-1746) + at least some of …

feat: make composition work server-side + some typing

---

packages/algoliasearch-helper/types/algoliasearch.d.ts

**Summary**
fixing a small error that went through the cracks

fix: composition search type

---

packages/algoliasearch-helper/index.d.ts
packages/instantsearch-core/src/connectors/connectCurrentRefinements.ts
packages/instantsearch-core/src/connectors/connectNumericMenu.ts
packages/instantsearch.js/src/components/Template/Template.tsx

- https://github.com/algolia/algoliasearch-helper-js/pull/800 made the todo in numeric menu no longer needed
- template is generic
[FX-3215]
[FX-3215]: https://algolia.atlassian.net/browse/FX-3215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove no longer needed comments

---

examples/vue/e-commerce/src/App.vue
tests/e2e/specs/initial-state-from-route.spec.ts
tests/e2e/specs/price-range.spec.ts

The component `vue-slider-component` throws an error with the new Vite build. I can't seem to find an underlying reason, so for now let's disable the component so release isn't blocked.

chore(vue example): remove price range

---

examples/vue/e-commerce/src/App.vue
examples/vue/e-commerce/vite.config.mjs
tests/e2e/specs/initial-state-from-route.spec.ts
tests/e2e/specs/price-range.spec.ts

chore(example): restore slider for vue example

---

package.json
packages/instantsearch.js/src/components/RefinementList/RefinementList.tsx
tests/common/widgets/refinement-list/options.ts
yarn.lock

**Summary**
If the `value` has a `"`, the query selector is invalid and throws an error. This PR fixes that case.
Code introduced in https://github.com/algolia/instantsearch/pull/6392 originally. Preact issue still open.
**Result**
we escape (only `"`, other characters have no impact) the value in the query selector, no error is thrown and the correct value is focused.
[CR-7674]
[CR-7674]: https://algolia.atlassian.net/browse/CR-7674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(refinement list): prevent error when value has a quote

---

packages/instantsearch.js/src/connectors/frequently-bought-together/connectFrequentlyBoughtTogether.ts
packages/instantsearch.js/src/connectors/looking-similar/connectLookingSimilar.ts
packages/instantsearch.js/src/connectors/related-products/connectRelatedProducts.ts
packages/instantsearch.js/src/connectors/trending-items/connectTrendingItems.ts
packages/instantsearch.js/src/widgets/frequently-bought-together/frequently-bought-together.tsx
packages/instantsearch.js/src/widgets/looking-similar/looking-similar.tsx
packages/instantsearch.js/src/widgets/related-products/related-products.tsx
packages/instantsearch.js/src/widgets/trending-items/trending-items.tsx
packages/react-instantsearch/src/widgets/FrequentlyBoughtTogether.tsx
packages/react-instantsearch/src/widgets/LookingSimilar.tsx

**Summary**
Follow-up on #6533
When using `sendEvent` with Recommend in InstantSearch.js we encounter a typing issue
```
Type 'AlgoliaHit<Record<string, any>>' is not assignable to type 'Hit'.
Property '__position' is missing in type 'AlgoliaHit<Record<string, any>>' but required in type '{ __position: number; __queryID?: string | undefined; }'
```
codesandbox to demonstrate the type issue https://codesandbox.io/p/sandbox/nzkfh7
This is because `AlgoliaHit` is only meant for hits that don't first go through `addAbsolutePosition` and `addQueryId`. This means that the type we actually mean to use is Hit in most cases.
**Result**
The issue was not caught by `yarn type-check` initially, I'm not sure how we could have done better to automatically catch it.

fix(recommend): use Hit type instead of AlgoliaHit

---

packages/react-instantsearch-nextjs/src/useInstantSearchRouting.ts

**Summary**
Fixes #6541
**Result**
Kind of hacky, but hydration errors seem to trigger effect cleanup functions while not actually remounting the components ?
Note we wouldn't have this problem if we had an InstantSearch instance outside of React lifecycle, which should probably be the way to go for the stable release.

fix(next-app-router): hydration error breaks routing

---

bundlesize.config.json
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/instantsearch.js/src/widgets/index/index.ts

**Summary**
In order to access some composition-related data (when `getRankingInfo` is requested), we need to access the root content of the API response, not just `results` (cf. [last example on this doc](https://algolia.atlassian.net/wiki/spaces/CMP/pages/5556273184/DD+-+Composition+API+updates)).
**Result**
exposing the root content of the API response (excluding `results` that is already exposed) through a `_rawContent` non-documented & non-typed property on search results.
it can therefor be accessed like this:
```ts
const { results: { _rawContent } } = useInstantSearch();
```

feat: expose raw request content under _rawContent

---

packages/algoliasearch-helper/src/algoliasearch.helper.js

**Summary**
Fixing an error made in #6544, where using `Object.create(content)` resulted in `rawContent` always being an empty object and the final `_rawContent` property always being `undefined`.
Now using a custom method to smartly clone `content` without the `results` property, which behaves correctly.
This approach avoids the need to delete the `results` property as it "just" creates a new object without it in the first place.
This result in a more performant approach than using the existing `merge` util + deleting the `results` property afterward.
**Result**
`_rawContent` as retrieved in the below example is now not always `undefined` anymore.
```ts
const { results: { _rawContent } } = useInstantSearch();
```

fix: rawContent was not correctly cloned (hence undefined)

---

packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/test/integration-spec/helper.searchOnce.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/pendingSearch.js

**Summary**
remove the callback from searchOnce
remove a bit of dead code
**Result**
Only promise is returned and no callback argument is accepted
BREAKING CHANGE: helper.searchOnce no longer accepts a callback, only promise is returned

feat(helper): remove searchOnce callback 

---

packages/algoliasearch-helper/index.d.ts
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/pages.js

These functions are redundant with the setPage and setQueryParameter/s/setState functions and aren't used in InstantSearch
BREAKING CHANGE: remove usage of helper.previousPage, helper.nextPage and use setPage, setState or setQueryParameter instead

feat(helper): remove previousPage and nextPage

---

.circleci/config.yml
packages/algoliasearch-helper/test/integration-spec/helper.distinct.facet.js
packages/algoliasearch-helper/test/integration-spec/helper.filters.js
packages/algoliasearch-helper/test/integration-spec/helper.numerics.js
packages/algoliasearch-helper/test/integration-spec/helper.searchOnce.js
packages/algoliasearch-helper/test/integration-spec/helper.tags.js
packages/algoliasearch-helper/test/integration-utils.js
packages/algoliasearch-helper/test/run.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/excludes.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/queryID.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/tags.js
packages/vue-instantsearch/src/util/__tests__/createServerRootMixin.test.js

**Summary**
Since a while, we haven't run the helper integration tests, and thus we haven't noticed that they don't pass on v5 anymore
**Result**
integration tests pass on v5 again
todo once this is passed, make sure we send the `INTEGRATION_TEST_API_KEY` and `INTEGRATION_TEST_APPID` env variables

chore(ci): make helper integration tests runnable

---

packages/create-instantsearch-app/src/templates/Vue InstantSearch/package.json

**Summary**
Using the vue instantsearch template with the `create-instantsearch-app` results in a dependency error when running `yarn start`. This fixes the `core-js` version to prevent that.
TODO:
- Check if other templates have the same error

fix(create-instantsearch-app): fix corejs version in vue-is template 

---

examples/react/css/package.json
examples/react/css/products/index.html
examples/react/css/vite.config.js
yarn.lock

This uses Vite instead of Parcel in the CSS example.
We couldn't set up Parcel to properly compile nested CSS at all, so went with Vite which just works.

build(examples): use Vite in CSS example

---

examples/react/css/src/App.tsx
examples/react/css/src/algolia.css
examples/react/css/src/reset.css

Would like to of utilised css nesting but couldn't get Parcel configured correctly.
Use Vanilla CSS for the reset instead of Scss
Move on from Scss and use native CSS

feat: use vanilla css reset

---

packages/react-instantsearch-nextjs/src/InitializePromise.ts
packages/react-instantsearch-nextjs/src/InstantSearchNext.tsx
packages/react-instantsearch-nextjs/src/TriggerSearch.ts
packages/react-instantsearch-nextjs/src/createInsertHTML.tsx

**Summary**
Fixes #6552
**Result**
Basically `search` was never called as we check for `_hasSearchWidgets`. It still rendered though as there was no `use` call either.
This triggered a weird hydration problem which was not even raised by Next.js.
Solved by injecting a script tag with empty initialResults.

fix(next): insert empty initial results for page with no widgets

---

examples/react/css/src/App.css
examples/react/css/src/App.tsx
examples/react/css/src/algolia.css
examples/react/css/src/highlight.css
examples/react/css/src/hits.css
examples/react/css/src/variables.css

**Summary**
This adds the `Hits`, `Highlight` and `Snippet` styles.

poc: add `Hits`, `Highlight` and `Snippet` styles

---

examples/react/ssr/src/searchClient.js
examples/react/ssr/src/server.js

**Summary**
[CR-6992](https://algolia.atlassian.net/browse/CR-6992)
Next.js examples does this with `responsesCache` not `requestsCache`, user had tried with `requestsCache` but it didn't fix anything as it was the wrong key, so I've updated the example too.
[CR-6992]: https://algolia.atlassian.net/browse/CR-6992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ssr-example): responsesCache instead of requestsCache

---

packages/algoliasearch-helper/src/requestBuilder.js
packages/instantsearch.js/src/lib/__tests__/InstantSearch-composition-test.tsx

**Summary**
[EMERCH-1942](https://algolia.atlassian.net/browse/EMERCH-1942)
- the Composition API has a limit of 20 facets annotated as `disjunctive`
- to limit the risk of reaching that limit, this PR does not annotated as `disjunctive` facets who do not have value selected
The reasoning is that when a facet has no value selected, the list of facet values will be the same with or without a disjunctive request.
**Result**
Less facets are annotated as disjunctive.
Notably, the `RefinementList` widget now does not annotate them by default anymore.
[EMERCH-1942]: https://algolia.atlassian.net/browse/EMERCH-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: don't transform facets as disjunctive if they have no value selected

---

examples/react/css/src/App.css
examples/react/css/src/App.tsx
examples/react/css/src/algolia.css
examples/react/css/src/common.css
examples/react/css/src/refinements.css
package.json

Current Refinements and Clear Refinements buttons

feat: current refinements & clear refinements

---

packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/src/utils/sortAndMergeRecommendations.js
packages/algoliasearch-helper/test/spec/utils/sortAndMergeRecommendations.js

**Summary**
When requesting multiple objectIDs, there is a chance that the merged results contains some of the input items.
We can filter those out for a more consistent output.

feat(recommend): filter out input objectIDs [RECO-2436]

---

bundlesize.config.json
packages/instantsearch.js/src/middlewares/__tests__/createInsightsMiddleware.ts
packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts

**Summary**
[FX-3372](https://algolia.atlassian.net/browse/FX-3372)
Fixes #6623 
**Result**
We should use the latest `appId` and `apiKey` as the latter can be rotated
[FX-3372]: https://algolia.atlassian.net/browse/FX-3372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(insights): use latest appId and apiKey

---

packages/react-instantsearch-core/src/lib/useSearchResults.ts
packages/react-instantsearch-core/src/lib/useSearchState.ts

**Summary**
This PR updates how `useSearchResults()` sets its results state. Instead of waiting for InstantSearch's `render` event, it immediately sets the state if results are available.
This can help in situations where results are received before the event listener can be set.
CR-8014

fix(useSearchResults): force setting results

---

packages/instantsearch.js/src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts
packages/react-instantsearch-core/src/connectors/__tests__/useInfiniteHits.test.tsx
packages/react-instantsearch/src/widgets/InfiniteHits.tsx
packages/react-instantsearch/src/widgets/__tests__/InfiniteHits.test.tsx

**Summary**
We default the infinite hits showPrevious to true, but in the initial render the functions `showPrevious` and `showMore` are not yet present in the sate. This fixes that and ensures the functions are always returned.
**Result**
- show more button always shows up by default (and doesn't flash)
- ensure that showMore and showPrevious functions are always defined, even if the first render is _with_ results (artificial for example)

fix(infiniteHits): always return valid showPrevious and showMore functions

---

bundlesize.config.json
packages/algoliasearch-helper/src/algoliasearch.helper.js
packages/algoliasearch-helper/test/spec/algoliasearch.helper/searchForFacetValues.js

**Summary**
We read the last results' facet ordering and apply hidden facets (not facet ordering) to the results array.
nbHits does not need to be changed as search for facet values doesn't return that key.
[CR-8645]
**Result**
hidden facets according to facetOrdering of the previous "full search" response are taken in account in search for facet values.
the lastResponse is always the most correct one if the index matches, if the previous search was for another index we do nothing
[CR-8645]: https://algolia.atlassian.net/browse/CR-8645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(facetOrdering): implement hidden facets in SFFV

---

packages/instantsearch.js/src/__tests__/common-shared.test.tsx
packages/instantsearch.js/src/connectors/breadcrumb/__tests__/connectBreadcrumb-test.ts
packages/instantsearch.js/src/connectors/breadcrumb/connectBreadcrumb.ts
packages/react-instantsearch/src/__tests__/common-shared.test.tsx
packages/vue-instantsearch/src/__tests__/common-shared.test.js
tests/common/shared/index.ts
tests/common/shared/insights.ts
tests/common/shared/interaction.ts
tests/common/shared/routing.ts

**Summary**
Breadcrumb connector accesses all facet names when generating the breadcrumb list. This results in a menu widget breaking functionality. This PR restricts the breadcrumb connector to only use attribute from the hierarchical menu to prevent this.
[CR-8481]
**Result**
Breadcrumbs now only shows hierarchical facets.
This also initializes an 'interaction' shared test suite which tests functionality of widgets used in tandem (only breadcrumbs + hierarchical menu + menu for now)
Codesandbox: https://codesandbox.io/p/sandbox/example-react-instantsearch-getting-started-l7y5j9
[CR-8481]: https://algolia.atlassian.net/browse/CR-8481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(breadcrumb): use hierarchical facets only

---

packages/instantsearch-ui-components/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch/package.json
yarn.lock

reason: [CVE-2025-27789](https://github.com/advisories/GHSA-968p-4wvh-cqc8) (which isn't actually reachable by our code, but good to get out of the way)
closes #6664
closes #6665

fix(babel): update babel/runtime

---

packages/instantsearch.js/src/connectors/infinite-hits/__tests__/connectInfiniteHits-test.ts
packages/instantsearch.js/src/connectors/infinite-hits/connectInfiniteHits.ts

**Summary**
Using helper state for getting a page would cause cache miss since infinite hits doesn't have access to base level widgets in a multi index scenario. Using the latest cache directly fixes this.
[CR-8905]
Closes: https://github.com/algolia/instantsearch/issues/6653
**Result**
Get previous page works correctly when preloaded via routing and multi index.
[CR-8905]: https://algolia.atlassian.net/browse/CR-8905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(infiniteHits): fix cache not using proper state

---

packages/instantsearch.js/src/components/Template/Template.tsx
packages/instantsearch.js/src/components/Template/__tests__/Template-test.tsx

**Summary**
"Playing" with facets can result to this error : 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nodeValue')
at a.value (algolia-instantsearch.min.js:2:229597)
at e (algolia-instantsearch.min.js:2:98166)
at e (algolia-instantsearch.min.js:2:98280)
at e (algolia-instantsearch.min.js:2:98280)
at $n (algolia-instantsearch.min.js:2:98366)
at algolia-instantsearch.min.js:2:102651
at Kn (algolia-instantsearch.min.js:2:103009)
at $n (algolia-instantsearch.min.js:2:97461)
at Kn (algolia-instantsearch.min.js:2:101481)
at $n (algolia-instantsearch.min.js:2:97461)
```
**Result**
Error is gone :)

FIX : in come cases, this.nodes[0] is undefined

---

packages/instantsearch.js/src/lib/InstantSearch.ts
packages/instantsearch.js/src/lib/__tests__/InstantSearch-test.tsx
packages/instantsearch.js/src/widgets/index/__tests__/index-test.ts
packages/instantsearch.js/src/widgets/index/index.ts

**Summary**
Accept composed widgets - a composed widget is a widget that itself is an array of widgets - as an argument to addWidgets and removeWidgets.
This will be useful for InstantSearch.js autocomplete widget that will have multiple widgets composing the single widget.
This enables the "pseudo-widget" signature of `function myWidget(params): Widget[]` instead of just `function myWidget(params): Widget`
**Result**
addWidgets and removeWidgets accept a widget that itself is a list, by flattening the list before using it.
[FX-3501]
[FX-3501]: https://algolia.atlassian.net/browse/FX-3501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(index): accept "composed" widgets in add/removeWidgets

---

packages/instantsearch.js/src/lib/chat/__tests__/chat.test.ts
packages/instantsearch.js/src/lib/chat/chat.ts

**Summary**
[FX-3521](https://algolia.atlassian.net/browse/FX-3521)
**Result**
Only implemented message persistence for now, we could also do the same for whether the panel should be open or not later, preferably once we mutualise logic between vanilla and react.
It saves messages only if the status is `ready`
[FX-3521]: https://algolia.atlassian.net/browse/FX-3521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(chat): save messages in session storage

---

packages/instantsearch.js/src/widgets/chat/chat.tsx
packages/react-instantsearch/src/widgets/Chat.tsx

**Summary**
This PR fixes the chat widget in InstantSearch.js by adding the missing props to the Chat UI component to achieve parity with the React InstantSearch chat widget.

fix(chat): add missing props to the IS.js chat widget

---

packages/instantsearch-ui-components/src/components/chat/Chat.tsx
packages/instantsearch-ui-components/src/components/chat/ChatPrompt.tsx
packages/instantsearch.js/src/widgets/chat/chat.tsx
packages/react-instantsearch/src/widgets/Chat.tsx

**Summary**
This PR fixes the auto-focus of the chat prompt when opening the chat for InstantSearch.js by passing an external ref from the widget (in InstantSearch.js and React InstantSearch).

fix(instantsearch-ui-components): fix auto focus on open
